In [1]:
import pandas as pd
import re
import numpy as np
import openpyxl
import arrival_compile_main as ac

%load_ext autoreload
%autoreload 2

In [2]:
path = r'C:\Users\fajar\Documents\Python\Data\Arrival List Raw\KE2 REDEEM VOUCHER INDO 2022.xlsx'

In [3]:

xl = pd.ExcelFile(path)
sheets = xl.sheet_names  # see all sheet names

delete_sheets = [
    'Old Cancel - Dec 2019',
    'CANCEL VOLCANO', 
    'CANCEL',
    'CANCEL AS OPENDATE', 
    'TSR Analysis Sep 22',
    'Cancel Discovery', 
    'Pending Discovery'
]

arr = np.array(sheets)
# arr = np.delete(arr, delete_sheets)

sheet_will_be_used = []

for i in sheets:
    sheets_name = i
    result = np.isin(sheets_name, delete_sheets)
    if result == True:
        print(sheets_name)
    else:
        print(sheets_name)
        sheet_will_be_used.extend([sheets_name])

sheet_will_be_used

# sheet_will_be_used = ['JAN 23']
# arr

Cancel Discovery
Pending Discovery
CANCEL
CANCEL AS OPENDATE
Sep 23
Apr 23
Feb 23
JAN 23
Dec 22
Nov 22
Oct 22
Sept 22
Aug 22
July 22
Jun 22
May 22
Apr 22
Mar 22
Feb 22
Jan 22
Dec 21

['Sep 23',
 'Apr 23',
 'Feb 23',
 'JAN 23',
 'Dec 22',
 'Nov 22',
 'Oct 22',
 'Sept 22',
 'Aug 22',
 'July 22',
 'Jun 22',
 'May 22',
 'Apr 22',
 'Mar 22',
 'Feb 22',
 'Jan 22',
 'Dec 21']

In [4]:
key_columns = 'No'

cols = [key_columns, 
        'Programme', 
        'Nationality',
        'Region',
        'Client Name', 
        'Phone Number', 
        'Email Address',
        'Check in',
        'Check out']

In [5]:
df = ac.load_data_multiple(path, sheet_will_be_used, cols, key_columns)
df.rename(columns = {
    key_columns:'Sheet Row No.',
    'Email Address' : 'Email',
    'Phone Number' : 'Phone'}, inplace = True)
df

Compiling sheets [Sep 23] - On progress : Proses Single Header
Compiling sheets [Apr 23] - On progress : Proses Multiple Header
Compiling sheets [Feb 23] - On progress : Proses Single Header
Compiling sheets [JAN 23] - On progress : Proses Single Header
Compiling sheets [Dec 22] - On progress : Proses Single Header
Compiling sheets [Nov 22] - On progress : Proses Multiple Header
Compiling sheets [Oct 22] - On progress : Proses Single Header
Compiling sheets [Sept 22] - On progress : Proses Multiple Header
Compiling sheets [Aug 22] - On progress : Proses Multiple Header
Compiling sheets [July 22] - On progress : Proses Multiple Header
Compiling sheets [Jun 22] - On progress : Proses Multiple Header
Compiling sheets [May 22] - On progress : Proses Multiple Header
Compiling sheets [Apr 22] - On progress : Proses Multiple Header
Compiling sheets [Mar 22] - On progress : Proses Multiple Header
Compiling sheets [Feb 22] - On progress : Proses Multiple Header
Compiling sheets [Jan 22] - On progress : Proses Multiple Header
Compiling sheets [Dec 21] - On progress : Proses Multiple Header

,Sheet Row No.,Programme,Nationality,Region,Client Name,Phone,Email,Check in,Check out,Sheet Name
0,1,KE2 Redeem Voucher,Indonesian,Indonesia,Wiryo Hartoyo & Vanny,81225919281,wiryohartoyo@gmail.com,2023-09-09 00:00:00,7 Nights,Sep 23
1,1,KARMA DISCOVERY VOUCHER,Indonesian,<NA>,M Kandaputra SE MM & Yoshinogi Fitria,0811808424,m.kanda13@yahoo.com,2023-04-29 00:00:00,2023-05-06 00:00:00,Apr 23
2,1,Redeem Karma Salak,Indonesian,Tangerang Selatan,Rendy Christiadi Soeng & Lanny Merlin Poulus,085105133527,lannypaulus@hotmail.com,2023-02-21 00:00:00,2023-02-27 00:00:00,Feb 23
3,1,Redeem Karma Salak,Indonesian,Jakarta Selatan,Faher Er Razi & Fajarini,081717198899,ririn.fajarini@gmail.com,2023-01-07 00:00:00,2023-01-14 00:00:00,JAN 23
4,2,Redeem Karma Salak,Indonesian,Jakarta Barat,Oey Giok Eng & Liliana Munadi,085214104549,giokeng6127@gmail.com,2023-01-07 00:00:00,2023-01-14 00:00:00,JAN 23
...,...,...,...,...,...,...,...,...,...,...
278,4,REDEEM KARMA SALAK VCHR,Indonesian,Jakarta Pusat,Tengku Abdullah Zaki & Rima Risoti Lubis,081392575705,tengkuzaki@gmail.com,2021-12-11 00:00:00,2021-12-18 00:00:00,Dec 21
279,5,REDEEM KARMA SALAK VCHR,Indonesian,Bekasi,Prima Respati & Tarida Tisyanditha Shafira,081230009363,ttstengker.mm@gmail.com,2021-12-11 00:00:00,2021-12-18 00:00:00,Dec 21
280,6,Redeem Karma Salak,Indonesian,Jakarta Barat,Wilson Darius & Ivana Tirtaningrum W.J,081510001456,ivana_wahyadi@yahoo.com,2021-12-11 00:00:00,2021-12-18 00:00:00,Dec 21
281,7,REDEEM KARMA SALAK VCHR,Indonesian,Jakarta Timur,Reza Fahlevi & Halimah Koeanda,081284171102,rezafahlevi@gmail.com,2021-12-11 00:00:00,2021-12-18 00:00:00,Dec 21
282,1,REDEEM KARMA DISCOVERY VCHR,Indonesian,Jakarta Barat,Jossy Sugondo & Devy,0817738015,jossy.sugondo@gmail.com,2021-12-11 00:00:00,2021-12-18 00:00:00,Dec 21

In [6]:
df.to_excel(r'C:\Users\fajar\Documents\Python\Data\Arrival List Raw\Compile Arrival\KE2 REDEEM VOUCHER INDO 2022-compile.xlsx', index=False)

In [7]:
# # jumlah header columns yang ada di sheets (menghitung berdasarkan jumlah nilai 'key columns' yang ada di kolom tersebut)
# count_header = df.loc[df[0] == key_columns].shape[0]

# # kumpulan index row dari setiap header columns yang ada di sheets
# arr_index = df.loc[df[0] == key_columns].index

# sheet_name = 'JAN 23'


# if count_header == 1:
#     print('Proses Single Header')
#     new_df = get_data_segment_single_header(sheet_name, df, arr_index, cols)

# elif count_header > 1:
#     print('Proses Multiple Header')
#     new_df = get_data_segment_multi_header(sheet_name, df, count_header, arr_index, cols)

# else:
#     print('Column Header Not Found')

# new_df

In [8]:
# df = pd.read_excel(path, dtype='string', sheet_name='JAN 23', index_col=None, header=None)
# df.shape[0]

In [9]:
# # mencari nomor row index untuk memulai compile data

# start_segment = df.loc[df[0] == key_columns].index.values.astype(int)[0]
# end_segment = df.shape[0]

# new_df = df.iloc[start_segment:end_segment].reset_index(drop=True).copy()
# new_df.columns = new_df.iloc[0] # define kolom berdasarkan row paling awal
# new_df.drop([0,0], inplace=True) # menghapus row yang sudah dijadikan kolom (karena meskipun row index 0 sudah di define sebagai kolom, row index 0 tetap ada di row record data)
# arr_df = new_df[cols].loc[~new_df[key_columns].isna()].copy()
# arr_df.reset_index(drop=True, inplace=True)
# arr_df

In [10]:
# df.loc[~df['Check in'].str.contains('00:00:00')]