In [42]:
import gspread
import pandas as pd
from fractions import Fraction
import re

import sys
sys.path.append('../zoho_data_app')

import main_module as m

# Pastikan permision access di menu "Share" di rubah ke anyone with the link terlebih dahulu, agar bisa mengunakan cara OAuth
# Jika Ingin lebih dibatasi menggunakan cara google service account lebih disarankan

gc = gspread.oauth(
    credentials_filename= r'C:\Users\fajar\Documents\Python\Data\Google Credentials\fajar-fatoni-OAuth.json'
)

SHEET_ID = '1B7e1rVK0c8Krh4ng5Fdc0Xew7-HMOVa28I_HwW3E2Ok'
SHEET_NAME = 'Karma Beach'
SHEET_NAME_2 = 'Karma Kandara'
SHEET_NAME_3 = 'Karma Jimbaran'

In [43]:
path = r'C:\Users\fajar\Documents\Python\Data\Leads_2024_08_05.csv'
zoho_df = pd.read_csv(path, dtype='string')
count_data_awal = zoho_df.shape[0]
zoho_df.fillna('empty', inplace=True)

In [44]:
# get data gsheet

spreadsheet = gc.open_by_key(SHEET_ID)
worksheet = spreadsheet.worksheet(SHEET_NAME)
rows = worksheet.get_all_records()

# print(rows[:5])

# print('==============================')
df = pd.DataFrame(rows)
df['Mobile Number'] = df['Mobile Number'].apply(Fraction)
df['Lead Location'] = SHEET_NAME

In [45]:
# get data gsheet

spreadsheet = gc.open_by_key(SHEET_ID)
worksheet = spreadsheet.worksheet(SHEET_NAME_2)
rows = worksheet.get_all_records()

# print(rows[:5])

# print('==============================')
df2 = pd.DataFrame(rows)
df2['Mobile Number'] = df2['Mobile Number'].apply(Fraction)
df2['Lead Location'] = SHEET_NAME_2

In [46]:
# get data gsheet

spreadsheet = gc.open_by_key(SHEET_ID)
worksheet = spreadsheet.worksheet(SHEET_NAME_3)
rows = worksheet.get_all_records()

# print(rows[:5])

# print('==============================')
df3 = pd.DataFrame(rows)
df3['Mobile Number'] = df3['Mobile Number'].apply(Fraction)
df3['Lead Location'] = SHEET_NAME_3

In [47]:
df_all = pd.concat([df,df2,df3], ignore_index=True)
df_all

,Name,Mobile Number,Tags,Last Active,Joined On,First Message Tag,Source,Incoming,Opted In,Intervened By,ZohoID,Email,Country,Lead Location
0,Nikolay,6246735045458,Past Purple Guest,,12/18/2023 4:54,,Zoho,Active,Yes,,zcrm_3584690000468250001,niclas@nistrom.com,,Karma Beach
1,Sjohnson,6261406439889,Past Purple Guest,,12/18/2023 4:54,,Zoho,Active,Yes,,zcrm_3584690000451668036,sjohnson@jio.com.au,,Karma Beach
2,Joan Doyon,626187863261685,Past Purple Guest,,12/18/2023 4:54,,Zoho,Active,Yes,,zcrm_3584690000247848310,joandoyon@hotmail.com,,Karma Beach
3,Popo Pribafi,6262811256068,Past Purple Guest,,12/18/2023 4:54,,Zoho,Active,Yes,,zcrm_3584690000448592111,pujipribadi@ymail.com,,Karma Beach
4,Ayesha,628121261021,Past Purple Guest | KB VIP Program Update,,12/18/2023 4:54,,Zoho,Active,Yes,,zcrm_3584690000297223302,ayesha.arrizki@gmqil.com,,Karma Beach
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19485,Hazem Sallam,201066557713,In House 2 August 24,,8/2/2024 1:10,,IMPORTED,Active,Yes,,NaN,NaN,NaN,Karma Jimbaran
19486,Margaret Ellen Mathiesen,61405609363,In House 2 August 24,,8/2/2024 1:10,,IMPORTED,Active,Yes,,NaN,NaN,NaN,Karma Jimbaran
19487,Ran Feifei,628113088069,In House 2 August 24,,8/2/2024 1:10,,IMPORTED,Active,Yes,,NaN,NaN,NaN,Karma Jimbaran
19488,Magomed Dzhamalov,79285999821,In House 2 August 24,,8/2/2024 1:10,,IMPORTED,Active,Yes,,NaN,NaN,NaN,Karma Jimbaran
19489,Krish Shah,919833460509,In House 2 August 24,,8/2/2024 1:10,,IMPORTED,Active,Yes,,NaN,NaN,NaN,Karma Jimbaran

In [48]:
df_organic = df_all.loc[df_all['Source'].str.contains('organic', regex=True, flags=re.I)].copy()
df_organic

,Name,Mobile Number,Tags,Last Active,Joined On,First Message Tag,Source,Incoming,Opted In,Intervened By,ZohoID,Email,Country,Lead Location
553,Karan.Nagra,919592733130,KK_Valentine_12Feb24 | Past Purple Guest,12/22/2023 7:55,12/22/2023 7:55,,ORGANIC,Active,Yes,,,,,Karma Beach
623,Servis Kompr,62895403807375,Past Purple Guest | KK_Valentine_12Feb24,12/27/2023 23:26,12/27/2023 23:24,,ORGANIC,Active,Yes,,,,,Karma Beach
624,Gabi,5513981219495,Past Purple Guest | KK_Valentine_12Feb24,12/29/2023 1:28,12/28/2023 11:06,,ORGANIC,Active,Yes,,,,,Karma Beach
625,Sudharshan,919489177367,Invalid | KK_Valentine_12Feb24,12/28/2023 16:11,12/28/2023 16:11,,ORGANIC,Active,No,,,,,Karma Beach
626,Emna Ben Ouaghram,447798642065,Past KBB VIP | KK_Valentine_12Feb24 | Past Pur...,12/31/2023 6:30,12/28/2023 17:11,,ORGANIC,Active,Yes,,,,,Karma Beach
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18855,Goyal Madhurima,919986885250,Past inHouse Guest,,4/16/2024 1:42,,ORGANIC,Active,Yes,,NaN,NaN,NaN,Karma Jimbaran
18856,Bryan Whiting,447931789709,Past inHouse Guest,,4/16/2024 1:42,,ORGANIC,Active,Yes,,NaN,NaN,NaN,Karma Jimbaran
18857,Oki Ramadhana,62811150700,In House 25 July 24 | Past inHouse Guest | In ...,,4/16/2024 1:42,,ORGANIC,Active,Yes,,NaN,NaN,NaN,Karma Jimbaran
18931,Arya Wijaya,6285738679736,,6/29/2024 12:44,5/4/2024 3:05,,ORGANIC,Active,Yes,Guest Services,NaN,NaN,NaN,Karma Jimbaran
19233,Info Bri,6281393445510,,6/22/2024 7:29,6/22/2024 7:29,,ORGANIC,Active,Yes,,NaN,NaN,NaN,Karma Jimbaran

In [49]:
df_organic['Name'] = df_organic['Name'].str.title()
split_name = df_organic['Name'].str.split(' ', expand=True, n=2)
df_organic['First Name'] =  split_name[0]
df_organic['Last Name'] =  split_name[1]

df_organic.loc[df_organic['First Name'] == 'None', 'First Name'] = df_organic['Name']
df_organic.loc[df_organic['Last Name'] == 'None', 'Last Name'] = '-'

In [50]:
df_organic

,Name,Mobile Number,Tags,Last Active,Joined On,First Message Tag,Source,Incoming,Opted In,Intervened By,ZohoID,Email,Country,Lead Location,First Name,Last Name
553,Karan.Nagra,919592733130,KK_Valentine_12Feb24 | Past Purple Guest,12/22/2023 7:55,12/22/2023 7:55,,ORGANIC,Active,Yes,,,,,Karma Beach,Karan.Nagra,None
623,Servis Kompr,62895403807375,Past Purple Guest | KK_Valentine_12Feb24,12/27/2023 23:26,12/27/2023 23:24,,ORGANIC,Active,Yes,,,,,Karma Beach,Servis,Kompr
624,Gabi,5513981219495,Past Purple Guest | KK_Valentine_12Feb24,12/29/2023 1:28,12/28/2023 11:06,,ORGANIC,Active,Yes,,,,,Karma Beach,Gabi,None
625,Sudharshan,919489177367,Invalid | KK_Valentine_12Feb24,12/28/2023 16:11,12/28/2023 16:11,,ORGANIC,Active,No,,,,,Karma Beach,Sudharshan,None
626,Emna Ben Ouaghram,447798642065,Past KBB VIP | KK_Valentine_12Feb24 | Past Pur...,12/31/2023 6:30,12/28/2023 17:11,,ORGANIC,Active,Yes,,,,,Karma Beach,Emna,Ben
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18855,Goyal Madhurima,919986885250,Past inHouse Guest,,4/16/2024 1:42,,ORGANIC,Active,Yes,,NaN,NaN,NaN,Karma Jimbaran,Goyal,Madhurima
18856,Bryan Whiting,447931789709,Past inHouse Guest,,4/16/2024 1:42,,ORGANIC,Active,Yes,,NaN,NaN,NaN,Karma Jimbaran,Bryan,Whiting
18857,Oki Ramadhana,62811150700,In House 25 July 24 | Past inHouse Guest | In ...,,4/16/2024 1:42,,ORGANIC,Active,Yes,,NaN,NaN,NaN,Karma Jimbaran,Oki,Ramadhana
18931,Arya Wijaya,6285738679736,,6/29/2024 12:44,5/4/2024 3:05,,ORGANIC,Active,Yes,Guest Services,NaN,NaN,NaN,Karma Jimbaran,Arya,Wijaya
19233,Info Bri,6281393445510,,6/22/2024 7:29,6/22/2024 7:29,,ORGANIC,Active,Yes,,NaN,NaN,NaN,Karma Jimbaran,Info,Bri

In [51]:
df_organic.to_excel(r'C:\Users\fajar\Documents\Python\Data\organic_wa.xlsx', index=False)