In [1]:
import pandas as pd
import re

import past_guest_module as pm

import sys
sys.path.append('../zoho_data_app/')

import main_module as m

%load_ext autoreload
%autoreload 2

In [2]:
path = r'C:\Users\fajar\Documents\Python\Data\Past Guest Data\Zoho Analytic\2025\Jan\19 Jan - 28 Jan\CRM_Rental_Report_19_Jan_-_28_Jan.xlsx'
df_analytic = pd.read_excel(path, dtype='string', sheet_name='Sheet1')
count_data_awal = df_analytic.shape[0]
df_analytic

,Booking_Id,TelNo,MobileNo,Email,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK063331,61414820224,61414820224,1carlymiles@gmail.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF112172,Mrs,...,2025-01-07 00:00:00,14,HOUSE_USE,V_OWNER_NRB,COMP,2,4,0,,
1,KK067901,+9316154580,9316154580,2532033@gmail.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF299925,Mr,...,2025-01-14 00:00:00,1,HOUSE_USE,V_OWNER_NRB,COMP,2,0,0,,
2,KK067554,081399975888,61415813168,7thcorporations@gmail.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF180153,Dr,...,2025-01-10 00:00:00,2,DIR,CHAT,DIGITAL,10,0,0,,
3,KK067638,+6281219438588,6281219438588,ageshgrace@gmail.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF299327,Ms,...,2025-01-09 00:00:00,1,OTA,OTA,RETAIL,4,0,0,,
4,KB046531,0179061195,<NA>,ahslyntaylrr@gmail.com,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297499,Miss,...,2025-01-06 00:00:00,7,WYNDHAM,WYNDHAM,WYNDHAM,2,0,0,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,KK067047,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Kandara,PF298273,Mr,...,2025-01-10 00:00:00,1,HOUSE_USE,V_OWNER_NRB,COMP,2,0,0,,
162,KB046527,+491781977963,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297281,Frau,...,2025-01-05 00:00:00,2,COMP,GER_OWE,COMP,2,0,0,,
163,KK053382,+61 499 912 596,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Kandara,PF268619,Mr,...,2025-01-14 00:00:00,4,OTA,OTA,RETAIL,6,0,0,,
164,KK052166,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Kandara,PF266361,Mr,...,2025-01-20 00:00:00,2,OTA,OTA,RETAIL,2,2,0,,
165,KK055932,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Kandara,PF274114,Mr,...,2025-01-16 00:00:00,1,OTA,OTA,RETAIL,2,0,0,,

In [3]:
df_analytic.columns

Index(['Booking_Id', 'TelNo', 'MobileNo', 'Email', 'Lead Brand',
       'Lead Sub- Brand', 'Lead Source', 'Resort_Name', 'ProfileRef',
       'Salutation', 'First_Name', 'Surname', 'Gender', 'Language', 'DOB',
       'Street', 'Area', 'Town', 'County', 'Country', 'Nationality',
       'PostCode', 'Exclude From Mailing', 'Opt In', 'Booking Code',
       'Booking Status', 'DateArrival', 'DateDepart', 'No. of Nights',
       'Market_Segment', 'Media_Code', 'Media Code Group', 'No. of Adult',
       'No. of Children', 'No. of Infants', 'Contact Type', 'Odyssey Members'],
      dtype='object')

In [4]:
new_cols = ['Booking_Id', 'Lead Brand', 'Lead Sub- Brand', 'Lead Source',
       'Resort_Name', 'ProfileRef', 'Salutation', 'First_Name', 'Surname',
       'Gender', 'Language', 'DOB', 'Street', 'Area', 'Town', 'County',
       'Country', 'Nationality', 'PostCode', 'TelNo', 'MobileNo', 'Email',
       'Exclude From Mailing', 'Opt In', 'Booking Status',
       'DateArrival', 'DateDepart', 'No. of Nights', 'Market_Segment',
       'Media_Code', 'Media Code Group', 'No. of Adult', 'No. of Children',
       'No. of Infants', 'Contact Type', 'Odyssey Members']																																																																																																																																						

df_analytic = df_analytic.reindex(columns=new_cols)

In [5]:
df_analytic.fillna('empty', inplace=True)
df_analytic['Contact Type'] = 'empty'
df_analytic['Odyssey Members'] = 'NO'

In [6]:
df_analytic.loc[df_analytic['Surname'] == 'empty', 'Surname'] = '-'

In [7]:
df_analytic['Salutation'].replace('empty', '', inplace=True)
df_analytic['First_Name'].replace('empty', '', inplace=True)
df_analytic['Surname'].replace('empty', '', inplace=True)

df_analytic['Salutation'] = df_analytic['Salutation'].str.title()
df_analytic['First_Name'] = df_analytic['First_Name'].str.title()
df_analytic['Surname'] = df_analytic['Surname'].str.title()

df_analytic

C:\Users\fajar\AppData\Local\Temp\ipykernel_10568\2281604359.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['Salutation'].replace('empty', '', inplace=True)
C:\Users\fajar\AppData\Local\Temp\ipykernel_10568\2281604359.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['First_Name'].replace('empty', '', inplace=True)
C:\Users\fajar\AppData\Local\Temp\ipykernel_10568\2281604359.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['Surname'].replace('empty', '', inplace=True)

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK063331,Karma Resorts,Other,Past Guests,Karma Kandara,PF112172,Mrs,Carly Louise,Miles,Female,...,2025-01-07 00:00:00,14,HOUSE_USE,V_OWNER_NRB,COMP,2,4,0,empty,NO
1,KK067901,Karma Resorts,Other,Past Guests,Karma Kandara,PF299925,Mr,Vladimir,Zhuravlev,Male,...,2025-01-14 00:00:00,1,HOUSE_USE,V_OWNER_NRB,COMP,2,0,0,empty,NO
2,KK067554,Karma Resorts,Other,Past Guests,Karma Kandara,PF180153,Dr,Chris,Gardjito,Male,...,2025-01-10 00:00:00,2,DIR,CHAT,DIGITAL,10,0,0,empty,NO
3,KK067638,Karma Resorts,Other,Past Guests,Karma Kandara,PF299327,Ms,Grace Agita,Purba,Female,...,2025-01-09 00:00:00,1,OTA,OTA,RETAIL,4,0,0,empty,NO
4,KB046531,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297499,Miss,Ashlyn,Taylor,Female,...,2025-01-06 00:00:00,7,WYNDHAM,WYNDHAM,WYNDHAM,2,0,0,empty,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,KK067047,Karma Resorts,Other,Past Guests,Karma Kandara,PF298273,Mr,.,Ardiansyah,Male,...,2025-01-10 00:00:00,1,HOUSE_USE,V_OWNER_NRB,COMP,2,0,0,empty,NO
162,KB046527,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297281,Frau,Lisa,Rimschneider,Female,...,2025-01-05 00:00:00,2,COMP,GER_OWE,COMP,2,0,0,empty,NO
163,KK053382,Karma Resorts,Other,Past Guests,Karma Kandara,PF268619,Mr,Jessica,Hallett,Male,...,2025-01-14 00:00:00,4,OTA,OTA,RETAIL,6,0,0,empty,NO
164,KK052166,Karma Resorts,Other,Past Guests,Karma Kandara,PF266361,Mr,Kamilul,Ihsan,Male,...,2025-01-20 00:00:00,2,OTA,OTA,RETAIL,2,2,0,empty,NO
165,KK055932,Karma Resorts,Other,Past Guests,Karma Kandara,PF274114,Mr,Mohd Alhafis Abdulah,Sani,Male,...,2025-01-16 00:00:00,1,OTA,OTA,RETAIL,2,0,0,empty,NO

In [8]:
m.clean_number(df_analytic, 'TelNo')
m.clean_number(df_analytic, 'MobileNo')
m.replace_not_valid_to_empty(df_analytic, 'TelNo')
m.replace_not_valid_to_empty(df_analytic, 'MobileNo')

df_analytic.loc[df_analytic['TelNo'].str.contains('00000'), 'TelNo'] = 'empty'
df_analytic.loc[df_analytic['MobileNo'].str.contains('00000'), 'MobileNo'] = 'empty'

m.clean_space(df_analytic, 'Email')
df_analytic['Email'] = m.lowercase(df_analytic, 'Email')
m.email_correction(df_analytic, 'Email')

c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:67: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:68: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('[^0-9]','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:90: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:223: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('^mailto:|-primary$|-pri$|-Mrs$|(noemailtobesent)$','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:251: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_mail), '@mail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:252: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail), '@gmail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:253: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail_com), '@gmail.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:254: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail), '@hotmail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:255: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail_com), '@hotmail.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:256: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_com), '@yahoo.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:257: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo), '@yahoo.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:258: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_in), '@yahoo.co.in', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:273: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df_columns].loc[~df[df_columns].str.contains('@', df_columns, na=False)] = ''

In [9]:
m.email_correction(df_analytic, 'Email')

c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:223: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('^mailto:|-primary$|-pri$|-Mrs$|(noemailtobesent)$','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:251: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_mail), '@mail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:252: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail), '@gmail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:253: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail_com), '@gmail.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:254: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail), '@hotmail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:255: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail_com), '@hotmail.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:256: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_com), '@yahoo.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:257: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo), '@yahoo.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:258: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_in), '@yahoo.co.in', regex=True, inplace=True)

In [10]:
df_analytic.loc[(df_analytic['Email'] != 'empty') & ((df_analytic['TelNo'] != 'empty') | (df_analytic['MobileNo'] != 'empty')), 'Contact Type'] = 'Email and Phone'
df_analytic.loc[(df_analytic['Email'] != 'empty') & ((df_analytic['TelNo'] == 'empty') & (df_analytic['MobileNo'] == 'empty')), 'Contact Type'] = 'Email Only'
df_analytic.loc[(df_analytic['Email'] == 'empty') & ((df_analytic['TelNo'] != 'empty') | (df_analytic['MobileNo'] != 'empty')), 'Contact Type'] = 'Phone Only'

df_analytic.loc[df_analytic['Contact Type'] == 'empty'].to_csv(r'C:\Users\fajar\Documents\Python\Data\contact_type_empty_analytic.csv', index=False)

count_contact_type_empty = df_analytic.loc[df_analytic['Contact Type'] == 'empty'].shape[0]

df_analytic.drop(df_analytic.loc[df_analytic['Contact Type'] == 'empty'].index, inplace=True)
df_analytic.reset_index(drop=True, inplace=True)

count_after_contact_type_empty = df_analytic.shape[0]

df_analytic

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK063331,Karma Resorts,Other,Past Guests,Karma Kandara,PF112172,Mrs,Carly Louise,Miles,Female,...,2025-01-07 00:00:00,14,HOUSE_USE,V_OWNER_NRB,COMP,2,4,0,Email and Phone,NO
1,KK067901,Karma Resorts,Other,Past Guests,Karma Kandara,PF299925,Mr,Vladimir,Zhuravlev,Male,...,2025-01-14 00:00:00,1,HOUSE_USE,V_OWNER_NRB,COMP,2,0,0,Email and Phone,NO
2,KK067554,Karma Resorts,Other,Past Guests,Karma Kandara,PF180153,Dr,Chris,Gardjito,Male,...,2025-01-10 00:00:00,2,DIR,CHAT,DIGITAL,10,0,0,Email and Phone,NO
3,KK067638,Karma Resorts,Other,Past Guests,Karma Kandara,PF299327,Ms,Grace Agita,Purba,Female,...,2025-01-09 00:00:00,1,OTA,OTA,RETAIL,4,0,0,Email and Phone,NO
4,KB046531,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297499,Miss,Ashlyn,Taylor,Female,...,2025-01-06 00:00:00,7,WYNDHAM,WYNDHAM,WYNDHAM,2,0,0,Email and Phone,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,KK067047,Karma Resorts,Other,Past Guests,Karma Kandara,PF298273,Mr,.,Ardiansyah,Male,...,2025-01-10 00:00:00,1,HOUSE_USE,V_OWNER_NRB,COMP,2,0,0,Email Only,NO
162,KB046527,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297281,Frau,Lisa,Rimschneider,Female,...,2025-01-05 00:00:00,2,COMP,GER_OWE,COMP,2,0,0,Email and Phone,NO
163,KK053382,Karma Resorts,Other,Past Guests,Karma Kandara,PF268619,Mr,Jessica,Hallett,Male,...,2025-01-14 00:00:00,4,OTA,OTA,RETAIL,6,0,0,Email and Phone,NO
164,KK052166,Karma Resorts,Other,Past Guests,Karma Kandara,PF266361,Mr,Kamilul,Ihsan,Male,...,2025-01-20 00:00:00,2,OTA,OTA,RETAIL,2,2,0,Email Only,NO
165,KK055932,Karma Resorts,Other,Past Guests,Karma Kandara,PF274114,Mr,Mohd Alhafis Abdulah,Sani,Male,...,2025-01-16 00:00:00,1,OTA,OTA,RETAIL,2,0,0,Email Only,NO

In [11]:
# Cek Email Karma
email_karma = m.find_karma(df_analytic, 'Email')
count_email_karma = email_karma.shape[0]
email_karma.to_csv(r'C:\Users\fajar\Documents\Python\Data\email_deleted_analytic.csv', index=False)

email_karma

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
13,KB043546,Karma Resorts,Other,Past Guests,Karma Bavaria,PF126784,Herr,Axel,Reimlinger,Male,...,2025-01-09 00:00:00,2,COMP,STAFF,COMP,1,0,0,Email and Phone,NO
19,KB046921,Karma Resorts,Other,Past Guests,Karma Bavaria,PF071902,Mr,Clinton,Albuquerque,Male,...,2025-01-13 00:00:00,2,COMP,STAFF,COMP,1,0,0,Email and Phone,NO
20,KB046224,Karma Resorts,Other,Past Guests,Karma Bavaria,PF071902,Mr,Clinton,Albuquerque,Male,...,2025-01-06 00:00:00,3,COMP,STAFF,COMP,1,0,0,Email and Phone,NO
26,KB047024,Karma Resorts,Other,Past Guests,Karma Bavaria,PF233671,Mr,Dario,Quinteros,Male,...,2025-01-09 00:00:00,1,COMP,STAFF,COMP,1,0,0,Email and Phone,NO
27,KB047117,Karma Resorts,Other,Past Guests,Karma Bavaria,PF233671,Mr,Dario,Quinteros,Male,...,2025-01-12 00:00:00,1,COMP,STAFF,COMP,1,0,0,Email and Phone,NO
42,KK060942,Karma Resorts,Other,Past Guests,Karma Kandara,PF085992,Mr,Jeffrey,Morfesse,Male,...,2025-01-06 00:00:00,2,HOUSE_USE,FOCVIP,KC,1,0,0,Email and Phone,NO
50,KLM007862,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF298662,Mr,John,Harrison,Male,...,2025-01-10 00:00:00,6,COMP,STAFF,COMP,1,0,0,Email and Phone,NO
51,KK066503,Karma Resorts,Other,Past Guests,Karma Kandara,PF255157,Mr,John,Spence,Male,...,2025-01-06 00:00:00,7,HOUSE_USE,VIP,COMP,1,0,0,Email and Phone,NO

In [12]:
# delete email Karma
count_after_clean_karma = m.delete_karma(df_analytic, 'Email')

df_analytic

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK063331,Karma Resorts,Other,Past Guests,Karma Kandara,PF112172,Mrs,Carly Louise,Miles,Female,...,2025-01-07 00:00:00,14,HOUSE_USE,V_OWNER_NRB,COMP,2,4,0,Email and Phone,NO
1,KK067901,Karma Resorts,Other,Past Guests,Karma Kandara,PF299925,Mr,Vladimir,Zhuravlev,Male,...,2025-01-14 00:00:00,1,HOUSE_USE,V_OWNER_NRB,COMP,2,0,0,Email and Phone,NO
2,KK067554,Karma Resorts,Other,Past Guests,Karma Kandara,PF180153,Dr,Chris,Gardjito,Male,...,2025-01-10 00:00:00,2,DIR,CHAT,DIGITAL,10,0,0,Email and Phone,NO
3,KK067638,Karma Resorts,Other,Past Guests,Karma Kandara,PF299327,Ms,Grace Agita,Purba,Female,...,2025-01-09 00:00:00,1,OTA,OTA,RETAIL,4,0,0,Email and Phone,NO
4,KB046531,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297499,Miss,Ashlyn,Taylor,Female,...,2025-01-06 00:00:00,7,WYNDHAM,WYNDHAM,WYNDHAM,2,0,0,Email and Phone,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,KK067047,Karma Resorts,Other,Past Guests,Karma Kandara,PF298273,Mr,.,Ardiansyah,Male,...,2025-01-10 00:00:00,1,HOUSE_USE,V_OWNER_NRB,COMP,2,0,0,Email Only,NO
154,KB046527,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297281,Frau,Lisa,Rimschneider,Female,...,2025-01-05 00:00:00,2,COMP,GER_OWE,COMP,2,0,0,Email and Phone,NO
155,KK053382,Karma Resorts,Other,Past Guests,Karma Kandara,PF268619,Mr,Jessica,Hallett,Male,...,2025-01-14 00:00:00,4,OTA,OTA,RETAIL,6,0,0,Email and Phone,NO
156,KK052166,Karma Resorts,Other,Past Guests,Karma Kandara,PF266361,Mr,Kamilul,Ihsan,Male,...,2025-01-20 00:00:00,2,OTA,OTA,RETAIL,2,2,0,Email Only,NO
157,KK055932,Karma Resorts,Other,Past Guests,Karma Kandara,PF274114,Mr,Mohd Alhafis Abdulah,Sani,Male,...,2025-01-16 00:00:00,1,OTA,OTA,RETAIL,2,0,0,Email Only,NO

In [13]:
df_analytic['Salutation']

0       Mrs
1        Mr
2        Dr
3        Ms
4      Miss
       ...
153      Mr
154    Frau
155      Mr
156      Mr
157      Mr
Name: Salutation, Length: 158, dtype: string

In [14]:
# Cek leads test
test_leads = df_analytic.loc[
    
        df_analytic['Email'].str.contains('^test@', flags=re.I, regex=True) |
        df_analytic['Email'].str.contains('\+test', flags=re.I, regex=True) |
    
        df_analytic['First_Name'].str.contains('^test$', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('^test$', flags=re.I, regex=True) |

        df_analytic['First_Name'].str.contains('test 1', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('test 2', flags=re.I, regex=True)|
        df_analytic['First_Name'].str.contains('test1', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('test2', flags=re.I, regex=True)|

        df_analytic['First_Name'].str.contains(' test ', flags=re.I, regex=True) | 
        df_analytic['Surname'].str.contains(' test ', flags=re.I, regex=True) | 
        df_analytic['Surname'].str.contains(' test$', flags=re.I, regex=True)
    ]

count_leads_test = test_leads.shape[0]

test_leads.to_csv(r'C:\Users\fajar\Documents\Python\Data\test_leads_analytic.csv', index=False)
test_leads

Empty DataFrame
Columns: [Booking_Id, Lead Brand, Lead Sub- Brand, Lead Source, Resort_Name, ProfileRef, Salutation, First_Name, Surname, Gender, Language, DOB, Street, Area, Town, County, Country, Nationality, PostCode, TelNo, MobileNo, Email, Exclude From Mailing, Opt In, Booking Status, DateArrival, DateDepart, No. of Nights, Market_Segment, Media_Code, Media Code Group, No. of Adult, No. of Children, No. of Infants, Contact Type, Odyssey Members]
Index: []

[0 rows x 36 columns]

In [15]:
df_analytic.drop(test_leads.index, inplace=True)
df_analytic.reset_index(drop=True, inplace=True)

count_after_dedup_test = df_analytic.shape[0]
count_after_dedup_test

158

In [16]:
count_final_data = count_after_dedup_test

In [17]:
# df_analytic.loc[(df_analytic['Email'] == 'jonmosley6@yahoo.com')]

In [18]:
df_analytic.replace('empty', '', inplace=True)

In [19]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Data Awal Zoho Analytic : "+str(count_data_awal))
print("Jumlah Data Email dan Phone Kosong : "+str(count_contact_type_empty))
print("Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : "+str(count_after_contact_type_empty))
print("Jumlah Data Email Yang Termasuk List Karma : "+str(count_email_karma))
print("Jumlah Data Email Setelah List Karma Dihapus : "+str(count_after_clean_karma))
print("Jumlah Data Test : "+str(count_leads_test))
print("Jumlah Data Email Setelah Data Test Dihapus : "+str(count_after_dedup_test))
print("Jumlah Data Akhir : "+str(count_final_data))

==========================================================
Summary
==========================================================
Jumlah Data Awal Zoho Analytic : 166
Jumlah Data Email dan Phone Kosong : 0
Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : 166
Jumlah Data Email Yang Termasuk List Karma : 8
Jumlah Data Email Setelah List Karma Dihapus : 158
Jumlah Data Test : 0
Jumlah Data Email Setelah Data Test Dihapus : 158
Jumlah Data Akhir : 158

In [20]:
df_analytic.to_excel(r'C:\Users\fajar\Documents\Python\Data\check_country_code_analytic.xlsx', index=False)