In [1]:
import pandas as pd
import re

import past_guest_module as pm

import sys
sys.path.append('../zoho_data_app/')

import main_module as m

%load_ext autoreload
%autoreload 2

In [2]:
path = r'C:\Users\fajar\Documents\Python\Data\Past Guest Data\Zoho Analytic\2024\Okt\6 Okt - 14 Okt\CRM_Rental_Report_6_Okt_-_14_Okt.xlsx'
df_analytic = pd.read_excel(path, dtype='string', sheet_name='Sheet1')
count_data_awal = df_analytic.shape[0]
df_analytic

,Booking_Id,TelNo,MobileNo,Email,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK058890,+86 20 3564 0799,8613552435101,798751021@qq.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF281578,Mr,...,2024-10-07 00:00:00,1,OTA,OTA,RETAIL,4,0,0,,
1,KK061292,8651410107888,<NA>,8531086@99.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF286883,Ms,...,2024-10-06 00:00:00,3,OTA,OTA,RETAIL,2,1,0,,
2,KLM006752,<NA>,<NA>,adrian.fatechand@karmagroup.com,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF267043,Mr,...,2024-10-13 00:00:00,2,COMP,STAFF,COMP,1,0,0,,
3,KSH018356,0773817058,07855896660,alison@naturesbase.co.uk,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF273299,Mrs,...,2024-10-08 00:00:00,1,DIR,WEBSITE,DIGITAL,1,0,0,,
4,KK058324,60305763,<NA>,amandw816@gmail.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF280340,Miss,...,2024-10-13 00:00:00,2,DIGITAL,GHPA,DIGITAL,2,0,0,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,KB042811,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,<NA>,Frau,...,2024-10-09 18:00:00,0,CB,CB,GROUP,1,0,0,,
102,KSM011095,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma St Martins,PF229563,Mr,...,2024-10-11 00:00:00,4,COMP,STAFF,COMP,2,0,0,,
103,KB040820,+33 6 72 70 83 79,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,PF265255,<NA>,...,2024-10-06 00:00:00,1,OTA,OTA,RETAIL,1,0,0,,
104,KB042379,+49 163 3692229,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,PF273832,<NA>,...,2024-10-06 00:00:00,1,OTA,OTA,RETAIL,2,0,0,,
105,KB043417,+49 172 6269477,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,PF280116,<NA>,...,2024-10-12 00:00:00,2,OTA,OTA,RETAIL,2,0,0,,

In [3]:
df_analytic.columns

Index(['Booking_Id', 'TelNo', 'MobileNo', 'Email', 'Lead Brand',
       'Lead Sub- Brand', 'Lead Source', 'Resort_Name', 'ProfileRef',
       'Salutation', 'First_Name', 'Surname', 'Gender', 'Language', 'DOB',
       'Street', 'Area', 'Town', 'County', 'Country', 'Nationality',
       'PostCode', 'Exclude From Mailing', 'Opt In', 'Booking Code',
       'Booking Status', 'DateArrival', 'DateDepart', 'No. of Nights',
       'Market_Segment', 'Media_Code', 'Media Code Group', 'No. of Adult',
       'No. of Children', 'No. of Infants', 'Contact Type', 'Odyssey Members'],
      dtype='object')

In [4]:
new_cols = ['Booking_Id', 'Lead Brand', 'Lead Sub- Brand', 'Lead Source',
       'Resort_Name', 'ProfileRef', 'Salutation', 'First_Name', 'Surname',
       'Gender', 'Language', 'DOB', 'Street', 'Area', 'Town', 'County',
       'Country', 'Nationality', 'PostCode', 'TelNo', 'MobileNo', 'Email',
       'Exclude From Mailing', 'Opt In', 'Booking Status',
       'DateArrival', 'DateDepart', 'No. of Nights', 'Market_Segment',
       'Media_Code', 'Media Code Group', 'No. of Adult', 'No. of Children',
       'No. of Infants', 'Contact Type', 'Odyssey Members']																																																																																																																																						

df_analytic = df_analytic.reindex(columns=new_cols)

In [5]:
df_analytic.fillna('empty', inplace=True)
df_analytic['Contact Type'] = 'empty'
df_analytic['Odyssey Members'] = 'NO'

In [6]:
df_analytic.loc[df_analytic['Surname'] == 'empty', 'Surname'] = '-'

In [7]:
df_analytic['Salutation'].replace('empty', '', inplace=True)
df_analytic['First_Name'].replace('empty', '', inplace=True)
df_analytic['Surname'].replace('empty', '', inplace=True)

df_analytic['Salutation'] = df_analytic['Salutation'].str.title()
df_analytic['First_Name'] = df_analytic['First_Name'].str.title()
df_analytic['Surname'] = df_analytic['Surname'].str.title()

df_analytic

C:\Users\fajar\AppData\Local\Temp\ipykernel_13748\2281604359.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['Salutation'].replace('empty', '', inplace=True)
C:\Users\fajar\AppData\Local\Temp\ipykernel_13748\2281604359.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['First_Name'].replace('empty', '', inplace=True)
C:\Users\fajar\AppData\Local\Temp\ipykernel_13748\2281604359.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['Surname'].replace('empty', '', inplace=True)

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK058890,Karma Resorts,Other,Past Guests,Karma Kandara,PF281578,Mr,Dongzhao,Tan,Male,...,2024-10-07 00:00:00,1,OTA,OTA,RETAIL,4,0,0,empty,NO
1,KK061292,Karma Resorts,Other,Past Guests,Karma Kandara,PF286883,Ms,Xue,Bai,Female,...,2024-10-06 00:00:00,3,OTA,OTA,RETAIL,2,1,0,empty,NO
2,KLM006752,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF267043,Mr,Adrian,Fatechand,Unknown,...,2024-10-13 00:00:00,2,COMP,STAFF,COMP,1,0,0,empty,NO
3,KSH018356,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF273299,Mrs,Alison,Morris,Female,...,2024-10-08 00:00:00,1,DIR,WEBSITE,DIGITAL,1,0,0,empty,NO
4,KK058324,Karma Resorts,Other,Past Guests,Karma Kandara,PF280340,Miss,Amanda,Wong,Female,...,2024-10-13 00:00:00,2,DIGITAL,GHPA,DIGITAL,2,0,0,empty,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,KB042811,Karma Resorts,Other,Past Guests,Karma Bavaria,empty,Frau,Johanna,Schneider,Unknown,...,2024-10-09 18:00:00,0,CB,CB,GROUP,1,0,0,empty,NO
102,KSM011095,Karma Resorts,Other,Past Guests,Karma St Martins,PF229563,Mr,Krg Sales,Sales,Male,...,2024-10-11 00:00:00,4,COMP,STAFF,COMP,2,0,0,empty,NO
103,KB040820,Karma Resorts,Other,Past Guests,Karma Bavaria,PF265255,,Rick,Noack,Unknown,...,2024-10-06 00:00:00,1,OTA,OTA,RETAIL,1,0,0,empty,NO
104,KB042379,Karma Resorts,Other,Past Guests,Karma Bavaria,PF273832,,Katja,Giesen,Unknown,...,2024-10-06 00:00:00,1,OTA,OTA,RETAIL,2,0,0,empty,NO
105,KB043417,Karma Resorts,Other,Past Guests,Karma Bavaria,PF280116,,Dietmar,Voetsch,Unknown,...,2024-10-12 00:00:00,2,OTA,OTA,RETAIL,2,0,0,empty,NO

In [8]:
m.clean_number(df_analytic, 'TelNo')
m.clean_number(df_analytic, 'MobileNo')
m.replace_not_valid_to_empty(df_analytic, 'TelNo')
m.replace_not_valid_to_empty(df_analytic, 'MobileNo')

df_analytic.loc[df_analytic['TelNo'].str.contains('00000'), 'TelNo'] = 'empty'
df_analytic.loc[df_analytic['MobileNo'].str.contains('00000'), 'MobileNo'] = 'empty'

m.clean_space(df_analytic, 'Email')
df_analytic['Email'] = m.lowercase(df_analytic, 'Email')

c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:67: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:68: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('[^0-9]','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:90: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)

In [9]:
pm.email_correction(df_analytic, 'Email')

c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:25: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_mail), '@mail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail), '@gmail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:35: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail_com), '@gmail.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:38: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail), '@hotmail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail_com), '@hotmail.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:45: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo), '@yahoo.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:48: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_ymail), '@ymail.', regex=True, inplace=True)

In [10]:
df_analytic.loc[(df_analytic['Email'] != 'empty') & ((df_analytic['TelNo'] != 'empty') | (df_analytic['MobileNo'] != 'empty')), 'Contact Type'] = 'Email and Phone'
df_analytic.loc[(df_analytic['Email'] != 'empty') & ((df_analytic['TelNo'] == 'empty') & (df_analytic['MobileNo'] == 'empty')), 'Contact Type'] = 'Email Only'
df_analytic.loc[(df_analytic['Email'] == 'empty') & ((df_analytic['TelNo'] != 'empty') | (df_analytic['MobileNo'] != 'empty')), 'Contact Type'] = 'Phone Only'

df_analytic.loc[df_analytic['Contact Type'] == 'empty'].to_csv(r'C:\Users\fajar\Documents\Python\Data\contact_type_empty_analytic.csv', index=False)

count_contact_type_empty = df_analytic.loc[df_analytic['Contact Type'] == 'empty'].shape[0]

df_analytic.drop(df_analytic.loc[df_analytic['Contact Type'] == 'empty'].index, inplace=True)
df_analytic.reset_index(drop=True, inplace=True)

count_after_contact_type_empty = df_analytic.shape[0]

df_analytic

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK058890,Karma Resorts,Other,Past Guests,Karma Kandara,PF281578,Mr,Dongzhao,Tan,Male,...,2024-10-07 00:00:00,1,OTA,OTA,RETAIL,4,0,0,Email and Phone,NO
1,KK061292,Karma Resorts,Other,Past Guests,Karma Kandara,PF286883,Ms,Xue,Bai,Female,...,2024-10-06 00:00:00,3,OTA,OTA,RETAIL,2,1,0,Email and Phone,NO
2,KLM006752,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF267043,Mr,Adrian,Fatechand,Unknown,...,2024-10-13 00:00:00,2,COMP,STAFF,COMP,1,0,0,Email Only,NO
3,KSH018356,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF273299,Mrs,Alison,Morris,Female,...,2024-10-08 00:00:00,1,DIR,WEBSITE,DIGITAL,1,0,0,Email and Phone,NO
4,KK058324,Karma Resorts,Other,Past Guests,Karma Kandara,PF280340,Miss,Amanda,Wong,Female,...,2024-10-13 00:00:00,2,DIGITAL,GHPA,DIGITAL,2,0,0,Email and Phone,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,KSH014362,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF251888,,Christine,Hansson,Unknown,...,2024-10-10 00:00:00,2,OTA,OTA,RETAIL,2,0,0,Phone Only,NO
81,KB039964,Karma Resorts,Other,Past Guests,Karma Bavaria,PF261833,,Natalie,Eichwald,Unknown,...,2024-10-13 00:00:00,2,OTA,OTA,RETAIL,8,0,0,Phone Only,NO
82,KB040820,Karma Resorts,Other,Past Guests,Karma Bavaria,PF265255,,Rick,Noack,Unknown,...,2024-10-06 00:00:00,1,OTA,OTA,RETAIL,1,0,0,Phone Only,NO
83,KB042379,Karma Resorts,Other,Past Guests,Karma Bavaria,PF273832,,Katja,Giesen,Unknown,...,2024-10-06 00:00:00,1,OTA,OTA,RETAIL,2,0,0,Phone Only,NO
84,KB043417,Karma Resorts,Other,Past Guests,Karma Bavaria,PF280116,,Dietmar,Voetsch,Unknown,...,2024-10-12 00:00:00,2,OTA,OTA,RETAIL,2,0,0,Phone Only,NO

In [11]:
# Cek Email Karma
email_karma = m.find_karma(df_analytic, 'Email')
count_email_karma = email_karma.shape[0]
email_karma.to_csv(r'C:\Users\fajar\Documents\Python\Data\email_deleted_analytic.csv', index=False)

email_karma

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
2,KLM006752,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF267043,Mr,Adrian,Fatechand,Unknown,...,2024-10-13 00:00:00,2,COMP,STAFF,COMP,1,0,0,Email Only,NO
5,KB043533,Karma Resorts,Other,Past Guests,Karma Bavaria,PF126784,Herr,Axel,Reimlinger,Male,...,2024-10-11 00:00:00,4,COMP,STAFF,COMP,1,0,0,Email and Phone,NO
9,KK061017,Karma Resorts,Other,Past Guests,Karma Kandara,PF071902,Mr,Clinton,Albuquerque,Male,...,2024-10-12 00:00:00,5,HOUSE_USE,STAFF,COMP,2,0,0,Email and Phone,NO
23,KK061790,Karma Resorts,Other,Past Guests,Karma Kandara,PF288183,Mrs,Babs,Leyton,Female,...,2024-10-07 00:00:00,1,HOUSE_USE,GSTAFF,COMP,1,0,0,Email and Phone,NO
54,KSM012424,Karma Resorts,Other,Past Guests,Karma St Martins,PF231659,Mr,Sebastian,Moeller,Unknown,...,2024-10-10 00:00:00,3,COMP,STAFF,COMP,1,0,0,Email Only,NO

In [12]:
# delete email Karma
count_after_clean_karma = m.delete_karma(df_analytic, 'Email')

df_analytic

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK058890,Karma Resorts,Other,Past Guests,Karma Kandara,PF281578,Mr,Dongzhao,Tan,Male,...,2024-10-07 00:00:00,1,OTA,OTA,RETAIL,4,0,0,Email and Phone,NO
1,KK061292,Karma Resorts,Other,Past Guests,Karma Kandara,PF286883,Ms,Xue,Bai,Female,...,2024-10-06 00:00:00,3,OTA,OTA,RETAIL,2,1,0,Email and Phone,NO
2,KSH018356,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF273299,Mrs,Alison,Morris,Female,...,2024-10-08 00:00:00,1,DIR,WEBSITE,DIGITAL,1,0,0,Email and Phone,NO
3,KK058324,Karma Resorts,Other,Past Guests,Karma Kandara,PF280340,Miss,Amanda,Wong,Female,...,2024-10-13 00:00:00,2,DIGITAL,GHPA,DIGITAL,2,0,0,Email and Phone,NO
4,KSM014107,Karma Resorts,Other,Past Guests,Karma St Martins,PF288431,Mr,Ben,Waters,Male,...,2024-10-07 00:00:00,2,COMP,STAFF,COMP,2,0,0,Email and Phone,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,KSH014362,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF251888,,Christine,Hansson,Unknown,...,2024-10-10 00:00:00,2,OTA,OTA,RETAIL,2,0,0,Phone Only,NO
76,KB039964,Karma Resorts,Other,Past Guests,Karma Bavaria,PF261833,,Natalie,Eichwald,Unknown,...,2024-10-13 00:00:00,2,OTA,OTA,RETAIL,8,0,0,Phone Only,NO
77,KB040820,Karma Resorts,Other,Past Guests,Karma Bavaria,PF265255,,Rick,Noack,Unknown,...,2024-10-06 00:00:00,1,OTA,OTA,RETAIL,1,0,0,Phone Only,NO
78,KB042379,Karma Resorts,Other,Past Guests,Karma Bavaria,PF273832,,Katja,Giesen,Unknown,...,2024-10-06 00:00:00,1,OTA,OTA,RETAIL,2,0,0,Phone Only,NO
79,KB043417,Karma Resorts,Other,Past Guests,Karma Bavaria,PF280116,,Dietmar,Voetsch,Unknown,...,2024-10-12 00:00:00,2,OTA,OTA,RETAIL,2,0,0,Phone Only,NO

In [13]:
df_analytic['Salutation']

0       Mr
1       Ms
2      Mrs
3     Miss
4       Mr
      ...
75
76
77
78
79
Name: Salutation, Length: 80, dtype: string

In [14]:
# Cek leads test
test_leads = df_analytic.loc[
    
        df_analytic['Email'].str.contains('^test@', flags=re.I, regex=True) |
        df_analytic['Email'].str.contains('\+test', flags=re.I, regex=True) |
    
        df_analytic['First_Name'].str.contains('^test$', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('^test$', flags=re.I, regex=True) |

        df_analytic['First_Name'].str.contains('test 1', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('test 2', flags=re.I, regex=True)|
        df_analytic['First_Name'].str.contains('test1', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('test2', flags=re.I, regex=True)|

        df_analytic['First_Name'].str.contains(' test ', flags=re.I, regex=True) | 
        df_analytic['Surname'].str.contains(' test ', flags=re.I, regex=True) | 
        df_analytic['Surname'].str.contains(' test$', flags=re.I, regex=True)
    ]

count_leads_test = test_leads.shape[0]

test_leads.to_csv(r'C:\Users\fajar\Documents\Python\Data\test_leads_analytic.csv', index=False)
test_leads

Empty DataFrame
Columns: [Booking_Id, Lead Brand, Lead Sub- Brand, Lead Source, Resort_Name, ProfileRef, Salutation, First_Name, Surname, Gender, Language, DOB, Street, Area, Town, County, Country, Nationality, PostCode, TelNo, MobileNo, Email, Exclude From Mailing, Opt In, Booking Status, DateArrival, DateDepart, No. of Nights, Market_Segment, Media_Code, Media Code Group, No. of Adult, No. of Children, No. of Infants, Contact Type, Odyssey Members]
Index: []

[0 rows x 36 columns]

In [15]:
df_analytic.drop(test_leads.index, inplace=True)
df_analytic.reset_index(drop=True, inplace=True)

count_after_dedup_test = df_analytic.shape[0]
count_after_dedup_test

80

In [16]:
count_final_data = count_after_dedup_test

In [17]:
# df_analytic.loc[(df_analytic['Email'] == 'jonmosley6@yahoo.com')]

In [18]:
df_analytic.replace('empty', '', inplace=True)

In [19]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Data Awal Zoho Analytic : "+str(count_data_awal))
print("Jumlah Data Email dan Phone Kosong : "+str(count_contact_type_empty))
print("Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : "+str(count_after_contact_type_empty))
print("Jumlah Data Email Yang Termasuk List Karma : "+str(count_email_karma))
print("Jumlah Data Email Setelah List Karma Dihapus : "+str(count_after_clean_karma))
print("Jumlah Data Test : "+str(count_leads_test))
print("Jumlah Data Email Setelah Data Test Dihapus : "+str(count_after_dedup_test))
print("Jumlah Data Akhir : "+str(count_final_data))

==========================================================
Summary
==========================================================
Jumlah Data Awal Zoho Analytic : 106
Jumlah Data Email dan Phone Kosong : 21
Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : 85
Jumlah Data Email Yang Termasuk List Karma : 5
Jumlah Data Email Setelah List Karma Dihapus : 80
Jumlah Data Test : 0
Jumlah Data Email Setelah Data Test Dihapus : 80
Jumlah Data Akhir : 80

In [20]:
df_analytic.to_excel(r'C:\Users\fajar\Documents\Python\Data\check_country_code_analytic.xlsx', index=False)