In [5]:
import pandas as pd
import re

import past_guest_module as pm

import sys
sys.path.append('../zoho_data_app/')

import main_module as m

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [6]:
path = r'C:\Users\fajar\Documents\Python\Data\Past Guest Data\Zoho Analytic\2024\Okt\29 Sep - 7 Okt\CRM_Rental_Report_29_Sep_-_07_Okt.xlsx'
df_analytic = pd.read_excel(path, dtype='string', sheet_name='Sheet1')
count_data_awal = df_analytic.shape[0]
df_analytic

,Booking_Id,TelNo,MobileNo,Email,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KSH018867,07767049555,<NA>,ahsaks@gmail.com,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF277226,Mr,...,2024-09-29 00:00:00,1,DIR,WEDDING,GROUP,2,0,0,,
1,KSH019065,<NA>,07902481240,ajury88@outlook.com,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF278852,Mrs,...,2024-09-29 00:00:00,1,DIR,WEDDING,GROUP,2,0,0,,
2,KB044464,<NA>,<NA>,allan.Leppeanen@karmabavaria.com,Karma Resorts,Other,Past Guests,Karma Bavaria,PF287635,Mr,...,2024-10-01 00:00:00,3,COMP,STAFF,COMP,2,0,0,,
3,KSH019256,07809746267,<NA>,andrew_beanson@hotmail.com,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF280564,Mr,...,2024-09-29 00:00:00,1,DIR,WEDDING,GROUP,2,0,0,,
4,KB044255,015141476578,<NA>,angelica@muth-fenn.de,Karma Resorts,Other,Past Guests,Karma Bavaria,PF286301,Frau,...,2024-09-29 00:00:00,1,LGR,LGR,GROUP,2,0,0,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,KK057117,+31 6 18595742,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Kandara,PF277206,Mr,...,2024-09-29 00:00:00,4,OTA,OTA,RETAIL,2,0,0,,
122,KB041001,+49 1517 0071386,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,PF266034,Frau,...,2024-10-05 00:00:00,2,OTA,OTA,RETAIL,3,1,0,,
123,KK054767,+351-214156075,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Kandara,PF271418,Mr,...,2024-10-04 00:00:00,3,OTA,OTA,RETAIL,2,0,0,,
124,KSH016711,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Salford Hall,<NA>,Mrs,...,2024-09-29 00:00:00,2,DIR,WEDDING,GROUP,1,0,0,,
125,KSH016713,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Salford Hall,<NA>,Mr,...,2024-09-29 00:00:00,2,DIR,WEDDING,GROUP,1,0,0,,

In [7]:
df_analytic.columns

Index(['Booking_Id', 'TelNo', 'MobileNo', 'Email', 'Lead Brand',
       'Lead Sub- Brand', 'Lead Source', 'Resort_Name', 'ProfileRef',
       'Salutation', 'First_Name', 'Surname', 'Gender', 'Language', 'DOB',
       'Street', 'Area', 'Town', 'County', 'Country', 'Nationality',
       'PostCode', 'Exclude From Mailing', 'Opt In', 'Booking Code',
       'Booking Status', 'DateArrival', 'DateDepart', 'No. of Nights',
       'Market_Segment', 'Media_Code', 'Media Code Group', 'No. of Adult',
       'No. of Children', 'No. of Infants', 'Contact Type', 'Odyssey Members'],
      dtype='object')

In [8]:
new_cols = ['Booking_Id', 'Lead Brand', 'Lead Sub- Brand', 'Lead Source',
       'Resort_Name', 'ProfileRef', 'Salutation', 'First_Name', 'Surname',
       'Gender', 'Language', 'DOB', 'Street', 'Area', 'Town', 'County',
       'Country', 'Nationality', 'PostCode', 'TelNo', 'MobileNo', 'Email',
       'Exclude From Mailing', 'Opt In', 'Booking Status',
       'DateArrival', 'DateDepart', 'No. of Nights', 'Market_Segment',
       'Media_Code', 'Media Code Group', 'No. of Adult', 'No. of Children',
       'No. of Infants', 'Contact Type', 'Odyssey Members']																																																																																																																																						

df_analytic = df_analytic.reindex(columns=new_cols)

In [9]:
df_analytic.fillna('empty', inplace=True)
df_analytic['Contact Type'] = 'empty'
df_analytic['Odyssey Members'] = 'NO'

In [10]:
df_analytic.loc[df_analytic['Surname'] == 'empty', 'Surname'] = '-'

In [11]:
df_analytic['Salutation'].replace('empty', '', inplace=True)
df_analytic['First_Name'].replace('empty', '', inplace=True)
df_analytic['Surname'].replace('empty', '', inplace=True)

df_analytic['Salutation'] = df_analytic['Salutation'].str.title()
df_analytic['First_Name'] = df_analytic['First_Name'].str.title()
df_analytic['Surname'] = df_analytic['Surname'].str.title()

df_analytic

C:\Users\fajar\AppData\Local\Temp\ipykernel_9304\2281604359.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['Salutation'].replace('empty', '', inplace=True)
C:\Users\fajar\AppData\Local\Temp\ipykernel_9304\2281604359.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['First_Name'].replace('empty', '', inplace=True)
C:\Users\fajar\AppData\Local\Temp\ipykernel_9304\2281604359.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['Surname'].replace('empty', '', inplace=True)

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KSH018867,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF277226,Mr,Abigail,Saks,Male,...,2024-09-29 00:00:00,1,DIR,WEDDING,GROUP,2,0,0,empty,NO
1,KSH019065,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF278852,Mrs,A,Godfrey,Female,...,2024-09-29 00:00:00,1,DIR,WEDDING,GROUP,2,0,0,empty,NO
2,KB044464,Karma Resorts,Other,Past Guests,Karma Bavaria,PF287635,Mr,Allan,Leppänen,Male,...,2024-10-01 00:00:00,3,COMP,STAFF,COMP,2,0,0,empty,NO
3,KSH019256,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF280564,Mr,Andrew,Beanson,Male,...,2024-09-29 00:00:00,1,DIR,WEDDING,GROUP,2,0,0,empty,NO
4,KB044255,Karma Resorts,Other,Past Guests,Karma Bavaria,PF286301,Frau,Angelika,Muth-Fenn,Unknown,...,2024-09-29 00:00:00,1,LGR,LGR,GROUP,2,0,0,empty,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,KK057117,Karma Resorts,Other,Past Guests,Karma Kandara,PF277206,Mr,Julien,Lardet,Male,...,2024-09-29 00:00:00,4,OTA,OTA,RETAIL,2,0,0,empty,NO
122,KB041001,Karma Resorts,Other,Past Guests,Karma Bavaria,PF266034,Frau,Ilona,Mohler,Female,...,2024-10-05 00:00:00,2,OTA,OTA,RETAIL,3,1,0,empty,NO
123,KK054767,Karma Resorts,Other,Past Guests,Karma Kandara,PF271418,Mr,Scheuringer,Philipp,Male,...,2024-10-04 00:00:00,3,OTA,OTA,RETAIL,2,0,0,empty,NO
124,KSH016711,Karma Resorts,Other,Past Guests,Karma Salford Hall,empty,Mrs,Janet,Edwards,Unknown,...,2024-09-29 00:00:00,2,DIR,WEDDING,GROUP,1,0,0,empty,NO
125,KSH016713,Karma Resorts,Other,Past Guests,Karma Salford Hall,empty,Mr,Brad,Hills,Unknown,...,2024-09-29 00:00:00,2,DIR,WEDDING,GROUP,1,0,0,empty,NO

In [12]:
m.clean_number(df_analytic, 'TelNo')
m.clean_number(df_analytic, 'MobileNo')
m.replace_not_valid_to_empty(df_analytic, 'TelNo')
m.replace_not_valid_to_empty(df_analytic, 'MobileNo')

df_analytic.loc[df_analytic['TelNo'].str.contains('00000'), 'TelNo'] = 'empty'
df_analytic.loc[df_analytic['MobileNo'].str.contains('00000'), 'MobileNo'] = 'empty'

m.clean_space(df_analytic, 'Email')
df_analytic['Email'] = m.lowercase(df_analytic, 'Email')

c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:67: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:68: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('[^0-9]','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:90: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)

In [13]:
pm.email_correction(df_analytic, 'Email')

c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:25: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_mail), '@mail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail), '@gmail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:35: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail_com), '@gmail.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:38: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail), '@hotmail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail_com), '@hotmail.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:45: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo), '@yahoo.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:48: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_ymail), '@ymail.', regex=True, inplace=True)

In [14]:
df_analytic.loc[(df_analytic['Email'] != 'empty') & ((df_analytic['TelNo'] != 'empty') | (df_analytic['MobileNo'] != 'empty')), 'Contact Type'] = 'Email and Phone'
df_analytic.loc[(df_analytic['Email'] != 'empty') & ((df_analytic['TelNo'] == 'empty') & (df_analytic['MobileNo'] == 'empty')), 'Contact Type'] = 'Email Only'
df_analytic.loc[(df_analytic['Email'] == 'empty') & ((df_analytic['TelNo'] != 'empty') | (df_analytic['MobileNo'] != 'empty')), 'Contact Type'] = 'Phone Only'

df_analytic.loc[df_analytic['Contact Type'] == 'empty'].to_csv(r'C:\Users\fajar\Documents\Python\Data\contact_type_empty_analytic.csv', index=False)

count_contact_type_empty = df_analytic.loc[df_analytic['Contact Type'] == 'empty'].shape[0]

df_analytic.drop(df_analytic.loc[df_analytic['Contact Type'] == 'empty'].index, inplace=True)
df_analytic.reset_index(drop=True, inplace=True)

count_after_contact_type_empty = df_analytic.shape[0]

df_analytic

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KSH018867,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF277226,Mr,Abigail,Saks,Male,...,2024-09-29 00:00:00,1,DIR,WEDDING,GROUP,2,0,0,Email and Phone,NO
1,KSH019065,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF278852,Mrs,A,Godfrey,Female,...,2024-09-29 00:00:00,1,DIR,WEDDING,GROUP,2,0,0,Email and Phone,NO
2,KB044464,Karma Resorts,Other,Past Guests,Karma Bavaria,PF287635,Mr,Allan,Leppänen,Male,...,2024-10-01 00:00:00,3,COMP,STAFF,COMP,2,0,0,Email Only,NO
3,KSH019256,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF280564,Mr,Andrew,Beanson,Male,...,2024-09-29 00:00:00,1,DIR,WEDDING,GROUP,2,0,0,Email and Phone,NO
4,KB044255,Karma Resorts,Other,Past Guests,Karma Bavaria,PF286301,Frau,Angelika,Muth-Fenn,Unknown,...,2024-09-29 00:00:00,1,LGR,LGR,GROUP,2,0,0,Email and Phone,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,KB043269,Karma Resorts,Other,Past Guests,Karma Bavaria,PF274543,,Iris,Wahl,Unknown,...,2024-10-05 00:00:00,1,OTA,OTA,RETAIL,2,2,0,Phone Only,NO
107,KK044954,Karma Resorts,Other,Past Guests,Karma Kandara,PF252923,Mr,Daesung,Jeon,Male,...,2024-10-05 00:00:00,2,OTA,OTA,RETAIL,2,0,0,Phone Only,NO
108,KK057117,Karma Resorts,Other,Past Guests,Karma Kandara,PF277206,Mr,Julien,Lardet,Male,...,2024-09-29 00:00:00,4,OTA,OTA,RETAIL,2,0,0,Phone Only,NO
109,KB041001,Karma Resorts,Other,Past Guests,Karma Bavaria,PF266034,Frau,Ilona,Mohler,Female,...,2024-10-05 00:00:00,2,OTA,OTA,RETAIL,3,1,0,Phone Only,NO
110,KK054767,Karma Resorts,Other,Past Guests,Karma Kandara,PF271418,Mr,Scheuringer,Philipp,Male,...,2024-10-04 00:00:00,3,OTA,OTA,RETAIL,2,0,0,Phone Only,NO

In [15]:
# Cek Email Karma
email_karma = m.find_karma(df_analytic, 'Email')
count_email_karma = email_karma.shape[0]
email_karma.to_csv(r'C:\Users\fajar\Documents\Python\Data\email_deleted_analytic.csv', index=False)

email_karma

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
2,KB044464,Karma Resorts,Other,Past Guests,Karma Bavaria,PF287635,Mr,Allan,Leppänen,Male,...,2024-10-01 00:00:00,3,COMP,STAFF,COMP,2,0,0,Email Only,NO
9,KB039535,Karma Resorts,Other,Past Guests,Karma Bavaria,PF066594,Mr,Christopher,Kindred,Male,...,2024-10-01 00:00:00,30,STAFF_PRIV,STAFF,COMP,1,0,0,Email and Phone,NO
15,KK061592,Karma Resorts,Other,Past Guests,Karma Kandara,PF090567,Mrs,Liu Zhao,Lan,Female,...,2024-09-29 00:00:00,1,HOUSE_USE,V_OWNER_NRB,COMP,1,0,0,Email and Phone,NO
48,KB044722,Karma Resorts,Other,Past Guests,Karma Bavaria,PF287731,Mr,Maik,Wilkinson,Male,...,2024-10-01 00:00:00,3,STAFF_PRIV,STAFF,COMP,1,0,0,Email Only,NO
72,KB044597,Karma Resorts,Other,Past Guests,Karma Bavaria,PF112154,Herr,Sebastian,Möller,Male,...,2024-10-01 00:00:00,1,COMP,STAFF,COMP,1,0,0,Email and Phone,NO

In [16]:
# delete email Karma
count_after_clean_karma = m.delete_karma(df_analytic, 'Email')

df_analytic

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KSH018867,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF277226,Mr,Abigail,Saks,Male,...,2024-09-29 00:00:00,1,DIR,WEDDING,GROUP,2,0,0,Email and Phone,NO
1,KSH019065,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF278852,Mrs,A,Godfrey,Female,...,2024-09-29 00:00:00,1,DIR,WEDDING,GROUP,2,0,0,Email and Phone,NO
2,KSH019256,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF280564,Mr,Andrew,Beanson,Male,...,2024-09-29 00:00:00,1,DIR,WEDDING,GROUP,2,0,0,Email and Phone,NO
3,KB044255,Karma Resorts,Other,Past Guests,Karma Bavaria,PF286301,Frau,Angelika,Muth-Fenn,Unknown,...,2024-09-29 00:00:00,1,LGR,LGR,GROUP,2,0,0,Email and Phone,NO
4,KSM013596,Karma Resorts,Other,Past Guests,Karma St Martins,PF281950,Mr,Friedrich,Byloff,Unknown,...,2024-09-30 00:00:00,4,DIR,TA,RETAIL,2,0,0,Email and Phone,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,KB043269,Karma Resorts,Other,Past Guests,Karma Bavaria,PF274543,,Iris,Wahl,Unknown,...,2024-10-05 00:00:00,1,OTA,OTA,RETAIL,2,2,0,Phone Only,NO
102,KK044954,Karma Resorts,Other,Past Guests,Karma Kandara,PF252923,Mr,Daesung,Jeon,Male,...,2024-10-05 00:00:00,2,OTA,OTA,RETAIL,2,0,0,Phone Only,NO
103,KK057117,Karma Resorts,Other,Past Guests,Karma Kandara,PF277206,Mr,Julien,Lardet,Male,...,2024-09-29 00:00:00,4,OTA,OTA,RETAIL,2,0,0,Phone Only,NO
104,KB041001,Karma Resorts,Other,Past Guests,Karma Bavaria,PF266034,Frau,Ilona,Mohler,Female,...,2024-10-05 00:00:00,2,OTA,OTA,RETAIL,3,1,0,Phone Only,NO
105,KK054767,Karma Resorts,Other,Past Guests,Karma Kandara,PF271418,Mr,Scheuringer,Philipp,Male,...,2024-10-04 00:00:00,3,OTA,OTA,RETAIL,2,0,0,Phone Only,NO

In [17]:
df_analytic['Salutation']

0        Mr
1       Mrs
2        Mr
3      Frau
4        Mr
       ...
101
102      Mr
103      Mr
104    Frau
105      Mr
Name: Salutation, Length: 106, dtype: string

In [18]:
# Cek leads test
test_leads = df_analytic.loc[
    
        df_analytic['Email'].str.contains('^test@', flags=re.I, regex=True) |
        df_analytic['Email'].str.contains('\+test', flags=re.I, regex=True) |
    
        df_analytic['First_Name'].str.contains('^test$', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('^test$', flags=re.I, regex=True) |

        df_analytic['First_Name'].str.contains('test 1', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('test 2', flags=re.I, regex=True)|
        df_analytic['First_Name'].str.contains('test1', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('test2', flags=re.I, regex=True)|

        df_analytic['First_Name'].str.contains(' test ', flags=re.I, regex=True) | 
        df_analytic['Surname'].str.contains(' test ', flags=re.I, regex=True) | 
        df_analytic['Surname'].str.contains(' test$', flags=re.I, regex=True)
    ]

count_leads_test = test_leads.shape[0]

test_leads.to_csv(r'C:\Users\fajar\Documents\Python\Data\test_leads_analytic.csv', index=False)
test_leads

Empty DataFrame
Columns: [Booking_Id, Lead Brand, Lead Sub- Brand, Lead Source, Resort_Name, ProfileRef, Salutation, First_Name, Surname, Gender, Language, DOB, Street, Area, Town, County, Country, Nationality, PostCode, TelNo, MobileNo, Email, Exclude From Mailing, Opt In, Booking Status, DateArrival, DateDepart, No. of Nights, Market_Segment, Media_Code, Media Code Group, No. of Adult, No. of Children, No. of Infants, Contact Type, Odyssey Members]
Index: []

[0 rows x 36 columns]

In [19]:
df_analytic.drop(test_leads.index, inplace=True)
df_analytic.reset_index(drop=True, inplace=True)

count_after_dedup_test = df_analytic.shape[0]
count_after_dedup_test

106

In [20]:
count_final_data = count_after_dedup_test

In [21]:
# df_analytic.loc[(df_analytic['Email'] == 'jonmosley6@yahoo.com')]

In [22]:
df_analytic.replace('empty', '', inplace=True)

In [23]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Data Awal Zoho Analytic : "+str(count_data_awal))
print("Jumlah Data Email dan Phone Kosong : "+str(count_contact_type_empty))
print("Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : "+str(count_after_contact_type_empty))
print("Jumlah Data Email Yang Termasuk List Karma : "+str(count_email_karma))
print("Jumlah Data Email Setelah List Karma Dihapus : "+str(count_after_clean_karma))
print("Jumlah Data Test : "+str(count_leads_test))
print("Jumlah Data Email Setelah Data Test Dihapus : "+str(count_after_dedup_test))
print("Jumlah Data Akhir : "+str(count_final_data))

==========================================================
Summary
==========================================================
Jumlah Data Awal Zoho Analytic : 126
Jumlah Data Email dan Phone Kosong : 15
Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : 111
Jumlah Data Email Yang Termasuk List Karma : 5
Jumlah Data Email Setelah List Karma Dihapus : 106
Jumlah Data Test : 0
Jumlah Data Email Setelah Data Test Dihapus : 106
Jumlah Data Akhir : 106

In [24]:
df_analytic.to_excel(r'C:\Users\fajar\Documents\Python\Data\check_country_code_analytic.xlsx', index=False)