In [3]:
import pandas as pd
import re

import past_guest_module as pm

import sys
sys.path.append('../zoho_data_app/')

import main_module as m

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [4]:
path = r'C:\Users\fajar\Documents\Python\Data\Past Guest Data\Zoho Analytic\2025\Feb\26 Jan - 3 Feb\CRM_Rental_Report_26_Jan_-_3_Feb.xlsx'
df_analytic = pd.read_excel(path, dtype='string', sheet_name='Sheet1')
count_data_awal = df_analytic.shape[0]
df_analytic

,Booking_Id,TelNo,MobileNo,Email,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK067950,082234031072,082234031072,1395259590@qq.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF299984,Mr,...,2025-01-26 00:00:00,3,HOUSE_USE,V_OWNER,COMP,7,0,0,,
1,KK067094,+86138131545460,86138131545460,210153682@gmail.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF298370,Mr,...,2025-01-31 00:00:00,1,OTA,OTA,RETAIL,4,0,0,,
2,KK066875,+86186755915,86186755915,350588817@gmail.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF298020,Mr,...,2025-01-30 00:00:00,1,OTA,OTA,RETAIL,4,0,0,,
3,KK069123,08572827337,<NA>,a@asd.ci,Karma Resorts,Other,Past Guests,Karma Kandara,PF302419,Mrs,...,2025-02-01 00:00:00,1,DIGITAL,GHPA,DIGITAL,2,0,0,,
4,KK067439,7021713456,<NA>,abc@gmail.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF298926,Mr,...,2025-02-01 00:00:00,3,DIGITAL,GHPA,DIGITAL,2,0,0,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,KSH020271,+44 7843 717977,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF287910,<NA>,...,2025-01-31 00:00:00,4,OTA,OTA,RETAIL,2,0,0,,
127,KB043376,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,<NA>,<NA>,...,2025-01-30 14:00:00,0,CB,CB,GROUP,1,0,0,,
128,KB046155,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,PF295139,Firma,...,2025-01-26 14:30:00,0,LGR,LGR,GROUP,1,0,0,,
129,KLM008155,<NA>,0741136905,<NA>,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF301640,Mrs,...,2025-01-26 00:00:00,1,DIR,TEL,RETAIL,2,0,0,,
130,KB043375,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,<NA>,<NA>,...,2025-01-29 18:00:00,0,CB,CB,GROUP,1,0,0,,

In [5]:
df_analytic.columns

Index(['Booking_Id', 'TelNo', 'MobileNo', 'Email', 'Lead Brand',
       'Lead Sub- Brand', 'Lead Source', 'Resort_Name', 'ProfileRef',
       'Salutation', 'First_Name', 'Surname', 'Gender', 'Language', 'DOB',
       'Street', 'Area', 'Town', 'County', 'Country', 'Nationality',
       'PostCode', 'Exclude From Mailing', 'Opt In', 'Booking Code',
       'Booking Status', 'DateArrival', 'DateDepart', 'No. of Nights',
       'Market_Segment', 'Media_Code', 'Media Code Group', 'No. of Adult',
       'No. of Children', 'No. of Infants', 'Contact Type', 'Odyssey Members'],
      dtype='object')

In [6]:
new_cols = ['Booking_Id', 'Lead Brand', 'Lead Sub- Brand', 'Lead Source',
       'Resort_Name', 'ProfileRef', 'Salutation', 'First_Name', 'Surname',
       'Gender', 'Language', 'DOB', 'Street', 'Area', 'Town', 'County',
       'Country', 'Nationality', 'PostCode', 'TelNo', 'MobileNo', 'Email',
       'Exclude From Mailing', 'Opt In', 'Booking Status',
       'DateArrival', 'DateDepart', 'No. of Nights', 'Market_Segment',
       'Media_Code', 'Media Code Group', 'No. of Adult', 'No. of Children',
       'No. of Infants', 'Contact Type', 'Odyssey Members']																																																																																																																																						

df_analytic = df_analytic.reindex(columns=new_cols)

In [7]:
df_analytic.fillna('empty', inplace=True)
df_analytic['Contact Type'] = 'empty'
df_analytic['Odyssey Members'] = 'NO'

In [8]:
df_analytic.loc[df_analytic['Surname'] == 'empty', 'Surname'] = '-'

In [9]:
df_analytic['Salutation'].replace('empty', '', inplace=True)
df_analytic['First_Name'].replace('empty', '', inplace=True)
df_analytic['Surname'].replace('empty', '', inplace=True)

df_analytic['Salutation'] = df_analytic['Salutation'].str.title()
df_analytic['First_Name'] = df_analytic['First_Name'].str.title()
df_analytic['Surname'] = df_analytic['Surname'].str.title()

df_analytic

C:\Users\fajar\AppData\Local\Temp\ipykernel_19292\2281604359.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['Salutation'].replace('empty', '', inplace=True)
C:\Users\fajar\AppData\Local\Temp\ipykernel_19292\2281604359.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['First_Name'].replace('empty', '', inplace=True)
C:\Users\fajar\AppData\Local\Temp\ipykernel_19292\2281604359.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['Surname'].replace('empty', '', inplace=True)

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK067950,Karma Resorts,Other,Past Guests,Karma Kandara,PF299984,Mr,Feng,Fengyuan,Male,...,2025-01-26 00:00:00,3,HOUSE_USE,V_OWNER,COMP,7,0,0,empty,NO
1,KK067094,Karma Resorts,Other,Past Guests,Karma Kandara,PF298370,Mr,Jie,Pan,Male,...,2025-01-31 00:00:00,1,OTA,OTA,RETAIL,4,0,0,empty,NO
2,KK066875,Karma Resorts,Other,Past Guests,Karma Kandara,PF298020,Mr,Wei,Li,Male,...,2025-01-30 00:00:00,1,OTA,OTA,RETAIL,4,0,0,empty,NO
3,KK069123,Karma Resorts,Other,Past Guests,Karma Kandara,PF302419,Mrs,Asd,Asdd,Female,...,2025-02-01 00:00:00,1,DIGITAL,GHPA,DIGITAL,2,0,0,empty,NO
4,KK067439,Karma Resorts,Other,Past Guests,Karma Kandara,PF298926,Mr,Abc,Def,Male,...,2025-02-01 00:00:00,3,DIGITAL,GHPA,DIGITAL,2,0,0,empty,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,KSH020271,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF287910,,Peter,Kenyon,Unknown,...,2025-01-31 00:00:00,4,OTA,OTA,RETAIL,2,0,0,empty,NO
127,KB043376,Karma Resorts,Other,Past Guests,Karma Bavaria,empty,,Munich Re,T30945310,Unknown,...,2025-01-30 14:00:00,0,CB,CB,GROUP,1,0,0,empty,NO
128,KB046155,Karma Resorts,Other,Past Guests,Karma Bavaria,PF295139,Firma,Karma,Bavaria,Unknown,...,2025-01-26 14:30:00,0,LGR,LGR,GROUP,1,0,0,empty,NO
129,KLM008155,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF301640,Mrs,Nicola,Peters,Female,...,2025-01-26 00:00:00,1,DIR,TEL,RETAIL,2,0,0,empty,NO
130,KB043375,Karma Resorts,Other,Past Guests,Karma Bavaria,empty,,Munich Re,T30945310,Unknown,...,2025-01-29 18:00:00,0,CB,CB,GROUP,1,0,0,empty,NO

In [10]:
m.clean_number(df_analytic, 'TelNo')
m.clean_number(df_analytic, 'MobileNo')
m.replace_not_valid_to_empty(df_analytic, 'TelNo')
m.replace_not_valid_to_empty(df_analytic, 'MobileNo')

df_analytic.loc[df_analytic['TelNo'].str.contains('00000'), 'TelNo'] = 'empty'
df_analytic.loc[df_analytic['MobileNo'].str.contains('00000'), 'MobileNo'] = 'empty'

m.clean_space(df_analytic, 'Email')
df_analytic['Email'] = m.lowercase(df_analytic, 'Email')
m.email_correction(df_analytic, 'Email')

c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:67: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:68: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('[^0-9]','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:90: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:223: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('^mailto:|-primary$|-pri$|-Mrs$|(noemailtobesent)$','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:251: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_mail), '@mail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:252: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail), '@gmail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:253: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail_com), '@gmail.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:254: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail), '@hotmail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:255: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail_com), '@hotmail.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:256: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_com), '@yahoo.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:257: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo), '@yahoo.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:258: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_in), '@yahoo.co.in', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:273: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df_columns].loc[~df[df_columns].str.contains('@', df_columns, na=False)] = ''

In [11]:
m.email_correction(df_analytic, 'Email')

c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:223: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('^mailto:|-primary$|-pri$|-Mrs$|(noemailtobesent)$','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:251: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_mail), '@mail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:252: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail), '@gmail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:253: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail_com), '@gmail.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:254: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail), '@hotmail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:255: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail_com), '@hotmail.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:256: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_com), '@yahoo.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:257: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo), '@yahoo.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:258: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_in), '@yahoo.co.in', regex=True, inplace=True)

In [12]:
df_analytic.loc[(df_analytic['Email'] != 'empty') & ((df_analytic['TelNo'] != 'empty') | (df_analytic['MobileNo'] != 'empty')), 'Contact Type'] = 'Email and Phone'
df_analytic.loc[(df_analytic['Email'] != 'empty') & ((df_analytic['TelNo'] == 'empty') & (df_analytic['MobileNo'] == 'empty')), 'Contact Type'] = 'Email Only'
df_analytic.loc[(df_analytic['Email'] == 'empty') & ((df_analytic['TelNo'] != 'empty') | (df_analytic['MobileNo'] != 'empty')), 'Contact Type'] = 'Phone Only'

df_analytic.loc[df_analytic['Contact Type'] == 'empty'].to_csv(r'C:\Users\fajar\Documents\Python\Data\contact_type_empty_analytic.csv', index=False)

count_contact_type_empty = df_analytic.loc[df_analytic['Contact Type'] == 'empty'].shape[0]

df_analytic.drop(df_analytic.loc[df_analytic['Contact Type'] == 'empty'].index, inplace=True)
df_analytic.reset_index(drop=True, inplace=True)

count_after_contact_type_empty = df_analytic.shape[0]

df_analytic

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK067950,Karma Resorts,Other,Past Guests,Karma Kandara,PF299984,Mr,Feng,Fengyuan,Male,...,2025-01-26 00:00:00,3,HOUSE_USE,V_OWNER,COMP,7,0,0,Email and Phone,NO
1,KK067094,Karma Resorts,Other,Past Guests,Karma Kandara,PF298370,Mr,Jie,Pan,Male,...,2025-01-31 00:00:00,1,OTA,OTA,RETAIL,4,0,0,Email and Phone,NO
2,KK066875,Karma Resorts,Other,Past Guests,Karma Kandara,PF298020,Mr,Wei,Li,Male,...,2025-01-30 00:00:00,1,OTA,OTA,RETAIL,4,0,0,Email and Phone,NO
3,KK069123,Karma Resorts,Other,Past Guests,Karma Kandara,PF302419,Mrs,Asd,Asdd,Female,...,2025-02-01 00:00:00,1,DIGITAL,GHPA,DIGITAL,2,0,0,Email and Phone,NO
4,KK067439,Karma Resorts,Other,Past Guests,Karma Kandara,PF298926,Mr,Abc,Def,Male,...,2025-02-01 00:00:00,3,DIGITAL,GHPA,DIGITAL,2,0,0,Email and Phone,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,KSH020271,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF287910,,Peter,Kenyon,Unknown,...,2025-01-31 00:00:00,4,OTA,OTA,RETAIL,2,0,0,Email and Phone,NO
127,KB043376,Karma Resorts,Other,Past Guests,Karma Bavaria,empty,,Munich Re,T30945310,Unknown,...,2025-01-30 14:00:00,0,CB,CB,GROUP,1,0,0,Email Only,NO
128,KB046155,Karma Resorts,Other,Past Guests,Karma Bavaria,PF295139,Firma,Karma,Bavaria,Unknown,...,2025-01-26 14:30:00,0,LGR,LGR,GROUP,1,0,0,Email Only,NO
129,KLM008155,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF301640,Mrs,Nicola,Peters,Female,...,2025-01-26 00:00:00,1,DIR,TEL,RETAIL,2,0,0,Email and Phone,NO
130,KB043375,Karma Resorts,Other,Past Guests,Karma Bavaria,empty,,Munich Re,T30945310,Unknown,...,2025-01-29 18:00:00,0,CB,CB,GROUP,1,0,0,Email Only,NO

In [13]:
# Cek Email Karma
email_karma = m.find_karma(df_analytic, 'Email')
count_email_karma = email_karma.shape[0]
email_karma.to_csv(r'C:\Users\fajar\Documents\Python\Data\email_deleted_analytic.csv', index=False)

email_karma

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
5,KLM007947,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF287311,Mr,Adrian,Fatechand,Male,...,2025-01-29 00:00:00,3,COMP,STAFF,COMP,1,0,0,Email and Phone,NO
13,KLM008160,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF066594,Mr,Christopher,Kindred,Male,...,2025-01-27 00:00:00,1,COMP,STAFF,COMP,2,0,0,Email and Phone,NO
17,KB047601,Karma Resorts,Other,Past Guests,Karma Bavaria,PF233671,Mr,Dario,Quinteros,Male,...,2025-01-29 00:00:00,2,COMP,STAFF,COMP,1,0,0,Email and Phone,NO
18,KB047032,Karma Resorts,Other,Past Guests,Karma Bavaria,PF102564,Mr,David,Beaghe,Male,...,2025-01-30 00:00:00,3,COMP,STAFF,COMP,1,0,0,Email and Phone,NO
21,KK066511,Karma Resorts,Other,Past Guests,Karma Kandara,PF097952,-,Dominika,Garajova,Female,...,2025-01-30 00:00:00,1,COMP,RESERVED,KC,2,0,0,Email and Phone,NO
22,KK067057,Karma Resorts,Other,Past Guests,Karma Kandara,PF097952,-,Dominika,Garajova,Female,...,2025-01-31 00:00:00,1,COMP,RESERVED,KC,4,0,0,Email and Phone,NO
23,KK066510,Karma Resorts,Other,Past Guests,Karma Kandara,PF097952,-,Dominika,Garajova,Female,...,2025-01-30 00:00:00,1,COMP,RESERVED,KC,4,4,0,Email and Phone,NO
40,KK067049,Karma Resorts,Other,Past Guests,Karma Kandara,PF298275,,Jessica,Fernandes,Unknown,...,2025-02-02 00:00:00,2,COMP,RESERVED,KC,3,0,0,Email and Phone,NO
41,KK067051,Karma Resorts,Other,Past Guests,Karma Kandara,PF298275,,Jessica,Fernandes,Unknown,...,2025-02-02 00:00:00,3,COMP,RESERVED,KC,2,0,0,Email and Phone,NO
42,KK067050,Karma Resorts,Other,Past Guests,Karma Kandara,PF298275,,Jessica,Fernandes,Unknown,...,2025-02-01 00:00:00,2,COMP,RESERVED,KC,4,0,0,Email and Phone,NO
43,KK067056,Karma Resorts,Other,Past Guests,Karma Kandara,PF298275,,Jessica,Fernandes,Unknown,...,2025-01-31 00:00:00,1,COMP,RESERVED,KC,4,0,0,Email and Phone,NO
44,KK067052,Karma Resorts,Other,Past Guests,Karma Kandara,PF298275,,Jessica,Fernandes,Unknown,...,2025-02-02 00:00:00,3,COMP,RESERVED,KC,2,0,0,Email and Phone,NO
45,KLM006953,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF210587,Mrs,Jo,Richards,Female,...,2025-01-31 00:00:00,3,COMP,STAFF,COMP,2,0,0,Email and Phone,NO
46,KB046584,Karma Resorts,Other,Past Guests,Karma Bavaria,PF250060,Mr,Joseph,Antonishek,Male,...,2025-01-26 00:00:00,7,COMP,STAFF,COMP,1,0,0,Email and Phone,NO
49,KLM007652,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF261021,Ms,Luisa,Nunes,Female,...,2025-01-30 00:00:00,4,COMP,STAFF,COMP,2,0,0,Email and Phone,NO
65,KB047031,Karma Resorts,Other,Past Guests,Karma Bavaria,PF112154,Mr,Sebastian,Moeller,Male,...,2025-01-31 00:00:00,4,COMP,STAFF,COMP,1,0,0,Email and Phone,NO
67,KK047347,Karma Resorts,Other,Past Guests,Karma Kandara,PF179260,Mr,Shaun,Duenhofen,Male,...,2025-01-31 00:00:00,396,HOUSE_USE,STAFF,COMP,2,1,0,Email and Phone,NO
91,KB047564,Karma Resorts,Other,Past Guests,Karma Bavaria,PF120802,Mr,Valerios,Koutsonis,Male,...,2025-01-30 00:00:00,2,COMP,WALKIN,RETAIL,2,0,0,Email and Phone,NO

In [14]:
# delete email Karma
count_after_clean_karma = m.delete_karma(df_analytic, 'Email')

df_analytic

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK067950,Karma Resorts,Other,Past Guests,Karma Kandara,PF299984,Mr,Feng,Fengyuan,Male,...,2025-01-26 00:00:00,3,HOUSE_USE,V_OWNER,COMP,7,0,0,Email and Phone,NO
1,KK067094,Karma Resorts,Other,Past Guests,Karma Kandara,PF298370,Mr,Jie,Pan,Male,...,2025-01-31 00:00:00,1,OTA,OTA,RETAIL,4,0,0,Email and Phone,NO
2,KK066875,Karma Resorts,Other,Past Guests,Karma Kandara,PF298020,Mr,Wei,Li,Male,...,2025-01-30 00:00:00,1,OTA,OTA,RETAIL,4,0,0,Email and Phone,NO
3,KK069123,Karma Resorts,Other,Past Guests,Karma Kandara,PF302419,Mrs,Asd,Asdd,Female,...,2025-02-01 00:00:00,1,DIGITAL,GHPA,DIGITAL,2,0,0,Email and Phone,NO
4,KK067439,Karma Resorts,Other,Past Guests,Karma Kandara,PF298926,Mr,Abc,Def,Male,...,2025-02-01 00:00:00,3,DIGITAL,GHPA,DIGITAL,2,0,0,Email and Phone,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,KSH020271,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF287910,,Peter,Kenyon,Unknown,...,2025-01-31 00:00:00,4,OTA,OTA,RETAIL,2,0,0,Email and Phone,NO
109,KB043376,Karma Resorts,Other,Past Guests,Karma Bavaria,empty,,Munich Re,T30945310,Unknown,...,2025-01-30 14:00:00,0,CB,CB,GROUP,1,0,0,Email Only,NO
110,KB046155,Karma Resorts,Other,Past Guests,Karma Bavaria,PF295139,Firma,Karma,Bavaria,Unknown,...,2025-01-26 14:30:00,0,LGR,LGR,GROUP,1,0,0,Email Only,NO
111,KLM008155,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF301640,Mrs,Nicola,Peters,Female,...,2025-01-26 00:00:00,1,DIR,TEL,RETAIL,2,0,0,Email and Phone,NO
112,KB043375,Karma Resorts,Other,Past Guests,Karma Bavaria,empty,,Munich Re,T30945310,Unknown,...,2025-01-29 18:00:00,0,CB,CB,GROUP,1,0,0,Email Only,NO

In [15]:
df_analytic['Salutation']

0         Mr
1         Mr
2         Mr
3        Mrs
4         Mr
       ...
108
109
110    Firma
111      Mrs
112
Name: Salutation, Length: 113, dtype: string

In [16]:
# Cek leads test
test_leads = df_analytic.loc[
    
        df_analytic['Email'].str.contains('^test@', flags=re.I, regex=True) |
        df_analytic['Email'].str.contains('\+test', flags=re.I, regex=True) |
    
        df_analytic['First_Name'].str.contains('^test$', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('^test$', flags=re.I, regex=True) |

        df_analytic['First_Name'].str.contains('test 1', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('test 2', flags=re.I, regex=True)|
        df_analytic['First_Name'].str.contains('test1', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('test2', flags=re.I, regex=True)|

        df_analytic['First_Name'].str.contains(' test ', flags=re.I, regex=True) | 
        df_analytic['Surname'].str.contains(' test ', flags=re.I, regex=True) | 
        df_analytic['Surname'].str.contains(' test$', flags=re.I, regex=True)
    ]

count_leads_test = test_leads.shape[0]

test_leads.to_csv(r'C:\Users\fajar\Documents\Python\Data\test_leads_analytic.csv', index=False)
test_leads

Empty DataFrame
Columns: [Booking_Id, Lead Brand, Lead Sub- Brand, Lead Source, Resort_Name, ProfileRef, Salutation, First_Name, Surname, Gender, Language, DOB, Street, Area, Town, County, Country, Nationality, PostCode, TelNo, MobileNo, Email, Exclude From Mailing, Opt In, Booking Status, DateArrival, DateDepart, No. of Nights, Market_Segment, Media_Code, Media Code Group, No. of Adult, No. of Children, No. of Infants, Contact Type, Odyssey Members]
Index: []

[0 rows x 36 columns]

In [17]:
df_analytic.drop(test_leads.index, inplace=True)
df_analytic.reset_index(drop=True, inplace=True)

count_after_dedup_test = df_analytic.shape[0]
count_after_dedup_test

113

In [18]:
count_final_data = count_after_dedup_test

In [19]:
# df_analytic.loc[(df_analytic['Email'] == 'jonmosley6@yahoo.com')]

In [20]:
df_analytic.replace('empty', '', inplace=True)

In [21]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Data Awal Zoho Analytic : "+str(count_data_awal))
print("Jumlah Data Email dan Phone Kosong : "+str(count_contact_type_empty))
print("Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : "+str(count_after_contact_type_empty))
print("Jumlah Data Email Yang Termasuk List Karma : "+str(count_email_karma))
print("Jumlah Data Email Setelah List Karma Dihapus : "+str(count_after_clean_karma))
print("Jumlah Data Test : "+str(count_leads_test))
print("Jumlah Data Email Setelah Data Test Dihapus : "+str(count_after_dedup_test))
print("Jumlah Data Akhir : "+str(count_final_data))

==========================================================
Summary
==========================================================
Jumlah Data Awal Zoho Analytic : 131
Jumlah Data Email dan Phone Kosong : 0
Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : 131
Jumlah Data Email Yang Termasuk List Karma : 18
Jumlah Data Email Setelah List Karma Dihapus : 113
Jumlah Data Test : 0
Jumlah Data Email Setelah Data Test Dihapus : 113
Jumlah Data Akhir : 113

In [22]:
df_analytic.to_excel(r'C:\Users\fajar\Documents\Python\Data\check_country_code_analytic.xlsx', index=False)