In [3]:
import pandas as pd
import re

import past_guest_module as pm

import sys
sys.path.append('../zoho_data_app/')

import main_module as m

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [4]:
path = r'C:\Users\fajar\Documents\Python\Data\Past Guest Data\Zoho Analytic\2024\Okt\13 Okt - 21 Okt\CRM_Rental_Report_13_Okt_-_21_Okt.xlsx'
df_analytic = pd.read_excel(path, dtype='string', sheet_name='Sheet1')
count_data_awal = df_analytic.shape[0]
df_analytic

,Booking_Id,TelNo,MobileNo,Email,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KB038782,<NA>,<NA>,jmatthews21@hotmail.com,Karma Resorts,Other,Past Guests,Karma Bavaria,PF254425,Frau,...,2024-10-14 20:30:00,0,DIR,WALKIN,RETAIL,1,0,0,,
1,KB044845,+49 172 6102071,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,PF288435,Herr,...,2024-10-13 00:00:00,1,OTA,OTA,RETAIL,2,0,0,,
2,KB040418,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,PF080008,<NA>,...,2024-10-13 19:30:00,0,CB,CB,GROUP,1,0,0,,
3,KK062364,0816861968,0816861968,utamaharry1@gmail.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF213219,Mr,...,2024-10-15 00:00:00,1,HOUSE_USE,V_OWNER_NRB,COMP,2,0,0,,
4,KK045201,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Kandara,PF253599,Ms,...,2024-10-16 00:00:00,3,TO,TO,RETAIL,2,0,0,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,KK062379,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Kandara,PF289583,Mr,...,2024-10-14 00:00:00,1,HOUSE_USE,V_OWNER_NRB,COMP,4,0,0,,
120,KK052041,<NA>,447767700834,ed.king@karmagroup.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF092162,Mr,...,2024-10-15 00:00:00,10,HOUSE_USE,STAFF,COMP,1,0,0,,
121,KLM006240,<NA>,07816854444,angiekkennedy101@hotmail.com,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF282393,Mr,...,2024-10-14 00:00:00,1,DIR,WEDDING,GROUP,2,0,0,,
122,KLM006752,<NA>,<NA>,adrian.fatechand@karmagroup.com,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF267043,Mr,...,2024-10-13 00:00:00,2,COMP,STAFF,COMP,1,0,0,,
123,KLM005370,<NA>,07792404003,alanmcharrie@aol.com,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF271129,Mr,...,2024-10-14 00:00:00,1,WEDDING,WEDDING,GROUP,2,0,0,,

In [5]:
df_analytic.columns

Index(['Booking_Id', 'TelNo', 'MobileNo', 'Email', 'Lead Brand',
       'Lead Sub- Brand', 'Lead Source', 'Resort_Name', 'ProfileRef',
       'Salutation', 'First_Name', 'Surname', 'Gender', 'Language', 'DOB',
       'Street', 'Area', 'Town', 'County', 'Country', 'Nationality',
       'PostCode', 'Exclude From Mailing', 'Opt In', 'Booking Code',
       'Booking Status', 'DateArrival', 'DateDepart', 'No. of Nights',
       'Market_Segment', 'Media_Code', 'Media Code Group', 'No. of Adult',
       'No. of Children', 'No. of Infants', 'Contact Type', 'Odyssey Members'],
      dtype='object')

In [6]:
new_cols = ['Booking_Id', 'Lead Brand', 'Lead Sub- Brand', 'Lead Source',
       'Resort_Name', 'ProfileRef', 'Salutation', 'First_Name', 'Surname',
       'Gender', 'Language', 'DOB', 'Street', 'Area', 'Town', 'County',
       'Country', 'Nationality', 'PostCode', 'TelNo', 'MobileNo', 'Email',
       'Exclude From Mailing', 'Opt In', 'Booking Status',
       'DateArrival', 'DateDepart', 'No. of Nights', 'Market_Segment',
       'Media_Code', 'Media Code Group', 'No. of Adult', 'No. of Children',
       'No. of Infants', 'Contact Type', 'Odyssey Members']																																																																																																																																						

df_analytic = df_analytic.reindex(columns=new_cols)

In [7]:
df_analytic.fillna('empty', inplace=True)
df_analytic['Contact Type'] = 'empty'
df_analytic['Odyssey Members'] = 'NO'

In [8]:
df_analytic.loc[df_analytic['Surname'] == 'empty', 'Surname'] = '-'

In [9]:
df_analytic['Salutation'].replace('empty', '', inplace=True)
df_analytic['First_Name'].replace('empty', '', inplace=True)
df_analytic['Surname'].replace('empty', '', inplace=True)

df_analytic['Salutation'] = df_analytic['Salutation'].str.title()
df_analytic['First_Name'] = df_analytic['First_Name'].str.title()
df_analytic['Surname'] = df_analytic['Surname'].str.title()

df_analytic

C:\Users\fajar\AppData\Local\Temp\ipykernel_6172\2281604359.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['Salutation'].replace('empty', '', inplace=True)
C:\Users\fajar\AppData\Local\Temp\ipykernel_6172\2281604359.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['First_Name'].replace('empty', '', inplace=True)
C:\Users\fajar\AppData\Local\Temp\ipykernel_6172\2281604359.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['Surname'].replace('empty', '', inplace=True)

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KB038782,Karma Resorts,Other,Past Guests,Karma Bavaria,PF254425,Frau,Jeannette,Matthews,Female,...,2024-10-14 20:30:00,0,DIR,WALKIN,RETAIL,1,0,0,empty,NO
1,KB044845,Karma Resorts,Other,Past Guests,Karma Bavaria,PF288435,Herr,Michael,Haeffner,Male,...,2024-10-13 00:00:00,1,OTA,OTA,RETAIL,2,0,0,empty,NO
2,KB040418,Karma Resorts,Other,Past Guests,Karma Bavaria,PF080008,,Kea,Marketing Gmbh,Unknown,...,2024-10-13 19:30:00,0,CB,CB,GROUP,1,0,0,empty,NO
3,KK062364,Karma Resorts,Other,Past Guests,Karma Kandara,PF213219,Mr,Harry,Utama,Male,...,2024-10-15 00:00:00,1,HOUSE_USE,V_OWNER_NRB,COMP,2,0,0,empty,NO
4,KK045201,Karma Resorts,Other,Past Guests,Karma Kandara,PF253599,Ms,Agnese,Graziani,Female,...,2024-10-16 00:00:00,3,TO,TO,RETAIL,2,0,0,empty,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,KK062379,Karma Resorts,Other,Past Guests,Karma Kandara,PF289583,Mr,Antoine,Rosset,Unknown,...,2024-10-14 00:00:00,1,HOUSE_USE,V_OWNER_NRB,COMP,4,0,0,empty,NO
120,KK052041,Karma Resorts,Other,Past Guests,Karma Kandara,PF092162,Mr,Ed,King,Male,...,2024-10-15 00:00:00,10,HOUSE_USE,STAFF,COMP,1,0,0,empty,NO
121,KLM006240,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF282393,Mr,John,Kennedy,Male,...,2024-10-14 00:00:00,1,DIR,WEDDING,GROUP,2,0,0,empty,NO
122,KLM006752,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF267043,Mr,Adrian,Fatechand,Unknown,...,2024-10-13 00:00:00,2,COMP,STAFF,COMP,1,0,0,empty,NO
123,KLM005370,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF271129,Mr,Alan,Mcharrie,Male,...,2024-10-14 00:00:00,1,WEDDING,WEDDING,GROUP,2,0,0,empty,NO

In [10]:
m.clean_number(df_analytic, 'TelNo')
m.clean_number(df_analytic, 'MobileNo')
m.replace_not_valid_to_empty(df_analytic, 'TelNo')
m.replace_not_valid_to_empty(df_analytic, 'MobileNo')

df_analytic.loc[df_analytic['TelNo'].str.contains('00000'), 'TelNo'] = 'empty'
df_analytic.loc[df_analytic['MobileNo'].str.contains('00000'), 'MobileNo'] = 'empty'

m.clean_space(df_analytic, 'Email')
df_analytic['Email'] = m.lowercase(df_analytic, 'Email')

c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:67: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:68: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('[^0-9]','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:90: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)

In [11]:
m.email_correction(df_analytic, 'Email')

c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:25: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_mail), '@mail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail), '@gmail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:35: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail_com), '@gmail.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:38: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail), '@hotmail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail_com), '@hotmail.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:45: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo), '@yahoo.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\past_guest_module.py:48: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_ymail), '@ymail.', regex=True, inplace=True)

In [12]:
df_analytic.loc[(df_analytic['Email'] != 'empty') & ((df_analytic['TelNo'] != 'empty') | (df_analytic['MobileNo'] != 'empty')), 'Contact Type'] = 'Email and Phone'
df_analytic.loc[(df_analytic['Email'] != 'empty') & ((df_analytic['TelNo'] == 'empty') & (df_analytic['MobileNo'] == 'empty')), 'Contact Type'] = 'Email Only'
df_analytic.loc[(df_analytic['Email'] == 'empty') & ((df_analytic['TelNo'] != 'empty') | (df_analytic['MobileNo'] != 'empty')), 'Contact Type'] = 'Phone Only'

df_analytic.loc[df_analytic['Contact Type'] == 'empty'].to_csv(r'C:\Users\fajar\Documents\Python\Data\contact_type_empty_analytic.csv', index=False)

count_contact_type_empty = df_analytic.loc[df_analytic['Contact Type'] == 'empty'].shape[0]

df_analytic.drop(df_analytic.loc[df_analytic['Contact Type'] == 'empty'].index, inplace=True)
df_analytic.reset_index(drop=True, inplace=True)

count_after_contact_type_empty = df_analytic.shape[0]

df_analytic

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KB038782,Karma Resorts,Other,Past Guests,Karma Bavaria,PF254425,Frau,Jeannette,Matthews,Female,...,2024-10-14 20:30:00,0,DIR,WALKIN,RETAIL,1,0,0,Email Only,NO
1,KB044845,Karma Resorts,Other,Past Guests,Karma Bavaria,PF288435,Herr,Michael,Haeffner,Male,...,2024-10-13 00:00:00,1,OTA,OTA,RETAIL,2,0,0,Phone Only,NO
2,KK062364,Karma Resorts,Other,Past Guests,Karma Kandara,PF213219,Mr,Harry,Utama,Male,...,2024-10-15 00:00:00,1,HOUSE_USE,V_OWNER_NRB,COMP,2,0,0,Email and Phone,NO
3,KLM006629,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF285804,Mrs,Susan,Thompson,Unknown,...,2024-10-13 00:00:00,1,OTA,OTA,RETAIL,2,0,0,Phone Only,NO
4,KSH019175,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF279905,Mr,David,Austin,Male,...,2024-10-14 00:00:00,1,DIGITAL,WEBSITE,DIGITAL,2,0,0,Email and Phone,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,KK062015,Karma Resorts,Other,Past Guests,Karma Kandara,PF244666,Ms,Isabella,Duric,Female,...,2024-10-14 00:00:00,3,HOUSE_USE,V_OWNER_NRB,COMP,1,0,0,Email and Phone,NO
87,KK052041,Karma Resorts,Other,Past Guests,Karma Kandara,PF092162,Mr,Ed,King,Male,...,2024-10-15 00:00:00,10,HOUSE_USE,STAFF,COMP,1,0,0,Email and Phone,NO
88,KLM006240,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF282393,Mr,John,Kennedy,Male,...,2024-10-14 00:00:00,1,DIR,WEDDING,GROUP,2,0,0,Email and Phone,NO
89,KLM006752,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF267043,Mr,Adrian,Fatechand,Unknown,...,2024-10-13 00:00:00,2,COMP,STAFF,COMP,1,0,0,Email Only,NO
90,KLM005370,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF271129,Mr,Alan,Mcharrie,Male,...,2024-10-14 00:00:00,1,WEDDING,WEDDING,GROUP,2,0,0,Email and Phone,NO

In [13]:
# Cek Email Karma
email_karma = m.find_karma(df_analytic, 'Email')
count_email_karma = email_karma.shape[0]
email_karma.to_csv(r'C:\Users\fajar\Documents\Python\Data\email_deleted_analytic.csv', index=False)

email_karma

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
23,KB043534,Karma Resorts,Other,Past Guests,Karma Bavaria,PF126784,Herr,Axel,Reimlinger,Male,...,2024-10-18 00:00:00,3,COMP,STAFF,COMP,1,0,0,Email and Phone,NO
32,KK061016,Karma Resorts,Other,Past Guests,Karma Kandara,PF255157,Mr,John,Spence,Male,...,2024-10-13 00:00:00,3,HOUSE_USE,VIP,COMP,1,0,0,Email and Phone,NO
35,KB039524,Karma Resorts,Other,Past Guests,Karma Bavaria,PF260003,Mr,Christopher,Reyes,Male,...,2024-10-19 00:00:00,250,STAFF_PRIV,STAFF,COMP,2,0,0,Email and Phone,NO
37,KK060714,Karma Resorts,Other,Past Guests,Karma Kandara,PF044484,Mr,Gary,Knowles,Male,...,2024-10-16 00:00:00,7,HOUSE_USE,FOCVIP,KC,2,0,0,Email and Phone,NO
59,KK062114,Karma Resorts,Other,Past Guests,Karma Kandara,PF233671,Mr,Dario,Quinteros,Male,...,2024-10-14 00:00:00,6,HOUSE_USE,STAFF,COMP,1,0,0,Email and Phone,NO
78,KK062425,Karma Resorts,Other,Past Guests,Karma Kandara,PF176861,Mr,Rai,Artawan,Male,...,2024-10-15 00:00:00,1,HOUSE_USE,STAFF,COMP,1,0,0,Email and Phone,NO
87,KK052041,Karma Resorts,Other,Past Guests,Karma Kandara,PF092162,Mr,Ed,King,Male,...,2024-10-15 00:00:00,10,HOUSE_USE,STAFF,COMP,1,0,0,Email and Phone,NO
89,KLM006752,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF267043,Mr,Adrian,Fatechand,Unknown,...,2024-10-13 00:00:00,2,COMP,STAFF,COMP,1,0,0,Email Only,NO

In [14]:
# delete email Karma
count_after_clean_karma = m.delete_karma(df_analytic, 'Email')

df_analytic

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KB038782,Karma Resorts,Other,Past Guests,Karma Bavaria,PF254425,Frau,Jeannette,Matthews,Female,...,2024-10-14 20:30:00,0,DIR,WALKIN,RETAIL,1,0,0,Email Only,NO
1,KB044845,Karma Resorts,Other,Past Guests,Karma Bavaria,PF288435,Herr,Michael,Haeffner,Male,...,2024-10-13 00:00:00,1,OTA,OTA,RETAIL,2,0,0,Phone Only,NO
2,KK062364,Karma Resorts,Other,Past Guests,Karma Kandara,PF213219,Mr,Harry,Utama,Male,...,2024-10-15 00:00:00,1,HOUSE_USE,V_OWNER_NRB,COMP,2,0,0,Email and Phone,NO
3,KLM006629,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF285804,Mrs,Susan,Thompson,Unknown,...,2024-10-13 00:00:00,1,OTA,OTA,RETAIL,2,0,0,Phone Only,NO
4,KSH019175,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF279905,Mr,David,Austin,Male,...,2024-10-14 00:00:00,1,DIGITAL,WEBSITE,DIGITAL,2,0,0,Email and Phone,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,KLM006739,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF286972,Mr,Sean,Kennedy,Male,...,2024-10-14 00:00:00,1,DIR,WEDDING,GROUP,2,0,0,Email and Phone,NO
79,KB044552,Karma Resorts,Other,Past Guests,Karma Bavaria,PF216954,Mr,David,Raguin,Male,...,2024-10-13 00:00:00,1,COMP,GER_OWE,COMP,2,2,0,Email and Phone,NO
80,KK062015,Karma Resorts,Other,Past Guests,Karma Kandara,PF244666,Ms,Isabella,Duric,Female,...,2024-10-14 00:00:00,3,HOUSE_USE,V_OWNER_NRB,COMP,1,0,0,Email and Phone,NO
81,KLM006240,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF282393,Mr,John,Kennedy,Male,...,2024-10-14 00:00:00,1,DIR,WEDDING,GROUP,2,0,0,Email and Phone,NO
82,KLM005370,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF271129,Mr,Alan,Mcharrie,Male,...,2024-10-14 00:00:00,1,WEDDING,WEDDING,GROUP,2,0,0,Email and Phone,NO

In [15]:
df_analytic['Salutation']

0     Frau
1     Herr
2       Mr
3      Mrs
4       Mr
      ...
78      Mr
79      Mr
80      Ms
81      Mr
82      Mr
Name: Salutation, Length: 83, dtype: string

In [16]:
# Cek leads test
test_leads = df_analytic.loc[
    
        df_analytic['Email'].str.contains('^test@', flags=re.I, regex=True) |
        df_analytic['Email'].str.contains('\+test', flags=re.I, regex=True) |
    
        df_analytic['First_Name'].str.contains('^test$', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('^test$', flags=re.I, regex=True) |

        df_analytic['First_Name'].str.contains('test 1', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('test 2', flags=re.I, regex=True)|
        df_analytic['First_Name'].str.contains('test1', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('test2', flags=re.I, regex=True)|

        df_analytic['First_Name'].str.contains(' test ', flags=re.I, regex=True) | 
        df_analytic['Surname'].str.contains(' test ', flags=re.I, regex=True) | 
        df_analytic['Surname'].str.contains(' test$', flags=re.I, regex=True)
    ]

count_leads_test = test_leads.shape[0]

test_leads.to_csv(r'C:\Users\fajar\Documents\Python\Data\test_leads_analytic.csv', index=False)
test_leads

Empty DataFrame
Columns: [Booking_Id, Lead Brand, Lead Sub- Brand, Lead Source, Resort_Name, ProfileRef, Salutation, First_Name, Surname, Gender, Language, DOB, Street, Area, Town, County, Country, Nationality, PostCode, TelNo, MobileNo, Email, Exclude From Mailing, Opt In, Booking Status, DateArrival, DateDepart, No. of Nights, Market_Segment, Media_Code, Media Code Group, No. of Adult, No. of Children, No. of Infants, Contact Type, Odyssey Members]
Index: []

[0 rows x 36 columns]

In [17]:
df_analytic.drop(test_leads.index, inplace=True)
df_analytic.reset_index(drop=True, inplace=True)

count_after_dedup_test = df_analytic.shape[0]
count_after_dedup_test

83

In [18]:
count_final_data = count_after_dedup_test

In [19]:
# df_analytic.loc[(df_analytic['Email'] == 'jonmosley6@yahoo.com')]

In [20]:
df_analytic.replace('empty', '', inplace=True)

In [21]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Data Awal Zoho Analytic : "+str(count_data_awal))
print("Jumlah Data Email dan Phone Kosong : "+str(count_contact_type_empty))
print("Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : "+str(count_after_contact_type_empty))
print("Jumlah Data Email Yang Termasuk List Karma : "+str(count_email_karma))
print("Jumlah Data Email Setelah List Karma Dihapus : "+str(count_after_clean_karma))
print("Jumlah Data Test : "+str(count_leads_test))
print("Jumlah Data Email Setelah Data Test Dihapus : "+str(count_after_dedup_test))
print("Jumlah Data Akhir : "+str(count_final_data))

==========================================================
Summary
==========================================================
Jumlah Data Awal Zoho Analytic : 124
Jumlah Data Email dan Phone Kosong : 33
Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : 91
Jumlah Data Email Yang Termasuk List Karma : 8
Jumlah Data Email Setelah List Karma Dihapus : 83
Jumlah Data Test : 0
Jumlah Data Email Setelah Data Test Dihapus : 83
Jumlah Data Akhir : 83

In [22]:
df_analytic.to_excel(r'C:\Users\fajar\Documents\Python\Data\check_country_code_analytic.xlsx', index=False)