In [3]:
import pandas as pd
import re

import past_guest_module as pm

import sys
sys.path.append('../zoho_data_app/')

import main_module as m

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [4]:
path = r'C:\Users\fajar\Documents\Python\Data\Past Guest Data\Zoho Analytic\2025\Jan\29 Dec - 6 Jan\CRM_Rental_Report_29_Dec_-_6_Jan.xlsx'
df_analytic = pd.read_excel(path, dtype='string', sheet_name='Sheet1')
count_data_awal = df_analytic.shape[0]
df_analytic

,Booking_Id,TelNo,MobileNo,Email,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK061992,+82 10 2620 4321,821026204321,432elije@gmail.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF288642,Mr,...,2025-01-01 00:00:00,4,OTA,OTA,RETAIL,2,0,0,,
1,KK066759,081334339314,081334339314,714pnb@gmail.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF297860,Mr,...,2024-12-29 00:00:00,1,COMP,GSTAFF,COMP,1,0,0,,
2,KK066845,+31 6 28947092,31628947092,adinahalil@yahoo.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF297759,Mr,...,2024-12-29 00:00:00,1,DIR,CHAT,DIGITAL,2,2,0,,
3,KK066606,+7 9119201221,79119201221,aleksndrbelkovich@gmail.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF297648,Mr,...,2025-01-02 00:00:00,6,HOUSE_USE,V_OWNER_NRB,COMP,5,2,0,,
4,KB046658,08457936764,<NA>,alex@biva-gmbh.de,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297717,Frau,...,2025-01-01 00:00:00,2,COMP,GER_OWE,COMP,2,0,0,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,KB046544,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297201,Frau,...,2024-12-29 00:00:00,1,COMP,GER_OWE,COMP,1,0,0,,
139,KB046151,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,PF295139,Firma,...,2024-12-29 14:30:00,0,LGR,LGR,GROUP,1,0,0,,
140,KK058207,+61 432 208 011,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Kandara,PF280129,Ms,...,2025-01-02 00:00:00,7,OTA,OTA,RETAIL,2,0,0,,
141,KSH021957,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF297839,Mr,...,2025-01-01 00:00:00,1,COMP,CB,GROUP,2,0,0,,
142,KK066010,<NA>,6738663240,<NA>,Karma Resorts,Other,Past Guests,Karma Kandara,PF296477,Mr,...,2025-01-03 00:00:00,5,OTA,OTA,RETAIL,4,0,0,,

In [5]:
df_analytic.columns

Index(['Booking_Id', 'TelNo', 'MobileNo', 'Email', 'Lead Brand',
       'Lead Sub- Brand', 'Lead Source', 'Resort_Name', 'ProfileRef',
       'Salutation', 'First_Name', 'Surname', 'Gender', 'Language', 'DOB',
       'Street', 'Area', 'Town', 'County', 'Country', 'Nationality',
       'PostCode', 'Exclude From Mailing', 'Opt In', 'Booking Code',
       'Booking Status', 'DateArrival', 'DateDepart', 'No. of Nights',
       'Market_Segment', 'Media_Code', 'Media Code Group', 'No. of Adult',
       'No. of Children', 'No. of Infants', 'Contact Type', 'Odyssey Members'],
      dtype='object')

In [6]:
new_cols = ['Booking_Id', 'Lead Brand', 'Lead Sub- Brand', 'Lead Source',
       'Resort_Name', 'ProfileRef', 'Salutation', 'First_Name', 'Surname',
       'Gender', 'Language', 'DOB', 'Street', 'Area', 'Town', 'County',
       'Country', 'Nationality', 'PostCode', 'TelNo', 'MobileNo', 'Email',
       'Exclude From Mailing', 'Opt In', 'Booking Status',
       'DateArrival', 'DateDepart', 'No. of Nights', 'Market_Segment',
       'Media_Code', 'Media Code Group', 'No. of Adult', 'No. of Children',
       'No. of Infants', 'Contact Type', 'Odyssey Members']																																																																																																																																						

df_analytic = df_analytic.reindex(columns=new_cols)

In [7]:
df_analytic.fillna('empty', inplace=True)
df_analytic['Contact Type'] = 'empty'
df_analytic['Odyssey Members'] = 'NO'

In [8]:
df_analytic.loc[df_analytic['Surname'] == 'empty', 'Surname'] = '-'

In [9]:
df_analytic['Salutation'].replace('empty', '', inplace=True)
df_analytic['First_Name'].replace('empty', '', inplace=True)
df_analytic['Surname'].replace('empty', '', inplace=True)

df_analytic['Salutation'] = df_analytic['Salutation'].str.title()
df_analytic['First_Name'] = df_analytic['First_Name'].str.title()
df_analytic['Surname'] = df_analytic['Surname'].str.title()

df_analytic

C:\Users\fajar\AppData\Local\Temp\ipykernel_20312\2281604359.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['Salutation'].replace('empty', '', inplace=True)
C:\Users\fajar\AppData\Local\Temp\ipykernel_20312\2281604359.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['First_Name'].replace('empty', '', inplace=True)
C:\Users\fajar\AppData\Local\Temp\ipykernel_20312\2281604359.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['Surname'].replace('empty', '', inplace=True)

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK061992,Karma Resorts,Other,Past Guests,Karma Kandara,PF288642,Mr,Bosul,Kim,Male,...,2025-01-01 00:00:00,4,OTA,OTA,RETAIL,2,0,0,empty,NO
1,KK066759,Karma Resorts,Other,Past Guests,Karma Kandara,PF297860,Mr,Colonel Pilot Trinanda,Hasan,Male,...,2024-12-29 00:00:00,1,COMP,GSTAFF,COMP,1,0,0,empty,NO
2,KK066845,Karma Resorts,Other,Past Guests,Karma Kandara,PF297759,Mr,Erik,Van Calveen,Male,...,2024-12-29 00:00:00,1,DIR,CHAT,DIGITAL,2,2,0,empty,NO
3,KK066606,Karma Resorts,Other,Past Guests,Karma Kandara,PF297648,Mr,Aleksandr,Belkovich,Male,...,2025-01-02 00:00:00,6,HOUSE_USE,V_OWNER_NRB,COMP,5,2,0,empty,NO
4,KB046658,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297717,Frau,Alexandra,Babic,Female,...,2025-01-01 00:00:00,2,COMP,GER_OWE,COMP,2,0,0,empty,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,KB046544,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297201,Frau,Myrtha,Gesenberg,Female,...,2024-12-29 00:00:00,1,COMP,GER_OWE,COMP,1,0,0,empty,NO
139,KB046151,Karma Resorts,Other,Past Guests,Karma Bavaria,PF295139,Firma,Karma,Bavaria,Unknown,...,2024-12-29 14:30:00,0,LGR,LGR,GROUP,1,0,0,empty,NO
140,KK058207,Karma Resorts,Other,Past Guests,Karma Kandara,PF280129,Ms,Diane,Antunes,Female,...,2025-01-02 00:00:00,7,OTA,OTA,RETAIL,2,0,0,empty,NO
141,KSH021957,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF297839,Mr,Dj,Funkomatic,Male,...,2025-01-01 00:00:00,1,COMP,CB,GROUP,2,0,0,empty,NO
142,KK066010,Karma Resorts,Other,Past Guests,Karma Kandara,PF296477,Mr,Kerry,Nelson,Male,...,2025-01-03 00:00:00,5,OTA,OTA,RETAIL,4,0,0,empty,NO

In [10]:
m.clean_number(df_analytic, 'TelNo')
m.clean_number(df_analytic, 'MobileNo')
m.replace_not_valid_to_empty(df_analytic, 'TelNo')
m.replace_not_valid_to_empty(df_analytic, 'MobileNo')

df_analytic.loc[df_analytic['TelNo'].str.contains('00000'), 'TelNo'] = 'empty'
df_analytic.loc[df_analytic['MobileNo'].str.contains('00000'), 'MobileNo'] = 'empty'

m.clean_space(df_analytic, 'Email')
df_analytic['Email'] = m.lowercase(df_analytic, 'Email')
m.email_correction(df_analytic, 'Email')

c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:67: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:68: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('[^0-9]','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:90: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:193: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('mailto:|-primary|-pri|-Mrs|(noemailtobesent)','', regex=True, inplace=True)

In [11]:
m.email_correction(df_analytic, 'Email')

In [12]:
df_analytic.loc[(df_analytic['Email'] != 'empty') & ((df_analytic['TelNo'] != 'empty') | (df_analytic['MobileNo'] != 'empty')), 'Contact Type'] = 'Email and Phone'
df_analytic.loc[(df_analytic['Email'] != 'empty') & ((df_analytic['TelNo'] == 'empty') & (df_analytic['MobileNo'] == 'empty')), 'Contact Type'] = 'Email Only'
df_analytic.loc[(df_analytic['Email'] == 'empty') & ((df_analytic['TelNo'] != 'empty') | (df_analytic['MobileNo'] != 'empty')), 'Contact Type'] = 'Phone Only'

df_analytic.loc[df_analytic['Contact Type'] == 'empty'].to_csv(r'C:\Users\fajar\Documents\Python\Data\contact_type_empty_analytic.csv', index=False)

count_contact_type_empty = df_analytic.loc[df_analytic['Contact Type'] == 'empty'].shape[0]

df_analytic.drop(df_analytic.loc[df_analytic['Contact Type'] == 'empty'].index, inplace=True)
df_analytic.reset_index(drop=True, inplace=True)

count_after_contact_type_empty = df_analytic.shape[0]

df_analytic

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK061992,Karma Resorts,Other,Past Guests,Karma Kandara,PF288642,Mr,Bosul,Kim,Male,...,2025-01-01 00:00:00,4,OTA,OTA,RETAIL,2,0,0,Email and Phone,NO
1,KK066759,Karma Resorts,Other,Past Guests,Karma Kandara,PF297860,Mr,Colonel Pilot Trinanda,Hasan,Male,...,2024-12-29 00:00:00,1,COMP,GSTAFF,COMP,1,0,0,Email and Phone,NO
2,KK066845,Karma Resorts,Other,Past Guests,Karma Kandara,PF297759,Mr,Erik,Van Calveen,Male,...,2024-12-29 00:00:00,1,DIR,CHAT,DIGITAL,2,2,0,Email and Phone,NO
3,KK066606,Karma Resorts,Other,Past Guests,Karma Kandara,PF297648,Mr,Aleksandr,Belkovich,Male,...,2025-01-02 00:00:00,6,HOUSE_USE,V_OWNER_NRB,COMP,5,2,0,Email and Phone,NO
4,KB046658,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297717,Frau,Alexandra,Babic,Female,...,2025-01-01 00:00:00,2,COMP,GER_OWE,COMP,2,0,0,Email and Phone,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,KB046544,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297201,Frau,Myrtha,Gesenberg,Female,...,2024-12-29 00:00:00,1,COMP,GER_OWE,COMP,1,0,0,Email Only,NO
139,KB046151,Karma Resorts,Other,Past Guests,Karma Bavaria,PF295139,Firma,Karma,Bavaria,Unknown,...,2024-12-29 14:30:00,0,LGR,LGR,GROUP,1,0,0,Email Only,NO
140,KK058207,Karma Resorts,Other,Past Guests,Karma Kandara,PF280129,Ms,Diane,Antunes,Female,...,2025-01-02 00:00:00,7,OTA,OTA,RETAIL,2,0,0,Email and Phone,NO
141,KSH021957,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF297839,Mr,Dj,Funkomatic,Male,...,2025-01-01 00:00:00,1,COMP,CB,GROUP,2,0,0,Email Only,NO
142,KK066010,Karma Resorts,Other,Past Guests,Karma Kandara,PF296477,Mr,Kerry,Nelson,Male,...,2025-01-03 00:00:00,5,OTA,OTA,RETAIL,4,0,0,Email and Phone,NO

In [13]:
# Cek Email Karma
email_karma = m.find_karma(df_analytic, 'Email')
count_email_karma = email_karma.shape[0]
email_karma.to_csv(r'C:\Users\fajar\Documents\Python\Data\email_deleted_analytic.csv', index=False)

email_karma

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
10,KB043545,Karma Resorts,Other,Past Guests,Karma Bavaria,PF126784,Herr,Axel,Reimlinger,Male,...,2025-01-03 00:00:00,4,COMP,STAFF,COMP,1,0,0,Email and Phone,NO
17,KB046224,Karma Resorts,Other,Past Guests,Karma Bavaria,PF071902,,Clinton,Albuquerque,Male,...,2025-01-06 00:00:00,3,COMP,STAFF,COMP,1,0,0,Email and Phone,NO
24,KK067131,Karma Resorts,Other,Past Guests,Karma Kandara,PF050759,,David,Scheckter,Male,...,2025-01-02 00:00:00,2,COMP,STAFF,COMP,1,0,0,Email and Phone,NO
26,KB044785,Karma Resorts,Other,Past Guests,Karma Bavaria,PF159006,Herr,Dennis,Rietveld,Male,...,2025-01-01 00:00:00,31,STAFF_PRIV,STAFF,COMP,1,0,0,Email and Phone,NO
36,KLM007247,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF193371,Mr,Adrian,Willmers,Male,...,2025-01-03 00:00:00,5,COMP,STAFF,COMP,2,0,0,Email and Phone,NO
54,KB039544,Karma Resorts,Other,Past Guests,Karma Bavaria,PF295307,Mr,Manish,Dubey,Male,...,2025-01-01 00:00:00,31,STAFF_PRIV,STAFF,COMP,1,0,0,Email and Phone,NO
58,KB046405,Karma Resorts,Other,Past Guests,Karma Bavaria,PF227502,Mr,Neil,Aitchison,Unknown,...,2025-01-01 00:00:00,11,STAFF_PRIV,STAFF,COMP,2,0,0,Email and Phone,NO
65,KB039543,Karma Resorts,Other,Past Guests,Karma Bavaria,PF228016,Mr,Peter,Aitchison,Male,...,2025-01-01 00:00:00,31,STAFF_PRIV,STAFF,COMP,1,0,0,Email Only,NO
91,KK066976,Karma Resorts,Other,Past Guests,Karma Kandara,PF076160,Mr,Vic,Faulkner,Male,...,2025-01-02 00:00:00,2,COMP,STAFF,COMP,1,0,0,Email and Phone,NO

In [14]:
# delete email Karma
count_after_clean_karma = m.delete_karma(df_analytic, 'Email')

df_analytic

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK061992,Karma Resorts,Other,Past Guests,Karma Kandara,PF288642,Mr,Bosul,Kim,Male,...,2025-01-01 00:00:00,4,OTA,OTA,RETAIL,2,0,0,Email and Phone,NO
1,KK066759,Karma Resorts,Other,Past Guests,Karma Kandara,PF297860,Mr,Colonel Pilot Trinanda,Hasan,Male,...,2024-12-29 00:00:00,1,COMP,GSTAFF,COMP,1,0,0,Email and Phone,NO
2,KK066845,Karma Resorts,Other,Past Guests,Karma Kandara,PF297759,Mr,Erik,Van Calveen,Male,...,2024-12-29 00:00:00,1,DIR,CHAT,DIGITAL,2,2,0,Email and Phone,NO
3,KK066606,Karma Resorts,Other,Past Guests,Karma Kandara,PF297648,Mr,Aleksandr,Belkovich,Male,...,2025-01-02 00:00:00,6,HOUSE_USE,V_OWNER_NRB,COMP,5,2,0,Email and Phone,NO
4,KB046658,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297717,Frau,Alexandra,Babic,Female,...,2025-01-01 00:00:00,2,COMP,GER_OWE,COMP,2,0,0,Email and Phone,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,KB046544,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297201,Frau,Myrtha,Gesenberg,Female,...,2024-12-29 00:00:00,1,COMP,GER_OWE,COMP,1,0,0,Email Only,NO
130,KB046151,Karma Resorts,Other,Past Guests,Karma Bavaria,PF295139,Firma,Karma,Bavaria,Unknown,...,2024-12-29 14:30:00,0,LGR,LGR,GROUP,1,0,0,Email Only,NO
131,KK058207,Karma Resorts,Other,Past Guests,Karma Kandara,PF280129,Ms,Diane,Antunes,Female,...,2025-01-02 00:00:00,7,OTA,OTA,RETAIL,2,0,0,Email and Phone,NO
132,KSH021957,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF297839,Mr,Dj,Funkomatic,Male,...,2025-01-01 00:00:00,1,COMP,CB,GROUP,2,0,0,Email Only,NO
133,KK066010,Karma Resorts,Other,Past Guests,Karma Kandara,PF296477,Mr,Kerry,Nelson,Male,...,2025-01-03 00:00:00,5,OTA,OTA,RETAIL,4,0,0,Email and Phone,NO

In [15]:
df_analytic['Salutation']

0         Mr
1         Mr
2         Mr
3         Mr
4       Frau
       ...
129     Frau
130    Firma
131       Ms
132       Mr
133       Mr
Name: Salutation, Length: 134, dtype: string

In [16]:
# Cek leads test
test_leads = df_analytic.loc[
    
        df_analytic['Email'].str.contains('^test@', flags=re.I, regex=True) |
        df_analytic['Email'].str.contains('\+test', flags=re.I, regex=True) |
    
        df_analytic['First_Name'].str.contains('^test$', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('^test$', flags=re.I, regex=True) |

        df_analytic['First_Name'].str.contains('test 1', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('test 2', flags=re.I, regex=True)|
        df_analytic['First_Name'].str.contains('test1', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('test2', flags=re.I, regex=True)|

        df_analytic['First_Name'].str.contains(' test ', flags=re.I, regex=True) | 
        df_analytic['Surname'].str.contains(' test ', flags=re.I, regex=True) | 
        df_analytic['Surname'].str.contains(' test$', flags=re.I, regex=True)
    ]

count_leads_test = test_leads.shape[0]

test_leads.to_csv(r'C:\Users\fajar\Documents\Python\Data\test_leads_analytic.csv', index=False)
test_leads

Empty DataFrame
Columns: [Booking_Id, Lead Brand, Lead Sub- Brand, Lead Source, Resort_Name, ProfileRef, Salutation, First_Name, Surname, Gender, Language, DOB, Street, Area, Town, County, Country, Nationality, PostCode, TelNo, MobileNo, Email, Exclude From Mailing, Opt In, Booking Status, DateArrival, DateDepart, No. of Nights, Market_Segment, Media_Code, Media Code Group, No. of Adult, No. of Children, No. of Infants, Contact Type, Odyssey Members]
Index: []

[0 rows x 36 columns]

In [17]:
df_analytic.drop(test_leads.index, inplace=True)
df_analytic.reset_index(drop=True, inplace=True)

count_after_dedup_test = df_analytic.shape[0]
count_after_dedup_test

134

In [18]:
count_final_data = count_after_dedup_test

In [19]:
# df_analytic.loc[(df_analytic['Email'] == 'jonmosley6@yahoo.com')]

In [20]:
df_analytic.replace('empty', '', inplace=True)

In [21]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Data Awal Zoho Analytic : "+str(count_data_awal))
print("Jumlah Data Email dan Phone Kosong : "+str(count_contact_type_empty))
print("Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : "+str(count_after_contact_type_empty))
print("Jumlah Data Email Yang Termasuk List Karma : "+str(count_email_karma))
print("Jumlah Data Email Setelah List Karma Dihapus : "+str(count_after_clean_karma))
print("Jumlah Data Test : "+str(count_leads_test))
print("Jumlah Data Email Setelah Data Test Dihapus : "+str(count_after_dedup_test))
print("Jumlah Data Akhir : "+str(count_final_data))

==========================================================
Summary
==========================================================
Jumlah Data Awal Zoho Analytic : 143
Jumlah Data Email dan Phone Kosong : 0
Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : 143
Jumlah Data Email Yang Termasuk List Karma : 9
Jumlah Data Email Setelah List Karma Dihapus : 134
Jumlah Data Test : 0
Jumlah Data Email Setelah Data Test Dihapus : 134
Jumlah Data Akhir : 134

In [22]:
df_analytic.to_excel(r'C:\Users\fajar\Documents\Python\Data\check_country_code_analytic.xlsx', index=False)