In [1]:
import pandas as pd
import re

import past_guest_module as pm

import sys
sys.path.append('../zoho_data_app/')

import main_module as m

%load_ext autoreload
%autoreload 2

In [2]:
path = r'C:\Users\fajar\Documents\Python\Data\Past Guest Data\Zoho Analytic\2024\Dec\15 Dec - 23 Dec\CRM_Rental_Report_15_Dec_-_23_Dec.xlsx'
df_analytic = pd.read_excel(path, dtype='string', sheet_name='Sheet1')
count_data_awal = df_analytic.shape[0]
df_analytic

,Booking_Id,TelNo,MobileNo,Email,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK066096,+61433450712,61433450712,chamabunay@yahoo.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF296726,Ms,...,2024-12-18 00:00:00,2,HOUSE_USE,V_OWNER_NRB,COMP,2,2,0,,
1,KB046143,0436445602,<NA>,clem@onlinefloormystore.com.au,Karma Resorts,Other,Past Guests,Karma Bavaria,PF296418,Mrs,...,2024-12-16 00:00:00,4,WYNDHAM,WYNDHAM,WYNDHAM,3,0,0,,
2,KK065230,0434891090,0434891090,georgiesimonesmith@gmail.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF202839,Ms,...,2024-12-16 00:00:00,2,HOUSE_USE,V_OWNER_NRB,COMP,1,0,0,,
3,KK047983,+447876596467,447876596467,steveandnatwest@gmail.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF259088,Miss,...,2024-12-22 00:00:00,7,HOUSE_USE,CHAT,DIGITAL,6,0,0,,
4,KK063111,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Kandara,PF291338,Mrs,...,2024-12-18 00:00:00,2,HOUSE_USE,V_OWNER,COMP,6,0,0,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,KK059814,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Kandara,<NA>,Ms,...,2024-12-15 00:00:00,1,WEDDING,WEDDING,GROUP,2,0,0,,
64,KB039996,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,<NA>,Firma,...,2024-12-18 18:00:00,0,CB,CB,GROUP,1,0,0,,
65,KB039995,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,<NA>,Firma,...,2024-12-17 18:00:00,0,CB,CB,GROUP,1,0,0,,
66,KB046245,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,<NA>,Mr,...,2024-12-18 00:00:00,3,WYNDHAM,WYNDHAM,WYNDHAM,2,0,0,,
67,KSH021634,+0-0-07926955248,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF295661,<NA>,...,2024-12-16 00:00:00,1,OTA,OTA,RETAIL,2,0,0,,

In [3]:
df_analytic.columns

Index(['Booking_Id', 'TelNo', 'MobileNo', 'Email', 'Lead Brand',
       'Lead Sub- Brand', 'Lead Source', 'Resort_Name', 'ProfileRef',
       'Salutation', 'First_Name', 'Surname', 'Gender', 'Language', 'DOB',
       'Street', 'Area', 'Town', 'County', 'Country', 'Nationality',
       'PostCode', 'Exclude From Mailing', 'Opt In', 'Booking Code',
       'Booking Status', 'DateArrival', 'DateDepart', 'No. of Nights',
       'Market_Segment', 'Media_Code', 'Media Code Group', 'No. of Adult',
       'No. of Children', 'No. of Infants', 'Contact Type', 'Odyssey Members'],
      dtype='object')

In [4]:
new_cols = ['Booking_Id', 'Lead Brand', 'Lead Sub- Brand', 'Lead Source',
       'Resort_Name', 'ProfileRef', 'Salutation', 'First_Name', 'Surname',
       'Gender', 'Language', 'DOB', 'Street', 'Area', 'Town', 'County',
       'Country', 'Nationality', 'PostCode', 'TelNo', 'MobileNo', 'Email',
       'Exclude From Mailing', 'Opt In', 'Booking Status',
       'DateArrival', 'DateDepart', 'No. of Nights', 'Market_Segment',
       'Media_Code', 'Media Code Group', 'No. of Adult', 'No. of Children',
       'No. of Infants', 'Contact Type', 'Odyssey Members']																																																																																																																																						

df_analytic = df_analytic.reindex(columns=new_cols)

In [5]:
df_analytic.fillna('empty', inplace=True)
df_analytic['Contact Type'] = 'empty'
df_analytic['Odyssey Members'] = 'NO'

In [6]:
df_analytic.loc[df_analytic['Surname'] == 'empty', 'Surname'] = '-'

In [7]:
df_analytic['Salutation'].replace('empty', '', inplace=True)
df_analytic['First_Name'].replace('empty', '', inplace=True)
df_analytic['Surname'].replace('empty', '', inplace=True)

df_analytic['Salutation'] = df_analytic['Salutation'].str.title()
df_analytic['First_Name'] = df_analytic['First_Name'].str.title()
df_analytic['Surname'] = df_analytic['Surname'].str.title()

df_analytic

C:\Users\fajar\AppData\Local\Temp\ipykernel_19980\2281604359.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['Salutation'].replace('empty', '', inplace=True)
C:\Users\fajar\AppData\Local\Temp\ipykernel_19980\2281604359.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['First_Name'].replace('empty', '', inplace=True)
C:\Users\fajar\AppData\Local\Temp\ipykernel_19980\2281604359.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['Surname'].replace('empty', '', inplace=True)

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK066096,Karma Resorts,Other,Past Guests,Karma Kandara,PF296726,Ms,Maricha,Mabunay,Female,...,2024-12-18 00:00:00,2,HOUSE_USE,V_OWNER_NRB,COMP,2,2,0,empty,NO
1,KB046143,Karma Resorts,Other,Past Guests,Karma Bavaria,PF296418,Mrs,Clement,Surgess,Female,...,2024-12-16 00:00:00,4,WYNDHAM,WYNDHAM,WYNDHAM,3,0,0,empty,NO
2,KK065230,Karma Resorts,Other,Past Guests,Karma Kandara,PF202839,Ms,Georgie,Smith,Female,...,2024-12-16 00:00:00,2,HOUSE_USE,V_OWNER_NRB,COMP,1,0,0,empty,NO
3,KK047983,Karma Resorts,Other,Past Guests,Karma Kandara,PF259088,Miss,Natalie,West,Female,...,2024-12-22 00:00:00,7,HOUSE_USE,CHAT,DIGITAL,6,0,0,empty,NO
4,KK063111,Karma Resorts,Other,Past Guests,Karma Kandara,PF291338,Mrs,Oriana,Mastro,Female,...,2024-12-18 00:00:00,2,HOUSE_USE,V_OWNER,COMP,6,0,0,empty,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,KK059814,Karma Resorts,Other,Past Guests,Karma Kandara,empty,Ms,Oxana,Khoroshavina,Unknown,...,2024-12-15 00:00:00,1,WEDDING,WEDDING,GROUP,2,0,0,empty,NO
64,KB039996,Karma Resorts,Other,Past Guests,Karma Bavaria,empty,Firma,Roche,Diagnostig,Unknown,...,2024-12-18 18:00:00,0,CB,CB,GROUP,1,0,0,empty,NO
65,KB039995,Karma Resorts,Other,Past Guests,Karma Bavaria,empty,Firma,Roche,Diagnostig,Unknown,...,2024-12-17 18:00:00,0,CB,CB,GROUP,1,0,0,empty,NO
66,KB046245,Karma Resorts,Other,Past Guests,Karma Bavaria,empty,Mr,Wmna,Tengateway,Unknown,...,2024-12-18 00:00:00,3,WYNDHAM,WYNDHAM,WYNDHAM,2,0,0,empty,NO
67,KSH021634,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF295661,,Lisa,Jeffery,Unknown,...,2024-12-16 00:00:00,1,OTA,OTA,RETAIL,2,0,0,empty,NO

In [8]:
m.clean_number(df_analytic, 'TelNo')
m.clean_number(df_analytic, 'MobileNo')
m.replace_not_valid_to_empty(df_analytic, 'TelNo')
m.replace_not_valid_to_empty(df_analytic, 'MobileNo')

df_analytic.loc[df_analytic['TelNo'].str.contains('00000'), 'TelNo'] = 'empty'
df_analytic.loc[df_analytic['MobileNo'].str.contains('00000'), 'MobileNo'] = 'empty'

m.clean_space(df_analytic, 'Email')
df_analytic['Email'] = m.lowercase(df_analytic, 'Email')
m.email_correction(df_analytic, 'Email')

c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:67: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:68: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('[^0-9]','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:90: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:193: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('mailto:|-primary|-pri|-Mrs|(noemailtobesent)','', regex=True, inplace=True)

In [9]:
m.email_correction(df_analytic, 'Email')

In [10]:
df_analytic.loc[(df_analytic['Email'] != 'empty') & ((df_analytic['TelNo'] != 'empty') | (df_analytic['MobileNo'] != 'empty')), 'Contact Type'] = 'Email and Phone'
df_analytic.loc[(df_analytic['Email'] != 'empty') & ((df_analytic['TelNo'] == 'empty') & (df_analytic['MobileNo'] == 'empty')), 'Contact Type'] = 'Email Only'
df_analytic.loc[(df_analytic['Email'] == 'empty') & ((df_analytic['TelNo'] != 'empty') | (df_analytic['MobileNo'] != 'empty')), 'Contact Type'] = 'Phone Only'

df_analytic.loc[df_analytic['Contact Type'] == 'empty'].to_csv(r'C:\Users\fajar\Documents\Python\Data\contact_type_empty_analytic.csv', index=False)

count_contact_type_empty = df_analytic.loc[df_analytic['Contact Type'] == 'empty'].shape[0]

df_analytic.drop(df_analytic.loc[df_analytic['Contact Type'] == 'empty'].index, inplace=True)
df_analytic.reset_index(drop=True, inplace=True)

count_after_contact_type_empty = df_analytic.shape[0]

df_analytic

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK066096,Karma Resorts,Other,Past Guests,Karma Kandara,PF296726,Ms,Maricha,Mabunay,Female,...,2024-12-18 00:00:00,2,HOUSE_USE,V_OWNER_NRB,COMP,2,2,0,Email and Phone,NO
1,KB046143,Karma Resorts,Other,Past Guests,Karma Bavaria,PF296418,Mrs,Clement,Surgess,Female,...,2024-12-16 00:00:00,4,WYNDHAM,WYNDHAM,WYNDHAM,3,0,0,Email and Phone,NO
2,KK065230,Karma Resorts,Other,Past Guests,Karma Kandara,PF202839,Ms,Georgie,Smith,Female,...,2024-12-16 00:00:00,2,HOUSE_USE,V_OWNER_NRB,COMP,1,0,0,Email and Phone,NO
3,KK047983,Karma Resorts,Other,Past Guests,Karma Kandara,PF259088,Miss,Natalie,West,Female,...,2024-12-22 00:00:00,7,HOUSE_USE,CHAT,DIGITAL,6,0,0,Email and Phone,NO
4,KK063111,Karma Resorts,Other,Past Guests,Karma Kandara,PF291338,Mrs,Oriana,Mastro,Female,...,2024-12-18 00:00:00,2,HOUSE_USE,V_OWNER,COMP,6,0,0,Email Only,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,KK059814,Karma Resorts,Other,Past Guests,Karma Kandara,empty,Ms,Oxana,Khoroshavina,Unknown,...,2024-12-15 00:00:00,1,WEDDING,WEDDING,GROUP,2,0,0,Email Only,NO
64,KB039996,Karma Resorts,Other,Past Guests,Karma Bavaria,empty,Firma,Roche,Diagnostig,Unknown,...,2024-12-18 18:00:00,0,CB,CB,GROUP,1,0,0,Email Only,NO
65,KB039995,Karma Resorts,Other,Past Guests,Karma Bavaria,empty,Firma,Roche,Diagnostig,Unknown,...,2024-12-17 18:00:00,0,CB,CB,GROUP,1,0,0,Email Only,NO
66,KB046245,Karma Resorts,Other,Past Guests,Karma Bavaria,empty,Mr,Wmna,Tengateway,Unknown,...,2024-12-18 00:00:00,3,WYNDHAM,WYNDHAM,WYNDHAM,2,0,0,Email Only,NO
67,KSH021634,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF295661,,Lisa,Jeffery,Unknown,...,2024-12-16 00:00:00,1,OTA,OTA,RETAIL,2,0,0,Email and Phone,NO

In [11]:
# Cek Email Karma
email_karma = m.find_karma(df_analytic, 'Email')
count_email_karma = email_karma.shape[0]
email_karma.to_csv(r'C:\Users\fajar\Documents\Python\Data\email_deleted_analytic.csv', index=False)

email_karma

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
9,KB043543,Karma Resorts,Other,Past Guests,Karma Bavaria,PF126784,Herr,Axel,Reimlinger,Male,...,2024-12-20 00:00:00,4,COMP,STAFF,COMP,1,0,0,Email and Phone,NO
55,KB046191,Karma Resorts,Other,Past Guests,Karma Bavaria,PF076160,Mr,Vic,Faulkner,Male,...,2024-12-16 00:00:00,2,COMP,STAFF,COMP,2,0,0,Email and Phone,NO
56,KLM007525,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF076160,Mr,Vic,Faulkner,Male,...,2024-12-18 00:00:00,2,COMP,STAFF,COMP,2,0,0,Email and Phone,NO

In [12]:
# delete email Karma
count_after_clean_karma = m.delete_karma(df_analytic, 'Email')

df_analytic

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK066096,Karma Resorts,Other,Past Guests,Karma Kandara,PF296726,Ms,Maricha,Mabunay,Female,...,2024-12-18 00:00:00,2,HOUSE_USE,V_OWNER_NRB,COMP,2,2,0,Email and Phone,NO
1,KB046143,Karma Resorts,Other,Past Guests,Karma Bavaria,PF296418,Mrs,Clement,Surgess,Female,...,2024-12-16 00:00:00,4,WYNDHAM,WYNDHAM,WYNDHAM,3,0,0,Email and Phone,NO
2,KK065230,Karma Resorts,Other,Past Guests,Karma Kandara,PF202839,Ms,Georgie,Smith,Female,...,2024-12-16 00:00:00,2,HOUSE_USE,V_OWNER_NRB,COMP,1,0,0,Email and Phone,NO
3,KK047983,Karma Resorts,Other,Past Guests,Karma Kandara,PF259088,Miss,Natalie,West,Female,...,2024-12-22 00:00:00,7,HOUSE_USE,CHAT,DIGITAL,6,0,0,Email and Phone,NO
4,KK063111,Karma Resorts,Other,Past Guests,Karma Kandara,PF291338,Mrs,Oriana,Mastro,Female,...,2024-12-18 00:00:00,2,HOUSE_USE,V_OWNER,COMP,6,0,0,Email Only,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,KK059814,Karma Resorts,Other,Past Guests,Karma Kandara,empty,Ms,Oxana,Khoroshavina,Unknown,...,2024-12-15 00:00:00,1,WEDDING,WEDDING,GROUP,2,0,0,Email Only,NO
61,KB039996,Karma Resorts,Other,Past Guests,Karma Bavaria,empty,Firma,Roche,Diagnostig,Unknown,...,2024-12-18 18:00:00,0,CB,CB,GROUP,1,0,0,Email Only,NO
62,KB039995,Karma Resorts,Other,Past Guests,Karma Bavaria,empty,Firma,Roche,Diagnostig,Unknown,...,2024-12-17 18:00:00,0,CB,CB,GROUP,1,0,0,Email Only,NO
63,KB046245,Karma Resorts,Other,Past Guests,Karma Bavaria,empty,Mr,Wmna,Tengateway,Unknown,...,2024-12-18 00:00:00,3,WYNDHAM,WYNDHAM,WYNDHAM,2,0,0,Email Only,NO
64,KSH021634,Karma Resorts,Other,Past Guests,Karma Salford Hall,PF295661,,Lisa,Jeffery,Unknown,...,2024-12-16 00:00:00,1,OTA,OTA,RETAIL,2,0,0,Email and Phone,NO

In [13]:
df_analytic['Salutation']

0        Ms
1       Mrs
2        Ms
3      Miss
4       Mrs
      ...
60       Ms
61    Firma
62    Firma
63       Mr
64
Name: Salutation, Length: 65, dtype: string

In [14]:
# Cek leads test
test_leads = df_analytic.loc[
    
        df_analytic['Email'].str.contains('^test@', flags=re.I, regex=True) |
        df_analytic['Email'].str.contains('\+test', flags=re.I, regex=True) |
    
        df_analytic['First_Name'].str.contains('^test$', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('^test$', flags=re.I, regex=True) |

        df_analytic['First_Name'].str.contains('test 1', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('test 2', flags=re.I, regex=True)|
        df_analytic['First_Name'].str.contains('test1', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('test2', flags=re.I, regex=True)|

        df_analytic['First_Name'].str.contains(' test ', flags=re.I, regex=True) | 
        df_analytic['Surname'].str.contains(' test ', flags=re.I, regex=True) | 
        df_analytic['Surname'].str.contains(' test$', flags=re.I, regex=True)
    ]

count_leads_test = test_leads.shape[0]

test_leads.to_csv(r'C:\Users\fajar\Documents\Python\Data\test_leads_analytic.csv', index=False)
test_leads

Empty DataFrame
Columns: [Booking_Id, Lead Brand, Lead Sub- Brand, Lead Source, Resort_Name, ProfileRef, Salutation, First_Name, Surname, Gender, Language, DOB, Street, Area, Town, County, Country, Nationality, PostCode, TelNo, MobileNo, Email, Exclude From Mailing, Opt In, Booking Status, DateArrival, DateDepart, No. of Nights, Market_Segment, Media_Code, Media Code Group, No. of Adult, No. of Children, No. of Infants, Contact Type, Odyssey Members]
Index: []

[0 rows x 36 columns]

In [15]:
df_analytic.drop(test_leads.index, inplace=True)
df_analytic.reset_index(drop=True, inplace=True)

count_after_dedup_test = df_analytic.shape[0]
count_after_dedup_test

65

In [16]:
count_final_data = count_after_dedup_test

In [17]:
# df_analytic.loc[(df_analytic['Email'] == 'jonmosley6@yahoo.com')]

In [18]:
df_analytic.replace('empty', '', inplace=True)

In [19]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Data Awal Zoho Analytic : "+str(count_data_awal))
print("Jumlah Data Email dan Phone Kosong : "+str(count_contact_type_empty))
print("Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : "+str(count_after_contact_type_empty))
print("Jumlah Data Email Yang Termasuk List Karma : "+str(count_email_karma))
print("Jumlah Data Email Setelah List Karma Dihapus : "+str(count_after_clean_karma))
print("Jumlah Data Test : "+str(count_leads_test))
print("Jumlah Data Email Setelah Data Test Dihapus : "+str(count_after_dedup_test))
print("Jumlah Data Akhir : "+str(count_final_data))

==========================================================
Summary
==========================================================
Jumlah Data Awal Zoho Analytic : 68
Jumlah Data Email dan Phone Kosong : 0
Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : 68
Jumlah Data Email Yang Termasuk List Karma : 3
Jumlah Data Email Setelah List Karma Dihapus : 65
Jumlah Data Test : 0
Jumlah Data Email Setelah Data Test Dihapus : 65
Jumlah Data Akhir : 65

In [20]:
df_analytic.to_excel(r'C:\Users\fajar\Documents\Python\Data\check_country_code_analytic.xlsx', index=False)