In [3]:
import pandas as pd
import re

import past_guest_module as pm

import sys
sys.path.append('../zoho_data_app/')

import main_module as m

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [4]:
path = r'C:\Users\fajar\Documents\Python\Data\Past Guest Data\Zoho Analytic\2025\Feb\2 Feb - 10 Feb\CRM_Rental_Report_02_Feb_-_10_Feb.xlsx'
df_analytic = pd.read_excel(path, dtype='string', sheet_name='Sheet1')
count_data_awal = df_analytic.shape[0]
df_analytic

,Booking_Id,TelNo,MobileNo,Email,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK065643,+86 20 3564 0799,862035640799,21193248@gmail.com,Karma Resorts,Other,Past Guests,Karma Kandara,PF295989,Mr,...,2025-02-04 00:00:00,1,OTA,OTA,RETAIL,3,2,0,,
1,KLM008209,07909983075,07909983075,andrew.tait85@outlook.com,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF302226,Mr,...,2025-02-05 00:00:00,1,DIR,WEBSITE,DIGITAL,2,0,0,,
2,KB047151,4179845427,<NA>,annabelger@web.de,Karma Resorts,Other,Past Guests,Karma Bavaria,PF300058,Frau,...,2025-02-02 00:00:00,1,DIR,WEBSITE,DIGITAL,2,1,0,,
3,KB047228,015141270403,<NA>,anton.mederer@freenet.de,Karma Resorts,Other,Past Guests,Karma Bavaria,PF289135,Frau,...,2025-02-02 00:00:00,2,COMP,GER_OWE,COMP,2,0,0,,
4,KK058834,0407703432,<NA>,bandghooper@optusnet.com.au,Karma Resorts,Other,Past Guests,Karma Kandara,PF281399,Mrs,...,2025-02-08 00:00:00,3,DIGITAL,GHPA,DIGITAL,2,0,0,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,KLM007662,+44 7775 883697,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF296748,<NA>,...,2025-02-02 00:00:00,1,OTA,OTA,RETAIL,2,0,0,,
81,KB047757,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,PF080008,<NA>,...,2025-02-03 19:30:00,0,LGR,LGR,GROUP,1,0,0,,
82,KB039339,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,PF259055,Mr,...,2025-02-09 00:00:00,5,WYNDHAM,WYNDHAM,WYNDHAM,2,0,0,,
83,KB046575,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297298,Firma,...,2025-02-05 18:00:00,0,CB,OTA,RETAIL,1,0,0,,
84,KB040236,<NA>,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Bavaria,PF262940,Mrs,...,2025-02-04 00:00:00,7,WYNDHAM,WYNDHAM,WYNDHAM,4,0,0,,

In [5]:
df_analytic.columns

Index(['Booking_Id', 'TelNo', 'MobileNo', 'Email', 'Lead Brand',
       'Lead Sub- Brand', 'Lead Source', 'Resort_Name', 'ProfileRef',
       'Salutation', 'First_Name', 'Surname', 'Gender', 'Language', 'DOB',
       'Street', 'Area', 'Town', 'County', 'Country', 'Nationality',
       'PostCode', 'Exclude From Mailing', 'Opt In', 'Booking Code',
       'Booking Status', 'DateArrival', 'DateDepart', 'No. of Nights',
       'Market_Segment', 'Media_Code', 'Media Code Group', 'No. of Adult',
       'No. of Children', 'No. of Infants', 'Contact Type', 'Odyssey Members'],
      dtype='object')

In [6]:
new_cols = ['Booking_Id', 'Lead Brand', 'Lead Sub- Brand', 'Lead Source',
       'Resort_Name', 'ProfileRef', 'Salutation', 'First_Name', 'Surname',
       'Gender', 'Language', 'DOB', 'Street', 'Area', 'Town', 'County',
       'Country', 'Nationality', 'PostCode', 'TelNo', 'MobileNo', 'Email',
       'Exclude From Mailing', 'Opt In', 'Booking Status',
       'DateArrival', 'DateDepart', 'No. of Nights', 'Market_Segment',
       'Media_Code', 'Media Code Group', 'No. of Adult', 'No. of Children',
       'No. of Infants', 'Contact Type', 'Odyssey Members']																																																																																																																																						

df_analytic = df_analytic.reindex(columns=new_cols)

In [7]:
df_analytic.fillna('empty', inplace=True)
df_analytic['Contact Type'] = 'empty'
df_analytic['Odyssey Members'] = 'NO'

In [8]:
df_analytic.loc[df_analytic['Surname'] == 'empty', 'Surname'] = '-'

In [9]:
df_analytic['Salutation'].replace('empty', '', inplace=True)
df_analytic['First_Name'].replace('empty', '', inplace=True)
df_analytic['Surname'].replace('empty', '', inplace=True)

df_analytic['Salutation'] = df_analytic['Salutation'].str.title()
df_analytic['First_Name'] = df_analytic['First_Name'].str.title()
df_analytic['Surname'] = df_analytic['Surname'].str.title()

df_analytic

C:\Users\fajar\AppData\Local\Temp\ipykernel_12440\2281604359.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['Salutation'].replace('empty', '', inplace=True)
C:\Users\fajar\AppData\Local\Temp\ipykernel_12440\2281604359.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['First_Name'].replace('empty', '', inplace=True)
C:\Users\fajar\AppData\Local\Temp\ipykernel_12440\2281604359.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_analytic['Surname'].replace('empty', '', inplace=True)

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK065643,Karma Resorts,Other,Past Guests,Karma Kandara,PF295989,Mr,Weijiong,Li,Male,...,2025-02-04 00:00:00,1,OTA,OTA,RETAIL,3,2,0,empty,NO
1,KLM008209,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF302226,Mr,Andy,Tait,Male,...,2025-02-05 00:00:00,1,DIR,WEBSITE,DIGITAL,2,0,0,empty,NO
2,KB047151,Karma Resorts,Other,Past Guests,Karma Bavaria,PF300058,Frau,Anna,Belger,Female,...,2025-02-02 00:00:00,1,DIR,WEBSITE,DIGITAL,2,1,0,empty,NO
3,KB047228,Karma Resorts,Other,Past Guests,Karma Bavaria,PF289135,Frau,Birgit,Mederer,Female,...,2025-02-02 00:00:00,2,COMP,GER_OWE,COMP,2,0,0,empty,NO
4,KK058834,Karma Resorts,Other,Past Guests,Karma Kandara,PF281399,Mrs,Belinda,Hooper,Female,...,2025-02-08 00:00:00,3,DIGITAL,GHPA,DIGITAL,2,0,0,empty,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,KLM007662,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF296748,,Russell,Martin,Unknown,...,2025-02-02 00:00:00,1,OTA,OTA,RETAIL,2,0,0,empty,NO
81,KB047757,Karma Resorts,Other,Past Guests,Karma Bavaria,PF080008,,Kea,Marketing Gmbh,Unknown,...,2025-02-03 19:30:00,0,LGR,LGR,GROUP,1,0,0,empty,NO
82,KB039339,Karma Resorts,Other,Past Guests,Karma Bavaria,PF259055,Mr,Rinku,Mukherjee,Male,...,2025-02-09 00:00:00,5,WYNDHAM,WYNDHAM,WYNDHAM,2,0,0,empty,NO
83,KB046575,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297298,Firma,7092 Siemens Ag,Erlangen,Unknown,...,2025-02-05 18:00:00,0,CB,OTA,RETAIL,1,0,0,empty,NO
84,KB040236,Karma Resorts,Other,Past Guests,Karma Bavaria,PF262940,Mrs,Katherine,Hooke,Female,...,2025-02-04 00:00:00,7,WYNDHAM,WYNDHAM,WYNDHAM,4,0,0,empty,NO

In [10]:
m.clean_number(df_analytic, 'TelNo')
m.clean_number(df_analytic, 'MobileNo')
m.replace_not_valid_to_empty(df_analytic, 'TelNo')
m.replace_not_valid_to_empty(df_analytic, 'MobileNo')

df_analytic.loc[df_analytic['TelNo'].str.contains('00000'), 'TelNo'] = 'empty'
df_analytic.loc[df_analytic['MobileNo'].str.contains('00000'), 'MobileNo'] = 'empty'

m.clean_space(df_analytic, 'Email')
df_analytic['Email'] = m.lowercase(df_analytic, 'Email')
m.email_correction(df_analytic, 'Email')

c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:67: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:68: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('[^0-9]','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:90: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:223: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('^mailto:|-primary$|-pri$|-Mrs$|(noemailtobesent)$','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:251: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_mail), '@mail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:252: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail), '@gmail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:253: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail_com), '@gmail.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:254: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail), '@hotmail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:255: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail_com), '@hotmail.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:256: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_com), '@yahoo.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:257: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo), '@yahoo.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:258: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_in), '@yahoo.co.in', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:273: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df_columns].loc[~df[df_columns].str.contains('@', df_columns, na=False)] = ''

In [11]:
m.email_correction(df_analytic, 'Email')

c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:223: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('^mailto:|-primary$|-pri$|-Mrs$|(noemailtobesent)$','', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:251: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_mail), '@mail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:252: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail), '@gmail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:253: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail_com), '@gmail.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:254: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail), '@hotmail.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:255: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail_com), '@hotmail.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:256: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_com), '@yahoo.com', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:257: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo), '@yahoo.', regex=True, inplace=True)
c:\Users\fajar\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:258: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_in), '@yahoo.co.in', regex=True, inplace=True)

In [12]:
df_analytic.loc[(df_analytic['Email'] != 'empty') & ((df_analytic['TelNo'] != 'empty') | (df_analytic['MobileNo'] != 'empty')), 'Contact Type'] = 'Email and Phone'
df_analytic.loc[(df_analytic['Email'] != 'empty') & ((df_analytic['TelNo'] == 'empty') & (df_analytic['MobileNo'] == 'empty')), 'Contact Type'] = 'Email Only'
df_analytic.loc[(df_analytic['Email'] == 'empty') & ((df_analytic['TelNo'] != 'empty') | (df_analytic['MobileNo'] != 'empty')), 'Contact Type'] = 'Phone Only'

df_analytic.loc[df_analytic['Contact Type'] == 'empty'].to_csv(r'C:\Users\fajar\Documents\Python\Data\contact_type_empty_analytic.csv', index=False)

count_contact_type_empty = df_analytic.loc[df_analytic['Contact Type'] == 'empty'].shape[0]

df_analytic.drop(df_analytic.loc[df_analytic['Contact Type'] == 'empty'].index, inplace=True)
df_analytic.reset_index(drop=True, inplace=True)

count_after_contact_type_empty = df_analytic.shape[0]

df_analytic

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK065643,Karma Resorts,Other,Past Guests,Karma Kandara,PF295989,Mr,Weijiong,Li,Male,...,2025-02-04 00:00:00,1,OTA,OTA,RETAIL,3,2,0,Email and Phone,NO
1,KLM008209,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF302226,Mr,Andy,Tait,Male,...,2025-02-05 00:00:00,1,DIR,WEBSITE,DIGITAL,2,0,0,Email and Phone,NO
2,KB047151,Karma Resorts,Other,Past Guests,Karma Bavaria,PF300058,Frau,Anna,Belger,Female,...,2025-02-02 00:00:00,1,DIR,WEBSITE,DIGITAL,2,1,0,Email and Phone,NO
3,KB047228,Karma Resorts,Other,Past Guests,Karma Bavaria,PF289135,Frau,Birgit,Mederer,Female,...,2025-02-02 00:00:00,2,COMP,GER_OWE,COMP,2,0,0,Email and Phone,NO
4,KK058834,Karma Resorts,Other,Past Guests,Karma Kandara,PF281399,Mrs,Belinda,Hooper,Female,...,2025-02-08 00:00:00,3,DIGITAL,GHPA,DIGITAL,2,0,0,Email and Phone,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,KLM007662,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF296748,,Russell,Martin,Unknown,...,2025-02-02 00:00:00,1,OTA,OTA,RETAIL,2,0,0,Email and Phone,NO
81,KB047757,Karma Resorts,Other,Past Guests,Karma Bavaria,PF080008,,Kea,Marketing Gmbh,Unknown,...,2025-02-03 19:30:00,0,LGR,LGR,GROUP,1,0,0,Email Only,NO
82,KB039339,Karma Resorts,Other,Past Guests,Karma Bavaria,PF259055,Mr,Rinku,Mukherjee,Male,...,2025-02-09 00:00:00,5,WYNDHAM,WYNDHAM,WYNDHAM,2,0,0,Email Only,NO
83,KB046575,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297298,Firma,7092 Siemens Ag,Erlangen,Unknown,...,2025-02-05 18:00:00,0,CB,OTA,RETAIL,1,0,0,Email Only,NO
84,KB040236,Karma Resorts,Other,Past Guests,Karma Bavaria,PF262940,Mrs,Katherine,Hooke,Female,...,2025-02-04 00:00:00,7,WYNDHAM,WYNDHAM,WYNDHAM,4,0,0,Email Only,NO

In [13]:
# Cek Email Karma
email_karma = m.find_karma(df_analytic, 'Email')
count_email_karma = email_karma.shape[0]
email_karma.to_csv(r'C:\Users\fajar\Documents\Python\Data\email_deleted_analytic.csv', index=False)

email_karma

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
27,KK067052,Karma Resorts,Other,Past Guests,Karma Kandara,PF298275,,Jessica,Fernandes,Unknown,...,2025-02-02 00:00:00,3,COMP,RESERVED,KC,2,0,0,Email and Phone,NO
28,KK067051,Karma Resorts,Other,Past Guests,Karma Kandara,PF298275,,Jessica,Fernandes,Unknown,...,2025-02-02 00:00:00,3,COMP,RESERVED,KC,2,0,0,Email and Phone,NO
29,KK067049,Karma Resorts,Other,Past Guests,Karma Kandara,PF298275,,Jessica,Fernandes,Unknown,...,2025-02-02 00:00:00,2,COMP,RESERVED,KC,3,0,0,Email and Phone,NO

In [14]:
# delete email Karma
count_after_clean_karma = m.delete_karma(df_analytic, 'Email')

df_analytic

,Booking_Id,Lead Brand,Lead Sub- Brand,Lead Source,Resort_Name,ProfileRef,Salutation,First_Name,Surname,Gender,...,DateDepart,No. of Nights,Market_Segment,Media_Code,Media Code Group,No. of Adult,No. of Children,No. of Infants,Contact Type,Odyssey Members
0,KK065643,Karma Resorts,Other,Past Guests,Karma Kandara,PF295989,Mr,Weijiong,Li,Male,...,2025-02-04 00:00:00,1,OTA,OTA,RETAIL,3,2,0,Email and Phone,NO
1,KLM008209,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF302226,Mr,Andy,Tait,Male,...,2025-02-05 00:00:00,1,DIR,WEBSITE,DIGITAL,2,0,0,Email and Phone,NO
2,KB047151,Karma Resorts,Other,Past Guests,Karma Bavaria,PF300058,Frau,Anna,Belger,Female,...,2025-02-02 00:00:00,1,DIR,WEBSITE,DIGITAL,2,1,0,Email and Phone,NO
3,KB047228,Karma Resorts,Other,Past Guests,Karma Bavaria,PF289135,Frau,Birgit,Mederer,Female,...,2025-02-02 00:00:00,2,COMP,GER_OWE,COMP,2,0,0,Email and Phone,NO
4,KK058834,Karma Resorts,Other,Past Guests,Karma Kandara,PF281399,Mrs,Belinda,Hooper,Female,...,2025-02-08 00:00:00,3,DIGITAL,GHPA,DIGITAL,2,0,0,Email and Phone,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,KLM007662,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,PF296748,,Russell,Martin,Unknown,...,2025-02-02 00:00:00,1,OTA,OTA,RETAIL,2,0,0,Email and Phone,NO
78,KB047757,Karma Resorts,Other,Past Guests,Karma Bavaria,PF080008,,Kea,Marketing Gmbh,Unknown,...,2025-02-03 19:30:00,0,LGR,LGR,GROUP,1,0,0,Email Only,NO
79,KB039339,Karma Resorts,Other,Past Guests,Karma Bavaria,PF259055,Mr,Rinku,Mukherjee,Male,...,2025-02-09 00:00:00,5,WYNDHAM,WYNDHAM,WYNDHAM,2,0,0,Email Only,NO
80,KB046575,Karma Resorts,Other,Past Guests,Karma Bavaria,PF297298,Firma,7092 Siemens Ag,Erlangen,Unknown,...,2025-02-05 18:00:00,0,CB,OTA,RETAIL,1,0,0,Email Only,NO
81,KB040236,Karma Resorts,Other,Past Guests,Karma Bavaria,PF262940,Mrs,Katherine,Hooke,Female,...,2025-02-04 00:00:00,7,WYNDHAM,WYNDHAM,WYNDHAM,4,0,0,Email Only,NO

In [15]:
df_analytic['Salutation']

0        Mr
1        Mr
2      Frau
3      Frau
4       Mrs
      ...
77
78
79       Mr
80    Firma
81      Mrs
Name: Salutation, Length: 82, dtype: string

In [16]:
# Cek leads test
test_leads = df_analytic.loc[
    
        df_analytic['Email'].str.contains('^test@', flags=re.I, regex=True) |
        df_analytic['Email'].str.contains('\+test', flags=re.I, regex=True) |
    
        df_analytic['First_Name'].str.contains('^test$', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('^test$', flags=re.I, regex=True) |

        df_analytic['First_Name'].str.contains('test 1', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('test 2', flags=re.I, regex=True)|
        df_analytic['First_Name'].str.contains('test1', flags=re.I, regex=True) |
        df_analytic['Surname'].str.contains('test2', flags=re.I, regex=True)|

        df_analytic['First_Name'].str.contains(' test ', flags=re.I, regex=True) | 
        df_analytic['Surname'].str.contains(' test ', flags=re.I, regex=True) | 
        df_analytic['Surname'].str.contains(' test$', flags=re.I, regex=True)
    ]

count_leads_test = test_leads.shape[0]

test_leads.to_csv(r'C:\Users\fajar\Documents\Python\Data\test_leads_analytic.csv', index=False)
test_leads

Empty DataFrame
Columns: [Booking_Id, Lead Brand, Lead Sub- Brand, Lead Source, Resort_Name, ProfileRef, Salutation, First_Name, Surname, Gender, Language, DOB, Street, Area, Town, County, Country, Nationality, PostCode, TelNo, MobileNo, Email, Exclude From Mailing, Opt In, Booking Status, DateArrival, DateDepart, No. of Nights, Market_Segment, Media_Code, Media Code Group, No. of Adult, No. of Children, No. of Infants, Contact Type, Odyssey Members]
Index: []

[0 rows x 36 columns]

In [17]:
df_analytic.drop(test_leads.index, inplace=True)
df_analytic.reset_index(drop=True, inplace=True)

count_after_dedup_test = df_analytic.shape[0]
count_after_dedup_test

82

In [18]:
count_final_data = count_after_dedup_test

In [19]:
# df_analytic.loc[(df_analytic['Email'] == 'jonmosley6@yahoo.com')]

In [20]:
df_analytic.replace('empty', '', inplace=True)

In [21]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Data Awal Zoho Analytic : "+str(count_data_awal))
print("Jumlah Data Email dan Phone Kosong : "+str(count_contact_type_empty))
print("Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : "+str(count_after_contact_type_empty))
print("Jumlah Data Email Yang Termasuk List Karma : "+str(count_email_karma))
print("Jumlah Data Email Setelah List Karma Dihapus : "+str(count_after_clean_karma))
print("Jumlah Data Test : "+str(count_leads_test))
print("Jumlah Data Email Setelah Data Test Dihapus : "+str(count_after_dedup_test))
print("Jumlah Data Akhir : "+str(count_final_data))

==========================================================
Summary
==========================================================
Jumlah Data Awal Zoho Analytic : 85
Jumlah Data Email dan Phone Kosong : 0
Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : 85
Jumlah Data Email Yang Termasuk List Karma : 3
Jumlah Data Email Setelah List Karma Dihapus : 82
Jumlah Data Test : 0
Jumlah Data Email Setelah Data Test Dihapus : 82
Jumlah Data Akhir : 82

In [22]:
df_analytic.to_excel(r'C:\Users\fajar\Documents\Python\Data\check_country_code_analytic.xlsx', index=False)