In [1]:
import pandas as pd
import re

import past_guest_module as pm

import sys
sys.path.append('../zoho_data_app/')

import main_module as m

%load_ext autoreload
%autoreload 2

In [2]:
path = r'C:\Users\fajar.fatoni\Documents\Python\Data\Past Guest Data\View Point\2025\Feb\16 Feb - 24 Feb\CheckOutReport 16 Feb - 24 Feb.xlsx'
df_viewpoint = pd.read_excel(path, dtype='string', sheet_name='Sheet1')
count_data_awal = df_viewpoint.shape[0]
df_viewpoint

,Title,Firstname,lastname,DOB,PAN CARD,Email,Phone,Mobile,AddressLine1,AddressLine2,...,CheckInDate,CheckOutDate,room,UnitCategory,BookingNo,BookingSourceDesc,BookingTypeDesc,Date of Tour,Sales Rep and Comments,Opt In
0,Mr,Ankush,Rana,1987-04-20 00:00:00,AOFPR7403B,108ankushrana@gmail.com,919418584112,919418123212,"FLAT NO 4, BLOCK - 4A","SECTOR 6, PHASE 3, NEW SHIMLA",...,2025-02-15 21:48:17,2025-02-19 14:21:18,V112,2 Bedroom Fractional,2638360,KC Member,Sales Gift,<NA>,<NA>,YES
1,Mr,Ankush,Rana,1987-04-20 00:00:00,AOFPR7403B,108ankushrana@gmail.com,919418584112,919418123212,"FLAT NO 4, BLOCK - 4A","SECTOR 6, PHASE 3, NEW SHIMLA",...,2025-02-20 02:35:20,2025-02-22 11:52:57,35,1 Bedroom Imperial,2638358,KC Member,Sales Gift,<NA>,<NA>,YES
2,Mr,PRASHANT SHANKAR,KAMBLE,<NA>,<NA>,1310.JANNAT@GMAIL.COM,919870990499,919664824345,"A-203, ABHISHEK CHS, NAIGAON,","DADAR EAST, MUMBAI-400014",...,2025-02-16 16:00:12,2025-02-20 15:36:59,303,Hotel Unit Deluxe,2761134,Fly Buy Indian,Karma Experience India,<NA>,<NA>,YES
3,Mr,ANAND,KUMAR M,<NA>,<NA>,1976ande@gmail.com,919844345365,919844034088,9/1 2ND CROSS MUNESHWARA BLOCK NAGAPPA STREET,GUTTAHALLI BANGALORE 560003,...,2025-02-17 15:23:07,2025-02-20 13:52:44,34(2),Non Member Studio,2756101,Fly Buy Indian,Karma Experience India,<NA>,<NA>,YES
4,Mr,byoungsu,Yu,1981-02-17 00:00:00,<NA>,2000namin@gmail.com,6285239098642,<NA>,-,-,...,2025-02-19 15:15:31,2025-02-22 12:02:13,11,3 Bedroom Garden View Pool Vil,2659272,Hotel Bookings,Nakula - Rental,<NA>,<NA>,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1809,-,Sarah,Sipula,<NA>,<NA>,<NA>,447796953853,<NA>,<NA>,<NA>,...,2025-02-20 04:53:30,2025-02-22 17:03:53,122,2 Bedroom Apartment,2774480,Hotel Bookings,Booking.com,<NA>,<NA>,YES
1810,<NA>,Adélé,Graffiti,<NA>,<NA>,<NA>,<NA>,<NA>,.,.,...,2025-02-23 02:12:47,2025-02-23 16:58:07,124,Studio Apartment,2778085,Hotel Bookings,Booking.com,<NA>,<NA>,YES
1811,<NA>,"Subramanian, Venkata & Guruswamy, Vijaya",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,2025-02-22 04:36:23,2025-02-23 17:14:32,114,1 Bedroom Apartment,2777287,Hotel Bookings,Wyndham Guests,<NA>,<NA>,YES
1812,<NA>,"Subramanian, Venkata & Guruswamy, Vijaya",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,2025-02-22 04:38:58,2025-02-23 17:20:39,113,2 Bedroom Apartment,2770737,Hotel Bookings,Wyndham Guests,<NA>,<NA>,YES
1813,krg,Fajar Fatoni,86,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [3]:
df_viewpoint.columns

Index(['Title', 'Firstname', 'lastname', 'DOB', 'PAN CARD', 'Email', 'Phone',
       'Mobile', 'AddressLine1', 'AddressLine2', 'Town', 'State', 'Country',
       'PostCode', 'Nationality', 'MaritalStatus', 'resortname', 'Arrival',
       'Departure', 'CheckInDate', 'CheckOutDate', 'room', 'UnitCategory',
       'BookingNo', 'BookingSourceDesc', 'BookingTypeDesc', 'Date of Tour',
       'Sales Rep and Comments', 'Opt In'],
      dtype='object')

In [4]:
df_viewpoint.fillna('empty', inplace=True)

df_viewpoint['Contact Type'] = 'empty'
df_viewpoint['Odyssey Members'] = 'NO'

df_viewpoint['Lead Brand'] = 'Karma Resorts'
df_viewpoint['Lead Sub-Brand'] = 'Other'
df_viewpoint['Lead Source'] = 'Past Guests'
df_viewpoint['Lead Locations'] = df_viewpoint['resortname']
df_viewpoint['Lead Source Description'] = 'Viewpoint'

In [5]:
df_viewpoint.loc[df_viewpoint['Opt In'] == 'YES', 'Exclude From Mailing'] = 'NO'
df_viewpoint.loc[df_viewpoint['Opt In'] == 'NO', 'Exclude From Mailing'] = 'YES'

In [6]:
df_viewpoint.loc[df_viewpoint['lastname'] == 'empty', 'lastname'] = '-'

In [7]:
df_viewpoint['Title'].replace('empty', '', inplace=True)
df_viewpoint['Firstname'].replace('empty', '', inplace=True)
df_viewpoint['lastname'].replace('empty', '', inplace=True)

df_viewpoint['Title'] = df_viewpoint['Title'].str.title()
df_viewpoint['Firstname'] = df_viewpoint['Firstname'].str.title()
df_viewpoint['lastname'] = df_viewpoint['lastname'].str.title()

df_viewpoint

C:\Users\fajar.fatoni\AppData\Local\Temp\ipykernel_8248\3404343493.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_viewpoint['Title'].replace('empty', '', inplace=True)
C:\Users\fajar.fatoni\AppData\Local\Temp\ipykernel_8248\3404343493.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_viewpoint['Firstname'].replace('empty', '', inplace=True)
C:\Users\fajar.fatoni\AppData\Local\Temp\ipykernel_8248\3404343493.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_viewpoint['lastname'].replace('empty', '', inplace=True)

,Title,Firstname,lastname,DOB,PAN CARD,Email,Phone,Mobile,AddressLine1,AddressLine2,...,Sales Rep and Comments,Opt In,Contact Type,Odyssey Members,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Exclude From Mailing
0,Mr,Ankush,Rana,1987-04-20 00:00:00,AOFPR7403B,108ankushrana@gmail.com,919418584112,919418123212,"FLAT NO 4, BLOCK - 4A","SECTOR 6, PHASE 3, NEW SHIMLA",...,empty,YES,empty,NO,Karma Resorts,Other,Past Guests,Karma Royal Haathi Mahal,Viewpoint,NO
1,Mr,Ankush,Rana,1987-04-20 00:00:00,AOFPR7403B,108ankushrana@gmail.com,919418584112,919418123212,"FLAT NO 4, BLOCK - 4A","SECTOR 6, PHASE 3, NEW SHIMLA",...,empty,YES,empty,NO,Karma Resorts,Other,Past Guests,Karma Royal Monterio,Viewpoint,NO
2,Mr,Prashant Shankar,Kamble,empty,empty,1310.JANNAT@GMAIL.COM,919870990499,919664824345,"A-203, ABHISHEK CHS, NAIGAON,","DADAR EAST, MUMBAI-400014",...,empty,YES,empty,NO,Karma Resorts,Other,Past Guests,Karma Royal Haathi Mahal,Viewpoint,NO
3,Mr,Anand,Kumar M,empty,empty,1976ande@gmail.com,919844345365,919844034088,9/1 2ND CROSS MUNESHWARA BLOCK NAGAPPA STREET,GUTTAHALLI BANGALORE 560003,...,empty,YES,empty,NO,Karma Resorts,Other,Past Guests,Karma Royal Palms,Viewpoint,NO
4,Mr,Byoungsu,Yu,1981-02-17 00:00:00,empty,2000namin@gmail.com,6285239098642,empty,-,-,...,empty,YES,empty,NO,Karma Resorts,Other,Past Guests,Karma Jimbaran,Viewpoint,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1809,-,Sarah,Sipula,empty,empty,empty,447796953853,empty,empty,empty,...,empty,YES,empty,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1810,,Adélé,Graffiti,empty,empty,empty,empty,empty,.,.,...,empty,YES,empty,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1811,,"Subramanian, Venkata & Guruswamy, Vijaya",-,empty,empty,empty,empty,empty,empty,empty,...,empty,YES,empty,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1812,,"Subramanian, Venkata & Guruswamy, Vijaya",-,empty,empty,empty,empty,empty,empty,empty,...,empty,YES,empty,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1813,Krg,Fajar Fatoni,86,empty,empty,empty,empty,empty,empty,empty,...,empty,empty,empty,NO,Karma Resorts,Other,Past Guests,empty,Viewpoint,NaN

In [8]:
m.clean_number(df_viewpoint, 'Phone')
m.clean_number(df_viewpoint, 'Mobile')
m.replace_not_valid_to_empty(df_viewpoint, 'Phone')
m.replace_not_valid_to_empty(df_viewpoint, 'Mobile')

df_viewpoint.loc[df_viewpoint['Phone'].str.contains('00000'), 'Phone'] = 'empty'
df_viewpoint.loc[df_viewpoint['Mobile'].str.contains('00000'), 'Mobile'] = 'empty'

m.clean_space(df_viewpoint, 'Email')
df_viewpoint['Email'] = m.lowercase(df_viewpoint, 'Email')
m.email_correction(df_viewpoint, 'Email')

c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:67: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:68: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('[^0-9]','', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:90: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:223: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('^mailto:|-primary$|-pri$|-Mrs$|(noemailtobesent)$','', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:251: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_mail), '@mail.', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:252: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail), '@gmail.', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:253: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail_com), '@gmail.com', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:254: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail), '@hotmail.', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:255: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail_com), '@hotmail.com', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:256: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_com), '@yahoo.com', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:257: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo), '@yahoo.', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:258: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_in), '@yahoo.co.in', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:273: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df_columns].loc[~df[df_columns].str.contains('@', df_columns, na=False)] = ''

In [9]:
m.email_correction(df_viewpoint, 'Email')

c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:223: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('^mailto:|-primary$|-pri$|-Mrs$|(noemailtobesent)$','', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:251: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_mail), '@mail.', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:252: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail), '@gmail.', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:253: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail_com), '@gmail.com', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:254: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail), '@hotmail.', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:255: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail_com), '@hotmail.com', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:256: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_com), '@yahoo.com', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:257: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo), '@yahoo.', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:258: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_in), '@yahoo.co.in', regex=True, inplace=True)

In [10]:
df_viewpoint.loc[(df_viewpoint['Email'] != 'empty') & ((df_viewpoint['Phone'] != 'empty') | (df_viewpoint['Mobile'] != 'empty')), 'Contact Type'] = 'Email and Phone'
df_viewpoint.loc[(df_viewpoint['Email'] != 'empty') & ((df_viewpoint['Phone'] == 'empty') & (df_viewpoint['Mobile'] == 'empty')), 'Contact Type'] = 'Email Only'
df_viewpoint.loc[(df_viewpoint['Email'] == 'empty') & ((df_viewpoint['Phone'] != 'empty') | (df_viewpoint['Mobile'] != 'empty')), 'Contact Type'] = 'Phone Only'

df_viewpoint.loc[df_viewpoint['Contact Type'] == 'empty'].to_csv(r'C:\Users\fajar.fatoni\Documents\Python\Data\contact_type_empty_viewpoint.csv', index=False)

count_contact_type_empty = df_viewpoint.loc[df_viewpoint['Contact Type'] == 'empty'].shape[0]

df_viewpoint.drop(df_viewpoint.loc[df_viewpoint['Contact Type'] == 'empty'].index, inplace=True)
df_viewpoint.reset_index(drop=True, inplace=True)

count_after_contact_type_empty = df_viewpoint.shape[0]

df_viewpoint

,Title,Firstname,lastname,DOB,PAN CARD,Email,Phone,Mobile,AddressLine1,AddressLine2,...,Sales Rep and Comments,Opt In,Contact Type,Odyssey Members,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Exclude From Mailing
0,Mr,Ankush,Rana,1987-04-20 00:00:00,AOFPR7403B,108ankushrana@gmail.com,919418584112,919418123212,"FLAT NO 4, BLOCK - 4A","SECTOR 6, PHASE 3, NEW SHIMLA",...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Royal Haathi Mahal,Viewpoint,NO
1,Mr,Ankush,Rana,1987-04-20 00:00:00,AOFPR7403B,108ankushrana@gmail.com,919418584112,919418123212,"FLAT NO 4, BLOCK - 4A","SECTOR 6, PHASE 3, NEW SHIMLA",...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Royal Monterio,Viewpoint,NO
2,Mr,Prashant Shankar,Kamble,empty,empty,1310.jannat@gmail.com,919870990499,919664824345,"A-203, ABHISHEK CHS, NAIGAON,","DADAR EAST, MUMBAI-400014",...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Royal Haathi Mahal,Viewpoint,NO
3,Mr,Anand,Kumar M,empty,empty,1976ande@gmail.com,919844345365,919844034088,9/1 2ND CROSS MUNESHWARA BLOCK NAGAPPA STREET,GUTTAHALLI BANGALORE 560003,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Royal Palms,Viewpoint,NO
4,Mr,Byoungsu,Yu,1981-02-17 00:00:00,empty,2000namin@gmail.com,6285239098642,empty,-,-,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Jimbaran,Viewpoint,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1809,-,Sarah,Sipula,empty,empty,,447796953853,empty,empty,empty,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1810,,Adélé,Graffiti,empty,empty,,empty,empty,.,.,...,empty,YES,Email Only,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1811,,"Subramanian, Venkata & Guruswamy, Vijaya",-,empty,empty,,empty,empty,empty,empty,...,empty,YES,Email Only,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1812,,"Subramanian, Venkata & Guruswamy, Vijaya",-,empty,empty,,empty,empty,empty,empty,...,empty,YES,Email Only,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1813,Krg,Fajar Fatoni,86,empty,empty,,empty,empty,empty,empty,...,empty,empty,Email Only,NO,Karma Resorts,Other,Past Guests,empty,Viewpoint,NaN

In [11]:
# Cek Email Karma
email_karma = m.find_karma(df_viewpoint, 'Email')
count_email_karma = email_karma.shape[0]
email_karma.to_csv(r'C:\Users\fajar.fatoni\Documents\Python\Data\email_deleted_viewpoint.csv', index=False)

email_karma

,Title,Firstname,lastname,DOB,PAN CARD,Email,Phone,Mobile,AddressLine1,AddressLine2,...,Sales Rep and Comments,Opt In,Contact Type,Odyssey Members,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Exclude From Mailing
283,,Maintenance Room,Karma Chakra,empty,empty,chakra@karmagroup.com,914812526252,919446080121,"Ward # 09, Block#12, Near Nasrath Church",KOTTAYAM,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,"Karma Chakra, Kerala",Viewpoint,NO
679,Mr,John Andrew,Spence,1961-02-23 00:00:00,empty,johnspence88@hotmail.com,empty,empty,"JL. BY PASS NGURAH RAI NO.61, PEMOGAN,",KEC. DENPASAR SEL.,...,empty,YES,Email Only,NO,Karma Resorts,Other,Past Guests,Karma Karnak,Viewpoint,NO
680,Mr,John Andrew,Spence,1961-02-23 00:00:00,empty,johnspence88@hotmail.com,empty,empty,"JL. BY PASS NGURAH RAI NO.61, PEMOGAN,",KEC. DENPASAR SEL.,...,empty,YES,Email Only,NO,Karma Resorts,Other,Past Guests,Karma Karnak,Viewpoint,NO
866,Ms,Marlinde Anne Maria,Verhoeff,empty,empty,marlinde.verhoeff@karmagroup.com,6282237493002,empty,INDONESIA,empty,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,"Karma Panalee, Koh Samui",Viewpoint,NO
916,-,Maintenance Room -,Karma Royal Monterio,empty,empty,mr.asstfom@karmagroup.com,918326716200,empty,karma royal monetrio,Arpora,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Royal Monterio,Viewpoint,NO
917,-,Maintenance Room -,Karma Royal Monterio,empty,empty,mr.asstfom@karmagroup.com,918326716200,empty,karma royal monetrio,Arpora,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Royal Monterio,Viewpoint,NO
918,-,Maintenance Room -,Karma Royal Monterio,empty,empty,mr.asstfom@karmagroup.com,918326716200,empty,karma royal monetrio,Arpora,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Royal Monterio,Viewpoint,NO
1522,Mr,Pramod,B,empty,empty,tarun.sharma@karmagroup.com,919893137377,empty,MP,empty,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Royal Palms,Viewpoint,NO

In [12]:
# delete email Karma
count_after_clean_karma = m.delete_karma(df_viewpoint, 'Email')

df_viewpoint

,Title,Firstname,lastname,DOB,PAN CARD,Email,Phone,Mobile,AddressLine1,AddressLine2,...,Sales Rep and Comments,Opt In,Contact Type,Odyssey Members,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Exclude From Mailing
0,Mr,Ankush,Rana,1987-04-20 00:00:00,AOFPR7403B,108ankushrana@gmail.com,919418584112,919418123212,"FLAT NO 4, BLOCK - 4A","SECTOR 6, PHASE 3, NEW SHIMLA",...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Royal Haathi Mahal,Viewpoint,NO
1,Mr,Ankush,Rana,1987-04-20 00:00:00,AOFPR7403B,108ankushrana@gmail.com,919418584112,919418123212,"FLAT NO 4, BLOCK - 4A","SECTOR 6, PHASE 3, NEW SHIMLA",...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Royal Monterio,Viewpoint,NO
2,Mr,Prashant Shankar,Kamble,empty,empty,1310.jannat@gmail.com,919870990499,919664824345,"A-203, ABHISHEK CHS, NAIGAON,","DADAR EAST, MUMBAI-400014",...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Royal Haathi Mahal,Viewpoint,NO
3,Mr,Anand,Kumar M,empty,empty,1976ande@gmail.com,919844345365,919844034088,9/1 2ND CROSS MUNESHWARA BLOCK NAGAPPA STREET,GUTTAHALLI BANGALORE 560003,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Royal Palms,Viewpoint,NO
4,Mr,Byoungsu,Yu,1981-02-17 00:00:00,empty,2000namin@gmail.com,6285239098642,empty,-,-,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Jimbaran,Viewpoint,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1801,-,Sarah,Sipula,empty,empty,,447796953853,empty,empty,empty,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1802,,Adélé,Graffiti,empty,empty,,empty,empty,.,.,...,empty,YES,Email Only,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1803,,"Subramanian, Venkata & Guruswamy, Vijaya",-,empty,empty,,empty,empty,empty,empty,...,empty,YES,Email Only,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1804,,"Subramanian, Venkata & Guruswamy, Vijaya",-,empty,empty,,empty,empty,empty,empty,...,empty,YES,Email Only,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1805,Krg,Fajar Fatoni,86,empty,empty,,empty,empty,empty,empty,...,empty,empty,Email Only,NO,Karma Resorts,Other,Past Guests,empty,Viewpoint,NaN

In [13]:
# Cek leads test
test_leads = df_viewpoint.loc[
    
        df_viewpoint['Email'].str.contains('^test@', flags=re.I, regex=True) |
        df_viewpoint['Email'].str.contains('\+test', flags=re.I, regex=True) |
    
        df_viewpoint['Firstname'].str.contains('^test$', flags=re.I, regex=True) |
        df_viewpoint['lastname'].str.contains('^test$', flags=re.I, regex=True) |

        df_viewpoint['Firstname'].str.contains('test 1', flags=re.I, regex=True) |
        df_viewpoint['lastname'].str.contains('test 2', flags=re.I, regex=True)|
        df_viewpoint['Firstname'].str.contains('test1', flags=re.I, regex=True) |
        df_viewpoint['lastname'].str.contains('test2', flags=re.I, regex=True)|

        df_viewpoint['Firstname'].str.contains(' test ', flags=re.I, regex=True) | 
        df_viewpoint['lastname'].str.contains(' test ', flags=re.I, regex=True) | 
        df_viewpoint['lastname'].str.contains(' test$', flags=re.I, regex=True)
    ]

count_leads_test = test_leads.shape[0]

test_leads.to_csv(r'C:\Users\fajar.fatoni\Documents\Python\Data\test_leads_viewpoint.csv', index=False)
test_leads

Empty DataFrame
Columns: [Title, Firstname, lastname, DOB, PAN CARD, Email, Phone, Mobile, AddressLine1, AddressLine2, Town, State, Country, PostCode, Nationality, MaritalStatus, resortname, Arrival, Departure, CheckInDate, CheckOutDate, room, UnitCategory, BookingNo, BookingSourceDesc, BookingTypeDesc, Date of Tour, Sales Rep and Comments, Opt In, Contact Type, Odyssey Members, Lead Brand, Lead Sub-Brand, Lead Source, Lead Locations, Lead Source Description, Exclude From Mailing]
Index: []

[0 rows x 37 columns]

In [14]:
df_viewpoint.drop(test_leads.index, inplace=True)
df_viewpoint.reset_index(drop=True, inplace=True)

count_after_dedup_test = df_viewpoint.shape[0]
count_after_dedup_test

1806

In [15]:
count_final_data = count_after_dedup_test

In [16]:
# df_viewpoint.loc[df_viewpoint['BookingNo'] == '2070341']

In [17]:
df_viewpoint.replace('empty', '', inplace=True)

In [18]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Data Awal Viewpoint : "+str(count_data_awal))
print("Jumlah Data Email dan Phone Kosong : "+str(count_contact_type_empty))
print("Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : "+str(count_after_contact_type_empty))
print("Jumlah Data Email Yang Termasuk List Karma : "+str(count_email_karma))
print("Jumlah Data Email Setelah List Karma Dihapus : "+str(count_after_clean_karma))
print("Jumlah Data Test : "+str(count_leads_test))
print("Jumlah Data Email Setelah Data Test Dihapus : "+str(count_after_dedup_test))
print("Jumlah Data Akhir : "+str(count_final_data))

==========================================================
Summary
==========================================================
Jumlah Data Awal Viewpoint : 1814
Jumlah Data Email dan Phone Kosong : 0
Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : 1814
Jumlah Data Email Yang Termasuk List Karma : 8
Jumlah Data Email Setelah List Karma Dihapus : 1806
Jumlah Data Test : 0
Jumlah Data Email Setelah Data Test Dihapus : 1806
Jumlah Data Akhir : 1806

In [19]:
df_viewpoint.to_excel(r'C:\Users\fajar.fatoni\Documents\Python\Data\check_country_code_viewpoint.xlsx', index=False)