In [6]:
import pandas as pd
import re

import past_guest_module as pm

import sys
sys.path.append('../zoho_data_app/')

import main_module as m

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [7]:
path = r'C:\Users\fajar.fatoni\Documents\Python\Data\Past Guest Data\View Point\2025\Mar\16 Mar - 24 Mar\CheckOutReport 16 Mar - 24 Mar.xlsx'
df_viewpoint = pd.read_excel(path, dtype='string', sheet_name='Sheet1')
count_data_awal = df_viewpoint.shape[0]
df_viewpoint

,Title,Firstname,lastname,DOB,PAN CARD,Email,Phone,Mobile,AddressLine1,AddressLine2,...,CheckInDate,CheckOutDate,room,UnitCategory,BookingNo,BookingSourceDesc,BookingTypeDesc,Date of Tour,Sales Rep and Comments,Opt In
0,Mr,Akshansh,Mishra,1991-06-19 00:00:00,<NA>,07singhparul@gmail.com,917290953138,918595378771,"006, Neighbourhood elite apt., Sri","Venkateshpura layout, Sampigehalli, Bangalore",...,2025-03-16 15:27:29,2025-03-20 00:05:37,28(2),2 Bedroom Apartment,2763053,KCE2 Indian,Karma Experience India,<NA>,<NA>,YES
1,Mr,Martin,Mcgraw Coyle,1956-02-12 00:00:00,<NA>,1066martinc@gmail.com,447747343535,<NA>,-,-,...,2025-03-17 00:32:52,2025-03-19 17:32:49,6,Heritage Room,2649871,Fly Buy Western,Booksi,2025-03-18 14:44:00,Elizabeth,YES
2,Mr,Adrian,Harvey,1961-03-25 00:00:00,<NA>,1adrianharvey@gmail.com,447976363533,<NA>,"Sunset, South Road",<NA>,...,2025-03-14 05:02:23,2025-03-16 19:02:13,<NA>,Main Building Double,2746723,Fly Buy Western,Booksi,2025-03-15 14:00:00,a.eastham,YES
3,Mrs,Monica,Rastogi Bisht,1918-01-01 00:00:00,AIUPB3085C,1monicabisht@gmail.com,919820967906,<NA>,F1704 KANAKIA PARIS,BANDRA EAST,...,2025-03-14 17:55:57,2025-03-21 02:32:07,315,Cabin Twin,2720190,KC Member,Luxor to Luxor cruise - 7 nights,<NA>,<NA>,YES
4,Mr,Harsh,Kumar,1985-01-24 00:00:00,CYXPK4415J,24kumarharsh@gmail.com,917303065585,918860560697,O 251/2 GILL COLONY NR DWAYS O,NARAYNPUR SAHRANPUR,...,2025-03-12 17:58:00,2025-03-16 15:26:40,16,1 Bedroom Apartment,2776751,KC Member,Sales Gift,<NA>,<NA>,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1899,<NA>,MICKAEL,LEBORGNE,<NA>,<NA>,<NA>,<NA>,<NA>,-,<NA>,...,2025-03-19 02:16:07,2025-03-19 16:03:55,126,1 Bedroom Apartment,2801137,Hotel Bookings,Expedia,<NA>,<NA>,YES
1900,<NA>,Mehdi,El Djilali,<NA>,<NA>,<NA>,<NA>,<NA>,-,<NA>,...,2025-03-19 04:19:00,2025-03-19 16:25:54,114,1 Bedroom Apartment,2801146,Hotel Bookings,Resort Rental,<NA>,<NA>,YES
1901,<NA>,Mehdi,El Djilali,<NA>,<NA>,<NA>,<NA>,<NA>,-,<NA>,...,2025-03-19 16:26:15,2025-03-20 18:33:32,114,1 Bedroom Apartment,2801156,Hotel Bookings,Resort Rental,<NA>,<NA>,YES
1902,-,AUGUSTINA,MEZA,<NA>,<NA>,<NA>,<NA>,<NA>,.,<NA>,...,2025-03-16 02:37:21,2025-03-22 14:33:18,102,2 Bedroom Apartment,2545682,Hotel Bookings,Wyndham Guests,<NA>,<NA>,YES
1903,krg,Fajar Fatoni,86,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [8]:
df_viewpoint.columns

Index(['Title', 'Firstname', 'lastname', 'DOB', 'PAN CARD', 'Email', 'Phone',
       'Mobile', 'AddressLine1', 'AddressLine2', 'Town', 'State', 'Country',
       'PostCode', 'Nationality', 'MaritalStatus', 'resortname', 'Arrival',
       'Departure', 'CheckInDate', 'CheckOutDate', 'room', 'UnitCategory',
       'BookingNo', 'BookingSourceDesc', 'BookingTypeDesc', 'Date of Tour',
       'Sales Rep and Comments', 'Opt In'],
      dtype='object')

In [9]:
df_viewpoint.fillna('empty', inplace=True)

df_viewpoint['Contact Type'] = 'empty'
df_viewpoint['Odyssey Members'] = 'NO'

df_viewpoint['Lead Brand'] = 'Karma Resorts'
df_viewpoint['Lead Sub-Brand'] = 'Other'
df_viewpoint['Lead Source'] = 'Past Guests'
df_viewpoint['Lead Locations'] = df_viewpoint['resortname']
df_viewpoint['Lead Source Description'] = 'Viewpoint'

In [10]:
df_viewpoint.loc[df_viewpoint['Opt In'] == 'YES', 'Exclude From Mailing'] = 'NO'
df_viewpoint.loc[df_viewpoint['Opt In'] == 'NO', 'Exclude From Mailing'] = 'YES'

In [11]:
df_viewpoint.loc[df_viewpoint['lastname'] == 'empty', 'lastname'] = '-'

In [12]:
df_viewpoint['Title'].replace('empty', '', inplace=True)
df_viewpoint['Firstname'].replace('empty', '', inplace=True)
df_viewpoint['lastname'].replace('empty', '', inplace=True)

df_viewpoint['Title'] = df_viewpoint['Title'].str.title()
df_viewpoint['Firstname'] = df_viewpoint['Firstname'].str.title()
df_viewpoint['lastname'] = df_viewpoint['lastname'].str.title()

df_viewpoint

C:\Users\fajar.fatoni\AppData\Local\Temp\ipykernel_10092\3404343493.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_viewpoint['Title'].replace('empty', '', inplace=True)
C:\Users\fajar.fatoni\AppData\Local\Temp\ipykernel_10092\3404343493.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_viewpoint['Firstname'].replace('empty', '', inplace=True)
C:\Users\fajar.fatoni\AppData\Local\Temp\ipykernel_10092\3404343493.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_viewpoint['lastname'].replace('empty', '', inplace=True)

,Title,Firstname,lastname,DOB,PAN CARD,Email,Phone,Mobile,AddressLine1,AddressLine2,...,Sales Rep and Comments,Opt In,Contact Type,Odyssey Members,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Exclude From Mailing
0,Mr,Akshansh,Mishra,1991-06-19 00:00:00,empty,07singhparul@gmail.com,917290953138,918595378771,"006, Neighbourhood elite apt., Sri","Venkateshpura layout, Sampigehalli, Bangalore",...,empty,YES,empty,NO,Karma Resorts,Other,Past Guests,Karma Royal Palms,Viewpoint,NO
1,Mr,Martin,Mcgraw Coyle,1956-02-12 00:00:00,empty,1066martinc@gmail.com,447747343535,empty,-,-,...,Elizabeth,YES,empty,NO,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,Viewpoint,NO
2,Mr,Adrian,Harvey,1961-03-25 00:00:00,empty,1adrianharvey@gmail.com,447976363533,empty,"Sunset, South Road",empty,...,a.eastham,YES,empty,NO,Karma Resorts,Other,Past Guests,Karma Salford Hall,Viewpoint,NO
3,Mrs,Monica,Rastogi Bisht,1918-01-01 00:00:00,AIUPB3085C,1monicabisht@gmail.com,919820967906,empty,F1704 KANAKIA PARIS,BANDRA EAST,...,empty,YES,empty,NO,Karma Resorts,Other,Past Guests,Karma Karnak,Viewpoint,NO
4,Mr,Harsh,Kumar,1985-01-24 00:00:00,CYXPK4415J,24kumarharsh@gmail.com,917303065585,918860560697,O 251/2 GILL COLONY NR DWAYS O,NARAYNPUR SAHRANPUR,...,empty,YES,empty,NO,Karma Resorts,Other,Past Guests,Karma Royal Monterio,Viewpoint,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1899,,Mickael,Leborgne,empty,empty,empty,empty,empty,-,empty,...,empty,YES,empty,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1900,,Mehdi,El Djilali,empty,empty,empty,empty,empty,-,empty,...,empty,YES,empty,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1901,,Mehdi,El Djilali,empty,empty,empty,empty,empty,-,empty,...,empty,YES,empty,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1902,-,Augustina,Meza,empty,empty,empty,empty,empty,.,empty,...,empty,YES,empty,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1903,Krg,Fajar Fatoni,86,empty,empty,empty,empty,empty,empty,empty,...,empty,empty,empty,NO,Karma Resorts,Other,Past Guests,empty,Viewpoint,NaN

In [13]:
m.clean_number(df_viewpoint, 'Phone')
m.clean_number(df_viewpoint, 'Mobile')
m.replace_not_valid_to_empty(df_viewpoint, 'Phone')
m.replace_not_valid_to_empty(df_viewpoint, 'Mobile')

df_viewpoint.loc[df_viewpoint['Phone'].str.contains('00000'), 'Phone'] = 'empty'
df_viewpoint.loc[df_viewpoint['Mobile'].str.contains('00000'), 'Mobile'] = 'empty'

m.clean_space(df_viewpoint, 'Email')
df_viewpoint['Email'] = m.lowercase(df_viewpoint, 'Email')
m.email_correction(df_viewpoint, 'Email')

c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:71: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:72: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('[^0-9]','', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:94: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:227: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('^mailto:|-primary$|-pri$|-Mrs$|(noemailtobesent)$','', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:255: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_mail), '@mail.', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:256: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail), '@gmail.', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:257: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail_com), '@gmail.com', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:258: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail), '@hotmail.', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:259: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail_com), '@hotmail.com', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:260: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_com), '@yahoo.com', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:261: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo), '@yahoo.', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:262: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_in), '@yahoo.co.in', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:277: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df_columns].loc[~df[df_columns].str.contains('@', df_columns, na=False)] = ''

In [14]:
m.email_correction(df_viewpoint, 'Email')

c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:227: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('^mailto:|-primary$|-pri$|-Mrs$|(noemailtobesent)$','', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:255: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_mail), '@mail.', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:256: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail), '@gmail.', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:257: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_gmail_com), '@gmail.com', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:258: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail), '@hotmail.', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:259: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_hotmail_com), '@hotmail.com', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:260: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_com), '@yahoo.com', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:261: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo), '@yahoo.', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\past_guest_toni_app\../zoho_data_app\main_module.py:262: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('|'.join(list_correction_yahoo_in), '@yahoo.co.in', regex=True, inplace=True)

In [15]:
df_viewpoint.loc[(df_viewpoint['Email'] != 'empty') & ((df_viewpoint['Phone'] != 'empty') | (df_viewpoint['Mobile'] != 'empty')), 'Contact Type'] = 'Email and Phone'
df_viewpoint.loc[(df_viewpoint['Email'] != 'empty') & ((df_viewpoint['Phone'] == 'empty') & (df_viewpoint['Mobile'] == 'empty')), 'Contact Type'] = 'Email Only'
df_viewpoint.loc[(df_viewpoint['Email'] == 'empty') & ((df_viewpoint['Phone'] != 'empty') | (df_viewpoint['Mobile'] != 'empty')), 'Contact Type'] = 'Phone Only'

df_viewpoint.loc[df_viewpoint['Contact Type'] == 'empty'].to_csv(r'C:\Users\fajar.fatoni\Documents\Python\Data\contact_type_empty_viewpoint.csv', index=False)

count_contact_type_empty = df_viewpoint.loc[df_viewpoint['Contact Type'] == 'empty'].shape[0]

df_viewpoint.drop(df_viewpoint.loc[df_viewpoint['Contact Type'] == 'empty'].index, inplace=True)
df_viewpoint.reset_index(drop=True, inplace=True)

count_after_contact_type_empty = df_viewpoint.shape[0]

df_viewpoint

,Title,Firstname,lastname,DOB,PAN CARD,Email,Phone,Mobile,AddressLine1,AddressLine2,...,Sales Rep and Comments,Opt In,Contact Type,Odyssey Members,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Exclude From Mailing
0,Mr,Akshansh,Mishra,1991-06-19 00:00:00,empty,07singhparul@gmail.com,917290953138,918595378771,"006, Neighbourhood elite apt., Sri","Venkateshpura layout, Sampigehalli, Bangalore",...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Royal Palms,Viewpoint,NO
1,Mr,Martin,Mcgraw Coyle,1956-02-12 00:00:00,empty,1066martinc@gmail.com,447747343535,empty,-,-,...,Elizabeth,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,Viewpoint,NO
2,Mr,Adrian,Harvey,1961-03-25 00:00:00,empty,1adrianharvey@gmail.com,447976363533,empty,"Sunset, South Road",empty,...,a.eastham,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Salford Hall,Viewpoint,NO
3,Mrs,Monica,Rastogi Bisht,1918-01-01 00:00:00,AIUPB3085C,1monicabisht@gmail.com,919820967906,empty,F1704 KANAKIA PARIS,BANDRA EAST,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Karnak,Viewpoint,NO
4,Mr,Harsh,Kumar,1985-01-24 00:00:00,CYXPK4415J,24kumarharsh@gmail.com,917303065585,918860560697,O 251/2 GILL COLONY NR DWAYS O,NARAYNPUR SAHRANPUR,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Royal Monterio,Viewpoint,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1899,,Mickael,Leborgne,empty,empty,,empty,empty,-,empty,...,empty,YES,Email Only,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1900,,Mehdi,El Djilali,empty,empty,,empty,empty,-,empty,...,empty,YES,Email Only,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1901,,Mehdi,El Djilali,empty,empty,,empty,empty,-,empty,...,empty,YES,Email Only,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1902,-,Augustina,Meza,empty,empty,,empty,empty,.,empty,...,empty,YES,Email Only,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1903,Krg,Fajar Fatoni,86,empty,empty,,empty,empty,empty,empty,...,empty,empty,Email Only,NO,Karma Resorts,Other,Past Guests,empty,Viewpoint,NaN

In [16]:
# Cek Email Karma
email_karma = m.find_karma(df_viewpoint, 'Email')
count_email_karma = email_karma.shape[0]
email_karma.to_csv(r'C:\Users\fajar.fatoni\Documents\Python\Data\email_deleted_viewpoint.csv', index=False)

email_karma

,Title,Firstname,lastname,DOB,PAN CARD,Email,Phone,Mobile,AddressLine1,AddressLine2,...,Sales Rep and Comments,Opt In,Contact Type,Odyssey Members,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Exclude From Mailing
744,,Maintenance Room,Karma Haveli,empty,empty,karma.haveli@karmagroup.com,9101412671027,9101412671597,"240 & 242, Gatore Road, Brahmapuri,",empty,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,"Karma Haveli, Jaipur",Viewpoint,NO
921,Ms,Marlinde Anne Maria,Verhoeff,empty,empty,marlinde.verhoeff@karmagroup.com,6282237493002,empty,INDONESIA,empty,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,"Karma Panalee, Koh Samui",Viewpoint,NO
990,-,Maintenance Room -,Karma Royal Monterio,empty,empty,mr.asstfom@karmagroup.com,918326716200,empty,karma royal monetrio,Arpora,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Royal Monterio,Viewpoint,NO
991,-,Maintenance Room -,Karma Royal Monterio,empty,empty,mr.asstfom@karmagroup.com,918326716200,empty,karma royal monetrio,Arpora,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Royal Monterio,Viewpoint,NO
1492,Ms,Shivani,Yeshwant,empty,empty,shivani.yeshwant@karmagroup.com,empty,empty,-,-,...,empty,YES,Email Only,NO,Karma Resorts,Other,Past Guests,"Karma Panalee, Koh Samui",Viewpoint,NO
1595,Mr,Karma Website,Test,empty,empty,subito.test@karmagroup.com,empty,empty,TBA,TBA,...,empty,YES,Email Only,NO,Karma Resorts,Other,Past Guests,"Karma Haveli, Jaipur",Viewpoint,NO
1606,Mr,Sukhjender Pal,Singh,empty,empty,sukhjender.singh@karmagroup.com,917807770241,empty,"Village Tohu, Indru Nag Road,",empty,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,"Karma Utopia, Manali",Viewpoint,NO
1607,Mr,Sukhjender Pal,Singh,empty,empty,sukhjender.singh@karmagroup.com,917807770241,empty,"Village Tohu, Indru Nag Road,",empty,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,"Karma Utopia, Manali",Viewpoint,NO
1608,Mr,Suleman,Ahamad,empty,empty,suleman.ahamad@karmagroup.com,empty,empty,empty,empty,...,empty,YES,Email Only,NO,Karma Resorts,Other,Past Guests,"Karma Panalee, Koh Samui",Viewpoint,NO
1656,Mr,Nirez,Khan,empty,empty,tarun.sharma@karmagroup.com,919893137377,empty,MP,empty,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Royal Palms,Viewpoint,NO

In [17]:
# delete email Karma
count_after_clean_karma = m.delete_karma(df_viewpoint, 'Email')

df_viewpoint

,Title,Firstname,lastname,DOB,PAN CARD,Email,Phone,Mobile,AddressLine1,AddressLine2,...,Sales Rep and Comments,Opt In,Contact Type,Odyssey Members,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Exclude From Mailing
0,Mr,Akshansh,Mishra,1991-06-19 00:00:00,empty,07singhparul@gmail.com,917290953138,918595378771,"006, Neighbourhood elite apt., Sri","Venkateshpura layout, Sampigehalli, Bangalore",...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Royal Palms,Viewpoint,NO
1,Mr,Martin,Mcgraw Coyle,1956-02-12 00:00:00,empty,1066martinc@gmail.com,447747343535,empty,-,-,...,Elizabeth,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Lake of Menteith,Viewpoint,NO
2,Mr,Adrian,Harvey,1961-03-25 00:00:00,empty,1adrianharvey@gmail.com,447976363533,empty,"Sunset, South Road",empty,...,a.eastham,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Salford Hall,Viewpoint,NO
3,Mrs,Monica,Rastogi Bisht,1918-01-01 00:00:00,AIUPB3085C,1monicabisht@gmail.com,919820967906,empty,F1704 KANAKIA PARIS,BANDRA EAST,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Karnak,Viewpoint,NO
4,Mr,Harsh,Kumar,1985-01-24 00:00:00,CYXPK4415J,24kumarharsh@gmail.com,917303065585,918860560697,O 251/2 GILL COLONY NR DWAYS O,NARAYNPUR SAHRANPUR,...,empty,YES,Email and Phone,NO,Karma Resorts,Other,Past Guests,Karma Royal Monterio,Viewpoint,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1889,,Mickael,Leborgne,empty,empty,,empty,empty,-,empty,...,empty,YES,Email Only,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1890,,Mehdi,El Djilali,empty,empty,,empty,empty,-,empty,...,empty,YES,Email Only,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1891,,Mehdi,El Djilali,empty,empty,,empty,empty,-,empty,...,empty,YES,Email Only,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1892,-,Augustina,Meza,empty,empty,,empty,empty,.,empty,...,empty,YES,Email Only,NO,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Viewpoint,NO
1893,Krg,Fajar Fatoni,86,empty,empty,,empty,empty,empty,empty,...,empty,empty,Email Only,NO,Karma Resorts,Other,Past Guests,empty,Viewpoint,NaN

In [18]:
# Cek leads test
test_leads = df_viewpoint.loc[
    
        df_viewpoint['Email'].str.contains('^test@', flags=re.I, regex=True) |
        df_viewpoint['Email'].str.contains('\+test', flags=re.I, regex=True) |
    
        df_viewpoint['Firstname'].str.contains('^test$', flags=re.I, regex=True) |
        df_viewpoint['lastname'].str.contains('^test$', flags=re.I, regex=True) |

        df_viewpoint['Firstname'].str.contains('test 1', flags=re.I, regex=True) |
        df_viewpoint['lastname'].str.contains('test 2', flags=re.I, regex=True)|
        df_viewpoint['Firstname'].str.contains('test1', flags=re.I, regex=True) |
        df_viewpoint['lastname'].str.contains('test2', flags=re.I, regex=True)|

        df_viewpoint['Firstname'].str.contains(' test ', flags=re.I, regex=True) | 
        df_viewpoint['lastname'].str.contains(' test ', flags=re.I, regex=True) | 
        df_viewpoint['lastname'].str.contains(' test$', flags=re.I, regex=True)
    ]

count_leads_test = test_leads.shape[0]

test_leads.to_csv(r'C:\Users\fajar.fatoni\Documents\Python\Data\test_leads_viewpoint.csv', index=False)
test_leads

Empty DataFrame
Columns: [Title, Firstname, lastname, DOB, PAN CARD, Email, Phone, Mobile, AddressLine1, AddressLine2, Town, State, Country, PostCode, Nationality, MaritalStatus, resortname, Arrival, Departure, CheckInDate, CheckOutDate, room, UnitCategory, BookingNo, BookingSourceDesc, BookingTypeDesc, Date of Tour, Sales Rep and Comments, Opt In, Contact Type, Odyssey Members, Lead Brand, Lead Sub-Brand, Lead Source, Lead Locations, Lead Source Description, Exclude From Mailing]
Index: []

[0 rows x 37 columns]

In [19]:
df_viewpoint.drop(test_leads.index, inplace=True)
df_viewpoint.reset_index(drop=True, inplace=True)

count_after_dedup_test = df_viewpoint.shape[0]
count_after_dedup_test

1894

In [20]:
count_final_data = count_after_dedup_test

In [21]:
# df_viewpoint.loc[df_viewpoint['BookingNo'] == '2070341']

In [22]:
df_viewpoint.replace('empty', '', inplace=True)

In [23]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Data Awal Viewpoint : "+str(count_data_awal))
print("Jumlah Data Email dan Phone Kosong : "+str(count_contact_type_empty))
print("Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : "+str(count_after_contact_type_empty))
print("Jumlah Data Email Yang Termasuk List Karma : "+str(count_email_karma))
print("Jumlah Data Email Setelah List Karma Dihapus : "+str(count_after_clean_karma))
print("Jumlah Data Test : "+str(count_leads_test))
print("Jumlah Data Email Setelah Data Test Dihapus : "+str(count_after_dedup_test))
print("Jumlah Data Akhir : "+str(count_final_data))

==========================================================
Summary
==========================================================
Jumlah Data Awal Viewpoint : 1904
Jumlah Data Email dan Phone Kosong : 0
Jumlah Data Setelah Hapus Email dan Phone Yang Kosong : 1904
Jumlah Data Email Yang Termasuk List Karma : 10
Jumlah Data Email Setelah List Karma Dihapus : 1894
Jumlah Data Test : 0
Jumlah Data Email Setelah Data Test Dihapus : 1894
Jumlah Data Akhir : 1894

In [24]:
df_viewpoint.to_excel(r'C:\Users\fajar.fatoni\Documents\Python\Data\check_country_code_viewpoint.xlsx', index=False)