In [20]:
import pandas as pd
import numpy as np
from fractions import Fraction

In [21]:
push_cols = ['BookRef', 'PrimaryGuestProfileRef', 'Lead_Locations', 'Language', 'Brand','Lead_Sub_Brand',
              'Lead_Source', 'Lead_Source_Description', 'Guest_Type', 'Booking_Status', 
              'Arrival_Date', 'Departure_Date', 'Street', 'Street2', 
              'City', 'State', 'Country', 'Nationality', 'Zip_Code', 'Phone', 'Mobile', 'Email',
              'Salutation', 'First_Name', 'Last_Name', 'Gender', 'Media_Source_Code', 'Market_Segment',
              'Adult', 'Children', 'Contact_type', 'Email_Opt_In', 'Email_Opt_Out', 'Email_status']

# "BookRef" : rw['BookRef'],
#                 "PrimaryGuestProfileRef" : rw['PrimaryGuestProfileRef'],
#                 "Destination" : rw['Lead_Locations'],
#                 "Language" : rw['Language'],
#                 "Brand": rw['Brand'],
#                 "Lead_Sub_Brand": rw['Lead_Sub_Brand'],
#                 "Lead_Source": rw['Lead_Source'],
#                 "Lead_Source_Description": rw['Lead_Source_Description'],
#                 "Lead_Locations": rw['Lead_Locations'],
#                 "Guest_Type": rw['Guest_Type'],
#                 "Booking_Status" : rw['Booking_Status'],
#                 "Arrival_Date" : rw['Arrival_Date'],
#                 "Departure_Date" : rw['Departure_Date'],
#                 "Street" : rw['Street'],
#                 "Street2" : rw['Street2'],
#                 "City": rw['City'],
#                 "State": rw['State'],
#                 "Country": rw['Country'],
#                 "Nationality": rw['Nationality'],
#                 "Zip_Code": rw['Zip_Code'],
#                 "Phone": rw['Phone'],
#                 "Mobile": rw['Mobile'],
#                 "Email": rw['Email'],
#                 "Salutation" : rw['Salutation'],
#                 "First_Name": rw['First_Name'],
#                 "Last_Name": rw['Last_Name'],
#                 "Gender": rw['Gender'],
#                 "Media_Source_Code": rw['Media_Source_Code'],
#                 "Market_Segment": rw['Market_Segment'],
#                 "Adult": str(rw['Adult']),
#                 "Children": str(rw['Children']),
#                 "Contact_type" : [rw['Contact_type']],
#                 "Email_Opt_In": boolConv(rw['Email_Opt_In']),
#                 "Email_Opt_Out": boolConv(rw['Email_Opt_Out']),
#                 "Do_Not_Mail": boolConv(rw['Email_Opt_Out']),
#                 "Email_status" : [rw['Email_status']]

In [22]:
path = r'C:\Users\fajar\Documents\Python\Data\normalize_checkout_debounce.csv'
df_check_out = pd.read_csv(path, encoding='utf8')

path = r'C:\Users\fajar\Documents\Python\Data\normalize_cancelled_debounce.csv'
df_cancelled = pd.read_csv(path, encoding='utf8')

path = r'C:\Users\fajar\Documents\Python\Data\normalize_viewpoint_debounce.csv'
df_viewpoint = pd.read_csv(path, encoding='utf8')

In [23]:
df_check_out.columns = df_check_out.columns.str.replace(' ', '')
df_cancelled.columns = df_cancelled.columns.str.replace(' ', '')
df_viewpoint.columns = df_viewpoint.columns.str.replace(' ', '')

In [24]:
# df_check_out.columns
# df_cancelled.columns
df_viewpoint.columns

Index(['BookRef', 'Email_Opt_In', 'Email_Opt_Out', 'Brand', 'Lead_Sub_Brand',
       'Lead_Source', 'Lead_Source_Description', 'Lead_Locations',
       'Guest_Type', 'Booking_Status', 'Arrival_Date', 'Departure_Date',
       'Street', 'Street2', 'City', 'State', 'Country', 'Nationality',
       'Zip_Code', 'Phone', 'Mobile', 'Email', 'Odyssey_Members', 'Salutation',
       'First_Name', 'Last_Name', 'Birthdate', 'Year_of_Birth', 'Contact_type',
       'Email_status', 'IDzoho', 'meta_id', 'zoho_check', 'debounce_check',
       'process_status', 'process_date', 'created'],
      dtype='object')

In [25]:
def con_fraction(phone):
    if phone == '':
        new_phone = ''
    else:
        new_phone = Fraction(phone)
    return new_phone

def con_str(phone):
    if phone == '':
        new_phone = ''
    else:
        new_phone = '+'+str(int(phone))
    return new_phone

def con_number(number):
    if number == '':
        new_number = ''
    else:
        new_number = int(number)
    return new_number

In [26]:
frames = [df_check_out, df_cancelled, df_viewpoint]
new_df = pd.concat(frames, ignore_index=True)

new_df.fillna('', inplace=True)

new_df['Destination'] = new_df['Lead_Locations']
new_df['Do_Not_Mail'] = new_df['Email_Opt_Out']


new_df['Phone'] = new_df.apply(
lambda x: con_str(x['Phone']),
    axis=1,
)

new_df['Mobile'] = new_df.apply(
    lambda x: con_str(x['Mobile']),
    axis=1,
)

# new_df['Phone'] = new_df.apply(
# lambda x: con_fraction(x['Phone']),
#     axis=1,
# )

# new_df['Mobile'] = new_df.apply(
#     lambda x: con_fraction(x['Mobile']),
#     axis=1,
# )

new_df['Adult'] = new_df.apply(
    lambda x: con_number(x['Adult']),
    axis=1,
)

new_df['Children'] = new_df.apply(
    lambda x: con_number(x['Children']),
    axis=1,
)

In [27]:
dob_con_date = pd.to_datetime(new_df['Birthdate'])
dob_date = dob_con_date.dt.strftime('%d/%m/%Y')

arr_con_date = pd.to_datetime(new_df['Arrival_Date'])
arr_date = arr_con_date.dt.strftime('%d/%m/%Y')

dep_con_date = pd.to_datetime(new_df['Departure_Date'])
dep_date = dep_con_date.dt.strftime('%d/%m/%Y')

new_df['Birthdate'] = dob_date
new_df['Arrival_Date'] = arr_date
new_df['Departure_Date'] = dep_date
new_df

,BookRef,Email_Opt_In,Email_Opt_Out,Brand,Lead_Sub_Brand,Lead_Source,Lead_Locations,Guest_Type,Booking_Status,Arrival_Date,...,IDzoho,meta_id,zoho_check,debounce_check,process_status,process_date,created,Lead_Source_Description,Destination,Do_Not_Mail
0,KK068307,True,False,Karma Resorts,Other,Past Guests,Karma Kandara,Checked-Out,CHECKED-OUT,18/01/2025,...,,185,False,False,Pendding,,2025-01-28 14:45:57,,Karma Kandara,False
1,KSH021937,True,False,Karma Resorts,Other,Past Guests,Karma Salford Hall,Checked-Out,CHECKED-OUT,18/01/2025,...,,185,False,False,Pendding,,2025-01-28 14:45:57,,Karma Salford Hall,False
2,KSH021937,False,True,Karma Resorts,Other,Past Guests,Karma Salford Hall,Checked-Out,CHECKED-OUT,18/01/2025,...,,185,False,False,Pendding,,2025-01-28 14:45:57,,Karma Salford Hall,True
3,KB044470,True,False,Karma Resorts,Other,Past Guests,Karma Bavaria,Checked-Out,CHECKED-OUT,17/01/2025,...,,185,False,False,Pendding,,2025-01-28 14:45:57,,Karma Bavaria,False
4,KK068295,True,False,Karma Resorts,Other,Past Guests,Karma Kandara,Checked-Out,CHECKED-OUT,18/01/2025,...,,185,False,False,Pendding,,2025-01-28 14:45:57,,Karma Kandara,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,2745795,True,False,Karma Resorts,Other,Past Guests,Karma Royal Haathi Mahal,Booking,Checked-Out,24/01/2025,...,,186,False,False,Pendding,,2025-01-28 14:44:47,Viewpoint,Karma Royal Haathi Mahal,False
536,2746549,True,False,Karma Resorts,Other,Past Guests,Karma Royal Haathi Mahal,Booking,Checked-Out,21/01/2025,...,,186,False,False,Pendding,,2025-01-28 14:44:47,Viewpoint,Karma Royal Haathi Mahal,False
537,2751987,True,False,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Booking,Checked-Out,26/01/2025,...,,186,False,False,Pendding,,2025-01-28 14:44:47,Viewpoint,Wyndham - Manoir des Deux Amants,False
538,2749956,True,False,Karma Resorts,Other,Past Guests,Wyndham - Manoir des Deux Amants,Booking,Checked-Out,26/01/2025,...,,186,False,False,Pendding,,2025-01-28 14:44:47,Viewpoint,Wyndham - Manoir des Deux Amants,False
539,2714284,True,False,Karma Resorts,Other,Past Guests,Karma Royal Palms,Booking,Checked-Out,23/01/2025,...,,186,False,False,Pendding,,2025-01-28 14:44:47,Viewpoint,Karma Royal Palms,False

In [28]:
list_GDPR = ['Russia', 'Germany', 'France', 'Italy', 'Spain','Ukraine','Poland','Romania','Netherlands','Belgium','Czechia','Greece','Portugal','Sweden','Hungary',
        'Belarus','Austria','Serbia','Switzerland','Bulgaria','Denmark','Finland','Slovakia','Norway','Ireland','Croatia','Moldova','Bosnia','Herzegovina','Albania','Lithuania',
        'North Macedonia','Slovenia','Latvia','Kosovo','Estonia','Montenegro','Luxembourg','Malta','Iceland','Andorra','Monaco','Liechtenstein','San Marino','Holy See',
        'Czech Republic','Israel','New Caledonia','Republic of Cyprus', 'England', 'United Kingdom', 'Wales', 'Scotland', 'Northern ireland']

In [29]:
new_df['GDPR Compliant'] =  False

# new_df.loc[new_df['Country'].isin(list_GDPR)]
new_df.loc[(new_df['Country'].isin(list_GDPR)) & (new_df['Email_Opt_In'] == True), 'GDPR Compliant'] = True
new_df[['Country', 'Email_Opt_In', 'GDPR Compliant']].loc[new_df['GDPR Compliant'] == True]

            Country  Email_Opt_In  GDPR Compliant
1    United Kingdom          True            True
3           Germany          True            True
5    United Kingdom          True            True
9           Germany          True            True
11          Germany          True            True
..              ...           ...             ...
525          France          True            True
528          France          True            True
532          France          True            True
537          France          True            True
538          France          True            True

[88 rows x 3 columns]

In [30]:
new_df.columns

Index(['BookRef', 'Email_Opt_In', 'Email_Opt_Out', 'Brand', 'Lead_Sub_Brand',
       'Lead_Source', 'Lead_Locations', 'Guest_Type', 'Booking_Status',
       'Arrival_Date', 'Departure_Date', 'Street', 'Street2', 'City', 'State',
       'Country', 'Nationality', 'Zip_Code', 'Phone', 'Mobile', 'Email',
       'Odyssey_Members', 'PrimaryGuestProfileRef', 'Salutation', 'First_Name',
       'Last_Name', 'Birthdate', 'Year_of_Birth', 'Gender',
       'Media_Source_Code', 'Market_Segment', 'Adult', 'Children', 'Infant',
       'Contact_type', 'Language', 'Email_status', 'IDzoho', 'meta_id',
       'zoho_check', 'debounce_check', 'process_status', 'process_date',
       'created', 'Lead_Source_Description', 'Destination', 'Do_Not_Mail',
       'GDPR Compliant'],
      dtype='object')

In [31]:
new_df.dtypes

BookRef                    object
Email_Opt_In                 bool
Email_Opt_Out                bool
Brand                      object
Lead_Sub_Brand             object
Lead_Source                object
Lead_Locations             object
Guest_Type                 object
Booking_Status             object
Arrival_Date               object
Departure_Date             object
Street                     object
Street2                    object
City                       object
State                      object
Country                    object
Nationality                object
Zip_Code                   object
Phone                      object
Mobile                     object
Email                      object
Odyssey_Members              bool
PrimaryGuestProfileRef     object
Salutation                 object
First_Name                 object
Last_Name                  object
Birthdate                  object
Year_of_Birth              object
Gender                     object
Media_Source_Code          object
Market_Segment             object
Adult                      object
Children                   object
Infant                     object
Contact_type               object
Language                   object
Email_status               object
IDzoho                     object
meta_id                     int64
zoho_check                   bool
debounce_check               bool
process_status             object
process_date               object
created                    object
Lead_Source_Description    object
Destination                object
Do_Not_Mail                  bool
GDPR Compliant               bool
dtype: object

In [32]:
new_push_cols = ['BookRef', 'PrimaryGuestProfileRef', 'Destination', 'Lead_Locations', 'Language', 'Brand','Lead_Sub_Brand',
              'Lead_Source', 'Lead_Source_Description', 'Guest_Type', 'Booking_Status', 
              'Arrival_Date', 'Departure_Date', 'Street', 'Street2', 
              'City', 'State', 'Country', 'Nationality', 'Zip_Code', 'Phone', 'Mobile', 'Email',
              'Salutation', 'First_Name', 'Last_Name', 'Gender', 'Media_Source_Code', 'Market_Segment',
              'Adult', 'Children', 'Contact_type', 'Email_Opt_In', 'Email_Opt_Out', 'Do_Not_Mail', 'GDPR Compliant', 'Email_status']

In [33]:
new_df.drop(new_df.columns.difference(new_push_cols), axis='columns', inplace=True)
new_df = new_df.reindex(columns=new_push_cols)
new_df.columns

Index(['BookRef', 'PrimaryGuestProfileRef', 'Destination', 'Lead_Locations',
       'Language', 'Brand', 'Lead_Sub_Brand', 'Lead_Source',
       'Lead_Source_Description', 'Guest_Type', 'Booking_Status',
       'Arrival_Date', 'Departure_Date', 'Street', 'Street2', 'City', 'State',
       'Country', 'Nationality', 'Zip_Code', 'Phone', 'Mobile', 'Email',
       'Salutation', 'First_Name', 'Last_Name', 'Gender', 'Media_Source_Code',
       'Market_Segment', 'Adult', 'Children', 'Contact_type', 'Email_Opt_In',
       'Email_Opt_Out', 'Do_Not_Mail', 'GDPR Compliant', 'Email_status'],
      dtype='object')

In [34]:
# test_df = new_df.loc[new_df['Email'].str.contains('bea.fliedner@google.com')]
# test_df.to_csv(r'C:\Users\fajar\Documents\Python\Data\compile_data_pastguest_test.csv', encoding='utf-8', index=False)

In [35]:
# new_df.to_csv(r'C:\Users\fajar\Documents\Python\Data\compile_data_pastguest.csv', encoding='utf-8', index=False)

new_df.to_excel(r'C:\Users\fajar\Documents\Python\Data\compile_data_pastguest.xlsx', index=False)