In [1]:

import sys

sys.path.append('../../')

import main_module as m
import bounce_clean_module as bc
import pandas as pd
import re
import numpy as np
from datetime import date
from datetime import datetime
from datetime import datetime, timedelta

%load_ext autoreload
%autoreload 2

dir_path = r'C:\Users\fajar\Documents\Python\Data\Zoho_Backup'
file_name = '\Leads_'

In [4]:
path = r'C:\Users\fajar\Documents\Python\Data\Debounce\mailwizz debounce log - vps\Email Debounce Mailwizz Master.xlsx'
zoho_df = pd.read_excel(path, dtype='string', sheet_name='mw_bounce_log')

zoho_df.reset_index(drop=True, inplace=True)
count_filter_awal = zoho_df.shape[0]

# mengisi kolom <NA> dengan value string 'empty' supaya mudah mengecek data member dan booking dengan isin
zoho_df.fillna('empty', inplace=True)
zoho_df

,log_id,email,message,bounce_type,name,date_added
0,5,kematrgn@yahoo.com,"smtp; 554 30 Sorry, your message to kematrgn@...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:12
1,8,rwant_kidz@yahoo.co.id,"smtp; 554 30 Sorry, your message to rwant_kid...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:12
2,14,suciptopo@yahoo.com,"smtp; 554 30 Sorry, your message to suciptopo...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:13
3,18,handy_j@yahoo.com,"smtp; 554 30 Sorry, your message to handy_j@y...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:13
4,24,mus123@yahoo.com,"smtp; 554 30 Sorry, your message to mus123@ya...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:13
...,...,...,...,...,...,...
39899,41735,shanju.t@lapoate.net,X-Postfix; connect to lapoate.net[199.59.243....,internal,3 | KCE | W1Jan24 | Karma Community | Vol. 206...,2024-01-03 02:10:08
39900,41736,proctor@proconbuilding.com,X-Postfix; connect to proconbuilding.com[13.2...,internal,3 | KCE | W1Jan24 | Karma Community | Vol. 206...,2024-01-03 02:10:08
39901,41737,tekguan03@yahpp.com,X-Postfix; connect to yahpp.com[47.254.33.193...,internal,3 | KCE | W1Jan24 | Karma Community | Vol. 206...,2024-01-03 02:20:08
39902,41738,hemant.boricha@sbi.co.in,smtp;550 5.7.1 TRANSPORT.RULES.RejectMessage;...,internal,2 | KCE | W1Jan24 | Karma Community | Vol. 206...,2024-01-03 03:10:08
39903,41739,dham_28@icloud.com,smtp; 554 5.7.1 [CS01] Message rejected due t...,internal,2 | KCE | W1Jan24 | Karma Community | Vol. 206...,2024-01-03 03:50:09

In [5]:
path = r'C:\Users\fajar\Documents\Python\Data\Debounce\mailwizz debounce log - vps\Email Debounce Mailwizz Master.xlsx'
df_email = pd.read_excel(path, dtype='string', sheet_name='Delete Email Master')
df_email

Empty DataFrame
Columns: [Email]
Index: []

In [6]:
# data phone, mobile dam email member yang ada di master data (wash member)
zoho_df['email'] = m.lowercase(zoho_df, 'email')
m.clean_space(zoho_df, 'email')

df_email['Email'] = m.lowercase(df_email, 'Email')
m.clean_space(df_email, 'Email')

Series([], Name: Email, dtype: string)

In [7]:
zoho_df["Delete"] = zoho_df.apply(
    lambda x: bc.get_desc(x['message']) ,
      
    axis=1,
)

delete_df = zoho_df.loc[
    zoho_df['Delete']=='Yes'
].copy()

count_delete = delete_df.shape[0]
delete_df

,log_id,email,message,bounce_type,name,date_added,Delete
0,5,kematrgn@yahoo.com,"smtp; 554 30 Sorry, your message to kematrgn@...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:12,Yes
1,8,rwant_kidz@yahoo.co.id,"smtp; 554 30 Sorry, your message to rwant_kid...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:12,Yes
2,14,suciptopo@yahoo.com,"smtp; 554 30 Sorry, your message to suciptopo...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:13,Yes
3,18,handy_j@yahoo.com,"smtp; 554 30 Sorry, your message to handy_j@y...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:13,Yes
4,24,mus123@yahoo.com,"smtp; 554 30 Sorry, your message to mus123@ya...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:13,Yes
...,...,...,...,...,...,...,...
39709,41545,maher.benmohamed@esprit.tn,smtp; 550 5.4.1 Recipient address rejected: A...,internal,2 | KCE | W1Jan24 | Karma Community | Vol. 206...,2024-01-02 19:10:13,Yes
39761,41597,andrew@veritywealth.com,smtp; 550 5.4.1 Recipient address rejected: A...,internal,3 | KCE | W1Jan24 | Karma Community | Vol. 206...,2024-01-02 20:40:23,Yes
39814,41650,johnb@firstgrade.com.au,smtp; 550 5.4.1 Recipient address rejected: A...,internal,3 | KCE | W1Jan24 | Karma Community | Vol. 206...,2024-01-02 21:10:18,Yes
39844,41680,heello@teganandjosh.com,smtp; 550 5.4.1 Recipient address rejected: A...,internal,3 | KCE | W1Jan24 | Karma Community | Vol. 206...,2024-01-02 21:20:16,Yes
39874,41710,naesm@yahoo.com,"smtp; 554 30 Sorry, your message to naesm@yah...",soft,3 | KCE | W1Jan24 | Karma Community | Vol. 206...,2024-01-02 21:40:12,Yes

In [8]:
count_dedup_master_delete_email = delete_df.loc[
    delete_df['email'].isin(df_email['Email'])
].shape[0]

delete_df.loc[
    delete_df['email'].isin(df_email['Email'])
]

Empty DataFrame
Columns: [log_id, email, message, bounce_type, name, date_added, Delete]
Index: []

In [9]:
delete_df.drop(delete_df.loc[
    
    delete_df['email'].isin(df_email['Email'])
].index, inplace=True)

delete_df.reset_index(drop=True, inplace=True)

count_after_dedup_master_delete_email = delete_df.shape[0]

delete_df

,log_id,email,message,bounce_type,name,date_added,Delete
0,5,kematrgn@yahoo.com,"smtp; 554 30 Sorry, your message to kematrgn@...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:12,Yes
1,8,rwant_kidz@yahoo.co.id,"smtp; 554 30 Sorry, your message to rwant_kid...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:12,Yes
2,14,suciptopo@yahoo.com,"smtp; 554 30 Sorry, your message to suciptopo...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:13,Yes
3,18,handy_j@yahoo.com,"smtp; 554 30 Sorry, your message to handy_j@y...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:13,Yes
4,24,mus123@yahoo.com,"smtp; 554 30 Sorry, your message to mus123@ya...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:13,Yes
...,...,...,...,...,...,...,...
1825,41545,maher.benmohamed@esprit.tn,smtp; 550 5.4.1 Recipient address rejected: A...,internal,2 | KCE | W1Jan24 | Karma Community | Vol. 206...,2024-01-02 19:10:13,Yes
1826,41597,andrew@veritywealth.com,smtp; 550 5.4.1 Recipient address rejected: A...,internal,3 | KCE | W1Jan24 | Karma Community | Vol. 206...,2024-01-02 20:40:23,Yes
1827,41650,johnb@firstgrade.com.au,smtp; 550 5.4.1 Recipient address rejected: A...,internal,3 | KCE | W1Jan24 | Karma Community | Vol. 206...,2024-01-02 21:10:18,Yes
1828,41680,heello@teganandjosh.com,smtp; 550 5.4.1 Recipient address rejected: A...,internal,3 | KCE | W1Jan24 | Karma Community | Vol. 206...,2024-01-02 21:20:16,Yes
1829,41710,naesm@yahoo.com,"smtp; 554 30 Sorry, your message to naesm@yah...",soft,3 | KCE | W1Jan24 | Karma Community | Vol. 206...,2024-01-02 21:40:12,Yes

In [10]:
print("==========================================================")
print("Summary Report")
print("==========================================================")
print("Jumlah Data Awal Yang Akan di Delete : "+str(count_delete))
print("Jumlah Wash Dengan Master Delete Email : "+str(count_dedup_master_delete_email))
print("Jumlah Setelah Wash Master Delete Email : "+str(count_after_dedup_master_delete_email))
print("Jumlah Data Akhir : "+str(count_after_dedup_master_delete_email))

==========================================================
Summary Report
==========================================================
Jumlah Data Awal Yang Akan di Delete : 1830
Jumlah Wash Dengan Master Delete Email : 0
Jumlah Setelah Wash Master Delete Email : 1830
Jumlah Data Akhir : 1830

In [11]:
# hitung jumlah duplicate

unique_email = delete_df.drop_duplicates(subset=['email']).copy()
unique_email

,log_id,email,message,bounce_type,name,date_added,Delete
0,5,kematrgn@yahoo.com,"smtp; 554 30 Sorry, your message to kematrgn@...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:12,Yes
1,8,rwant_kidz@yahoo.co.id,"smtp; 554 30 Sorry, your message to rwant_kid...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:12,Yes
2,14,suciptopo@yahoo.com,"smtp; 554 30 Sorry, your message to suciptopo...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:13,Yes
3,18,handy_j@yahoo.com,"smtp; 554 30 Sorry, your message to handy_j@y...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:13,Yes
4,24,mus123@yahoo.com,"smtp; 554 30 Sorry, your message to mus123@ya...",soft,KCW | W2Aug22 | Welcoming a new members,2022-08-12 10:10:13,Yes
...,...,...,...,...,...,...,...
1817,41260,drscnegi@yahoo.com,"smtp; 552 1 Requested mail action aborted, ma...",hard,KCE Coldline India,2024-01-01 23:40:06,Yes
1818,41262,gangolianand@yahoo.com,"smtp; 552 1 Requested mail action aborted, ma...",hard,KCE Coldline India,2024-01-02 00:00:04,Yes
1819,41273,prince_30000@yahoo.in,"smtp; 552 1 Requested mail action aborted, ma...",hard,KCE Coldline India,2024-01-02 01:10:04,Yes
1820,41279,gulcin_bg@hotmail.com,smtp; 550 5.5.0 Requested action not taken: m...,hard,KCE Coldline Bali,2024-01-02 02:10:03,Yes
1821,41281,naesm@yahoo.com,"smtp; 554 30 Sorry, your message to naesm@yah...",soft,KCE Coldline Bali,2024-01-02 02:20:06,Yes

In [12]:
today = datetime.now() 
date = today.strftime("%d-%m-%Y")
path = r'C:\Users\fajar\Documents\Python\Data\Debounce\mailwizz debounce log - vps\All Debounce\2024\Jan\03 Jan\data_ready_to_delete_'+str(date)+'.xlsx'

count_check_delete = delete_df.groupby(['message'])['log_id'].count().reset_index(name='Count Email').sort_values('message', ascending=True).copy()
count_check_delete.to_excel(path, sheet_name='Message Summary', index=False)

In [13]:
# jika ingin menambahkan sheets baru
with pd.ExcelWriter(path, mode="a", engine="openpyxl") as writer:
    delete_df.to_excel(writer, sheet_name="Delete Data Detail", index=False)
    unique_email['email'].to_excel(writer, sheet_name="Unique Email", index=False)