In [1]:
import sys
sys.path.append('../')

import main_module as m
import gdpr_filter_module as fil
import pandas as pd
import re
import numpy as np

%load_ext autoreload
%autoreload 2

dir_path = r'C:\Users\fajar\Documents\Python\Data\Zoho_Backup'
file_name = '\Leads_'

cols = ['Record Id',	
'Created Time',
'Created Date',	
'First Name',	
'Last Name',	
'Email',	
'Phone',	
'Mobile',	
'Birthdate',	
'Year of Birth',
'Street',	
'Street2',	
'City',	
'State',	
'Country',	
'Nationality',
'Booking Status', 
'BookRef',
'Departure Date',	
'Arrival Date',	
'Card Type',	
'Marital Status',	
'Lead Brand',	
'Lead Sub-Brand',	
'Lead Source',	
'Lead Locations',	
'Lead Source Description',	
'Lead Regions',
'Lead Status',
'Email Opt Out',	
'Opt In',
'Do Not Contact',
'Do Not Mail',
'EU Territory']

In [2]:
df = m.load_data_multiple(dir_path, file_name, cols)
count_data_awal = df.shape[0]
df = df.reindex(columns=cols)
df.shape[0]

df['Created Time'] = pd.to_datetime(df['Created Time'], format='%Y-%m-%d %H:%M:%S')
# fungsi errors cource untuk menhindari error jika value data date null atau kosong
# df['Birthdate'] = pd.to_datetime(df['Birthdate'], format='%Y-%m-%d', errors='coerce')
df.dtypes
df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Do Not Contact,Do Not Mail,EU Territory
0,zcrm_3584690000000404058,2019-01-07 15:08:38,2019-01-06,Nicholas,Wood,1230woodnicholas@gmail.com,+61438600845,<NA>,<NA>,<NA>,...,Wifi,<NA>,Purple Wifi,SEAP,New Lead,false,false,true,false,false
1,zcrm_3584690000000404059,2019-01-07 15:08:38,2019-01-06,Liao,Yuan,158066546@qq.com,8618718399923,<NA>,<NA>,<NA>,...,Wifi,<NA>,Purple Wifi,Other,New Lead,false,false,true,false,false
2,zcrm_3584690000000404060,2019-01-07 15:08:38,2019-01-06,Vedanta,Abhiyoga,abhiyoga.vedanta@gmail.com,+6282146524550,<NA>,2000-07-05,2000,...,Wifi,<NA>,Purple Wifi,SEAP,New Lead,false,false,true,false,false
3,zcrm_3584690000000404065,2019-01-07 15:08:38,2019-01-06,Aidai,Atakanova,aidai.nurbek@gmail.com,996779641590,<NA>,1997-02-05,1997,...,Wifi,<NA>,Purple Wifi,UK/Europe,New Lead,false,false,true,false,true
4,zcrm_3584690000000404068,2019-01-07 15:08:38,2019-01-06,Ardra,Ardra,aliefardraqariru@gmail.com,+6282139300818,+6282139300818,2005-01-20,2005,...,Wifi,Mall 21,Purple Wifi,SEAP,New Lead,false,false,true,false,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4671280,zcrm_3584690000466570191,2023-10-23 16:40:38,<NA>,Preeti,Mungale,mungalepreeti@gmail.com,+918380023336,<NA>,<NA>,<NA>,...,Facebook Ads,<NA>,IND | FB AF | KRP,<NA>,<NA>,false,false,false,false,false
4671281,zcrm_3584690000466570226,2023-10-23 17:16:05,<NA>,James,Bradley,james-bradley90@hotmail.co.uk,447966175742,<NA>,<NA>,<NA>,...,Web Enquiry,<NA>,Form Contact Us,UK/Europe,<NA>,false,true,false,false,true
4671282,zcrm_3584690000466571001,2023-10-23 15:49:03,<NA>,Siipan,Ruzicka,stipan@aol.com,+61413213392,<NA>,1960-04-20,1960,...,Guest Exit,Sales Deck Jimbaran,Jimbaran | REGISTRATION CONFIRMED | Your Exclu...,SEAP,Hot Prospect,false,true,false,false,false
4671283,zcrm_3584690000466571041,2023-10-23 17:33:06,<NA>,Ron,Hovestad,coyoletremec@gmail.com,+12507416680,<NA>,1961-02-23,1961,...,Guest Exit,Sales Deck Vietnam,Vietnam | REGISTRATION CONFIRMED | Your Exclus...,SEAP,Hot Prospect,false,true,false,false,false
4671284,zcrm_3584690000466573001,2023-10-23 17:00:57,<NA>,K,Buckle,noemailfield+383832@karmagroup.com,+447921292124,+447921292124,<NA>,<NA>,...,Web Enquiry,General,KE | Web | W3SEP23 | Restaurant Feedback Vietnam,<NA>,New Lead,false,false,false,false,false

In [3]:
zoho_filter = fil.eu_teritory(df)
zoho_df = df.loc[zoho_filter].copy() # menggunakan copy untuk menghindari setting copy warning
zoho_df.reset_index(drop=True, inplace=True)
count_filter_awal = zoho_df.shape[0]

# mengisi kolom <NA> dengan value string 'empty' supaya mudah mengecek data member dan booking dengan isin

zoho_df.fillna('empty', inplace=True)
zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Do Not Contact,Do Not Mail,EU Territory
0,zcrm_3584690000228671406,2020-09-05 23:10:36,empty,Allister,Reid,allister.reid@outlook.com,empty,empty,empty,empty,...,Member,empty,empty,empty,New Lead,false,false,false,false,false
1,zcrm_3584690000228672575,2020-09-05 23:10:48,empty,Andrew,Lytle,lytle@globalnet.co.uk,empty,empty,empty,empty,...,Member,empty,empty,empty,New Lead,false,false,false,false,false
2,zcrm_3584690000228681168,2020-09-05 23:12:10,empty,Stephen,Mcilroy,stevemackers@hotmail.com,empty,empty,empty,empty,...,Member,empty,empty,empty,New Lead,false,false,false,false,false
3,zcrm_3584690000228682822,2020-09-05 23:12:26,empty,Richard,Pryce,edy.rickypryce@hotmail.co.uk,empty,empty,empty,empty,...,Member,empty,empty,empty,New Lead,false,false,false,false,false
4,zcrm_3584690000228697324,2020-09-05 23:14:46,empty,Patrick,Tierney,pjtierney78@gmail.com,empty,empty,empty,empty,...,Member,empty,empty,empty,New Lead,false,false,false,false,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,zcrm_3584690000463504022,2023-10-02 14:32:45,empty,Florian,Franke,empty,491632896998,empty,empty,empty,...,Past Guests,Karma Bavaria,empty,empty,empty,true,false,false,true,false
1006,zcrm_3584690000463505001,2023-10-02 14:32:13,empty,Ganna,Kaplun,empty,380632761099,empty,empty,empty,...,Past Guests,Karma Bavaria,empty,empty,empty,true,false,false,true,false
1007,zcrm_3584690000463511029,2023-10-02 14:45:57,empty,Stéphanie,Dessi,empty,33672029061,empty,empty,empty,...,Past Guests,Karma Lake of Menteith,Viewpoint,empty,empty,false,true,false,false,false
1008,zcrm_3584690000463563001,2023-10-02 16:06:33,empty,Steve,Lubin,sara-l_arhab@outlook.fr,+33782726763,empty,1996-11-23,1996,...,Guest Exit,Sales Deck Jimbaran,REGISTRATION CONFIRMED | Your Exclusive 7 NIGH...,SEAP,Not Qualified,false,true,false,false,false
1009,zcrm_3584690000463567041,2023-10-02 16:32:34,empty,Christopher,Lynch,christopher.lynch2018@gmail.com,+353858360054,empty,1992-04-21,1992,...,Guest Exit,Sales Deck Jimbaran,REGISTRATION CONFIRMED | Your Exclusive 7 NIGH...,SEAP,Hot Prospect,false,true,false,false,false

In [4]:
zoho_df.groupby('Country').count()

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Do Not Contact,Do Not Mail,EU Territory
Country,,,,,,,,,,,,,,,,,,,,,
AUSTRIA,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Albania,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
Andorra,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Austria,32,32,32,32,32,32,32,32,32,32,...,32,32,32,32,32,32,32,32,32,32
BELGIUM,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Belgium,16,16,16,16,16,16,16,16,16,16,...,16,16,16,16,16,16,16,16,16,16
CROATIA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
CZECH REPUBLIC,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Croatia,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
DENMARK,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
Denmark,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
FRANCE,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
France,118,118,118,118,118,118,118,118,118,118,...,118,118,118,118,118,118,118,118,118,118
Germany,379,379,379,379,379,379,379,379,379,379,...,379,379,379,379,379,379,379,379,379,379
Greece,9,9,9,9,9,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
Hungary,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
IRELAND,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
ITALY,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Ireland,13,13,13,13,13,13,13,13,13,13,...,13,13,13,13,13,13,13,13,13,13
Israel,13,13,13,13,13,13,13,13,13,13,...,13,13,13,13,13,13,13,13,13,13
Italy,85,85,85,85,85,85,85,85,85,85,...,85,85,85,85,85,85,85,85,85,85
LUXEMBOURG,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Latvia,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Lithuania,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Luxembourg,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
MALTA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Malta,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
NETHERLANDS,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
NORWAY,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Netherlands,48,48,48,48,48,48,48,48,48,48,...,48,48,48,48,48,48,48,48,48,48
North Ireland,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
North Macedonia,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Northern Ireland,15,15,15,15,15,15,15,15,15,15,...,15,15,15,15,15,15,15,15,15,15
Norway,8,8,8,8,8,8,8,8,8,8,...,8,8,8,8,8,8,8,8,8,8
POLAND,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
PORTUGAL,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Poland,16,16,16,16,16,16,16,16,16,16,...,16,16,16,16,16,16,16,16,16,16
Portugal,24,24,24,24,24,24,24,24,24,24,...,24,24,24,24,24,24,24,24,24,24
ROMANIA,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
Romania,21,21,21,21,21,21,21,21,21,21,...,21,21,21,21,21,21,21,21,21,21
Russia,46,46,46,46,46,46,46,46,46,46,...,46,46,46,46,46,46,46,46,46,46
Russian Federation,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
SPAIN,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
SWEDEN,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
SWITZERLAND,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Serbia,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Slovakia,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Slovenia,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Spain,39,39,39,39,39,39,39,39,39,39,...,39,39,39,39,39,39,39,39,39,39
Sweden,11,11,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
Switzerland,24,24,24,24,24,24,24,24,24,24,...,24,24,24,24,24,24,24,24,24,24
Ukraine,11,11,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
spain,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [5]:
zoho_df.groupby('EU Territory').count()

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Do Not Contact,Do Not Mail
EU Territory,,,,,,,,,,,,,,,,,,,,,
false,1010,1010,1010,1010,1010,1010,1010,1010,1010,1010,...,1010,1010,1010,1010,1010,1010,1010,1010,1010,1010

In [7]:
zoho_df.replace('empty', '', inplace=True)
zoho_df.to_excel(r'C:\Users\fajar\Documents\Python\Data\update_eu_checkbox.xlsx', index=False)