In [1]:
import sys

import clean_data_modul as fil

sys.path.append('../')

import main_module as m
import pandas as pd
import re
import numpy as np

from datetime import date
from datetime import datetime
from datetime import datetime, timedelta

%load_ext autoreload
%autoreload 2

dir_path = r'C:\Users\fajar\Documents\Python\Data\Zoho_Backup'
file_name = '\Leads_'

cols = ['Record Id',	
'Created Time',
'Created Date',	
'First Name',	
'Last Name',	
'Email',	
'Phone',	
'Mobile',	
'Birthdate',	
'Year of Birth',
'Street',	
'Street2',	
'City',	
'State',	
'Country',	
'Nationality',
'Booking Status', 
'BookRef',
'Departure Date',	
'Arrival Date',	
'Card Type',	
'Marital Status',	
'Lead Brand',	
'Lead Sub-Brand',	
'Lead Source',	
'Lead Locations',	
'Lead Location Description',	
'Lead Source Description',	
'Lead Regions',
'Lead Status',
'Email Opt Out',	
'Opt In',
'Do Not Contact',
'Do Not Mail']

In [2]:
zoho_df = m.load_data_multiple(dir_path, file_name, cols)
count_data_awal = zoho_df.shape[0]
zoho_df = zoho_df.reindex(columns=cols)
zoho_df.shape[0]

zoho_df['Created Time'] = pd.to_datetime(zoho_df['Created Time'], format='%Y-%m-%d %H:%M:%S')
# fungsi errors cource untuk menhindari error jika value data date null atau kosong
# df['Birthdate'] = pd.to_datetime(df['Birthdate'], format='%Y-%m-%d', errors='coerce')

zoho_df.fillna('empty', inplace=True)
zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source,Lead Locations,Lead Location Description,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Do Not Contact,Do Not Mail
0,zcrm_3584690000000404058,2019-01-07 15:08:38,2019-01-06,Nicholas,Wood,1230woodnicholas@gmail.com,+61438600845,empty,empty,empty,...,Wifi,empty,empty,Purple Wifi,SEAP,New Lead,false,false,true,false
1,zcrm_3584690000000404059,2019-01-07 15:08:38,2019-01-06,Liao,Yuan,158066546@qq.com,8618718399923,empty,empty,empty,...,Wifi,empty,empty,Purple Wifi,Other,New Lead,false,false,true,false
2,zcrm_3584690000000404060,2019-01-07 15:08:38,2019-01-06,Vedanta,Abhiyoga,abhiyoga.vedanta@gmail.com,+6282146524550,empty,2000-07-05,2000,...,Wifi,empty,empty,Purple Wifi,SEAP,New Lead,false,false,true,false
3,zcrm_3584690000000404065,2019-01-07 15:08:38,2019-01-06,Aidai,Atakanova,aidai.nurbek@gmail.com,996779641590,empty,1997-02-05,1997,...,Wifi,empty,empty,Purple Wifi,UK/Europe,New Lead,false,false,true,false
4,zcrm_3584690000000404068,2019-01-07 15:08:38,2019-01-06,Ardra,Ardra,aliefardraqariru@gmail.com,+6282139300818,+6282139300818,2005-01-20,2005,...,Wifi,Mall 21,empty,Purple Wifi,SEAP,New Lead,false,false,true,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4717718,zcrm_3584690000475135007,2024-01-01 18:16:02,empty,Upendra,Mishra,upendra.sir@gmail.com,+919036084550,empty,empty,empty,...,Web Enquiry,Karma Sunshine Village,empty,Timeshare Booking Request,India,empty,false,true,false,false
4717719,zcrm_3584690000475135045,2024-01-01 18:16:37,empty,Mehul,Prajapati,mehul.m111985@gmail.com,+919714713689,empty,empty,empty,...,Facebook Ads,General,empty,IND | FB MF | Lead captured,empty,empty,false,false,false,false
4717720,zcrm_3584690000475136005,2024-01-01 18:17:13,empty,swati,agarwala,cswatiadv@gmail.com,+919733055636,empty,empty,empty,...,Facebook Ads,Karma Martam,empty,IND | FB MF | Martam,empty,empty,false,false,false,false
4717721,zcrm_3584690000475138034,2024-01-01 18:48:36,empty,SUMON,SAHOO,sumonsahoo@gmail.com,+918910484814,empty,empty,empty,...,Facebook Ads,Karma Martam,empty,IND | FB MF | Martam,empty,empty,false,false,false,false
4717722,zcrm_3584690000475138069,2024-01-01 18:52:24,empty,Rohit,Kadam,rohit0918.rk@gmail.com,+919819185446,empty,empty,empty,...,Facebook Ads,Royal Palms,empty,IND | FB AF | KRP,empty,empty,false,false,false,false

In [3]:
path = r'C:\Users\fajar\Documents\Python\Data\Debounce\mailwizz debounce log - vps\Email Debounce Mailwizz Master.xlsx'
df_email = pd.read_excel(path, dtype='string', sheet_name='Delete Email Master')
df_email

                       Email           Unnamed: 1
0         kematrgn@yahoo.com                 <NA>
1     rwant_kidz@yahoo.co.id                 <NA>
2        suciptopo@yahoo.com                 <NA>
3          handy_j@yahoo.com                 <NA>
4           mus123@yahoo.com                 <NA>
...                      ...                  ...
1450      drscnegi@yahoo.com                 <NA>
1451  gangolianand@yahoo.com                 <NA>
1452   prince_30000@yahoo.in                 <NA>
1453   gulcin_bg@hotmail.com                 <NA>
1454         naesm@yahoo.com  2024-01-03 00:00:00

[1455 rows x 2 columns]

In [4]:
df_email

                       Email           Unnamed: 1
0         kematrgn@yahoo.com                 <NA>
1     rwant_kidz@yahoo.co.id                 <NA>
2        suciptopo@yahoo.com                 <NA>
3          handy_j@yahoo.com                 <NA>
4           mus123@yahoo.com                 <NA>
...                      ...                  ...
1450      drscnegi@yahoo.com                 <NA>
1451  gangolianand@yahoo.com                 <NA>
1452   prince_30000@yahoo.in                 <NA>
1453   gulcin_bg@hotmail.com                 <NA>
1454         naesm@yahoo.com  2024-01-03 00:00:00

[1455 rows x 2 columns]

In [5]:
# data phone, mobile dam email member yang ada di master data (wash member)
zoho_df['Email'] = m.lowercase(zoho_df, 'Email')
m.clean_space(zoho_df, 'Email')

df_email['Email'] = m.lowercase(df_email, 'Email')
m.clean_space(df_email, 'Email')

0           kematrgn@yahoo.com
1       rwant_kidz@yahoo.co.id
2          suciptopo@yahoo.com
3            handy_j@yahoo.com
4             mus123@yahoo.com
                 ...
1450        drscnegi@yahoo.com
1451    gangolianand@yahoo.com
1452     prince_30000@yahoo.in
1453     gulcin_bg@hotmail.com
1454           naesm@yahoo.com
Name: Email, Length: 1455, dtype: string

In [6]:
# data phone, mobile dam email member yang ada di master data 
count_deleted_email = zoho_df.loc[

    zoho_df['Email'].isin(df_email['Email'])

].shape[0]

# data phone, mobile dam email member yang ada di master data 
deleted_email = zoho_df.loc[

    zoho_df['Email'].isin(df_email['Email'])

].copy()

In [7]:
count_email_only = deleted_email.loc[(deleted_email['Email'] != 'empty') & ((deleted_email['Phone'] == 'empty') & (deleted_email['Mobile'] == 'empty'))].shape[0]
count_phone_only = deleted_email.loc[(deleted_email['Email'] == 'empty') & ((deleted_email['Phone'] != 'empty') | (deleted_email['Mobile'] != 'empty'))].shape[0]
count_email_and_phone = deleted_email.loc[(deleted_email['Email'] != 'empty') & ((deleted_email['Phone'] != 'empty') | (deleted_email['Mobile'] != 'empty'))].shape[0]

count_blank = deleted_email.loc[(deleted_email['Email'] =='empty') & (deleted_email['Phone']=='empty') & (deleted_email['Mobile']=='empty')].shape[0]

# deleted_email.loc[(deleted_email['Email'] =='empty') & (deleted_email['Phone']=='empty') & (deleted_email['Mobile']=='empty')].to_excel(r'C:\Users\fajar\Documents\Python\Data\blank_data.xlsx', index=False)

deleted_email.loc[(deleted_email['Email'] != 'empty') & ((deleted_email['Phone'] == 'empty') & (deleted_email['Mobile'] == 'empty')), 'Contact Type'] = 'Email Only'
deleted_email.loc[(deleted_email['Email'] == 'empty') & ((deleted_email['Phone'] != 'empty') | (deleted_email['Mobile'] != 'empty')), 'Contact Type'] = 'Phone Only'
deleted_email.loc[(deleted_email['Email'] != 'empty') & ((deleted_email['Phone'] != 'empty') | (deleted_email['Mobile'] != 'empty')), 'Contact Type'] = 'Email and Phone'

deleted_email.drop(deleted_email.loc[(deleted_email['Email'] =='empty') & (deleted_email['Phone']=='empty') & (deleted_email['Mobile']=='empty')].index, inplace=True)
deleted_email.reset_index(drop=True, inplace=True)

count_after_wash_blank = deleted_email.shape[0]

In [8]:
print("Jumlah Data Yang Akan di Delete : "+str(count_deleted_email))
print("Jumlah Phone Email Blank (Setelah phone yang tidak valid dihapus) : "+str(count_blank))
print("Jumlah Setelah Wash Phone Email Blank : "+str(count_after_wash_blank))
print("==========================================================")
print("Contact Type")
print("==========================================================")
print("Jumlah Email Only : "+str(count_email_only))
print("Jumlah Phone Only : "+str(count_phone_only))
print("Jumlah Email dan Phone : "+str(count_email_and_phone))

Jumlah Data Yang Akan di Delete : 730
Jumlah Phone Email Blank (Setelah phone yang tidak valid dihapus) : 0
Jumlah Setelah Wash Phone Email Blank : 730
==========================================================
Contact Type
==========================================================
Jumlah Email Only : 25
Jumlah Phone Only : 0
Jumlah Email dan Phone : 705

In [9]:
deleted_email.replace('empty', '', inplace=True)

In [10]:
deleted_email

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Locations,Lead Location Description,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Do Not Contact,Do Not Mail,Contact Type
0,zcrm_3584690000004846160,2019-03-21 16:39:59,2019-03-21,Craig,Deloney,karenpitts@adam.com.au,+61421562624,,1971-06-18,1971,...,Sales Deck Jimbaran,,,SEAP,,false,false,false,false,Email and Phone
1,zcrm_3584690000006849347,2019-04-02 04:42:40,2013-05-25,Paul,Magnusson,kapmango@adam.com.au,+61403848348,,,,...,,,KarmaRoyalGroup-Indonesia-EmailOnly,SEAP,,false,false,false,false,Email and Phone
2,zcrm_3584690000007454431,2019-04-02 05:59:24,2017-03-31,Yan,Wahyudin,suryanawahyudin@yahoo.com,+6282112182844,+620082112182844,1971-10-23,1971,...,,,BGID - Digital - FB1 - w2dec17 - Atanaya Hotel,SEAP,,false,false,false,false,Email and Phone
3,zcrm_3584690000007571732,2019-04-02 06:11:29,2018-07-31,Erwanto,Erwanto,rwant_kidz@yahoo.co.id,+6285101607082,,,,...,,,BGID - Digital - FB3 - w2jul18 - Harris Hotel ...,SEAP,,false,false,false,false,Email and Phone
4,zcrm_3584690000028291127,2019-04-30 20:29:04,2019-04-21,Sunilkumar a,Kamble,kamblesunilkumar@yahoo.com,+919449923593,,,,...,,,Gexit South Goa Apr 2019,India,New Lead,false,false,false,false,Email and Phone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,zcrm_3584690000474266001,2023-12-24 11:55:27,,Sohail,Khan,sohailkhan22@hotmail.com,+923343721258,,1992-05-06,1992,...,Sales Deck Jimbaran,,Jimbaran | REGISTRATION CONFIRMED | Your Exclu...,SEAP,Hot Prospect,false,true,false,false,Email and Phone
726,zcrm_3584690000474560001,2023-12-27 12:58:25,,Bill,Martin,ultimatebowling@bellsouth.nrt,+19178044808,,1946-08-25,1946,...,Sales Deck Jimbaran,,Jimbaran | REGISTRATION CONFIRMED | Your Exclu...,SEAP,Hot Prospect,false,true,false,false,Email and Phone
727,zcrm_3584690000474756042,2023-12-29 12:51:57,,Ruza,Kozaroska,branko53@0ptusnet.com.au,+61405003300,,1953-06-21,1953,...,Sales Deck Petitenget,,Petitenget | REGISTRATION CONFIRMED | Your Exc...,SEAP,Hot Prospect,false,true,false,false,Email and Phone
728,zcrm_3584690000474800033,2023-12-29 11:28:46,,Darren,Wade,cdkerb@gmail.com.au,+61448112472,,1965-12-05,1965,...,Sales Deck Jimbaran,,Jimbaran | REGISTRATION CONFIRMED | Your Exclu...,SEAP,Hot Prospect,false,true,false,false,Email and Phone
729,zcrm_3584690000475063171,2023-12-31 14:33:41,,John,Mavili,gulcin_bg@hotmail.com,+61423764206,,1969-01-26,1969,...,Sales Deck Jimbaran,,Jimbaran | REGISTRATION CONFIRMED | Your Exclu...,SEAP,Hot Prospect,false,true,false,false,Email and Phone

In [11]:
delete_record_crm = deleted_email.loc[deleted_email['Contact Type'] == 'Email Only'].copy()
update_record_crm = deleted_email.loc[deleted_email['Contact Type'] == 'Email and Phone'].copy()


delete_crm_cols = ['Record Id']
update_crm_cols = ['Record Id','Email']

delete_record_crm = delete_record_crm.reindex(columns=delete_crm_cols)
update_record_crm = update_record_crm.reindex(columns=update_crm_cols)

delete_record_crm['Test'] = True
update_record_crm['Email'] = ''

In [12]:
# delete_record_crm.to_excel(r'C:\Users\fajar\Documents\Python\Data\Debounce\mailwizz debounce log - vps\Clean\2024\Jan\02 Jan\delete_record_crm.xlsx', index=False)
# update_record_crm.to_excel(r'C:\Users\fajar\Documents\Python\Data\Debounce\mailwizz debounce log - vps\Clean\2024\Jan\02 Jan\update_record_crm.xlsx', index=False)
# deleted_email.to_excel(r'C:\Users\fajar\Documents\Python\Data\Debounce\mailwizz debounce log - vps\Clean\2024\Jan\02 Jan\clean_data_email.xlsx', index=False)

delete_record_crm.to_csv(r'C:\Users\fajar\Documents\Python\Data\Debounce\mailwizz debounce log - vps\Clean\2024\Jan\03 Jan\delete_record_crm.csv', index=False)
update_record_crm.to_csv(r'C:\Users\fajar\Documents\Python\Data\Debounce\mailwizz debounce log - vps\Clean\2024\Jan\03 Jan\update_record_crm.csv', index=False)
deleted_email.to_excel(r'C:\Users\fajar\Documents\Python\Data\Debounce\mailwizz debounce log - vps\Clean\2024\Jan\03 Jan\clean_data_email.xlsx', index=False)