In [13]:
import sys

import clean_data_modul as fil

sys.path.append('../')

import main_module as m
import pandas as pd
import re
import numpy as np

from datetime import date
from datetime import datetime
from datetime import datetime, timedelta

%load_ext autoreload
%autoreload 2

dir_path = r'C:\Users\fajar\Documents\Python\Data\Zoho_Backup'
file_name = '\Leads_'

cols = ['Record Id',	
'Created Time',
'Created Date',	
'First Name',	
'Last Name',	
'Email',	
'Phone',	
'Mobile',	
'Birthdate',	
'Year of Birth',
'Street',	
'Street2',	
'City',	
'State',	
'Country',	
'Nationality',
'Booking Status', 
'BookRef',
'Departure Date',	
'Arrival Date',	
'Card Type',	
'Marital Status',	
'Lead Brand',	
'Lead Sub-Brand',	
'Lead Source',	
'Lead Locations',	
'Lead Location Description',	
'Lead Source Description',	
'Lead Regions',
'Lead Status',
'Email Opt Out',	
'Opt In',
'Do Not Contact',
'Do Not Mail']

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [14]:
zoho_df = m.load_data_multiple(dir_path, file_name, cols)
count_data_awal = zoho_df.shape[0]
zoho_df = zoho_df.reindex(columns=cols)
zoho_df.shape[0]

zoho_df['Created Time'] = pd.to_datetime(zoho_df['Created Time'], format='%Y-%m-%d %H:%M:%S')
# fungsi errors cource untuk menhindari error jika value data date null atau kosong
# df['Birthdate'] = pd.to_datetime(df['Birthdate'], format='%Y-%m-%d', errors='coerce')

zoho_df.fillna('empty', inplace=True)
zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source,Lead Locations,Lead Location Description,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Do Not Contact,Do Not Mail
0,zcrm_3584690000000404058,2019-01-07 15:08:38,2019-01-06,Nicholas,Wood,1230woodnicholas@gmail.com,+61438600845,empty,empty,empty,...,Wifi,empty,empty,Purple Wifi,SEAP,New Lead,false,false,true,false
1,zcrm_3584690000000404059,2019-01-07 15:08:38,2019-01-06,Liao,Yuan,158066546@qq.com,8618718399923,empty,empty,empty,...,Wifi,empty,empty,Purple Wifi,Other,New Lead,false,false,true,false
2,zcrm_3584690000000404060,2019-01-07 15:08:38,2019-01-06,Vedanta,Abhiyoga,abhiyoga.vedanta@gmail.com,+6282146524550,empty,2000-07-05,2000,...,Wifi,empty,empty,Purple Wifi,SEAP,New Lead,false,false,true,false
3,zcrm_3584690000000404065,2019-01-07 15:08:38,2019-01-06,Aidai,Atakanova,aidai.nurbek@gmail.com,996779641590,empty,1997-02-05,1997,...,Wifi,empty,empty,Purple Wifi,UK/Europe,New Lead,false,false,true,false
4,zcrm_3584690000000404068,2019-01-07 15:08:38,2019-01-06,Ardra,Ardra,aliefardraqariru@gmail.com,+6282139300818,+6282139300818,2005-01-20,2005,...,Wifi,Mall 21,empty,Purple Wifi,SEAP,New Lead,false,false,true,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4717718,zcrm_3584690000475135007,2024-01-01 18:16:02,empty,Upendra,Mishra,upendra.sir@gmail.com,+919036084550,empty,empty,empty,...,Web Enquiry,Karma Sunshine Village,empty,Timeshare Booking Request,India,empty,false,true,false,false
4717719,zcrm_3584690000475135045,2024-01-01 18:16:37,empty,Mehul,Prajapati,mehul.m111985@gmail.com,+919714713689,empty,empty,empty,...,Facebook Ads,General,empty,IND | FB MF | Lead captured,empty,empty,false,false,false,false
4717720,zcrm_3584690000475136005,2024-01-01 18:17:13,empty,swati,agarwala,cswatiadv@gmail.com,+919733055636,empty,empty,empty,...,Facebook Ads,Karma Martam,empty,IND | FB MF | Martam,empty,empty,false,false,false,false
4717721,zcrm_3584690000475138034,2024-01-01 18:48:36,empty,SUMON,SAHOO,sumonsahoo@gmail.com,+918910484814,empty,empty,empty,...,Facebook Ads,Karma Martam,empty,IND | FB MF | Martam,empty,empty,false,false,false,false
4717722,zcrm_3584690000475138069,2024-01-01 18:52:24,empty,Rohit,Kadam,rohit0918.rk@gmail.com,+919819185446,empty,empty,empty,...,Facebook Ads,Royal Palms,empty,IND | FB AF | KRP,empty,empty,false,false,false,false

In [15]:
path = r'C:\Users\fajar\Documents\Python\Data\Debounce\mailwizz debounce log\Email Debounce Mailwizz Master.xlsx'
df_email = pd.read_excel(path, dtype='string', sheet_name='Delete Email Master')
df_email

                               Email           Unnamed: 1
0      strawberryandcheese@yahoo.com                 <NA>
1           reyn.agustinus@yahoo.com                 <NA>
2                   igun88@yahoo.com                 <NA>
3       zatria_christian@yahoo.co.id                 <NA>
4               yatch_dpon@yahoo.com                 <NA>
...                              ...                  ...
16999            timdun4@yahoo.co.uk                 <NA>
17000    hashleyboylan17@hotmail.com                 <NA>
17001   cristopher.evans@hotmail.com                 <NA>
17002    claire-musgrave@hotmail.com                 <NA>
17003       camilladuclos@hotmail.fr  2023-02-01 00:00:00

[17004 rows x 2 columns]

In [16]:
df_email

                               Email           Unnamed: 1
0      strawberryandcheese@yahoo.com                 <NA>
1           reyn.agustinus@yahoo.com                 <NA>
2                   igun88@yahoo.com                 <NA>
3       zatria_christian@yahoo.co.id                 <NA>
4               yatch_dpon@yahoo.com                 <NA>
...                              ...                  ...
16999            timdun4@yahoo.co.uk                 <NA>
17000    hashleyboylan17@hotmail.com                 <NA>
17001   cristopher.evans@hotmail.com                 <NA>
17002    claire-musgrave@hotmail.com                 <NA>
17003       camilladuclos@hotmail.fr  2023-02-01 00:00:00

[17004 rows x 2 columns]

In [17]:
# data phone, mobile dam email member yang ada di master data (wash member)
zoho_df['Email'] = m.lowercase(zoho_df, 'Email')
m.clean_space(zoho_df, 'Email')

df_email['Email'] = m.lowercase(df_email, 'Email')
m.clean_space(df_email, 'Email')

0        strawberryandcheese@yahoo.com
1             reyn.agustinus@yahoo.com
2                     igun88@yahoo.com
3         zatria_christian@yahoo.co.id
4                 yatch_dpon@yahoo.com
                     ...
16999              timdun4@yahoo.co.uk
17000      hashleyboylan17@hotmail.com
17001     cristopher.evans@hotmail.com
17002      claire-musgrave@hotmail.com
17003         camilladuclos@hotmail.fr
Name: Email, Length: 17004, dtype: string

In [18]:
# data phone, mobile dam email member yang ada di master data 
count_deleted_email = zoho_df.loc[

    zoho_df['Email'].isin(df_email['Email'])

].shape[0]

# data phone, mobile dam email member yang ada di master data 
deleted_email = zoho_df.loc[

    zoho_df['Email'].isin(df_email['Email'])

].copy()

In [19]:
count_email_only = deleted_email.loc[(deleted_email['Email'] != 'empty') & ((deleted_email['Phone'] == 'empty') & (deleted_email['Mobile'] == 'empty'))].shape[0]
count_phone_only = deleted_email.loc[(deleted_email['Email'] == 'empty') & ((deleted_email['Phone'] != 'empty') | (deleted_email['Mobile'] != 'empty'))].shape[0]
count_email_and_phone = deleted_email.loc[(deleted_email['Email'] != 'empty') & ((deleted_email['Phone'] != 'empty') | (deleted_email['Mobile'] != 'empty'))].shape[0]

count_blank = deleted_email.loc[(deleted_email['Email'] =='empty') & (deleted_email['Phone']=='empty') & (deleted_email['Mobile']=='empty')].shape[0]

# deleted_email.loc[(deleted_email['Email'] =='empty') & (deleted_email['Phone']=='empty') & (deleted_email['Mobile']=='empty')].to_excel(r'C:\Users\fajar\Documents\Python\Data\blank_data.xlsx', index=False)

deleted_email.loc[(deleted_email['Email'] != 'empty') & ((deleted_email['Phone'] == 'empty') & (deleted_email['Mobile'] == 'empty')), 'Contact Type'] = 'Email Only'
deleted_email.loc[(deleted_email['Email'] == 'empty') & ((deleted_email['Phone'] != 'empty') | (deleted_email['Mobile'] != 'empty')), 'Contact Type'] = 'Phone Only'
deleted_email.loc[(deleted_email['Email'] != 'empty') & ((deleted_email['Phone'] != 'empty') | (deleted_email['Mobile'] != 'empty')), 'Contact Type'] = 'Email and Phone'

deleted_email.drop(deleted_email.loc[(deleted_email['Email'] =='empty') & (deleted_email['Phone']=='empty') & (deleted_email['Mobile']=='empty')].index, inplace=True)
deleted_email.reset_index(drop=True, inplace=True)

count_after_wash_blank = deleted_email.shape[0]

In [20]:
print("Jumlah Data Yang Akan di Delete : "+str(count_deleted_email))
print("Jumlah Phone Email Blank (Setelah phone yang tidak valid dihapus) : "+str(count_blank))
print("Jumlah Setelah Wash Phone Email Blank : "+str(count_after_wash_blank))
print("==========================================================")
print("Contact Type")
print("==========================================================")
print("Jumlah Email Only : "+str(count_email_only))
print("Jumlah Phone Only : "+str(count_phone_only))
print("Jumlah Email dan Phone : "+str(count_email_and_phone))

Jumlah Data Yang Akan di Delete : 7562
Jumlah Phone Email Blank (Setelah phone yang tidak valid dihapus) : 0
Jumlah Setelah Wash Phone Email Blank : 7562
==========================================================
Contact Type
==========================================================
Jumlah Email Only : 1413
Jumlah Phone Only : 0
Jumlah Email dan Phone : 6149

In [21]:
deleted_email.replace('empty', '', inplace=True)

In [22]:
deleted_email

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Locations,Lead Location Description,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Do Not Contact,Do Not Mail,Contact Type
0,zcrm_3584690000000405145,2019-01-08 11:23:21,2019-01-05,Agi,Jaggy,a.perfectshape@yahoo.com,41791979126,,1970-10-13,1970,...,,,Purple Wifi,UK/Europe,New Lead,false,false,false,false,Email and Phone
1,zcrm_3584690000000456274,2019-01-09 11:10:49,,Alexander,Karlin,alenxander.karlin86@gmx.de,+49017664317294,,1986-10-04,1986,...,Karma Bavaria,,,UK/Europe,New Lead,false,true,false,false,Email and Phone
2,zcrm_3584690000000456494,2019-01-09 11:10:52,,Alfredo,Canavero,alfredo.canavero@uni.mi.it,390295343231,,1948-02-17,1948,...,Karma Bavaria,,,UK/Europe,New Lead,false,true,false,false,Email and Phone
3,zcrm_3584690000000456924,2019-01-09 11:10:54,,Austen Malcolm,Slattery,austenslattery@lrs.com,+442085295414,,,,...,Karma Manoir,,,UK/Europe,New Lead,false,false,false,false,Email and Phone
4,zcrm_3584690000000457023,2019-01-09 11:10:54,,Benjamin,Schnell,benny-schnell@yahoo.de,+491731747160,,1993-12-09,1993,...,Karma Bavaria,,,UK/Europe,New Lead,false,false,false,false,Email and Phone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7557,zcrm_3584690000472558202,2023-12-11 17:56:06,,Nik,S,pa@storonsky.com,447572914711,,,,...,Karma Beach,,Reservation di Mare Restaurant & Karma Beach ...,SEAP,New Lead,false,true,false,false,Email and Phone
7558,zcrm_3584690000472559419,2023-12-11 17:56:10,,Gggg,Vbnky,tuh@gng.fyu,62956558005,,,,...,Karma Beach,,Reservation di Mare Restaurant & Karma Beach ...,SEAP,New Lead,false,true,false,false,Email and Phone
7559,zcrm_3584690000472559918,2023-12-11 17:56:12,,Jyoti,Yadav,swt.jyotiyadav@gmail.con,918527930695,,,,...,Karma Beach,,Reservation di Mare Restaurant & Karma Beach ...,SEAP,New Lead,false,true,false,false,Email and Phone
7560,zcrm_3584690000473514918,2023-12-19 14:36:33,2022-02-06,Andyka,-,raden_andyka@yahoo.com,081314143696,,,,...,Karma Kandara,,,,New Lead,false,true,false,false,Email and Phone
7561,zcrm_3584690000474838065,2023-12-29 17:49:10,,vrm,ghu,123@yahoo.com,+917869012345,,,,...,Karma Golden Camp,,IND | FB MF | KGC,,,false,false,false,false,Email and Phone

In [23]:
delete_record_crm = deleted_email.loc[deleted_email['Contact Type'] == 'Email Only'].copy()
update_record_crm = deleted_email.loc[deleted_email['Contact Type'] == 'Email and Phone'].copy()


delete_crm_cols = ['Record Id']
update_crm_cols = ['Record Id','Email']

delete_record_crm = delete_record_crm.reindex(columns=delete_crm_cols)
update_record_crm = update_record_crm.reindex(columns=update_crm_cols)

delete_record_crm['Test'] = True
update_record_crm['Email'] = ''

In [24]:
# delete_record_crm.to_excel(r'C:\Users\fajar\Documents\Python\Data\Debounce\mailwizz debounce log\Clean\2024\Jan\02 Jan\delete_record_crm.xlsx', index=False)
# update_record_crm.to_excel(r'C:\Users\fajar\Documents\Python\Data\Debounce\mailwizz debounce log\Clean\2024\Jan\02 Jan\update_record_crm.xlsx', index=False)
# deleted_email.to_excel(r'C:\Users\fajar\Documents\Python\Data\Debounce\mailwizz debounce log\Clean\2024\Jan\02 Jan\clean_data_email.xlsx', index=False)

delete_record_crm.to_csv(r'C:\Users\fajar\Documents\Python\Data\Debounce\mailwizz debounce log\Clean\2024\Jan\02 Jan\delete_record_crm.csv', index=False)
update_record_crm.to_csv(r'C:\Users\fajar\Documents\Python\Data\Debounce\mailwizz debounce log\Clean\2024\Jan\02 Jan\update_record_crm.csv', index=False)
deleted_email.to_excel(r'C:\Users\fajar\Documents\Python\Data\Debounce\mailwizz debounce log\Clean\2024\Jan\02 Jan\clean_data_email.xlsx', index=False)