In [2]:
import sys
sys.path.append('../')

import main_module as m
import zoho_filter_module as fil
import pandas as pd
import re
import numpy as np

%load_ext autoreload
%autoreload 2

dir_path = r'C:\Users\fajar\Documents\Python\Data\Zoho_Backup'
file_name = '\Leads_'

cols = ['Record Id',	
'Created Time',
'Created Date',	
'First Name',	
'Last Name',	
'Email',	
'Phone',	
'Mobile',	
'Birthdate',	
'Year of Birth',
'Street',	
'Street2',	
'City',	
'State',	
'Country',	
'Nationality',
'Booking Status', 
'BookRef',
'Departure Date',	
'Arrival Date',	
'Card Type',	
'Marital Status',	
'Lead Brand',	
'Lead Sub-Brand',	
'Lead Source',	
'Lead Locations',	
'Lead Source Description',	
'Lead Regions',
'Lead Status',
'Email Opt Out',	
'Opt In',
'Do Not Contact',
'Do Not Mail']

In [4]:
df = m.load_data_multiple(dir_path, file_name, cols)
count_data_awal = df.shape[0]
df = df.reindex(columns=cols)
df.shape[0]

# df['Created Time'] = pd.to_datetime(df['Created Time'], format='%Y-%m-%d %H:%M:%S')
# fungsi errors cource untuk menhindari error jika value data date null atau kosong
# df['Birthdate'] = pd.to_datetime(df['Birthdate'], format='%Y-%m-%d', errors='coerce')
df.dtypes
df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Do Not Contact,Do Not Mail
0,zcrm_3584690000000404058,2019-01-07 15:08:38,2019-01-06,Nicholas,Wood,1230woodnicholas@gmail.com,+61438600845,<NA>,<NA>,<NA>,...,Other Bali DB,Wifi,<NA>,Purple Wifi,SEAP,New Lead,false,false,true,false
1,zcrm_3584690000000404059,2019-01-07 15:08:38,2019-01-06,Liao,Yuan,158066546@qq.com,8618718399923,<NA>,<NA>,<NA>,...,Other Bali DB,Wifi,<NA>,Purple Wifi,Other,New Lead,false,false,true,false
2,zcrm_3584690000000404060,2019-01-07 15:08:38,2019-01-06,Vedanta,Abhiyoga,abhiyoga.vedanta@gmail.com,+6282146524550,<NA>,2000-07-05,2000,...,Other Bali DB,Wifi,<NA>,Purple Wifi,SEAP,New Lead,false,false,true,false
3,zcrm_3584690000000404065,2019-01-07 15:08:38,2019-01-06,Aidai,Atakanova,aidai.nurbek@gmail.com,996779641590,<NA>,1997-02-05,1997,...,Other Bali DB,Wifi,<NA>,Purple Wifi,UK/Europe,New Lead,false,false,true,false
4,zcrm_3584690000000404068,2019-01-07 15:08:38,2019-01-06,Ardra,Ardra,aliefardraqariru@gmail.com,+6282139300818,+6282139300818,2005-01-20,2005,...,Other Bali DB,Wifi,Mall 21,Purple Wifi,SEAP,New Lead,false,false,true,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4652430,zcrm_3584690000461818028,2023-09-18 17:22:55,<NA>,Garry,Martin,garrymatin70@gmail.com,+610413105878,+610413105878,<NA>,<NA>,...,Karma Experience,Web Enquiry,General,KE | Web | Newsletter Footer,SEAP,Not Qualified,false,false,false,false
4652431,zcrm_3584690000461818081,2023-09-18 17:47:12,<NA>,Naveen,Krishnamurthy,naveen.alfa@gmail.com,+919742227105,<NA>,<NA>,<NA>,...,Karma Experience IN,Facebook Ads,<NA>,IND | FB AF | KRP,<NA>,<NA>,false,false,false,false
4652432,zcrm_3584690000461819032,2023-09-18 17:20:21,<NA>,Nirmala,John,nirmalajohn10@gmail.com,+919845290043,<NA>,<NA>,<NA>,...,Karma Experience IN,Facebook Ads,<NA>,IND | FB AF | KRP,<NA>,<NA>,false,false,false,false
4652433,zcrm_3584690000461819067,2023-09-18 17:31:37,<NA>,Arman,Bagwa,abacademybgm@gmail.com,+918722649244,<NA>,<NA>,<NA>,...,Other Bali DB,Wifi,Karma Beach Bali,Purple Wifi,India,New Lead,false,false,false,false
4652434,zcrm_3584690000461819102,2023-09-18 17:51:32,<NA>,Ajay,Sharma,Ajaysharmaihm@yahoo.co.in,+919990502000,<NA>,<NA>,<NA>,...,Karma Experience IN,Facebook Ads,<NA>,IND | FB MF | Sitabani,<NA>,<NA>,false,false,false,false

In [5]:
new_df = df.groupby(['Country'])['Record Id'].count().reset_index(name='Amount Count').copy()
new_df

            Country  Amount Count
0           ALGERIA             7
1         ARGENTINA             4
2           ARMENIA             1
3         AUSTRALIA            25
4           AUSTRIA             2
..              ...           ...
438  united kingdom            12
439     wales, u.k.             1
440   zackary bruce             3
441   Åland Islands             3
442          Россия             1

[443 rows x 2 columns]

In [6]:
new_df.to_excel(r'C:\Users\fajar\Documents\Python\Data\Zoho CRM\clean data\update\all data\country\country_list.xlsx', index=False)