In [47]:
import pandas as pd
import re
import openpyxl


import sys
sys.path.append('../')

import main_module as m

In [48]:
path = r'C:\Users\fajar\Documents\Python\Data\Zoho_Campaign\push data\check exist\karma-spa-zoho-campaign.csv'
df_campaign = pd.read_csv(path, dtype='string')

In [49]:
path = r'C:\Users\fajar\Documents\Python\Data\Zoho_Campaign\push data\check exist\karma-spa-zoho-crm.xlsx'
df_crm = pd.read_excel(path, dtype='string', engine='openpyxl', sheet_name='Sheet0')

C:\Users\fajar\AppData\Roaming\Python\Python310\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [50]:
df_crm.shape[0]

7527

In [38]:
df_campaign.columns

Index(['Contact Email', 'Opt_in', 'Confirmed Time',
       'Agreed to Privacy Policy and Terms', 'Opt-in type'],
      dtype='object')

In [39]:
df_campaign

,Contact Email,Opt_in,Confirmed Time,Agreed to Privacy Policy and Terms,Opt-in type
0,000helentmorrow000@gmail.com,false,<NA>,false,None
1,007shivshivu@gmail.com,false,<NA>,false,None
2,05simransingh@gmail.com,false,<NA>,false,None
3,09ambac@gmail.com,false,<NA>,false,None
4,09MARKTAYLOR@GOOGLEMAIL.COM,false,<NA>,false,None
...,...,...,...,...,...
13052,zuzarkanch@gmail.com,false,<NA>,false,None
13053,zvezdakhorola@gmail.com,false,<NA>,false,None
13054,zvezdakov@list.ru,false,<NA>,false,None
13055,zx123xz321hm3@hotmail.com,false,<NA>,false,None
13056,zxleong070827@hotmail.com,false,<NA>,false,None

In [51]:
df_crm.fillna('empty', inplace=True)
df_crm

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Booking Status,BookRef,Guest Type,External ID
0,zcrm_3584690000370851001,2022-05-27 18:31:00,2022-05-04 00:00:00,tesa,Evangeline,tesa.evin@gmail.com,+628119333628,empty,empty,empty,...,Karma Kandara,empty,empty,New Lead,false,false,empty,empty,empty,empty
1,zcrm_3584690000370751169,2022-05-27 14:26:00,2022-05-02 00:00:00,Ng Siu,lan,hariyandi.tio@gmail.com,+62216695374,empty,empty,empty,...,Karma Kandara,empty,empty,New Lead,false,false,empty,empty,empty,empty
2,zcrm_3584690000370734377,2022-05-27 14:58:00,2022-05-04 00:00:00,Aletha,Stania,theastania@gmail.com,+6282146466763,empty,empty,empty,...,Karma Kandara,empty,empty,New Lead,false,false,empty,empty,empty,empty
3,zcrm_3584690000370729366,2022-05-27 14:51:00,2022-05-03 00:00:00,Nabila,Hana,nabila.hanarita@yahoo.com,+6281218000613,empty,empty,empty,...,Karma Kandara,empty,empty,New Lead,false,false,empty,empty,empty,empty
4,zcrm_3584690000370729343,2022-05-27 14:28:00,2022-05-02 00:00:00,Jessica,thurber,thurber0210@gmail.com,+12629604425,empty,empty,empty,...,Karma Kandara,empty,empty,New Lead,false,false,empty,empty,empty,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7522,zcrm_3584690000002904071,2019-02-26 21:10:00,empty,Ebony,St Quintin,davidstq@hotmail.com,empty,empty,empty,empty,...,Karma Rottnest,Karma Rottnest Spa January 2019,Other,New Lead,false,false,empty,empty,empty,empty
7523,zcrm_3584690000002904070,2019-02-26 21:10:00,empty,Leonie,Plowman,leonieplowman@bigpond.com.au,empty,empty,empty,empty,...,Karma Rottnest,Karma Rottnest Spa January 2019,SEAP,New Lead,false,false,empty,empty,empty,empty
7524,zcrm_3584690000002904066,2019-02-26 21:10:00,empty,Wendy,Price,asrama@iinet.net.au,empty,empty,empty,empty,...,Karma Rottnest,Karma Rottnest Spa January 2019,SEAP,New Lead,false,false,empty,empty,empty,empty
7525,zcrm_3584690000002904065,2019-02-26 21:10:00,empty,Kylie,Williamson,kylie.binks@yahoo.com.au,empty,empty,empty,empty,...,Karma Rottnest,Karma Rottnest Spa January 2019,SEAP,New Lead,false,false,empty,empty,empty,empty
7526,zcrm_3584690000002904064,2019-02-26 21:10:00,empty,Sally,Glenn,geoff.sally@agmaster.com.au,empty,empty,empty,empty,...,Karma Rottnest,Karma Rottnest Spa January 2019,SEAP,New Lead,false,false,empty,empty,empty,empty

In [52]:
df_crm['Email'] = m.lowercase(df_crm, 'Email')
m.clean_space(df_crm, 'Email')

df_campaign['Contact Email'] = m.lowercase(df_campaign, 'Contact Email')
m.clean_space(df_campaign, 'Contact Email')

df_crm

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Booking Status,BookRef,Guest Type,External ID
0,zcrm_3584690000370851001,2022-05-27 18:31:00,2022-05-04 00:00:00,tesa,Evangeline,tesa.evin@gmail.com,+628119333628,empty,empty,empty,...,Karma Kandara,empty,empty,New Lead,false,false,empty,empty,empty,empty
1,zcrm_3584690000370751169,2022-05-27 14:26:00,2022-05-02 00:00:00,Ng Siu,lan,hariyandi.tio@gmail.com,+62216695374,empty,empty,empty,...,Karma Kandara,empty,empty,New Lead,false,false,empty,empty,empty,empty
2,zcrm_3584690000370734377,2022-05-27 14:58:00,2022-05-04 00:00:00,Aletha,Stania,theastania@gmail.com,+6282146466763,empty,empty,empty,...,Karma Kandara,empty,empty,New Lead,false,false,empty,empty,empty,empty
3,zcrm_3584690000370729366,2022-05-27 14:51:00,2022-05-03 00:00:00,Nabila,Hana,nabila.hanarita@yahoo.com,+6281218000613,empty,empty,empty,...,Karma Kandara,empty,empty,New Lead,false,false,empty,empty,empty,empty
4,zcrm_3584690000370729343,2022-05-27 14:28:00,2022-05-02 00:00:00,Jessica,thurber,thurber0210@gmail.com,+12629604425,empty,empty,empty,...,Karma Kandara,empty,empty,New Lead,false,false,empty,empty,empty,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7522,zcrm_3584690000002904071,2019-02-26 21:10:00,empty,Ebony,St Quintin,davidstq@hotmail.com,empty,empty,empty,empty,...,Karma Rottnest,Karma Rottnest Spa January 2019,Other,New Lead,false,false,empty,empty,empty,empty
7523,zcrm_3584690000002904070,2019-02-26 21:10:00,empty,Leonie,Plowman,leonieplowman@bigpond.com.au,empty,empty,empty,empty,...,Karma Rottnest,Karma Rottnest Spa January 2019,SEAP,New Lead,false,false,empty,empty,empty,empty
7524,zcrm_3584690000002904066,2019-02-26 21:10:00,empty,Wendy,Price,asrama@iinet.net.au,empty,empty,empty,empty,...,Karma Rottnest,Karma Rottnest Spa January 2019,SEAP,New Lead,false,false,empty,empty,empty,empty
7525,zcrm_3584690000002904065,2019-02-26 21:10:00,empty,Kylie,Williamson,kylie.binks@yahoo.com.au,empty,empty,empty,empty,...,Karma Rottnest,Karma Rottnest Spa January 2019,SEAP,New Lead,false,false,empty,empty,empty,empty
7526,zcrm_3584690000002904064,2019-02-26 21:10:00,empty,Sally,Glenn,geoff.sally@agmaster.com.au,empty,empty,empty,empty,...,Karma Rottnest,Karma Rottnest Spa January 2019,SEAP,New Lead,false,false,empty,empty,empty,empty

In [28]:
# df_crm.loc[df_crm['Email'].str.contains('Bhanuprasadmodi', flags=re.I, regex=True)]
# df_campaign.loc[df_campaign['Contact Email'].str.contains('Bhanuprasadmodi', flags=re.I, regex=True)]

,Contact Email,Opt_in,Confirmed Time,Agreed to Privacy Policy and Terms,Opt-in type
1499,bhanuprasadmodi@gmail.com,false,<NA>,false,None

In [56]:
push_df = df_crm.loc[~df_crm['Email'].isin(df_campaign['Contact Email'])].copy()
push_df.reset_index(drop=True, inplace=True)
push_df.replace('empty', '', inplace=True)
push_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Booking Status,BookRef,Guest Type,External ID
0,zcrm_3584690000370851001,2022-05-27 18:31:00,2022-05-04 00:00:00,tesa,Evangeline,tesa.evin@gmail.com,+628119333628,,,,...,Karma Kandara,,,New Lead,false,false,,,,
1,zcrm_3584690000370719235,2022-05-27 14:46:00,2022-05-03 00:00:00,Hendrik,Siman,henrdrik8820siman@gmail.com,+6281294656000,,,,...,Karma Kandara,,,New Lead,false,false,,,,
2,zcrm_3584690000370702342,2022-05-27 14:50:00,2022-05-03 00:00:00,Yasmine,Minaski,yasmine.minaski@gmail.com,+61424341511,,,,...,Karma Kandara,,,New Lead,false,false,,,,
3,zcrm_3584690000370701318,2022-05-27 13:46:00,2022-05-01 00:00:00,Chandra,A,chandra.adhisuya@gmail.com,+6281511566666,,,,...,Karma Kandara,,,New Lead,false,false,,,,
4,zcrm_3584690000370694343,2022-05-27 14:40:00,2022-05-03 00:00:00,Natalia,Medayanti,nataliamedayanti79@yahoo.com,+6287823635298,,,,...,Karma Kandara,,,New Lead,false,false,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2562,zcrm_3584690000002904071,2019-02-26 21:10:00,,Ebony,St Quintin,davidstq@hotmail.com,,,,,...,Karma Rottnest,Karma Rottnest Spa January 2019,Other,New Lead,false,false,,,,
2563,zcrm_3584690000002904070,2019-02-26 21:10:00,,Leonie,Plowman,leonieplowman@bigpond.com.au,,,,,...,Karma Rottnest,Karma Rottnest Spa January 2019,SEAP,New Lead,false,false,,,,
2564,zcrm_3584690000002904066,2019-02-26 21:10:00,,Wendy,Price,asrama@iinet.net.au,,,,,...,Karma Rottnest,Karma Rottnest Spa January 2019,SEAP,New Lead,false,false,,,,
2565,zcrm_3584690000002904065,2019-02-26 21:10:00,,Kylie,Williamson,kylie.binks@yahoo.com.au,,,,,...,Karma Rottnest,Karma Rottnest Spa January 2019,SEAP,New Lead,false,false,,,,
2566,zcrm_3584690000002904064,2019-02-26 21:10:00,,Sally,Glenn,geoff.sally@agmaster.com.au,,,,,...,Karma Rottnest,Karma Rottnest Spa January 2019,SEAP,New Lead,false,false,,,,

In [54]:
push_df.to_excel(r'C:\Users\fajar\Documents\Python\Data\Zoho_Campaign\push data\push-karma-spa.xlsx', index=False)