In [1]:
import pandas as pd
import re
import openpyxl


import sys
sys.path.append('../')

import main_module as m
%load_ext autoreload
%autoreload 2

In [349]:
path = r'C:\Users\fajar\Documents\Python\Data\allcontacts.csv'
df_compare = pd.read_csv(path, dtype='string')
count_total_data = df_compare.shape[0]
df_compare

,Contact Email,Opt_in,Confirmed Time,Agreed to Privacy Policy and Terms,Opt-in type
0,000008@163.com,false,<NA>,false,None
1,00001111den@gmail.com,false,<NA>,false,None
2,000helentmorrow000@gmail.com,false,<NA>,false,None
3,006rileysmith@gmail.com,false,<NA>,false,None
4,007dhananjaykumbhar@gmail.com,false,<NA>,false,None
...,...,...,...,...,...
92652,zzangss75@hotmail.com,false,<NA>,false,None
92653,zzhang1987@gmail.com,false,<NA>,false,None
92654,zzigi0124@naver.com,false,<NA>,false,None
92655,Zzoella77@yahoo.com,false,<NA>,false,None
92656,zzpp@hotmail.fr,false,<NA>,false,None

In [2]:
path = r'C:\Users\fajar\Documents\Python\Data\Debounce\debounce_backup.csv'
df_bounced = pd.read_csv(path, dtype='string')
df_bounced

,EMAIL,RESULT,REASON,STATUS CODE,ROLE,FREE,DOMAIN,Sheet Name
0,00001111den@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
1,007dhananjaykumbhar@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
2,0597396@mail.ru,Safe to Send,Deliverable,5,No,Yes,mail.ru,All Campaign
3,07deepanshu@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
4,1078049354@qq.com,Safe to Send,Deliverable,5,No,Yes,qq.com,All Campaign
...,...,...,...,...,...,...,...,...
1224782,z_forbes_92@hotmail.com,Safe to Send,Deliverable,5,No,Yes,hotmail.com,Purple WIFI
1224783,z_mingwei@hotmail.com,Safe to Send,Deliverable,5,No,Yes,hotmail.com,Purple WIFI
1224784,z_o_ni@hotmail.com,Safe to Send,Deliverable,5,No,Yes,hotmail.com,Purple WIFI
1224785,_argo@mail.ru,Safe to Send,Deliverable,5,No,Yes,mail.ru,Purple WIFI
1224786,_joanne_mckay@hotmail.co.nz,Safe to Send,Deliverable,5,No,Yes,hotmail.co.nz,Purple WIFI

In [351]:
df_bounced.groupby('EMAIL').count().sort_values('RESULT', ascending=False)

,RESULT,REASON,STATUS CODE,ROLE,FREE,DOMAIN,Sheet Name
EMAIL,,,,,,,
lisa-666@live.com,5,5,5,5,5,5,5
rennymakruf@gmail.com,5,5,5,5,5,5,5
petrinasmith12@gmail.com,4,4,4,4,4,4,4
fran@otcgs.com.au,4,4,4,4,4,4,4
ajwells96@gmail.com,4,4,4,4,4,4,4
...,...,...,...,...,...,...,...
hollyanneshaw@hotmail.co.uk,1,1,1,1,1,1,1
holly_robins@hotmail.com,1,1,1,1,1,1,1
linda.a.hodder@gmail.com,0,0,0,0,0,0,1
kezathome@msn.com,0,0,0,0,0,0,1
lozzacarbolt1963@gmail.com,0,0,0,0,0,0,1

In [352]:
df_bounced.loc[df_bounced['EMAIL'] == 'alisa.liddiardcolman@karmagroup.com']

,EMAIL,RESULT,REASON,STATUS CODE,ROLE,FREE,DOMAIN,Sheet Name
47785,alisa.liddiardcolman@karmagroup.com,Risky,Accept All,4,No,No,karmagroup.com,29 Apr 22

In [353]:
df_bounced.drop_duplicates(subset='EMAIL', inplace=True)
df_bounced.reset_index(drop=True, inplace=True)
df_bounced

,EMAIL,RESULT,REASON,STATUS CODE,ROLE,FREE,DOMAIN,Sheet Name
0,00001111den@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
1,007dhananjaykumbhar@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
2,0597396@mail.ru,Safe to Send,Deliverable,5,No,Yes,mail.ru,All Campaign
3,07deepanshu@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
4,1078049354@qq.com,Safe to Send,Deliverable,5,No,Yes,qq.com,All Campaign
...,...,...,...,...,...,...,...,...
982853,z_forbes_92@hotmail.com,Safe to Send,Deliverable,5,No,Yes,hotmail.com,Purple WIFI
982854,z_mingwei@hotmail.com,Safe to Send,Deliverable,5,No,Yes,hotmail.com,Purple WIFI
982855,z_o_ni@hotmail.com,Safe to Send,Deliverable,5,No,Yes,hotmail.com,Purple WIFI
982856,_argo@mail.ru,Safe to Send,Deliverable,5,No,Yes,mail.ru,Purple WIFI
982857,_joanne_mckay@hotmail.co.nz,Safe to Send,Deliverable,5,No,Yes,hotmail.co.nz,Purple WIFI

In [354]:
df_compare['Contact Email'] = m.lowercase(df_compare, 'Contact Email')
m.clean_space(df_compare, 'Contact Email')

df_bounced['EMAIL'] = m.lowercase(df_bounced, 'EMAIL')
m.clean_space(df_bounced, 'EMAIL')

0                 00001111den@gmail.com
1         007dhananjaykumbhar@gmail.com
2                       0597396@mail.ru
3                 07deepanshu@gmail.com
4                     1078049354@qq.com
                      ...
982853          z_forbes_92@hotmail.com
982854            z_mingwei@hotmail.com
982855               z_o_ni@hotmail.com
982856                    _argo@mail.ru
982857      _joanne_mckay@hotmail.co.nz
Name: EMAIL, Length: 982858, dtype: string

In [355]:
# Cek Email Karma
email_karma = m.find_karma(df_compare, 'Contact Email')
count_email_karma = email_karma.shape[0]
# email_OTA.to_excel(r'C:\Users\fajar\Documents\Python\Data\email_OTA.xlsx', index=False)

email_karma

johnspence88@hotmail\.com|baligetaway|rottnestlodge\.com\.au|hotel.discount|adimahkota\.com|baligetaway\.co\.id|baligetaway\.com\.au|catkingproductions\.com|complementarystay-karmaexperience\.com|confirmation-karmaexperience\.com|tiketmurahbali\.com|karmasanctumsoho\.co|experiencekarmaclub\.com|karmabavaria\.com|karmabeach\.com|karmaclub\.com|karmadevelopments\.com|karmaestates\.com|karmaexperience\.co\.uk|karmaexperience\.com|karmaexperience\.in|karmagroup\.com|karmajimbaran\.com|karmakandara\.com|karmaminoan\.com|karmanormandy\.com|karmapelikanos\.com|karmareef\.com|karmaresorts\.com|karmaroyalexperience\.co\.uk|karmaroyalexperience\.com|karmaroyalgroup\.com|karmaroyalvacations\.com|karmasalak\.com|karmasalfordhall\.com|karmastmartins\.com|karmgroup\.com|krresidences\.com|lepreverger\.com|odysseypremier\.com|rci\.com|thebaligetaway\.comkarmarottnest\.com\.au|karmasanctumonthegreen\.com|karmasanctumclub\.com|karma\.co\.uk|karma\.com|karmarottnest\.com\.au|karmasanctumsoho\.com|karmaroyalpromotions\.com

,Contact Email,Opt_in,Confirmed Time,Agreed to Privacy Policy and Terms,Opt-in type
1776,aakash.sharma@karmagroup.com,false,<NA>,false,None
1829,aaron.glasson@karmagroup.com,false,<NA>,false,None
1995,abdul.waris@karmaexperience.in,false,<NA>,false,None
2115,abhishek.kasi@karmagroup.com,false,<NA>,false,None
2173,abigail.salda@karmagroup.com,false,<NA>,false,None
...,...,...,...,...,...
92324,zeenat.mulla@karmagroup.com,false,<NA>,false,None
92474,zivio.fernandes@karmagroup.com,false,<NA>,false,None
92557,zohaib.hooda@karmagroup.com,false,<NA>,false,None
92558,zohaib.shaikh@karmagroup.com,false,<NA>,false,None
92559,zoho.campaign@karmagroup.com,false,<NA>,false,None

In [356]:
# delete email Karma
count_after_clean_karma = m.delete_karma(df_compare, 'Contact Email')
# zoho_df_bounced.to_excel(r'C:\Users\fajar\Documents\Python\Data\after_clean_OTA.xlsx', index=False)

email_karma
count_after_clean_karma

90947

In [357]:
df_compare.fillna('empty', inplace=True)
df_compare.loc[df_compare['Contact Email'].isin(df_bounced['EMAIL'])]

,Contact Email,Opt_in,Confirmed Time,Agreed to Privacy Policy and Terms,Opt-in type
0,000008@163.com,false,empty,false,None
1,00001111den@gmail.com,false,empty,false,None
2,000helentmorrow000@gmail.com,false,empty,false,None
3,006rileysmith@gmail.com,false,empty,false,None
4,007dhananjaykumbhar@gmail.com,false,empty,false,None
...,...,...,...,...,...
90942,zzangss75@hotmail.com,false,empty,false,None
90943,zzhang1987@gmail.com,false,empty,false,None
90944,zzigi0124@naver.com,false,empty,false,None
90945,zzoella77@yahoo.com,false,empty,false,None
90946,zzpp@hotmail.fr,false,empty,false,None

In [358]:
joined_df = pd.merge(df_compare,
                     df_bounced,
                     left_on ='Contact Email',
                     right_on ='EMAIL',
                     how ='left')

joined_cols = ['Contact Email', 
        'RESULT',
        'REASON',
        'Sheet Name']

joined_list = joined_df.loc[~joined_df['RESULT'].isna()].copy()
joined_list = joined_list.reindex(columns=joined_cols)
joined_list.reset_index(drop=True, inplace=True)

not_exist_list = joined_df.loc[joined_df['RESULT'].isna()].copy()
not_exist_list = not_exist_list.reindex(columns=joined_cols)
not_exist_list.reset_index(drop=True, inplace=True)

count_exist_in_bounce = joined_list.shape[0]
count_not_exist_in_bounce = not_exist_list.shape[0]

In [359]:
safe_to_send = joined_list.loc[joined_list['RESULT'] == 'Safe to Send'].copy()
safe_to_send.reset_index(drop=True, inplace=True)
count_safe_to_send = safe_to_send.shape[0]

ex_safe_to_send = joined_list.loc[joined_list['RESULT'] != 'Safe to Send'].copy()
ex_safe_to_send.reset_index(drop=True, inplace=True)
count_ex_safe_to_send = ex_safe_to_send.shape[0]

In [360]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Total Data : "+str(count_total_data))
print("Jumlah Data Email Karma : "+str(count_email_karma))
print("Jumlah Setelah Wash Email Karma : "+str(count_after_clean_karma))
print("Jumlah Data Exist di Database Bounce : "+str(count_exist_in_bounce))
print("Jumlah Data Tidak Exist di Database Bounce : "+str(count_not_exist_in_bounce))
print("==========================================================")
print("Summary Bounced")
print("==========================================================")
print("Jumlah Data Safe to Send : "+str(count_safe_to_send))
print("Jumlah Data not Safe to Send : "+str(count_ex_safe_to_send))

==========================================================
Summary
==========================================================
Jumlah Total Data : 92657
Jumlah Data Email Karma : 1710
Jumlah Setelah Wash Email Karma : 90947
Jumlah Data Exist di Database Bounce : 90947
Jumlah Data Tidak Exist di Database Bounce : 0
==========================================================
Summary Bounced
==========================================================
Jumlah Data Safe to Send : 90346
Jumlah Data not Safe to Send : 601

In [361]:
# ex_safe_to_send.to_csv(r'C:\Users\fajar\Documents\Python\Data\unsubs_campaign.csv', index=False, encoding='utf-8')

In [362]:
# not_exist_list.to_csv(r'C:\Users\fajar\Documents\Python\Data\check_debounce.csv', index=False, encoding='utf-8')

In [363]:
ex_safe_to_send.to_csv(r'C:\Users\fajar\Documents\Python\Data\import_unsubs_new.csv', index=False, encoding='utf-8')