In [20]:
import pandas as pd
import re
import openpyxl

import sys
sys.path.append('../')

import main_module as m

In [21]:
cols = ['First Name', 
    'Last Name',
    'Email', 
    'Phone', 
    'Mobile', 
    'City', 
    'State',
    'Country', 
    'Nationality',
    'Lead Locations', 
    'Booking Status',
    'Lead Source', 
    'BookRef']

In [22]:
path = r'C:\Users\fajar\Documents\Python\Data\push-pastguest.xlsx'
df_push = pd.read_excel(path, dtype='string', usecols=cols, sheet_name='Sheet0', engine='openpyxl')
df_push.fillna('empty', inplace=True)
count_total_data = df_push.shape[0]
df_push.columns

Index(['First Name', 'Last Name', 'Email', 'Phone', 'Mobile', 'City', 'State',
       'Country', 'Nationality', 'Lead Source', 'Lead Locations',
       'Booking Status', 'BookRef'],
      dtype='object')

In [23]:
df_push

,First Name,Last Name,Email,Phone,Mobile,City,State,Country,Nationality,Lead Source,Lead Locations,Booking Status,BookRef
0,George De La,Cour,dlc_fea@yahoo.co.uk,+85295280927,empty,Hong Kong,-,Hong Kong,British,Past Guests,"KRR @ Karma Kandara, Mentari Residences",Checked-Out,2690917
1,Karan,Dhawan,ravina2394@gmail.com,+918700153609,+919582557870,UTTAM NAGAR,NEW DELHI,India,Indian,Past Guests,"Karma Utopia, Manali",Checked-Out,2688152
2,Mandar Prakash,Bhatt,bhattmandar444@gmail.com,+919975289309,+918007566870,THANE,MAHARASHTRA,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2679450
3,Vikas,Chandok,vik.4151@ymail.com,+917986322727,+919888504151,AMRITSAR,PUNJAB,India,Indian,Past Guests,"Karma Utopia, Manali",Checked-Out,2690027
4,Aman,Madaan,amanmadaan80@gmail.com,+919971235785,+919910152793,DELHI,NEW DELHI,India,Indian,Past Guests,"Karma Sitabani, Corbett",Checked-Out,2686600
...,...,...,...,...,...,...,...,...,...,...,...,...,...
616,Devesh Prakash,Vaishnav,devesh_vaishnav@hotmail.com,+919480036806,+918105563291,BANGALORE,KARNATAKA,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2657413
617,Nazir Ahmed,Hullur,nihullur@gmail.com,+919481126428,+918762835448,HUBLI,KARNATAKA,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2674520
618,Toby,Edwards,theangler37@icloud.com,+441620614347,+441620614347,empty,empty,United Kingdom,British,Past Guests,Karma Lake of Menteith,CANCELLED,KLM006246
619,Marie Louise,Garms,mlgarms@gmail.com,+4917623555095,empty,Parsdorf,empty,Germany,German,Past Guests,Karma Bavaria,CANCELLED,KB044110
620,Jack,Weller,jack.weller@live.com,+642108410947,empty,Auckland,empty,New Zealand,empty,Past Guests,Karma Kandara,CANCELLED,KK064104

In [24]:
path = r'C:\Users\fajar\Documents\Python\Data\Debounce\debounce_backup.csv'
df_1 = pd.read_csv(path, dtype='string')

path = r'C:\Users\fajar\Documents\Python\Data\Debounce\debounce_new_temp.csv'
df_2 = pd.read_csv(path, dtype='string')


frames = [df_1, df_2]
df_bounced = pd.concat(frames, ignore_index=True)
df_bounced

,EMAIL,RESULT,REASON,STATUS CODE,ROLE,FREE,DOMAIN,Sheet Name
0,00001111den@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
1,007dhananjaykumbhar@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
2,0597396@mail.ru,Safe to Send,Deliverable,5,No,Yes,mail.ru,All Campaign
3,07deepanshu@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
4,1078049354@qq.com,Safe to Send,Deliverable,5,No,Yes,qq.com,All Campaign
...,...,...,...,...,...,...,...,...
1266206,amanmadaan80@gmail.com,Invalid,HandShacke Fail,10,false,false,<NA>,<NA>
1266207,vik.4151@ymail.com,Invalid,HandShacke Fail,10,false,false,<NA>,<NA>
1266208,bhattmandar444@gmail.com,Invalid,HandShacke Fail,10,false,false,<NA>,<NA>
1266209,ravina2394@gmail.com,Invalid,HandShacke Fail,10,false,false,<NA>,<NA>
1266210,dlc_fea@yahoo.co.uk,Invalid,HandShacke Fail,10,false,false,<NA>,<NA>

In [25]:
df_bounced.drop_duplicates(subset='EMAIL', inplace=True)
df_bounced.reset_index(drop=True, inplace=True)
df_bounced

,EMAIL,RESULT,REASON,STATUS CODE,ROLE,FREE,DOMAIN,Sheet Name
0,00001111den@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
1,007dhananjaykumbhar@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
2,0597396@mail.ru,Safe to Send,Deliverable,5,No,Yes,mail.ru,All Campaign
3,07deepanshu@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
4,1078049354@qq.com,Safe to Send,Deliverable,5,No,Yes,qq.com,All Campaign
...,...,...,...,...,...,...,...,...
1020076,amanmadaan80@gmail.com,Invalid,HandShacke Fail,10,false,false,<NA>,<NA>
1020077,vik.4151@ymail.com,Invalid,HandShacke Fail,10,false,false,<NA>,<NA>
1020078,bhattmandar444@gmail.com,Invalid,HandShacke Fail,10,false,false,<NA>,<NA>
1020079,ravina2394@gmail.com,Invalid,HandShacke Fail,10,false,false,<NA>,<NA>
1020080,dlc_fea@yahoo.co.uk,Invalid,HandShacke Fail,10,false,false,<NA>,<NA>

In [26]:
df_push['Email'] = m.lowercase(df_push, 'Email')
m.clean_space(df_push, 'Email')

df_bounced['EMAIL'] = m.lowercase(df_bounced, 'EMAIL')
m.clean_space(df_bounced, 'EMAIL')

c:\Users\fajar\Documents\Python\Task Offline\zoho_data_app\zoho_campaign\..\main_module.py:90: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)

0                  00001111den@gmail.com
1          007dhananjaykumbhar@gmail.com
2                        0597396@mail.ru
3                  07deepanshu@gmail.com
4                      1078049354@qq.com
                       ...
1020076           amanmadaan80@gmail.com
1020077               vik.4151@ymail.com
1020078         bhattmandar444@gmail.com
1020079             ravina2394@gmail.com
1020080              dlc_fea@yahoo.co.uk
Name: EMAIL, Length: 1020081, dtype: string

In [27]:
df_push.loc[df_push['Email'].isin(df_bounced['EMAIL'])]

,First Name,Last Name,Email,Phone,Mobile,City,State,Country,Nationality,Lead Source,Lead Locations,Booking Status,BookRef
0,George De La,Cour,dlc_fea@yahoo.co.uk,+85295280927,empty,Hong Kong,-,Hong Kong,British,Past Guests,"KRR @ Karma Kandara, Mentari Residences",Checked-Out,2690917
1,Karan,Dhawan,ravina2394@gmail.com,+918700153609,+919582557870,UTTAM NAGAR,NEW DELHI,India,Indian,Past Guests,"Karma Utopia, Manali",Checked-Out,2688152
2,Mandar Prakash,Bhatt,bhattmandar444@gmail.com,+919975289309,+918007566870,THANE,MAHARASHTRA,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2679450
3,Vikas,Chandok,vik.4151@ymail.com,+917986322727,+919888504151,AMRITSAR,PUNJAB,India,Indian,Past Guests,"Karma Utopia, Manali",Checked-Out,2690027
4,Aman,Madaan,amanmadaan80@gmail.com,+919971235785,+919910152793,DELHI,NEW DELHI,India,Indian,Past Guests,"Karma Sitabani, Corbett",Checked-Out,2686600
...,...,...,...,...,...,...,...,...,...,...,...,...,...
614,Manoj K,Bhise,krushnai2012@gmail.com,+919822232888,+918208698844,NAGPUR,MAHARASHTRA,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2675596
615,Ramandeep Singh,Kaberwal,ramandeep6682@gmail.com,+919987439662,+919619621313,MUMBAI,MAHARASHTRA,India,Indian,Past Guests,"Karma Utopia, Manali",Checked-Out,2544976
616,Devesh Prakash,Vaishnav,devesh_vaishnav@hotmail.com,+919480036806,+918105563291,BANGALORE,KARNATAKA,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2657413
617,Nazir Ahmed,Hullur,nihullur@gmail.com,+919481126428,+918762835448,HUBLI,KARNATAKA,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2674520
620,Jack,Weller,jack.weller@live.com,+642108410947,empty,Auckland,empty,New Zealand,empty,Past Guests,Karma Kandara,CANCELLED,KK064104

In [28]:
count_empty_contact = df_push.loc[(df_push['Email'] == 'empty') &
            (df_push['Phone'] == 'empty') &
            (df_push['Mobile'] == 'empty')].shape[0]

df_push.drop(df_push.loc[(df_push['Email'] == 'empty') &
            (df_push['Phone'] == 'empty') &
            (df_push['Mobile'] == 'empty')
            ].index, inplace=True)

count_after_wash_empty_contact = df_push.shape[0]

In [29]:
# df_bounced.loc[df_bounced['EMAIL'] == 'pawan_chhikara2001@yahoo.com']

In [30]:
joined_df = pd.merge(df_push,
                     df_bounced,
                     left_on ='Email',
                     right_on ='EMAIL',
                     how ='left')
joined_df

,First Name,Last Name,Email,Phone,Mobile,City,State,Country,Nationality,Lead Source,...,Booking Status,BookRef,EMAIL,RESULT,REASON,STATUS CODE,ROLE,FREE,DOMAIN,Sheet Name
0,George De La,Cour,dlc_fea@yahoo.co.uk,+85295280927,empty,Hong Kong,-,Hong Kong,British,Past Guests,...,Checked-Out,2690917,dlc_fea@yahoo.co.uk,Invalid,HandShacke Fail,10,false,false,<NA>,<NA>
1,Karan,Dhawan,ravina2394@gmail.com,+918700153609,+919582557870,UTTAM NAGAR,NEW DELHI,India,Indian,Past Guests,...,Checked-Out,2688152,ravina2394@gmail.com,Invalid,HandShacke Fail,10,false,false,<NA>,<NA>
2,Mandar Prakash,Bhatt,bhattmandar444@gmail.com,+919975289309,+918007566870,THANE,MAHARASHTRA,India,Indian,Past Guests,...,Checked-Out,2679450,bhattmandar444@gmail.com,Invalid,HandShacke Fail,10,false,false,<NA>,<NA>
3,Vikas,Chandok,vik.4151@ymail.com,+917986322727,+919888504151,AMRITSAR,PUNJAB,India,Indian,Past Guests,...,Checked-Out,2690027,vik.4151@ymail.com,Invalid,HandShacke Fail,10,false,false,<NA>,<NA>
4,Aman,Madaan,amanmadaan80@gmail.com,+919971235785,+919910152793,DELHI,NEW DELHI,India,Indian,Past Guests,...,Checked-Out,2686600,amanmadaan80@gmail.com,Invalid,HandShacke Fail,10,false,false,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
616,Devesh Prakash,Vaishnav,devesh_vaishnav@hotmail.com,+919480036806,+918105563291,BANGALORE,KARNATAKA,India,Indian,Past Guests,...,Checked-Out,2657413,devesh_vaishnav@hotmail.com,Safe to Send,Deliverable,5,False,True,<NA>,Past Guest
617,Nazir Ahmed,Hullur,nihullur@gmail.com,+919481126428,+918762835448,HUBLI,KARNATAKA,India,Indian,Past Guests,...,Checked-Out,2674520,nihullur@gmail.com,Safe to Send,Deliverable,5,False,True,<NA>,Past Guest
618,Toby,Edwards,theangler37@icloud.com,+441620614347,+441620614347,empty,empty,United Kingdom,British,Past Guests,...,CANCELLED,KLM006246,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
619,Marie Louise,Garms,mlgarms@gmail.com,+4917623555095,empty,Parsdorf,empty,Germany,German,Past Guests,...,CANCELLED,KB044110,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
620,Jack,Weller,jack.weller@live.com,+642108410947,empty,Auckland,empty,New Zealand,empty,Past Guests,...,CANCELLED,KK064104,jack.weller@live.com,Safe to Send,Deliverable,5,False,True,<NA>,Past Guest

In [31]:
joined_list = joined_df.loc[~joined_df['RESULT'].isna()].copy()
joined_list.reset_index(drop=True, inplace=True)

not_exist_list = joined_df.loc[joined_df['RESULT'].isna()].copy()
not_exist_list.reset_index(drop=True, inplace=True)

count_exist_in_bounce = joined_list.shape[0]
count_not_exist_in_bounce = not_exist_list.shape[0]

In [32]:
safe_to_send = joined_list.loc[joined_list['RESULT'] == 'Safe to Send'].copy()
safe_to_send.reset_index(drop=True, inplace=True)
count_safe_to_send = safe_to_send.shape[0]

ex_safe_to_send = joined_list.loc[joined_list['RESULT'] != 'Safe to Send'].copy()
ex_safe_to_send.reset_index(drop=True, inplace=True)
count_ex_safe_to_send = ex_safe_to_send.shape[0]

In [33]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Total Data : "+str(count_total_data))
print("Jumlah Data Contact Empty : "+str(count_empty_contact))
print("Jumlah Data Setelah Wash Empty Contact : "+str(count_empty_contact))
print("Jumlah Data Exist di Database Bounce : "+str(count_exist_in_bounce))
print("Jumlah Data Tidak Exist di Database Bounce : "+str(count_not_exist_in_bounce))
print("==========================================================")
print("Summary Bounced")
print("==========================================================")
print("Jumlah Data Safe to Send : "+str(count_safe_to_send))
print("Jumlah Data not Safe to Send : "+str(count_ex_safe_to_send))

==========================================================
Summary
==========================================================
Jumlah Total Data : 621
Jumlah Data Contact Empty : 0
Jumlah Data Setelah Wash Empty Contact : 0
Jumlah Data Exist di Database Bounce : 619
Jumlah Data Tidak Exist di Database Bounce : 2
==========================================================
Summary Bounced
==========================================================
Jumlah Data Safe to Send : 91
Jumlah Data not Safe to Send : 528

In [34]:
not_exist_list.loc[not_exist_list['Email'] == 'mohdasifaliak2016@gmail.com']
# df_1.loc[df_1['EMAIL'] == 'matthew.w.giles@gmail.com']
# df_1.loc[df_1['EMAIL'] == 'venkjaya@gmail.com']
# joined_df.loc[joined_df['RESULT'] == 'Safe to Send']
# df_bounced.loc[df_bounced['EMAIL'] == ]

Empty DataFrame
Columns: [First Name, Last Name, Email, Phone, Mobile, City, State, Country, Nationality, Lead Source, Lead Locations, Booking Status, BookRef, EMAIL, RESULT, REASON, STATUS CODE, ROLE, FREE, DOMAIN, Sheet Name]
Index: []

[0 rows x 21 columns]

In [35]:
joined_df.loc[joined_df['Email'] == 'mohdasifaliak2016@gmail.com']

Empty DataFrame
Columns: [First Name, Last Name, Email, Phone, Mobile, City, State, Country, Nationality, Lead Source, Lead Locations, Booking Status, BookRef, EMAIL, RESULT, REASON, STATUS CODE, ROLE, FREE, DOMAIN, Sheet Name]
Index: []

[0 rows x 21 columns]

In [36]:
safe_to_send.replace('empty', '', inplace=True)
safe_to_send.reset_index(drop=True, inplace=True)
df_safe = safe_to_send.reindex(columns=cols)
df_safe.rename(columns={'Lead Source':'Lead Sources'}, inplace=True)
df_safe['Tags'] = 'Non Members,Past Guest'

df_safe.to_csv(r'C:\Users\fajar\Documents\Python\Data\push-pastguest-formatted.csv', index=False, encoding='utf-8')

In [37]:
ex_safe_to_send.replace('empty', '', inplace=True)
ex_safe_to_send.reset_index(drop=True, inplace=True)
df_ex_safe_to_send = ex_safe_to_send.reindex(columns=cols)
df_ex_safe_to_send

df_ex_safe_to_send.to_excel(r'C:\Users\fajar\Documents\Python\Data\not-safe-to-send-debounce.xlsx', index=False)

In [38]:
not_exist_list.replace('empty', '', inplace=True)
not_exist_list.reset_index(drop=True, inplace=True)
df_not_exist = not_exist_list.reindex(columns=cols)
df_not_exist

df_not_exist.to_excel(r'C:\Users\fajar\Documents\Python\Data\not-exist-debounce.xlsx', index=False)