In [1]:
import pandas as pd
import re
import openpyxl

import sys
sys.path.append('../')

import main_module as m

In [2]:
cols = ['First Name', 
    'Last Name',
    'Email', 
    'Phone', 
    'Mobile', 
    'City', 
    'Country', 
    'Nationality',
    'Lead Locations', 
    'Booking Status',
    'Lead Source', 
    'BookRef']

In [3]:
path = r'C:\Users\fajar\Documents\Python\Data\push-pastguest.xlsx'
df_push = pd.read_excel(path, dtype='string', usecols=cols, sheet_name='Sheet0', engine='openpyxl')
df_push.fillna('empty', inplace=True)
count_total_data = df_push.shape[0]
df_push.columns

C:\Users\fajar\AppData\Roaming\Python\Python310\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Index(['First Name', 'Last Name', 'Email', 'Phone', 'Mobile', 'City',
       'Country', 'Nationality', 'Lead Source', 'Lead Locations',
       'Booking Status', 'BookRef'],
      dtype='object')

In [4]:
df_push

,First Name,Last Name,Email,Phone,Mobile,City,Country,Nationality,Lead Source,Lead Locations,Booking Status,BookRef
0,Rahul,Agrawal,rahulagrawal427@gmail.com,+919131331655,empty,Korba,India,Indian,Past Guests,"KRR @ Karma Kandara, Mentari Residences",Checked-Out,2578611
1,Sandeep Singh,Bhadouria,sandeep.bhadourya@gmail.com,+919545231100,+918390305170,PUNE,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2518438
2,Leanne,Pereira,leannepereira2002@gmail.com,+919741992031,empty,Banglore,India,Indian,Past Guests,Karma Sunshine Village,Checked-Out,2539018
3,Lawrence,Pereira,lawry_pereira@yahoo.com,+919901907414,empty,Banglore,India,Indian,Past Guests,Karma Sunshine Village,Checked-Out,2539019
4,Ojas,Rao,neha.deshpande26@gmail.com,+918095861162,+918147338292,BENGALURU,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2574113
...,...,...,...,...,...,...,...,...,...,...,...,...
255,Alice,Shuttleworth,alice_shuttleworth@yahoo.co.uk,+447815960436,empty,empty,United Kingdom,British,Past Guests,Karma La Herriza,Checked-Out,2522243
256,Shih-Ping,Yang,tsaeyang002@yahoo.com.tw,+886983185791,empty,-,Taiwan,Taiwanese,Past Guests,Karma Jimbaran,Checked-Out,2558600
257,Seah Cheng,San,chengsan@singnet.com.sg,empty,empty,.,Singapore,Singaporean,Past Guests,"KRR @ Karma Kandara, Mentari Residences",Checked-Out,2456671
258,Deepak,Kumar,deepakmuteja1979@gmail.com,+919996006842,+918529084740,BHIWANI,India,Indian,Past Guests,"Karma Sitabani, Corbett",Checked-Out,2537352
259,Sarah,Mhlanga,sarahgreen82@googlemail.com,+447557117808,empty,empty,United Kingdom,British,Past Guests,Karma La Herriza,Checked-Out,2530230

In [5]:
path = r'C:\Users\fajar\Documents\Python\Data\Debounce\debounce_backup.csv'
df_1 = pd.read_csv(path, dtype='string')

path = r'C:\Users\fajar\Documents\Python\Data\Debounce\debounce_new_temp.csv'
df_2 = pd.read_csv(path, dtype='string')


frames = [df_1, df_2]
df_bounced = pd.concat(frames, ignore_index=True)
df_bounced

,EMAIL,RESULT,REASON,STATUS CODE,ROLE,FREE,DOMAIN,Sheet Name
0,00001111den@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
1,007dhananjaykumbhar@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
2,0597396@mail.ru,Safe to Send,Deliverable,5,No,Yes,mail.ru,All Campaign
3,07deepanshu@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
4,1078049354@qq.com,Safe to Send,Deliverable,5,No,Yes,qq.com,All Campaign
...,...,...,...,...,...,...,...,...
1258263,kppahwa@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
1258264,jb8886@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
1258265,ashwinkarhade2002@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
1258266,jobykr@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
1258267,neha.deshpande26@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>

In [6]:
df_bounced.drop_duplicates(subset='EMAIL', inplace=True)
df_bounced.reset_index(drop=True, inplace=True)
df_bounced

,EMAIL,RESULT,REASON,STATUS CODE,ROLE,FREE,DOMAIN,Sheet Name
0,00001111den@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
1,007dhananjaykumbhar@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
2,0597396@mail.ru,Safe to Send,Deliverable,5,No,Yes,mail.ru,All Campaign
3,07deepanshu@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
4,1078049354@qq.com,Safe to Send,Deliverable,5,No,Yes,qq.com,All Campaign
...,...,...,...,...,...,...,...,...
1014501,kppahwa@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
1014502,jb8886@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
1014503,ashwinkarhade2002@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
1014504,jobykr@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
1014505,neha.deshpande26@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>

In [7]:
df_push['Email'] = m.lowercase(df_push, 'Email')
m.clean_space(df_push, 'Email')

df_bounced['EMAIL'] = m.lowercase(df_bounced, 'EMAIL')
m.clean_space(df_bounced, 'EMAIL')

0                  00001111den@gmail.com
1          007dhananjaykumbhar@gmail.com
2                        0597396@mail.ru
3                  07deepanshu@gmail.com
4                      1078049354@qq.com
                       ...
1014501                kppahwa@gmail.com
1014502                 jb8886@gmail.com
1014503      ashwinkarhade2002@gmail.com
1014504                 jobykr@gmail.com
1014505       neha.deshpande26@gmail.com
Name: EMAIL, Length: 1014506, dtype: string

In [8]:
df_push.loc[df_push['Email'].isin(df_bounced['EMAIL'])]

,First Name,Last Name,Email,Phone,Mobile,City,Country,Nationality,Lead Source,Lead Locations,Booking Status,BookRef
0,Rahul,Agrawal,rahulagrawal427@gmail.com,+919131331655,empty,Korba,India,Indian,Past Guests,"KRR @ Karma Kandara, Mentari Residences",Checked-Out,2578611
1,Sandeep Singh,Bhadouria,sandeep.bhadourya@gmail.com,+919545231100,+918390305170,PUNE,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2518438
2,Leanne,Pereira,leannepereira2002@gmail.com,+919741992031,empty,Banglore,India,Indian,Past Guests,Karma Sunshine Village,Checked-Out,2539018
3,Lawrence,Pereira,lawry_pereira@yahoo.com,+919901907414,empty,Banglore,India,Indian,Past Guests,Karma Sunshine Village,Checked-Out,2539019
4,Ojas,Rao,neha.deshpande26@gmail.com,+918095861162,+918147338292,BENGALURU,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2574113
...,...,...,...,...,...,...,...,...,...,...,...,...
255,Alice,Shuttleworth,alice_shuttleworth@yahoo.co.uk,+447815960436,empty,empty,United Kingdom,British,Past Guests,Karma La Herriza,Checked-Out,2522243
256,Shih-Ping,Yang,tsaeyang002@yahoo.com.tw,+886983185791,empty,-,Taiwan,Taiwanese,Past Guests,Karma Jimbaran,Checked-Out,2558600
257,Seah Cheng,San,chengsan@singnet.com.sg,empty,empty,.,Singapore,Singaporean,Past Guests,"KRR @ Karma Kandara, Mentari Residences",Checked-Out,2456671
258,Deepak,Kumar,deepakmuteja1979@gmail.com,+919996006842,+918529084740,BHIWANI,India,Indian,Past Guests,"Karma Sitabani, Corbett",Checked-Out,2537352
259,Sarah,Mhlanga,sarahgreen82@googlemail.com,+447557117808,empty,empty,United Kingdom,British,Past Guests,Karma La Herriza,Checked-Out,2530230

In [9]:
count_empty_contact = df_push.loc[(df_push['Email'] == 'empty') &
            (df_push['Phone'] == 'empty') &
            (df_push['Mobile'] == 'empty')].shape[0]

df_push.drop(df_push.loc[(df_push['Email'] == 'empty') &
            (df_push['Phone'] == 'empty') &
            (df_push['Mobile'] == 'empty')
            ].index, inplace=True)

count_after_wash_empty_contact = df_push.shape[0]

In [10]:
# df_bounced.loc[df_bounced['EMAIL'] == 'pawan_chhikara2001@yahoo.com']

In [11]:
joined_df = pd.merge(df_push,
                     df_bounced,
                     left_on ='Email',
                     right_on ='EMAIL',
                     how ='left')
joined_df

,First Name,Last Name,Email,Phone,Mobile,City,Country,Nationality,Lead Source,Lead Locations,Booking Status,BookRef,EMAIL,RESULT,REASON,STATUS CODE,ROLE,FREE,DOMAIN,Sheet Name
0,Rahul,Agrawal,rahulagrawal427@gmail.com,+919131331655,empty,Korba,India,Indian,Past Guests,"KRR @ Karma Kandara, Mentari Residences",Checked-Out,2578611,rahulagrawal427@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
1,Sandeep Singh,Bhadouria,sandeep.bhadourya@gmail.com,+919545231100,+918390305170,PUNE,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2518438,sandeep.bhadourya@gmail.com,Invalid,Bounce,6,FALSE,TRUE,<NA>,<NA>
2,Leanne,Pereira,leannepereira2002@gmail.com,+919741992031,empty,Banglore,India,Indian,Past Guests,Karma Sunshine Village,Checked-Out,2539018,leannepereira2002@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
3,Lawrence,Pereira,lawry_pereira@yahoo.com,+919901907414,empty,Banglore,India,Indian,Past Guests,Karma Sunshine Village,Checked-Out,2539019,lawry_pereira@yahoo.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
4,Ojas,Rao,neha.deshpande26@gmail.com,+918095861162,+918147338292,BENGALURU,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2574113,neha.deshpande26@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,Alice,Shuttleworth,alice_shuttleworth@yahoo.co.uk,+447815960436,empty,empty,United Kingdom,British,Past Guests,Karma La Herriza,Checked-Out,2522243,alice_shuttleworth@yahoo.co.uk,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
256,Shih-Ping,Yang,tsaeyang002@yahoo.com.tw,+886983185791,empty,-,Taiwan,Taiwanese,Past Guests,Karma Jimbaran,Checked-Out,2558600,tsaeyang002@yahoo.com.tw,Invalid,Bounce,6,FALSE,TRUE,<NA>,<NA>
257,Seah Cheng,San,chengsan@singnet.com.sg,empty,empty,.,Singapore,Singaporean,Past Guests,"KRR @ Karma Kandara, Mentari Residences",Checked-Out,2456671,chengsan@singnet.com.sg,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
258,Deepak,Kumar,deepakmuteja1979@gmail.com,+919996006842,+918529084740,BHIWANI,India,Indian,Past Guests,"Karma Sitabani, Corbett",Checked-Out,2537352,deepakmuteja1979@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
259,Sarah,Mhlanga,sarahgreen82@googlemail.com,+447557117808,empty,empty,United Kingdom,British,Past Guests,Karma La Herriza,Checked-Out,2530230,sarahgreen82@googlemail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>

In [12]:
joined_list = joined_df.loc[~joined_df['RESULT'].isna()].copy()
joined_list.reset_index(drop=True, inplace=True)

not_exist_list = joined_df.loc[joined_df['RESULT'].isna()].copy()
not_exist_list.reset_index(drop=True, inplace=True)

count_exist_in_bounce = joined_list.shape[0]
count_not_exist_in_bounce = not_exist_list.shape[0]

In [13]:
safe_to_send = joined_list.loc[joined_list['RESULT'] == 'Safe to Send'].copy()
safe_to_send.reset_index(drop=True, inplace=True)
count_safe_to_send = safe_to_send.shape[0]

ex_safe_to_send = joined_list.loc[joined_list['RESULT'] != 'Safe to Send'].copy()
ex_safe_to_send.reset_index(drop=True, inplace=True)
count_ex_safe_to_send = ex_safe_to_send.shape[0]

In [14]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Total Data : "+str(count_total_data))
print("Jumlah Data Contact Empty : "+str(count_empty_contact))
print("Jumlah Data Setelah Wash Empty Contact : "+str(count_empty_contact))
print("Jumlah Data Exist di Database Bounce : "+str(count_exist_in_bounce))
print("Jumlah Data Tidak Exist di Database Bounce : "+str(count_not_exist_in_bounce))
print("==========================================================")
print("Summary Bounced")
print("==========================================================")
print("Jumlah Data Safe to Send : "+str(count_safe_to_send))
print("Jumlah Data not Safe to Send : "+str(count_ex_safe_to_send))

==========================================================
Summary
==========================================================
Jumlah Total Data : 260
Jumlah Data Contact Empty : 0
Jumlah Data Setelah Wash Empty Contact : 0
Jumlah Data Exist di Database Bounce : 260
Jumlah Data Tidak Exist di Database Bounce : 0
==========================================================
Summary Bounced
==========================================================
Jumlah Data Safe to Send : 229
Jumlah Data not Safe to Send : 31

In [15]:
not_exist_list.loc[not_exist_list['Email'] == 'mohdasifaliak2016@gmail.com']
# df_1.loc[df_1['EMAIL'] == 'matthew.w.giles@gmail.com']
# df_1.loc[df_1['EMAIL'] == 'venkjaya@gmail.com']
# joined_df.loc[joined_df['RESULT'] == 'Safe to Send']
# df_bounced.loc[df_bounced['EMAIL'] == ]

Empty DataFrame
Columns: [First Name, Last Name, Email, Phone, Mobile, City, Country, Nationality, Lead Source, Lead Locations, Booking Status, BookRef, EMAIL, RESULT, REASON, STATUS CODE, ROLE, FREE, DOMAIN, Sheet Name]
Index: []

In [16]:
joined_df.loc[joined_df['Email'] == 'mohdasifaliak2016@gmail.com']

Empty DataFrame
Columns: [First Name, Last Name, Email, Phone, Mobile, City, Country, Nationality, Lead Source, Lead Locations, Booking Status, BookRef, EMAIL, RESULT, REASON, STATUS CODE, ROLE, FREE, DOMAIN, Sheet Name]
Index: []

In [17]:
safe_to_send.replace('empty', '', inplace=True)
safe_to_send.reset_index(drop=True, inplace=True)
df_safe = safe_to_send.reindex(columns=cols)
df_safe.rename(columns={'Lead Source':'Lead Sources'}, inplace=True)

df_safe.to_csv(r'C:\Users\fajar\Documents\Python\Data\push-pastguest-formatted.csv', index=False, encoding='utf-8')

In [18]:
ex_safe_to_send.replace('empty', '', inplace=True)
ex_safe_to_send.reset_index(drop=True, inplace=True)
df_ex_safe_to_send = ex_safe_to_send.reindex(columns=cols)
df_ex_safe_to_send

df_ex_safe_to_send.to_excel(r'C:\Users\fajar\Documents\Python\Data\not-safe-to-send-debounce.xlsx', index=False)

In [19]:
not_exist_list.replace('empty', '', inplace=True)
not_exist_list.reset_index(drop=True, inplace=True)
df_not_exist = not_exist_list.reindex(columns=cols)
df_not_exist

df_not_exist.to_excel(r'C:\Users\fajar\Documents\Python\Data\not-exist-debounce.xlsx', index=False)