In [39]:
import pandas as pd
import re
import openpyxl

import sys
sys.path.append('../')

import main_module as m

In [40]:
cols = ['First Name', 
    'Last Name',
    'Email', 
    'Phone', 
    'Mobile', 
    'City', 
    'State',
    'Country', 
    'Nationality',
    'Lead Locations', 
    'Booking Status',
    'Lead Source', 
    'BookRef']

In [41]:
path = r'C:\Users\fajar\Documents\Python\Data\push-pastguest.xlsx'
df_push = pd.read_excel(path, dtype='string', usecols=cols, sheet_name='Sheet0', engine='openpyxl')
df_push.fillna('empty', inplace=True)
count_total_data = df_push.shape[0]
df_push.columns

c:\Users\fajar\Documents\Python\Task Offline\venv12\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Index(['First Name', 'Last Name', 'Email', 'Phone', 'Mobile', 'City', 'State',
       'Country', 'Nationality', 'Lead Source', 'Lead Locations',
       'Booking Status', 'BookRef'],
      dtype='object')

In [42]:
df_push

,First Name,Last Name,Email,Phone,Mobile,City,State,Country,Nationality,Lead Source,Lead Locations,Booking Status,BookRef
0,Vincent,Satish,satishvincent6294@gmail.com,+918904248017,+919243468016,BANGALORE,KARNATAKA,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2677544
1,Pawan Kumar,Gangar,fanie.gangar@gmail.com,+919911919092,+919953679365,DELHI,NEW DELHI,India,Indian,Past Guests,"Karma Sitabani, Corbett",Checked-Out,2646711
2,Umesh,Zagade,umeshzag@gmail.com,+919545922555,+919545922550,PUNE,MAHARASHTRA,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2673305
3,Devesh Prakash,Vaishnav,devesh_vaishnav@hotmail.com,+919480036806,+918105563291,BANGALORE,KARNATAKA,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2657413
4,Premjeet,Furtado,premjeetf@rediffmail.com,+918108255558,empty,MUMBAI,MAHARASHTRA,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2618917
...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,Maria,Corba,vcorba@peptalk.com.ar,+541143129516,empty,CIUDAD AUTONOMA BS AS,CF,Argentina,Argentinean,Past Guests,Karma Borgo Di Colleoli,Checked-Out,2377274
366,John,Critchley,j.critchley@hotmail.co.uk,+441204883506,empty,Bury,-,England,British,Past Guests,Karma Lake of Menteith,Checked-Out,2036204
367,Rakesh,Soni,rakeshsoni@prajhipurity.net,+918425861354,+919833170708,MUMBAI,MAHARASHTRA,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2627867
368,Jack,Weller,jack.weller@live.com,+622108410947,empty,Auckland,empty,New Zealand,empty,Past Guests,Karma Kandara,CANCELLED,KK064104
369,Nadine,Remmert,nadine.remmert@gmx.de,+4917660930047,empty,empty,empty,Germany,German,Past Guests,Karma Bavaria,CANCELLED,KB044403

In [43]:
path = r'C:\Users\fajar\Documents\Python\Data\Debounce\debounce_backup.csv'
df_1 = pd.read_csv(path, dtype='string')

path = r'C:\Users\fajar\Documents\Python\Data\Debounce\debounce_new_temp.csv'
df_2 = pd.read_csv(path, dtype='string')


frames = [df_1, df_2]
df_bounced = pd.concat(frames, ignore_index=True)
df_bounced

,EMAIL,RESULT,REASON,STATUS CODE,ROLE,FREE,DOMAIN,Sheet Name
0,00001111den@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
1,007dhananjaykumbhar@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
2,0597396@mail.ru,Safe to Send,Deliverable,5,No,Yes,mail.ru,All Campaign
3,07deepanshu@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
4,1078049354@qq.com,Safe to Send,Deliverable,5,No,Yes,qq.com,All Campaign
...,...,...,...,...,...,...,...,...
1264334,kristamajay1989@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
1264335,croan@kpmg.com.au,Safe to Send,Deliverable,5,FALSE,FALSE,<NA>,<NA>
1264336,premjeetf@rediffmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
1264337,nitijoshi56@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
1264338,energysealinc@yahoo.com,Invalid,Bounce,6,FALSE,TRUE,<NA>,<NA>

In [44]:
df_bounced.drop_duplicates(subset='EMAIL', inplace=True)
df_bounced.reset_index(drop=True, inplace=True)
df_bounced

,EMAIL,RESULT,REASON,STATUS CODE,ROLE,FREE,DOMAIN,Sheet Name
0,00001111den@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
1,007dhananjaykumbhar@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
2,0597396@mail.ru,Safe to Send,Deliverable,5,No,Yes,mail.ru,All Campaign
3,07deepanshu@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
4,1078049354@qq.com,Safe to Send,Deliverable,5,No,Yes,qq.com,All Campaign
...,...,...,...,...,...,...,...,...
1019554,kristamajay1989@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
1019555,croan@kpmg.com.au,Safe to Send,Deliverable,5,FALSE,FALSE,<NA>,<NA>
1019556,premjeetf@rediffmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
1019557,nitijoshi56@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
1019558,energysealinc@yahoo.com,Invalid,Bounce,6,FALSE,TRUE,<NA>,<NA>

In [45]:
df_push['Email'] = m.lowercase(df_push, 'Email')
m.clean_space(df_push, 'Email')

df_bounced['EMAIL'] = m.lowercase(df_bounced, 'EMAIL')
m.clean_space(df_bounced, 'EMAIL')

c:\Users\fajar\Documents\Python\Task Offline\zoho_data_app\zoho_campaign\..\main_module.py:90: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)

0                  00001111den@gmail.com
1          007dhananjaykumbhar@gmail.com
2                        0597396@mail.ru
3                  07deepanshu@gmail.com
4                      1078049354@qq.com
                       ...
1019554        kristamajay1989@gmail.com
1019555                croan@kpmg.com.au
1019556         premjeetf@rediffmail.com
1019557            nitijoshi56@gmail.com
1019558          energysealinc@yahoo.com
Name: EMAIL, Length: 1019559, dtype: string

In [46]:
df_push.loc[df_push['Email'].isin(df_bounced['EMAIL'])]

,First Name,Last Name,Email,Phone,Mobile,City,State,Country,Nationality,Lead Source,Lead Locations,Booking Status,BookRef
0,Vincent,Satish,satishvincent6294@gmail.com,+918904248017,+919243468016,BANGALORE,KARNATAKA,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2677544
1,Pawan Kumar,Gangar,fanie.gangar@gmail.com,+919911919092,+919953679365,DELHI,NEW DELHI,India,Indian,Past Guests,"Karma Sitabani, Corbett",Checked-Out,2646711
2,Umesh,Zagade,umeshzag@gmail.com,+919545922555,+919545922550,PUNE,MAHARASHTRA,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2673305
3,Devesh Prakash,Vaishnav,devesh_vaishnav@hotmail.com,+919480036806,+918105563291,BANGALORE,KARNATAKA,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2657413
4,Premjeet,Furtado,premjeetf@rediffmail.com,+918108255558,empty,MUMBAI,MAHARASHTRA,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2618917
...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,Maria,Corba,vcorba@peptalk.com.ar,+541143129516,empty,CIUDAD AUTONOMA BS AS,CF,Argentina,Argentinean,Past Guests,Karma Borgo Di Colleoli,Checked-Out,2377274
366,John,Critchley,j.critchley@hotmail.co.uk,+441204883506,empty,Bury,-,England,British,Past Guests,Karma Lake of Menteith,Checked-Out,2036204
367,Rakesh,Soni,rakeshsoni@prajhipurity.net,+918425861354,+919833170708,MUMBAI,MAHARASHTRA,India,Indian,Past Guests,Karma Royal Palms,Checked-Out,2627867
368,Jack,Weller,jack.weller@live.com,+622108410947,empty,Auckland,empty,New Zealand,empty,Past Guests,Karma Kandara,CANCELLED,KK064104
369,Nadine,Remmert,nadine.remmert@gmx.de,+4917660930047,empty,empty,empty,Germany,German,Past Guests,Karma Bavaria,CANCELLED,KB044403

In [47]:
count_empty_contact = df_push.loc[(df_push['Email'] == 'empty') &
            (df_push['Phone'] == 'empty') &
            (df_push['Mobile'] == 'empty')].shape[0]

df_push.drop(df_push.loc[(df_push['Email'] == 'empty') &
            (df_push['Phone'] == 'empty') &
            (df_push['Mobile'] == 'empty')
            ].index, inplace=True)

count_after_wash_empty_contact = df_push.shape[0]

In [48]:
# df_bounced.loc[df_bounced['EMAIL'] == 'pawan_chhikara2001@yahoo.com']

In [49]:
joined_df = pd.merge(df_push,
                     df_bounced,
                     left_on ='Email',
                     right_on ='EMAIL',
                     how ='left')
joined_df

,First Name,Last Name,Email,Phone,Mobile,City,State,Country,Nationality,Lead Source,...,Booking Status,BookRef,EMAIL,RESULT,REASON,STATUS CODE,ROLE,FREE,DOMAIN,Sheet Name
0,Vincent,Satish,satishvincent6294@gmail.com,+918904248017,+919243468016,BANGALORE,KARNATAKA,India,Indian,Past Guests,...,Checked-Out,2677544,satishvincent6294@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
1,Pawan Kumar,Gangar,fanie.gangar@gmail.com,+919911919092,+919953679365,DELHI,NEW DELHI,India,Indian,Past Guests,...,Checked-Out,2646711,fanie.gangar@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
2,Umesh,Zagade,umeshzag@gmail.com,+919545922555,+919545922550,PUNE,MAHARASHTRA,India,Indian,Past Guests,...,Checked-Out,2673305,umeshzag@gmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
3,Devesh Prakash,Vaishnav,devesh_vaishnav@hotmail.com,+919480036806,+918105563291,BANGALORE,KARNATAKA,India,Indian,Past Guests,...,Checked-Out,2657413,devesh_vaishnav@hotmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
4,Premjeet,Furtado,premjeetf@rediffmail.com,+918108255558,empty,MUMBAI,MAHARASHTRA,India,Indian,Past Guests,...,Checked-Out,2618917,premjeetf@rediffmail.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,Maria,Corba,vcorba@peptalk.com.ar,+541143129516,empty,CIUDAD AUTONOMA BS AS,CF,Argentina,Argentinean,Past Guests,...,Checked-Out,2377274,vcorba@peptalk.com.ar,Risky,Accept All,4,FALSE,FALSE,<NA>,<NA>
366,John,Critchley,j.critchley@hotmail.co.uk,+441204883506,empty,Bury,-,England,British,Past Guests,...,Checked-Out,2036204,j.critchley@hotmail.co.uk,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
367,Rakesh,Soni,rakeshsoni@prajhipurity.net,+918425861354,+919833170708,MUMBAI,MAHARASHTRA,India,Indian,Past Guests,...,Checked-Out,2627867,rakeshsoni@prajhipurity.net,Safe to Send,Deliverable,5,FALSE,FALSE,<NA>,<NA>
368,Jack,Weller,jack.weller@live.com,+622108410947,empty,Auckland,empty,New Zealand,empty,Past Guests,...,CANCELLED,KK064104,jack.weller@live.com,Safe to Send,Deliverable,5,FALSE,TRUE,<NA>,<NA>
369,Nadine,Remmert,nadine.remmert@gmx.de,+4917660930047,empty,empty,empty,Germany,German,Past Guests,...,CANCELLED,KB044403,nadine.remmert@gmx.de,Unknown,Unreachable,7,FALSE,TRUE,<NA>,<NA>

In [50]:
joined_list = joined_df.loc[~joined_df['RESULT'].isna()].copy()
joined_list.reset_index(drop=True, inplace=True)

not_exist_list = joined_df.loc[joined_df['RESULT'].isna()].copy()
not_exist_list.reset_index(drop=True, inplace=True)

count_exist_in_bounce = joined_list.shape[0]
count_not_exist_in_bounce = not_exist_list.shape[0]

In [51]:
safe_to_send = joined_list.loc[joined_list['RESULT'] == 'Safe to Send'].copy()
safe_to_send.reset_index(drop=True, inplace=True)
count_safe_to_send = safe_to_send.shape[0]

ex_safe_to_send = joined_list.loc[joined_list['RESULT'] != 'Safe to Send'].copy()
ex_safe_to_send.reset_index(drop=True, inplace=True)
count_ex_safe_to_send = ex_safe_to_send.shape[0]

In [52]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Total Data : "+str(count_total_data))
print("Jumlah Data Contact Empty : "+str(count_empty_contact))
print("Jumlah Data Setelah Wash Empty Contact : "+str(count_empty_contact))
print("Jumlah Data Exist di Database Bounce : "+str(count_exist_in_bounce))
print("Jumlah Data Tidak Exist di Database Bounce : "+str(count_not_exist_in_bounce))
print("==========================================================")
print("Summary Bounced")
print("==========================================================")
print("Jumlah Data Safe to Send : "+str(count_safe_to_send))
print("Jumlah Data not Safe to Send : "+str(count_ex_safe_to_send))

==========================================================
Summary
==========================================================
Jumlah Total Data : 370
Jumlah Data Contact Empty : 0
Jumlah Data Setelah Wash Empty Contact : 0
Jumlah Data Exist di Database Bounce : 370
Jumlah Data Tidak Exist di Database Bounce : 0
==========================================================
Summary Bounced
==========================================================
Jumlah Data Safe to Send : 331
Jumlah Data not Safe to Send : 39

In [53]:
not_exist_list.loc[not_exist_list['Email'] == 'mohdasifaliak2016@gmail.com']
# df_1.loc[df_1['EMAIL'] == 'matthew.w.giles@gmail.com']
# df_1.loc[df_1['EMAIL'] == 'venkjaya@gmail.com']
# joined_df.loc[joined_df['RESULT'] == 'Safe to Send']
# df_bounced.loc[df_bounced['EMAIL'] == ]

Empty DataFrame
Columns: [First Name, Last Name, Email, Phone, Mobile, City, State, Country, Nationality, Lead Source, Lead Locations, Booking Status, BookRef, EMAIL, RESULT, REASON, STATUS CODE, ROLE, FREE, DOMAIN, Sheet Name]
Index: []

[0 rows x 21 columns]

In [54]:
joined_df.loc[joined_df['Email'] == 'mohdasifaliak2016@gmail.com']

Empty DataFrame
Columns: [First Name, Last Name, Email, Phone, Mobile, City, State, Country, Nationality, Lead Source, Lead Locations, Booking Status, BookRef, EMAIL, RESULT, REASON, STATUS CODE, ROLE, FREE, DOMAIN, Sheet Name]
Index: []

[0 rows x 21 columns]

In [55]:
safe_to_send.replace('empty', '', inplace=True)
safe_to_send.reset_index(drop=True, inplace=True)
df_safe = safe_to_send.reindex(columns=cols)
df_safe.rename(columns={'Lead Source':'Lead Sources'}, inplace=True)

df_safe.to_csv(r'C:\Users\fajar\Documents\Python\Data\push-pastguest-formatted.csv', index=False, encoding='utf-8')

In [56]:
ex_safe_to_send.replace('empty', '', inplace=True)
ex_safe_to_send.reset_index(drop=True, inplace=True)
df_ex_safe_to_send = ex_safe_to_send.reindex(columns=cols)
df_ex_safe_to_send

df_ex_safe_to_send.to_excel(r'C:\Users\fajar\Documents\Python\Data\not-safe-to-send-debounce.xlsx', index=False)

In [58]:
not_exist_list.replace('empty', '', inplace=True)
not_exist_list.reset_index(drop=True, inplace=True)
df_not_exist = not_exist_list.reindex(columns=cols)
df_not_exist

df_not_exist.to_excel(r'C:\Users\fajar\Documents\Python\Data\not-exist-debounce.xlsx', index=False)