In [1]:
import pandas as pd
import re
import numpy as np
import openpyxl

import sys
sys.path.append('../../zoho_data_app/')

import main_module as m
import zoho_filter_module as fil

%load_ext autoreload
%autoreload 2

In [2]:
path = r'C:\Users\fajar\Documents\Python\Data\Arrival List Raw\BG INDO ARRIVAL LIST 2022.xlsx'
xl = pd.ExcelFile(path)
sheets = xl.sheet_names  # see all sheet names
sheets

['Old Cancel - Dec 2019',
 'CANCEL VOLCANO',
 'CANCEL',
 'CANCEL AS OPENDATE',
 'TSR Analysis Sep 22',
 'Feb 23',
 'Jan 23',
 'Dec 22',
 'Nov 22',
 'Oct 22',
 'Sep 22',
 'Aug 22',
 'July 22',
 'June 22',
 'May 22',
 'Apr 22',
 'Mar 22',
 'FEB 22',
 'JAN 22',
 'Dec 21',
 'Sheet5',
 'Sheet6']

In [3]:
delete_sheets = [
    'Old Cancel - Dec 2019',
    'CANCEL VOLCANO', 
    'CANCEL',
    'CANCEL AS OPENDATE', 
    'TSR Analysis Sep 22',
    'Sheet5', 
    'Sheet6'
]

arr = np.array(sheets)
# arr = np.delete(arr, delete_sheets)

sheet_will_be_used = []

for i in sheets:
    sheets_name = i
    result = np.isin(sheets_name, delete_sheets)
    if result == True:
        print('take out sheets ' + sheets_name)
    else:
        print('add sheets' + sheets_name)
        sheet_will_be_used.extend([sheets_name])

# arr

take out sheets Old Cancel - Dec 2019
take out sheets CANCEL VOLCANO
take out sheets CANCEL
take out sheets CANCEL AS OPENDATE
take out sheets TSR Analysis Sep 22
add sheetsFeb 23
add sheetsJan 23
add sheetsDec 22
add sheetsNov 22
add sheetsOct 22
add sheetsSep 22
add sheetsAug 22
add sheetsJuly 22
add sheetsJune 22
add sheetsMay 22
add sheetsApr 22
add sheetsMar 22
add sheetsFEB 22
add sheetsJAN 22
add sheetsDec 21
take out sheets Sheet5
take out sheets Sheet6

In [4]:
def load_data_multiple(dir_path, sheet_will_be_used, cols):

    import os

    count = 0
    frames = []

    for i in sheet_will_be_used:
        print('Compiling sheets '+i+' On progress')
        count += 1
        globals()['df%s' % count] = pd.read_excel(path, dtype='string', sheet_name=i, index_col=None, header=None)
        globals()['new_df_start_segment%s' % count] = globals()['df%s' % count].loc[globals()['df%s' % count][0] == 'NO.'].index.values.astype(int)[0]
        globals()['new_df_end_segment%s' % count] = globals()['df%s' % count].shape[0]

        globals()['new_df%s' % count] = globals()['df%s' % count].iloc[globals()['new_df_start_segment%s' % count]:globals()['new_df_end_segment%s' % count]].reset_index().copy()
        globals()['new_df%s' % count].columns = globals()['new_df%s' % count].iloc[0]
        globals()['new_df%s' % count].drop([0,0], inplace=True)
        globals()['arr_df%s' % count] = globals()['new_df%s' % count][cols].loc[~globals()['new_df%s' % count]['NO.'].isna()].copy()
        globals()['arr_df%s' % count].reset_index(inplace=True)
        globals()['arr_df%s' % count].drop(globals()['arr_df%s' % count].columns[[0]],axis = 1, inplace=True)
        globals()['arr_df%s' % count]['Sheet Name'] = i
        frames.append(globals()['arr_df%s' % count])

    result = pd.concat(frames, ignore_index=True)
    return result

In [5]:
cols = ['NO.', 
        'Programme', 
        'Nationality',
        'Region',
        'Client Name', 
        'Email Address', 
        'Phone Number',
        'Check in',
        'Check out']

df = load_data_multiple(path, sheet_will_be_used, cols)
df

Compiling sheets Feb 23 On progress
Compiling sheets Jan 23 On progress
Compiling sheets Dec 22 On progress
Compiling sheets Nov 22 On progress
Compiling sheets Oct 22 On progress
Compiling sheets Sep 22 On progress
Compiling sheets Aug 22 On progress
Compiling sheets July 22 On progress
Compiling sheets June 22 On progress
Compiling sheets May 22 On progress
Compiling sheets Apr 22 On progress
Compiling sheets Mar 22 On progress
Compiling sheets FEB 22 On progress
Compiling sheets JAN 22 On progress
Compiling sheets Dec 21 On progress

,NO.,Programme,Nationality,Region,Client Name,Email Address,Phone Number,Check in,Check out,Sheet Name
0,1,Re-Marketing,Indonesian,SLeman,"Ong Hok San Sonny & Inge Setiawaty, SE",kikir_wati@yahoo.com,081285828482,2023-02-07 00:00:00,2023-02-10 00:00:00,Feb 23
1,1,FB Ads,Indonesian,Bogor,Mashendra & Maya Astuti,mayahendra@yahoo.co.id,081322855687,2023-01-01 00:00:00,2023-01-04 00:00:00,Jan 23
2,2,FB Ads,Indonesian,Surabaya,"Yudhi Eko Prasetyo & Maria Agnes Cendrawati, SE",yudhi@outlook.com,08123182180,2023-01-01 00:00:00,2023-01-04 00:00:00,Jan 23
3,3,Re-Marketing,Indonesian,Banyuwangi,"Kurniawan Adiputra, SP & Ervy Shandear, SP",ervyshandear26@gmail.com,082336618821,2023-01-01 00:00:00,2023-01-04 00:00:00,Jan 23
4,4,FB Ads ZF_00228905,Indonesian,Jakarta Selatan,Dedi Rihaldi Huspa & Pitut Aprilia Savitri,pitut_a@yahoo.com,08161999318,1-Jan-23 1-Jan-23,4-Jan-23 3-Jan-23,Jan 23
...,...,...,...,...,...,...,...,...,...,...
2194,196,Facebook Comp,Indonesian,Jakarta Pusat,Leonardo Cajady & Catherine Widianto,leonardo.cajadi@gmail.com,08161159887,2021-12-30 00:00:00,2022-01-02 00:00:00,Dec 21
2195,197,Referral,Indonesian,Jombang,Steven Christianto Gunawan SE & Levina Hanhout...,pheng_innamorata@yahoo.com,081330008899,2021-12-30 00:00:00,2022-01-02 00:00:00,Dec 21
2196,198,Facebook Comp,Indonesian,Jakarta Timur,Efendi T. Bolon & Dr. Shinta VR. Hutajulu,shintavera12@gmail.com,081513540005,2021-12-30 00:00:00,2022-01-02 00:00:00,Dec 21
2197,199,EDM,Indonesian,Pekanbaru,Hidayat & Titi Lasmini,thdayat090@gmail.com,082285105305,2021-12-30 00:00:00,2022-01-02 00:00:00,Dec 21
2198,200,Landing Page,Indonesian,Mimika,Herry Wijaya & Helmi Sitanajah,wijayaheri62@yahoo.co.id,0811497488,2021-12-30 00:00:00,2022-01-02 00:00:00,Dec 21

In [6]:
# df = pd.read_excel(path, dtype='string', sheet_name='Nov 22', index_col=None, header=None)
# df

In [7]:
# cols = ['NO.', 
#         'Programme', 
#         'Nationality',
#         'Region',
#         'Client Name', 
#         'Email Address', 
#         'Phone Number',
#         'Check in',
#         'Check out']

# # mencari nomor row index untuk memulai compile data
# start_segment = df.loc[df[0] == 'NO.'].index.values.astype(int)[0]
# end_segment = df.shape[0]

# new_df = df.iloc[start_segment:end_segment].reset_index().copy()
# new_df.columns = new_df.iloc[0]
# new_df.drop([0,0], inplace=True)
# arr_df = new_df[cols].loc[~new_df['NO.'].isna()].copy()
# arr_df.reset_index(inplace=True)
# arr_df.drop(arr_df.columns[[0]],axis = 1, inplace=True)
# arr_df

In [8]:
# arr_df.loc[~arr_df['Check in'].str.contains('00:00:00')]

In [9]:
df.loc[~df['Check in'].str.contains('00:00:00')]

,NO.,Programme,Nationality,Region,Client Name,Email Address,Phone Number,Check in,Check out,Sheet Name
4,4,FB Ads ZF_00228905,Indonesian,Jakarta Selatan,Dedi Rihaldi Huspa & Pitut Aprilia Savitri,pitut_a@yahoo.com,08161999318,1-Jan-23 1-Jan-23,4-Jan-23 3-Jan-23,Jan 23
106,106,Re-Marketing,Indonesian,Jakarta Utara,Muljadi Wongsonegoro & Lina Sutjiatmadja,linachia99@gmail.com,081219666777,13-Jan-23 14-Jan-23,14-Jan-23 16-Jan-23,Jan 23
179,179,FB Ads,Indonesian,Banyuwangi,Agus Imam Santoso & Imi Jamilah,ahmadhamidi1874@gmail.com,085258636374,22-Jan-23 22-Jan-23,24-Jan-23 25-Jan-23,Jan 23
306,39,Re-Marketing,Indonesian,Jakarta Barat,Marsito & Ivana Waty,ing_boing@yahoo.com,089687678392,9-Dec-22 10-Dec-22,10-Dec-22 12-Dec-22,Dec 22
309,42,Facebook Comp,Indonesian,Jakarta,"Dicky H.W Pitoy, MBA & Dedek",ongsiaolian79@yahoo.com,081218621509,9-Dec-22 10-Dec-22,10-Dec-22 12-Dec-22,Dec 22
...,...,...,...,...,...,...,...,...,...,...
2088,90,Facebook Ads S&W ZF_0012804,Indonesian,Jakarta Barat,Ady Wijaya & Jean Chisca Jingga,yangin_blue@yahoo.com,0818997098,15-Dec-21 17-Dec-21,17-Dec-21 18-Dec-21,Dec 21
2119,121,SMS,Indonesian,Bandung,Krisdianto Gunawan & Diana Heryanti,d33varo@gmail.com,085722557570,18-Dec-21 20-Dec-21,20-Dec-21 21-Dec-21,Dec 21
2137,139,Facebook Com ZF_0036819,Indonesian,Yogyakarta,Vicky Affandi & Amelia Handoko,vi.melz88@gmail.com,082218102080,20-Dec-21 21-Dec-21,21-Dec-21 23-Dec-21,Dec 21
2159,161,SMS,Indonesian,Jakarta Timur,Joddy Purnama Hadi & RR Ayu Sawitri,joddyph@yahoo.com,0811184867,24-Dec-21 25-Dec-21,25-Dec-21 27-Dec-21,Dec 21
2163,165,EDM,Indonesian,Subang,Anton Wijaya & Rian Aryanti,anton.wijaya.aw85@gmail.com,082121114785,25-Dec-21 27-Dec-21,27-Dec-21 28-Dec-21,Dec 21

In [10]:
df.rename(columns = {'NO.':'Sheet Row No.'}, inplace = True)

In [11]:
# df.to_excel(r'C:\Users\fajar\Documents\Python\Data\Arrival List Raw\Compile Arrival\BG INDO ARRIVAL LIST 2022-compile.xlsx', index=False)