In [4]:
import os
import pandas as pd
import re
 
# Get the list of all files and directories
# dir_path = "C://Users//Vanshi//Desktop//gfg"
dir_path = r"C:\Users\fajar.fatoni\Documents\Python\Data\Member Data\vp\report 119 all details\17 Mar\compile"

# dir_list = os.listdir(dir_path)
 
# print("Files and directories in '", dir_path, "' :")
 
# # prints all files
# print(dir_list)

frames = []

# itterate file di dalam directory
for path in os.listdir(dir_path):

    # cek apakah di dalam directory ada file
    if os.path.isfile(os.path.join(dir_path, path)):
        if ".xlsx" in path:
            print(path)
            df = pd.read_excel(dir_path+'\\'+path, dtype='string')
            df['filename'] = path
            frames.append(df)

        if ".csv" in path:
            print(path)
            df = pd.read_csv(dir_path+'\\'+path, dtype='string', on_bad_lines='skip')
            df['filename'] = path
            frames.append(df)
    else:
        print('file doesn\'t exist')

result = pd.concat(frames, ignore_index=True)
result

119 - kcb.xlsx
119 - kci.xlsx

,Account ID,ContactID,FirstName,LastName,AddressLine1,AddressLine2,Town,City,Country,Post Code,...,No_Concierge_EDM,No_Events_EDM,No_Community_EDM,No_MC_EDM,CreateDateTime,Modified By,Modified Date,KC EDM Received,Preferred Communication Method,filename
0,1000056,921274,Yohanes,Mustamu,WELLINGTON RESIDENCE BLOK A1,"RT. 009/009 BENDA BARU, PAMULANG",TANGERANG SELATAN,BANTEN,Indonesia,15417,...,<NA>,<NA>,<NA>,<NA>,<NA>,Jessica Whytcross (vp5),2024-11-25 14:22:07,YES,<NA>,119 - kcb.xlsx
1,1000056,921301,Jane,Chrisdianty,WELLINGTON RESIDENCE BLOK A1,"RT. 009/009 BENDA BARU, PAMULANG",TANGERANG SELATAN,BANTEN,Indonesia,-,...,<NA>,<NA>,<NA>,<NA>,<NA>,Karma Website (api2),2023-11-15 15:31:30,YES,<NA>,119 - kcb.xlsx
2,1000056,921274,Yohanes,Mustamu,WELLINGTON RESIDENCE BLOK A1,"RT. 009/009 BENDA BARU, PAMULANG",TANGERANG SELATAN,BANTEN,Indonesia,15417,...,<NA>,<NA>,<NA>,<NA>,<NA>,Jessica Whytcross (vp5),2024-11-25 14:22:07,YES,<NA>,119 - kcb.xlsx
3,1000109,921347,Willy Stevan Berny,Suak,"JL. KEMBANG NO 59, SARIO KOTA BARU",<NA>,MANADO,SULAWESI UTARA,Indonesia,95114,...,<NA>,<NA>,<NA>,<NA>,<NA>,Haritha Subramani (vp1846),2024-11-13 18:25:41,<NA>,<NA>,119 - kcb.xlsx
4,1000109,921354,Cecilia Ingrid,Tjan,"JL. KEMBANG NO 59, SARIO KOTA BARU",<NA>,MANADO,SULAWESI UTARA,Indonesia,95114,...,<NA>,<NA>,<NA>,<NA>,<NA>,Haritha Subramani (vp1846),2024-11-13 18:25:51,<NA>,<NA>,119 - kcb.xlsx
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99444,53032,57165,Samuel,Jacob,"#12, MARUTHI MEADOWS CROSSOPP","S.A.B.C. GATE, KOTHANUR",BENGALURU,KARNATAKA,India,560 077,...,<NA>,<NA>,<NA>,<NA>,<NA>,Karma Website (api2),2024-01-04 19:16:43,YES,<NA>,119 - kci.xlsx
99445,53044,57178,M. Anand,Krishna,"ARCHITHA AITHAL AAROHI APARTMENT, FLAT#403","SRI THIRUCHI MAHASWAMY ROAD, RAJARAJESHWARI NAGAR",BENGALURU,KARNATAKA,India,560098,...,<NA>,<NA>,<NA>,<NA>,<NA>,Karma Website (api2),2024-01-04 19:18:14,<NA>,<NA>,119 - kci.xlsx
99446,53044,183697,K.N. Savitha,Anand,"ARCHITHA AITHAL AAROHI APARTMENT, FLAT #403,","SRI THIRUCHI MAHASWAMY ROAD, RAJARAJESWARI NAGAR",BENGALURU,KARNATAKA,India,560098,...,<NA>,<NA>,<NA>,<NA>,<NA>,Karma Website (api2),2024-01-04 19:18:16,<NA>,<NA>,119 - kci.xlsx
99447,53044,934334,Akshatha,Anand,"ARCHITHA AITHAL AAROHI APARTMENT, FLAT #403,","SRI THIRUCHI MAHASWAMY ROAD, RAJARAJESWARI NAGAR",BENGALURU,KARNATAKA,India,560098,...,<NA>,<NA>,<NA>,<NA>,<NA>,Karma Website (api2),2024-01-04 19:18:17,<NA>,<NA>,119 - kci.xlsx
99448,53044,934335,Sharvari,Anand,"ARCHITHA AITHAL AAROHI APARTMENT, FLAT #403,","SRI THIRUCHI MAHASWAMY ROAD, RAJARAJESWARI NAGAR",BENGALURU,KARNATAKA,India,560098,...,<NA>,<NA>,<NA>,<NA>,<NA>,Karma Website (api2),2024-01-04 19:18:18,<NA>,<NA>,119 - kci.xlsx

In [5]:
df = result.loc[
    (result['Primary'] == 'Primary') &
    (~result['Country'].str.contains('Australia|Indonesia', regex=True, flags=re.I))
    ].copy()

In [7]:
result.to_excel(r'C:\Users\fajar.fatoni\Documents\Python\Data\Member Data\vp\report 119 all details\17 Mar\compile\df_member.xlsx', index=False)
df.to_excel(r'C:\Users\fajar.fatoni\Documents\Python\Data\Member Data\vp\report 119 all details\17 Mar\compile\df_member_primary(exclude ID & AU).xlsx', index=False)