In [12]:
import main_module as m
import zoho_filter_module as fil
import pandas as pd
import re
import numpy as np
import openpyxl

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [13]:
path = r'C:\Users\fajar\Documents\Python\Data\GUEST EXIT_ SEAP 2022-NEW.xlsx'
df_guest_exit = pd.read_excel(path, dtype='string', sheet_name='Progress')

In [14]:
path = r'C:\Users\fajar\Documents\Python\Data\Arrival List Edited Toni.xlsx'
df_phone = pd.read_excel(path, dtype='string', sheet_name='Master Dedup Phone')

path = r'C:\Users\fajar\Documents\Python\Data\Arrival List Edited Toni.xlsx'
df_email = pd.read_excel(path, dtype='string', sheet_name='Master Dedup Email')

# ====================== Awal Filter Umum ======================

In [15]:
# data phone, mobile dam email member yang ada di master data (wash member)

m.clean_number(df_guest_exit, 'Phone')
m.clean_number(df_guest_exit, 'Phone 2')
m.replace_not_valid_to_empty(df_guest_exit, 'Phone')
m.replace_not_valid_to_empty(df_guest_exit, 'Phone 2')

df_guest_exit['Primary_Email'] = m.lowercase(df_guest_exit, 'Primary_Email')
m.clean_space(df_guest_exit, 'Primary_Email')

df_guest_exit['Primary_Email2'] = m.lowercase(df_guest_exit, 'Primary_Email2')
m.clean_space(df_guest_exit, 'Primary_Email2')

m.clean_number(df_phone, 'Mobile')

df_email['Email'] = m.lowercase(df_email, 'Email')
m.clean_space(df_email, 'Email')

0       initial.d.martin@gmail.com
1        yennysitongan13@gmail.com
2           jimmytjugito@gmail.com
3         budisuroso2777@gmail.com
4           yandoank1707@gmail.com
                   ...
1211    johnson.fraser@yahoo.co.uk
1212       ridwanbu2603@icloud.com
1213            arsyati6@gmail.com
1214          jazzysuryo@gmail.com
1215           mumsy9851@gmail.com
Name: Email, Length: 1216, dtype: string

In [16]:
find_member_booking = df_guest_exit.copy()

# find_member_booking.fillna('empty', inplace=True)


find_member_booking.loc[find_member_booking['Phone'].isin(df_phone['Mobile']), 'Same Value Find Booking'] = 'Booking-Mobile'
find_member_booking.loc[find_member_booking['Phone 2'].isin(df_phone['Mobile']), 'Same Value Find Booking'] = 'Booking-Mobile' 

find_member_booking.loc[find_member_booking['Primary_Email'].isin(df_email['Email']), 'Same Value Find Booking'] = 'Booking-Email'
find_member_booking.loc[find_member_booking['Primary_Email2'].isin(df_email['Email']), 'Same Value Find Booking'] = 'Booking-Email'


find_member_booking.fillna('empty', inplace=True)

find_member_booking.drop(find_member_booking.loc[find_member_booking['Same Value Find Booking'] == 'empty'].index, inplace=True)

count_booking_dedup = find_member_booking.loc[find_member_booking['Same Value Find Booking'].str.contains('Booking',  regex=True)].shape[0]

find_member_booking.replace('empty', '', inplace=True)

find_member_booking.to_excel(r'C:\Users\fajar\Documents\Python\Data\booking-dedup.xlsx', index=False)

#find_member_booking.loc[find_member_booking['Same Value Find'] == 'Booking-Phone1']

In [17]:
df_guest_exit['HAS A FUTURE BOOKING'] = 'NO'

df_guest_exit.loc[

    df_guest_exit['Phone'].isin(df_phone['Mobile']) |
    df_guest_exit['Phone 2'].isin(df_phone['Mobile']) | 
    df_guest_exit['Primary_Email'].isin(df_email['Email'])|
    df_guest_exit['Primary_Email2'].isin(df_email['Email']),
'HAS A FUTURE BOOKING'
] = 'YES'

In [18]:
df_guest_exit.columns

Index(['SALES APP profile_id', 'Tour_Date', 'Sales Venue', 'Group_Venue',
       'Primary_Fname', 'Primary_Lname', 'Primary_Nationality', 'Phone',
       'Phone 2', 'Primary_Email', 'Primary_Email2', 'Profile_Address_Line1',
       'Profile_Address_city', 'Profile_Address_Postcode',
       'Profile_Address_State', 'Profile_Address_Country',
       'Tour_Details_Qualified_Status', 'Tour_Details_Guest_Status',
       'Profile_Stay_Resort_Name', 'IS A MEMBER', 'HAS A FUTURE BOOKING'],
      dtype='object')

In [19]:
df_guest_exit.replace('empty', '', inplace=True)
df_guest_exit

,SALES APP profile_id,Tour_Date,Sales Venue,Group_Venue,Primary_Fname,Primary_Lname,Primary_Nationality,Phone,Phone 2,Primary_Email,...,Profile_Address_Line1,Profile_Address_city,Profile_Address_Postcode,Profile_Address_State,Profile_Address_Country,Tour_Details_Qualified_Status,Tour_Details_Guest_Status,Profile_Stay_Resort_Name,IS A MEMBER,HAS A FUTURE BOOKING
0,IVO20227045,2022-10-01 00:00:00,JIMBARAN SALES DECK,COLDLINE,PAOLO,MOUSTACHE,SEYCHELLOIS,2482525268,<NA>,p_moustache@yahoo.com,...,<NA>,<NA>,<NA>,<NA>,SEYCHELLES,Cat 2,Qualified,GRAND INA KUTA,NO,YES
1,IVO20226633,2022-09-18 00:00:00,JIMBARAN SALES DECK,COLDLINE,CHADI,EL SERRY,LEBANESE,9613040374,<NA>,chady.serry@gmail.com,...,<NA>,<NA>,<NA>,<NA>,LEBANON,Cat 2,Qualified,VILLA KAYU RAJA,NO,NO
2,IVO20226734,2022-09-21 00:00:00,JIMBARAN SALES DECK,COLDLINE,PEKKA,LAMMI,FINNISH,3585905907,<NA>,pekka.lammi1@gmail.com,...,<NA>,<NA>,<NA>,<NA>,FINLAND,<NA>,Non Qualified,TIRTHA CANGGU SUITE,NO,NO
3,IVO20228806,2022-12-01 00:00:00,JIMBARAN SALES DECK,COLDLINE,BEE KIAT,HO,SINGAPOREAN,656634752,<NA>,librakiat@gmail.com,...,<NA>,<NA>,<NA>,<NA>,SINGAPORE,Cat 2,Qualified,HOLIDAY INN EXPRESS,NO,NO
4,IVO20225826,2022-08-28 00:00:00,JIMBARAN SALES DECK,COLDLINE,ZAHEEM,ABDULLA,MALDIVIAN,9607933303,<NA>,zahyy42@hotmail.com,...,<NA>,<NA>,<NA>,<NA>,MALDIVES,Cat 2,Qualified,ANANTA LEGIAN,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8204,IVO20229595,2022-12-27 00:00:00,JIMBARAN SALES DECK,FLYBUY,TROY,HARPER,AUSTRALIAN,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,AUSTRALIA,Q,Qualified,EPISODE,NO,NO
8205,IVO20229597,2022-12-27 00:00:00,JIMBARAN SALES DECK,FLYBUY,ROSHAN,GILL,AUSTRALIAN,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,AUSTRALIA,<NA>,Garden Party,MELASTI,NO,NO
8206,IVO20229591,2022-12-27 00:00:00,JIMBARAN SALES DECK,FLYBUY,RONI,HANDOKO,INDONESIAN,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,INDONESIA,Q,Qualified,BEDROCK,NO,NO
8207,IVO20229593,2022-12-27 00:00:00,JIMBARAN SALES DECK,FLYBUY,CANDRA,NEGARA,INDONESIAN,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,INDONESIA,Q,Qualified,EDEN,NO,NO
8208,IVO20229596,2022-12-27 00:00:00,JIMBARAN SALES DECK,FLYBUY,MICHAEL,BRADY,AUSTRALIAN,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,AUSTRALIA,Q,Qualified,MELASTI,NO,NO

In [20]:
# print("==========================================================")
# print("Summary")
# print("==========================================================")
# print("Jumlah Keseluruhan Master Zoho : "+str(count_data_awal))
# print("Jumlah Filter Leads Awal : "+str(count_filter_awal))
# print("Jumlah Format Email Salah : "+str(count_deleted_wrong_fromat))
# print("Jumlah Setelah Clean Format Email Salah : "+str(count_after_deleted_wrong_format))
# print("Jumlah Email OTA : "+str(count_email_OTA))
# print("Jumlah Setelah Clean Email OTA : "+str(count_after_clean_OTA))
# print("Jumlah Duplicate (Phone, Mobile dan Email) : "+str(count_duplicate_general))
# print("Jumlah Setelah Clean Duplicate : "+str(count_after_dedup_duplicate))
# print("Jumlah Wash Booking dan Member : "+str(count_wash_member))
# print("Jumlah Setelah Wash Member : "+str(count_after_wash_member))

# ====================== Akhir Filter Umum ======================

In [21]:
df_guest_exit.replace('empty', '', inplace=True)
# df_guest_exit.to_excel(r'C:\Users\fajar\Documents\Python\Data\guest_exit_booking.xlsx', index=False)
df_guest_exit.to_csv(r'C:\Users\fajar\Documents\Python\Data\guest_exit_booking.csv', index=False)