In [269]:
import main_module as m
import zoho_filter_module as fil
import pandas as pd
import re
import numpy as np

%load_ext autoreload
%autoreload 2

dir_path = r'C:\Users\fajar\Documents\Python\Data\Zoho_Backup'
file_name = '\Leads_'

cols = ['Record Id',	
'Created Time',
'Created Date',	
'First Name',	
'Last Name',	
'Email',	
'Phone',	
'Mobile',	
'Birthdate',	
'Year of Birth',
'Street',	
'Street2',	
'City',	
'State',	
'Country',	
'Nationality',
'Booking Status', 
'BookRef',
'Departure Date',	
'Arrival Date',	
'Card Type',	
'Marital Status',	
'Lead Brand',	
'Lead Sub-Brand',	
'Lead Source',	
'Lead Locations',	
'Lead Source Description',	
'Lead Regions',
'Lead Status',
'Email Opt Out',	
'Opt In']

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [270]:
df = m.load_data_multiple(dir_path, file_name, cols)
count_data_awal = df.shape[0]
df = df.reindex(columns=cols)
df.shape[0]

df['Created Time'] = pd.to_datetime(df['Created Time'], format='%Y-%m-%d %H:%M:%S')
df.dtypes

Record Id                          string
Created Time               datetime64[ns]
Created Date                       string
First Name                         string
Last Name                          string
Email                              string
Phone                              string
Mobile                             string
Birthdate                          string
Year of Birth                      string
Street                             string
Street2                            string
City                               string
State                              string
Country                            string
Nationality                        string
Booking Status                     string
BookRef                            string
Departure Date                     string
Arrival Date                       string
Card Type                          string
Marital Status                     string
Lead Brand                         string
Lead Sub-Brand                     string
Lead Source                        string
Lead Locations                     string
Lead Source Description            string
Lead Regions                       string
Lead Status                        string
Email Opt Out                      string
Opt In                             string
dtype: object

In [271]:
path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04eXpvS1NXTWF2RVE\_BOOKING\Booking By Year\FlyBuy Booking Data (BGAU & BGID & KE).xlsx'
df_booking = pd.read_excel(path, dtype='string', sheet_name='booking Start feb 2021')

path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04UUNBME5GOVhoMjA\_ODYSSEY\Phone Members.xlsx'
df_phone = pd.read_excel(path, dtype='string', sheet_name='Sheet1')

path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04UUNBME5GOVhoMjA\_ODYSSEY\Email Members.xlsx'
df_email = pd.read_excel(path, dtype='string', sheet_name='Sheet1')

In [272]:
zoho_filter = fil.user_req(df)
zoho_df = df.loc[zoho_filter].copy() # menggunakan copy untuk menghindari setting copy warning
zoho_df.reset_index(drop=True, inplace=True)
count_filter_awal = zoho_df.shape[0]

# mengisi kolom <NA> dengan value string 'empty' supaya mudah mengecek data member dan booking dengan isin

zoho_df.fillna('empty', inplace=True)
zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Marital Status,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In
0,zcrm_3584690000426781936,2023-02-06 13:12:19,empty,Kamna,Kapoor,kamna.kapoor@yarratrams.com.au,61466947313,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Royal Candidasa,Viewpoint,empty,empty,false,true
1,zcrm_3584690000426927090,2023-02-06 13:17:14,empty,Sarah,Noller,sarah@noller.id.au,61450429274,61450429274,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Royal Sanur,Viewpoint,empty,empty,false,true
2,zcrm_3584690000426932041,2023-02-06 13:16:48,empty,John,Major,majorbricks54@gmail.com,61406397873,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Royal Candidasa,Viewpoint,empty,empty,false,true
3,zcrm_3584690000426935052,2023-02-06 13:17:43,empty,Nathan,Claypole,claypole.nathan@gmail.com,61430188682,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Royal Jimbaran,Viewpoint,empty,empty,false,true
4,zcrm_3584690000428132582,2023-02-13 15:18:13,empty,Paul,Kottos,paulkottos@gmail.com,61414908909,61414908909,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,empty,empty,false,true
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,zcrm_3584690000439838156,2023-04-10 12:52:55,empty,Kelvin,Tjia,ktjia.kt@gmail.com,6181510539008,6181510539008,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,empty,empty,false,true
175,zcrm_3584690000439839377,2023-04-10 13:01:29,empty,Sonya,Stephens,molly2410@icloud.com,61438490055,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Song Hoai,Viewpoint,empty,empty,false,true
176,zcrm_3584690000439840143,2023-04-10 12:53:41,empty,Randhir,Kowlessur,australia@luckydodomigration.com,6193052167,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,empty,empty,true,false
177,zcrm_3584690000439840661,2023-04-10 13:03:12,empty,Lisa Marie,O'Donnell,lisaodonnell@email.com,61414445510,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Bavaria,Viewpoint,empty,empty,false,true
178,zcrm_3584690000439852124,2023-04-10 13:02:33,empty,Nicola,Bartley,nicola_ny@hotmail.com,61431410910,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Song Hoai,Viewpoint,empty,empty,false,true

# ====================== Awal Filter Umum ======================

In [273]:
# data phone, mobile dam email member yang ada di master data (wash member)

m.clean_number(zoho_df, 'Phone')
m.clean_number(zoho_df, 'Mobile')
m.replace_not_valid_to_empty(zoho_df, 'Phone')
m.replace_not_valid_to_empty(zoho_df, 'Mobile')
zoho_df['Email'] = m.lowercase(zoho_df, 'Email')
m.clean_space(zoho_df, 'Email')

m.clean_number(df_booking, 'Phone1')
m.clean_number(df_booking, 'Mobile')
df_booking['Email'] = m.lowercase(df_booking, 'Email')
m.clean_space(df_booking, 'Email')

m.clean_number(df_phone, 'Mobile')

df_email['Email'] = m.lowercase(df_email, 'Email')
m.clean_space(df_email, 'Email')

count_deleted_wrong_format = m.delete_email_wrong_format(zoho_df, 'Email')
count_after_deleted_wrong_format = zoho_df.shape[0]

In [274]:
path = r'C:\Users\fajar\Documents\Python\Data\dedup_aunz.xlsx'
df_aunz = pd.read_excel(path, dtype='string', sheet_name='Sheet1')

# data phone, mobile dam email member yang ada di master data 
count_wash_prev = zoho_df.loc[
    zoho_df['Record Id'].isin(df_aunz['Record Id']) 
].shape[0]

count_wash_prev

40

In [275]:
zoho_df.drop(zoho_df.loc[
    zoho_df['Record Id'].isin(df_aunz['Record Id']) 
].index, inplace=True)
df.reset_index(drop=True, inplace=True)

count_after_wash_aunz = zoho_df.shape[0]

In [276]:
# Cek leads test
test_leads = zoho_df.loc[
    
        zoho_df['Email'].str.contains('^test@', flags=re.I, regex=True) |
        zoho_df['Email'].str.contains('\+test', flags=re.I, regex=True) |
    
        zoho_df['First Name'].str.contains('^test$', flags=re.I, regex=True) |
        zoho_df['Last Name'].str.contains('^test$', flags=re.I, regex=True) |

        zoho_df['First Name'].str.contains('test 1', flags=re.I, regex=True) |
        zoho_df['Last Name'].str.contains('test 2', flags=re.I, regex=True)|
        zoho_df['First Name'].str.contains('test1', flags=re.I, regex=True) |
        zoho_df['Last Name'].str.contains('test2', flags=re.I, regex=True)|

        zoho_df['First Name'].str.contains(' test ', flags=re.I, regex=True) | 
        zoho_df['Last Name'].str.contains(' test ', flags=re.I, regex=True) | 
        zoho_df['Last Name'].str.contains(' test$', flags=re.I, regex=True)
    ]

count_leads_test = test_leads.shape[0]

# test_leads.to_excel(r'C:\Users\fajar\Documents\Python\Data\test_leads_2.xlsx', index=False)
test_leads

Empty DataFrame
Columns: [Record Id, Created Time, Created Date, First Name, Last Name, Email, Phone, Mobile, Birthdate, Year of Birth, Street, Street2, City, State, Country, Nationality, Booking Status, BookRef, Departure Date, Arrival Date, Card Type, Marital Status, Lead Brand, Lead Sub-Brand, Lead Source, Lead Locations, Lead Source Description, Lead Regions, Lead Status, Email Opt Out, Opt In]
Index: []

[0 rows x 31 columns]

In [277]:
zoho_df.drop(test_leads.index, inplace=True)
zoho_df.reset_index(drop=True, inplace=True)

count_after_dedup_test = zoho_df.shape[0]

In [278]:
# Cek Email Karma
email_karma = m.find_karma(zoho_df, 'Email')
count_email_karma = email_karma.shape[0]
# email_OTA.to_excel(r'C:\Users\fajar\Documents\Python\Data\email_OTA.xlsx', index=False)

email_karma

johnspence88@hotmail\.com|baligetaway|rottnestlodge\.com\.au|hotel\.discount|balirewardscard\.com|conceptvenues\.com|discoverkarma\.com|discoveryourkarma\.com|geales\.com|haathimahal\.com|adimahkota\.com|baligetaway\.co\.id|baligetaway\.com\.au|catkingproductions\.com|complementarystay-karmaexperience\.com|confirmation-karmaexperience\.com|tiketmurahbali\.com|karmasanctumsoho\.co|experiencekarmaclub\.com|karmabavaria\.com|karmabeach\.com|karmaclub\.com|karmadevelopments\.com|karmaestates\.com|karmaexperience\.co\.uk|karmaexperience\.com|karmaexperience\.in|karmagroup\.com|karmajimbaran\.com|karmakandara\.com|karmaminoan\.com|karmanormandy\.com|karmapelikanos\.com|karmareef\.com|karmaresorts\.com|karmaroyalexperience\.co\.uk|karmaroyalexperience\.com|karmaroyalgroup\.com|karmaroyalvacations\.com|karmasalak\.com|karmasalfordhall\.com|karmastmartins\.com|karmgroup\.com|krresidences\.com|lepreverger\.com|odysseypremier\.com|rci\.com|thebaligetaway\.comkarmarottnest\.com\.au|karmasanctumonthegreen\.com|karmasanctumclub\.com|balifreestay\.com|karma25\.com|karmarottnest\.com\.au|karmasanctumsoho\.com|karmaroyalpromotions\.com|justclickbali\.com|karmaapsara\.com|karmabahamas\.com|karmaborgodicolleoli\.com|karmacamino\.com|karmaclub\.community|karmaclubhouse\.club|karmaclubhouse\.com|karma-concierge|karmaconcierge|karmaconstellation\.com|karmadestinations\.com|karmaexperiences\.com|karmaexperiences\.com|karmagroupreviews\.com|karmakasa|karmalaherizza|karmamargaretriver\.com|karmamayura\.com|karmaminoan\.com|karmamykonos\.com|karmapassport\.com|karmaprivilege\.com|karmaprivileges\.com|karmaresortdestinations\.com|karmarestaurants\.com|karmaroyalbellavista\.com|karmaroyalboatlagoon\.com|karmaroyalresidences\.com|karmasanctum\.com|karmasanctumspa\.com|karmaspa\.com|karmaspas\.com|karmastmartin\.com|karmaubud\.com|karmawinery\.com|krgstorage\.com|mykarmaconcierge\.com|odysseykarma\.com|odysseypremier\.com|royalbalitimeshare\.com|royalperspective\.com|royalresortsasia\.com|royalresortstimeshare\.com|sanctumhotel\.com|sanctumsoho\.com|thebaligetaway\.com|thekarmaclub\.com|thekarmacollection|themoleandbadger\.com|timesharebali\.com|wildheartbarandgrill\.com|wildheartsoho\.com|yuktamasya\.com

Empty DataFrame
Columns: [Record Id, Created Time, Created Date, First Name, Last Name, Email, Phone, Mobile, Birthdate, Year of Birth, Street, Street2, City, State, Country, Nationality, Booking Status, BookRef, Departure Date, Arrival Date, Card Type, Marital Status, Lead Brand, Lead Sub-Brand, Lead Source, Lead Locations, Lead Source Description, Lead Regions, Lead Status, Email Opt Out, Opt In]
Index: []

[0 rows x 31 columns]

In [279]:
# delete email Karma
count_after_clean_karma = m.delete_karma(zoho_df, 'Email')
# zoho_df.to_excel(r'C:\Users\fajar\Documents\Python\Data\after_clean_OTA.xlsx', index=False)

zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Marital Status,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In
0,zcrm_3584690000426781936,2023-02-06 13:12:19,empty,Kamna,Kapoor,kamna.kapoor@yarratrams.com.au,61466947313,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Royal Candidasa,Viewpoint,empty,empty,false,true
1,zcrm_3584690000428158680,2023-02-13 15:18:20,empty,Deane Jacqueline,Brosnan,deanebrosnan@hotmail.com,61411696222,61411696222,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,empty,empty,false,true
2,zcrm_3584690000428174965,2023-02-13 15:18:11,empty,Jason,Crofts,jcrofts@bigpond.net.au,6143798932,6143798932,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,empty,empty,false,true
3,zcrm_3584690000428450383,2023-02-13 15:31:14,empty,Shiji,Titus,shiji_titus@yahoo.co.uk,61405516642,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Royal Candidasa,Viewpoint,empty,empty,false,true
4,zcrm_3584690000428450665,2023-02-13 15:38:50,empty,Samuel,Riley,samriley77@gmail.com,61488250049,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,KRR @ Karma Kandara;Karma Kandara,Viewpoint,empty,empty,false,true
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,zcrm_3584690000439838156,2023-04-10 12:52:55,empty,Kelvin,Tjia,ktjia.kt@gmail.com,6181510539008,6181510539008,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,empty,empty,false,true
135,zcrm_3584690000439839377,2023-04-10 13:01:29,empty,Sonya,Stephens,molly2410@icloud.com,61438490055,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Song Hoai,Viewpoint,empty,empty,false,true
136,zcrm_3584690000439840143,2023-04-10 12:53:41,empty,Randhir,Kowlessur,australia@luckydodomigration.com,6193052167,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,empty,empty,true,false
137,zcrm_3584690000439840661,2023-04-10 13:03:12,empty,Lisa Marie,O'Donnell,lisaodonnell@email.com,61414445510,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Bavaria,Viewpoint,empty,empty,false,true
138,zcrm_3584690000439852124,2023-04-10 13:02:33,empty,Nicola,Bartley,nicola_ny@hotmail.com,61431410910,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Song Hoai,Viewpoint,empty,empty,false,true

In [280]:
# hitung jumlah duplicate
count_duplicate_general = zoho_df.loc[zoho_df.duplicated(subset=['Phone','Mobile','Email'])].shape[0]

zoho_df.loc[zoho_df.duplicated(subset=['Phone','Mobile','Email'])]

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Marital Status,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In
7,zcrm_3584690000428466005,2023-02-13 15:29:26,empty,Shiji,Titus,shiji_titus@yahoo.co.uk,61405516642,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Royal Sanur,Viewpoint,empty,empty,false,true

In [281]:
zoho_df.drop_duplicates(subset=['Phone','Mobile','Email'], inplace=True)
zoho_df.reset_index(drop=True, inplace=True)

# hitung jumlah setelah value duplicate dihapus
count_after_dedup_duplicate = zoho_df.shape[0]

zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Marital Status,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In
0,zcrm_3584690000426781936,2023-02-06 13:12:19,empty,Kamna,Kapoor,kamna.kapoor@yarratrams.com.au,61466947313,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Royal Candidasa,Viewpoint,empty,empty,false,true
1,zcrm_3584690000428158680,2023-02-13 15:18:20,empty,Deane Jacqueline,Brosnan,deanebrosnan@hotmail.com,61411696222,61411696222,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,empty,empty,false,true
2,zcrm_3584690000428174965,2023-02-13 15:18:11,empty,Jason,Crofts,jcrofts@bigpond.net.au,6143798932,6143798932,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,empty,empty,false,true
3,zcrm_3584690000428450383,2023-02-13 15:31:14,empty,Shiji,Titus,shiji_titus@yahoo.co.uk,61405516642,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Royal Candidasa,Viewpoint,empty,empty,false,true
4,zcrm_3584690000428450665,2023-02-13 15:38:50,empty,Samuel,Riley,samriley77@gmail.com,61488250049,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,KRR @ Karma Kandara;Karma Kandara,Viewpoint,empty,empty,false,true
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,zcrm_3584690000439838156,2023-04-10 12:52:55,empty,Kelvin,Tjia,ktjia.kt@gmail.com,6181510539008,6181510539008,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,empty,empty,false,true
134,zcrm_3584690000439839377,2023-04-10 13:01:29,empty,Sonya,Stephens,molly2410@icloud.com,61438490055,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Song Hoai,Viewpoint,empty,empty,false,true
135,zcrm_3584690000439840143,2023-04-10 12:53:41,empty,Randhir,Kowlessur,australia@luckydodomigration.com,6193052167,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,empty,empty,true,false
136,zcrm_3584690000439840661,2023-04-10 13:03:12,empty,Lisa Marie,O'Donnell,lisaodonnell@email.com,61414445510,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Bavaria,Viewpoint,empty,empty,false,true
137,zcrm_3584690000439852124,2023-04-10 13:02:33,empty,Nicola,Bartley,nicola_ny@hotmail.com,61431410910,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Song Hoai,Viewpoint,empty,empty,false,true

In [282]:
find_member_booking = zoho_df.copy()

find_member_booking.loc[find_member_booking['Phone'].isin(df_booking['Phone1']), 'Same Value Find'] = 'Booking-Phone1'
find_member_booking.loc[find_member_booking['Phone'].isin(df_booking['Mobile']), 'Same Value Find'] = 'Booking-Mobile'
find_member_booking.loc[find_member_booking['Mobile'].isin(df_booking['Phone1']), 'Same Value Find'] = 'Booking-Phone1' 
find_member_booking.loc[find_member_booking['Mobile'].isin(df_booking['Mobile']), 'Same Value Find'] = 'Booking-Mobile'
find_member_booking.loc[find_member_booking['Email'].isin(df_booking['Email']), 'Same Value Find'] = 'Booking-Email'

find_member_booking.loc[find_member_booking['Phone'].isin(df_phone['Mobile']), 'Same Value Find'] = 'Member-Mobile' 
find_member_booking.loc[find_member_booking['Mobile'].isin(df_phone['Mobile']), 'Same Value Find'] = 'Member-Mobile'

find_member_booking.loc[find_member_booking['Email'].isin(df_email['Email']), 'Same Value Find'] = 'Member-Email'

find_member_booking.drop(find_member_booking.loc[find_member_booking['Same Value Find'].isna()].index, inplace=True)

count_booking_dedup = find_member_booking.loc[find_member_booking['Same Value Find'].str.contains('Booking', flags=re.I, regex=True)].shape[0]
count_member_dedup = find_member_booking.loc[find_member_booking['Same Value Find'].str.contains('Member', flags=re.I, regex=True)].shape[0]

find_member_booking.replace('empty', '', inplace=True)
#find_member_booking.to_csv(r'C:\Users\fajar\Documents\Python\Data\booking-member-dedup.csv', index=False)

#find_member_booking.loc[find_member_booking['Same Value Find'] == 'Booking-Phone1']

In [283]:
# data phone, mobile dam email member yang ada di master data 
count_wash_member = zoho_df.loc[
    zoho_df['Phone'].isin(df_booking['Phone1']) | 
    zoho_df['Phone'].isin(df_booking['Mobile']) |
    zoho_df['Mobile'].isin(df_booking['Phone1']) | 
    zoho_df['Mobile'].isin(df_booking['Mobile']) |
    zoho_df['Email'].isin(df_booking['Email'])| 

    zoho_df['Phone'].isin(df_phone['Mobile']) | 
    zoho_df['Mobile'].isin(df_phone['Mobile']) |

    zoho_df['Email'].isin(df_email['Email'])

].shape[0]

zoho_df.drop(zoho_df.loc[
    zoho_df['Phone'].isin(df_booking['Phone1']) | 
    zoho_df['Phone'].isin(df_booking['Mobile']) |
    zoho_df['Mobile'].isin(df_booking['Phone1']) | 
    zoho_df['Mobile'].isin(df_booking['Mobile']) |
    zoho_df['Email'].isin(df_booking['Email']) |
    
    zoho_df['Phone'].isin(df_phone['Mobile']) | 
    zoho_df['Mobile'].isin(df_phone['Mobile']) |

    zoho_df['Email'].isin(df_email['Email'])

    ].index, inplace=True)
    
zoho_df.reset_index(drop=True, inplace=True)

count_after_wash_member = zoho_df.shape[0]

In [284]:
count_email_only = zoho_df.loc[(zoho_df['Email'] != 'empty') & ((zoho_df['Phone'] == 'empty') & (zoho_df['Mobile'] == 'empty'))].shape[0]
count_phone_only = zoho_df.loc[(zoho_df['Email'] == 'empty') & ((zoho_df['Phone'] != 'empty') | (zoho_df['Mobile'] != 'empty'))].shape[0]
count_email_and_phone = zoho_df.loc[(zoho_df['Email'] != 'empty') & ((zoho_df['Phone'] != 'empty') | (zoho_df['Mobile'] != 'empty'))].shape[0]

count_blank = zoho_df.loc[(zoho_df['Email'] =='empty') & (zoho_df['Phone']=='empty') & (zoho_df['Mobile']=='empty')].shape[0]

# zoho_df.loc[(zoho_df['Email'] =='empty') & (zoho_df['Phone']=='empty') & (zoho_df['Mobile']=='empty')].to_excel(r'C:\Users\fajar\Documents\Python\Data\blank_data.xlsx', index=False)

zoho_df.loc[(zoho_df['Email'] != 'empty') & ((zoho_df['Phone'] == 'empty') & (zoho_df['Mobile'] == 'empty')), 'Contact Type'] = 'Email Only'
zoho_df.loc[(zoho_df['Email'] == 'empty') & ((zoho_df['Phone'] != 'empty') | (zoho_df['Mobile'] != 'empty')), 'Contact Type'] = 'Phone Only'
zoho_df.loc[(zoho_df['Email'] != 'empty') & ((zoho_df['Phone'] != 'empty') | (zoho_df['Mobile'] != 'empty')), 'Contact Type'] = 'Email and Phone'

zoho_df.drop(zoho_df.loc[(zoho_df['Email'] =='empty') & (zoho_df['Phone']=='empty') & (zoho_df['Mobile']=='empty')].index, inplace=True)
zoho_df.reset_index(drop=True, inplace=True)

count_after_wash_blank = zoho_df.shape[0]

In [285]:
path = r'C:\Users\fajar\Documents\Python\Data\Debounce\bounced_zoho.csv'
df_bounced_zoho = pd.read_csv(path, dtype='string', on_bad_lines='skip')

# data phone, mobile dam email member yang ada di master data 
count_wash_bounced_zoho = zoho_df.loc[
    zoho_df['Email'].isin(df_bounced_zoho['Contact Email'])

].shape[0]

# zoho_df.loc[
#     zoho_df['Email'].isin(df_bounced_zoho['Contact Email'])

# ].to_excel(r'C:\Users\fajar\Documents\Python\Data\Debounce\dedup_bounced_zoho.xlsx', index=False)

zoho_df.drop(zoho_df.loc[
    zoho_df['Email'].isin(df_bounced_zoho['Contact Email'])

].index, inplace=True)
zoho_df.reset_index(drop=True, inplace=True)

count_after_wash_bounced_zoho = zoho_df.shape[0]
count_after_wash_bounced_zoho

105

In [286]:
path = r'C:\Users\fajar\Documents\Python\Data\Debounce\unsubs_zoho.csv'
df_unsub_zoho = pd.read_csv(path, dtype='string', on_bad_lines='skip')

# data phone, mobile dam email member yang ada di master data 
count_wash_unsub_zoho = zoho_df.loc[
    zoho_df['Email'].isin(df_unsub_zoho['Contact Email'])

].shape[0]

# zoho_df.loc[
#     zoho_df['Email'].isin(df_unsub_zoho['Contact Email'])

# ].to_excel(r'C:\Users\fajar\Documents\Python\Data\Debounce\dedup_unsub_zoho.xlsx', index=False)

zoho_df.drop(zoho_df.loc[
    zoho_df['Email'].isin(df_unsub_zoho['Contact Email'])

].index, inplace=True)
zoho_df.reset_index(drop=True, inplace=True)

count_after_wash_unsub_zoho = zoho_df.shape[0]
count_after_wash_unsub_zoho

92

In [287]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Keseluruhan Master Zoho : "+str(count_data_awal))
print("Jumlah Filter Leads Awal : "+str(count_filter_awal))
print("Jumlah Data Dedup AUNZ : "+str(count_wash_prev))
print("Jumlah After Wash AUNZ : "+str(count_after_wash_aunz))
print("Jumlah Format Email Salah : "+str(count_deleted_wrong_format))
print("Jumlah Setelah Clean Format Email Salah : "+str(count_after_deleted_wrong_format))
print("Jumlah Lead Test : "+str(count_leads_test))
print("Jumlah Setelah Clean Lead Test : "+str(count_after_dedup_test))
print("Jumlah Email Karma : "+str(count_email_karma))
print("Jumlah Setelah Clean Email Karma : "+str(count_after_clean_karma))
print("Jumlah Duplicate (Phone, Mobile dan Email) : "+str(count_duplicate_general))
print("Jumlah Setelah Clean Duplicate : "+str(count_after_dedup_duplicate))
print("Jumlah Wash Member : "+str(count_member_dedup))
print("Jumlah Wash Booking : "+str(count_booking_dedup))
print("Jumlah Setelah Wash Member : "+str(count_after_wash_member))
print("==========================================================")
print("Contact Type")
print("==========================================================")
print("Jumlah Email Only : "+str(count_email_only))
print("Jumlah Phone Only : "+str(count_phone_only))
print("Jumlah Email dan Phone : "+str(count_email_and_phone))
print("Jumlah Phone Email Blank (Setelah phone yang tidak valid dihapus) : "+str(count_blank))
print("Jumlah Setelah Wash Phone Email Blank : "+str(count_after_wash_blank))
print("Jumlah Data Dedup bounced zoho : "+str(count_wash_bounced_zoho))
print("Jumlah After Wash bounced zoho : "+str(count_after_wash_bounced_zoho))
print("Jumlah Data Dedup unsubs zoho : "+str(count_wash_unsub_zoho))
print("Jumlah After Wash unsubs zoho : "+str(count_after_wash_unsub_zoho))

==========================================================
Summary
==========================================================
Jumlah Keseluruhan Master Zoho : 4704484
Jumlah Filter Leads Awal : 179
Jumlah Data Dedup AUNZ : 40
Jumlah After Wash AUNZ : 139
Jumlah Format Email Salah : 0
Jumlah Setelah Clean Format Email Salah : 179
Jumlah Lead Test : 0
Jumlah Setelah Clean Lead Test : 139
Jumlah Email Karma : 0
Jumlah Setelah Clean Email Karma : 139
Jumlah Duplicate (Phone, Mobile dan Email) : 1
Jumlah Setelah Clean Duplicate : 138
Jumlah Wash Member : 2
Jumlah Wash Booking : 29
Jumlah Setelah Wash Member : 107
==========================================================
Contact Type
==========================================================
Jumlah Email Only : 2
Jumlah Phone Only : 20
Jumlah Email dan Phone : 85
Jumlah Phone Email Blank (Setelah phone yang tidak valid dihapus) : 0
Jumlah Setelah Wash Phone Email Blank : 107
Jumlah Data Dedup bounced zoho : 2
Jumlah After Wash bounced zoho : 105
Jumlah Data Dedup unsubs zoho : 13
Jumlah After Wash unsubs zoho : 92

# ====================== Akhir Filter Umum ======================

In [288]:
zoho_df.replace('empty', '', inplace=True)
zoho_df.to_excel(r'C:\Users\fajar\Documents\Python\Data\past_guest_au_clean.xlsx', index=False)

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\fajar\\Documents\\Python\\Data\\past_guest_au_clean.xlsx'