In [1]:
import main_module as m
import zoho_filter_module as fil
import pandas as pd
import re
import numpy as np

%load_ext autoreload
%autoreload 2

dir_path = r'C:\Users\fajar\Documents\Python\Data\Zoho_Backup'
file_name = '\Leads_'

In [2]:
path = r'C:\Users\fajar\Documents\Python\Data\Request Data\Suhali\Agustus\10 Agustus\Flybuy ID\Update 12 Dec\zoho_tm_id_clean_update_12_dec.xlsx'
zoho_df = pd.read_excel(path, dtype='string', sheet_name='Sheet1')

zoho_df.reset_index(drop=True, inplace=True)
count_filter_awal = zoho_df.shape[0]

# mengisi kolom <NA> dengan value string 'empty' supaya mudah mengecek data member dan booking dengan isin

zoho_df.fillna('empty', inplace=True)
zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Do Not Contact,Do Not Mail,Contact Type
0,zcrm_3584690000000404471,2019-01-08 11:07:28,2019-01-03,Ayuk,Purnama,piscesia88@gmail.com,6281901228055,empty,empty,empty,...,Wifi,empty,Purple Wifi,SEAP,New Lead,false,false,false,false,Email and Phone
1,zcrm_3584690000000404474,2019-01-08 11:07:28,2019-01-03,Luh,Srik,sriyaniluh@gmail.com,6281936915201,empty,1997-02-22,1997,...,Wifi,empty,Purple Wifi,SEAP,New Lead,false,false,false,false,Email and Phone
2,zcrm_3584690000000404477,2019-01-08 11:07:28,2019-01-03,Anak,Kleyangan,timotiustono83.tt@gmail.com,6285737081378,empty,empty,empty,...,Wifi,empty,Purple Wifi,SEAP,New Lead,false,false,false,false,Email and Phone
3,zcrm_3584690000000404481,2019-01-08 11:07:28,2019-01-03,Michael,Margono,michaelmargono@gmail.com,6287862823000,6287862823000,2001-01-16,2001,...,Wifi,Mall 21,Purple Wifi,SEAP,New Lead,false,false,false,false,Email and Phone
4,zcrm_3584690000000404589,2019-01-08 11:07:28,2019-01-03,Baden,Gray,baden@prosper.org.nz,62272446663,empty,1968-06-26,1968,...,Wifi,empty,Purple Wifi,SEAP,New Lead,false,false,false,false,Email and Phone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709061,zcrm_3584690000456702029,2023-08-06 11:57:54,empty,Cici,Asih,cici21.liocollection@gmail.com,6281353358951,empty,empty,empty,...,Wifi,Karma Beach Bali,Purple Wifi,SEAP,New Lead,false,false,false,false,Email and Phone
709062,zcrm_3584690000456702731,2023-08-07 17:43:41,empty,Hsjhs,Uuieug,raafh@gmail.com,628167769289,empty,empty,empty,...,Wifi,Karma Beach Bali,Purple Wifi,SEAP,New Lead,false,false,false,false,Email and Phone
709063,zcrm_3584690000456724001,2023-08-06 18:30:10,empty,Isyana,Yudita,isyanayl@gmail.com,6281277120679,6281277120679,empty,1982,...,Web Enquiry,Nyoman Cafe Jimbaran,YTID | Web | W2MAR23 | Guest Survey ID Nyoman ...,SEAP,Hot Prospect,false,false,false,false,Email and Phone
709064,zcrm_3584690000456725027,2023-08-06 18:44:57,empty,Agung,Agung,aduuunk@gmail.com,6281282819991,6281282819991,empty,1982,...,Web Enquiry,Rame Restaurant,YTID | Web | W2MAR23 | Guest Survey ID Rame Re...,SEAP,Hot Prospect,false,false,false,false,Email and Phone
709065,zcrm_3584690000456727041,2023-08-07 01:38:47,empty,Ela,Ela,blacklanaa@gmail.com,6287869605822,6287869605822,empty,1984,...,Web Enquiry,Pandan Sari,YTID | Web | W2MAR23 | Guest Survey ID Pandan ...,SEAP,Hot Prospect,false,false,false,false,Email and Phone

In [3]:
path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04eXpvS1NXTWF2RVE\_BOOKING\Booking By Year\FlyBuy Booking Data (BGAU & BGID & KE).xlsx'
df_booking = pd.read_excel(path, dtype='string', sheet_name='BOOKING_BGAU_BGID_KE')

path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04UUNBME5GOVhoMjA\_ODYSSEY\Phone Members.xlsx'
df_phone = pd.read_excel(path, dtype='string', sheet_name='Sheet1')

path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04UUNBME5GOVhoMjA\_ODYSSEY\Email Members.xlsx'
df_email = pd.read_excel(path, dtype='string', sheet_name='Sheet1')

# ====================== Awal Filter Umum ======================

In [4]:
# data phone, mobile dam email member yang ada di master data (wash member)

m.clean_number(zoho_df, 'Phone')
m.clean_number(zoho_df, 'Mobile')
m.replace_not_valid_to_empty(zoho_df, 'Phone')
m.replace_not_valid_to_empty(zoho_df, 'Mobile')
zoho_df['Email'] = m.lowercase(zoho_df, 'Email')
m.clean_space(zoho_df, 'Email')

m.clean_number(df_booking, 'Phone1')
m.clean_number(df_booking, 'Mobile')
df_booking['Email'] = m.lowercase(df_booking, 'Email')
m.clean_space(df_booking, 'Email')

m.clean_number(df_phone, 'Mobile')

df_email['Email'] = m.lowercase(df_email, 'Email')
m.clean_space(df_email, 'Email')

0               harvey@liblink.co.za
1                _benezi@hotmail.com
2                    0000987@mail.ru
3                  0007psc@gmail.com
4                 001paras@gmail.com
                     ...
304941    narkhede.sheetal@gmail.com
304942    joshua.redmond81@gmail.com
304943    phoebe.e.cetoupe@gmail.com
304944    rithikahedge0010@gmail.com
304945            sheila@amaneer.com
Name: Email, Length: 304946, dtype: string

In [5]:
find_member_booking = zoho_df.copy()

find_member_booking.loc[find_member_booking['Phone'].isin(df_booking['Phone1']), 'Same Value Find'] = 'Booking-Phone1'
find_member_booking.loc[find_member_booking['Phone'].isin(df_booking['Mobile']), 'Same Value Find'] = 'Booking-Mobile'
find_member_booking.loc[find_member_booking['Mobile'].isin(df_booking['Phone1']), 'Same Value Find'] = 'Booking-Phone1' 
find_member_booking.loc[find_member_booking['Mobile'].isin(df_booking['Mobile']), 'Same Value Find'] = 'Booking-Mobile'
find_member_booking.loc[find_member_booking['Email'].isin(df_booking['Email']), 'Same Value Find'] = 'Booking-Email'

find_member_booking.loc[find_member_booking['Phone'].isin(df_phone['Mobile']), 'Same Value Find'] = 'Member-Mobile' 
find_member_booking.loc[find_member_booking['Mobile'].isin(df_phone['Mobile']), 'Same Value Find'] = 'Member-Mobile'

find_member_booking.loc[find_member_booking['Email'].isin(df_email['Email']), 'Same Value Find'] = 'Member-Email'

find_member_booking.drop(find_member_booking.loc[find_member_booking['Same Value Find'].isna()].index, inplace=True)

count_booking_dedup = find_member_booking.loc[find_member_booking['Same Value Find'].str.contains('Booking', flags=re.I, regex=True)].shape[0]
count_member_dedup = find_member_booking.loc[find_member_booking['Same Value Find'].str.contains('Member', flags=re.I, regex=True)].shape[0]

find_member_booking.replace('empty', '', inplace=True)
# find_member_booking.to_csv(r'C:\Users\fajar\Documents\Python\Data\booking-member-dedup.csv', index=False)
# find_member_booking.to_excel(r'C:\Users\fajar\Documents\Python\Data\booking-member-dedup.xlsx', index=False)

#find_member_booking.loc[find_member_booking['Same Value Find'] == 'Booking-Phone1']

In [6]:
# data phone, mobile dam email member yang ada di master data 
count_wash_member = zoho_df.loc[
    zoho_df['Phone'].isin(df_booking['Phone1']) | 
    zoho_df['Phone'].isin(df_booking['Mobile']) |
    zoho_df['Mobile'].isin(df_booking['Phone1']) | 
    zoho_df['Mobile'].isin(df_booking['Mobile']) |
    zoho_df['Email'].isin(df_booking['Email'])| 

    zoho_df['Phone'].isin(df_phone['Mobile']) | 
    zoho_df['Mobile'].isin(df_phone['Mobile']) |

    zoho_df['Email'].isin(df_email['Email'])

].shape[0]

zoho_df.drop(zoho_df.loc[
    zoho_df['Phone'].isin(df_booking['Phone1']) | 
    zoho_df['Phone'].isin(df_booking['Mobile']) |
    zoho_df['Mobile'].isin(df_booking['Phone1']) | 
    zoho_df['Mobile'].isin(df_booking['Mobile']) |
    zoho_df['Email'].isin(df_booking['Email']) |
    
    zoho_df['Phone'].isin(df_phone['Mobile']) | 
    zoho_df['Mobile'].isin(df_phone['Mobile']) |

    zoho_df['Email'].isin(df_email['Email'])

    ].index, inplace=True)
    
zoho_df.reset_index(drop=True, inplace=True)

count_after_wash_member = zoho_df.shape[0]

In [7]:
count_final = zoho_df.shape[0]
zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Do Not Contact,Do Not Mail,Contact Type
0,zcrm_3584690000000404471,2019-01-08 11:07:28,2019-01-03,Ayuk,Purnama,piscesia88@gmail.com,6281901228055,empty,empty,empty,...,Wifi,empty,Purple Wifi,SEAP,New Lead,false,false,false,false,Email and Phone
1,zcrm_3584690000000404474,2019-01-08 11:07:28,2019-01-03,Luh,Srik,sriyaniluh@gmail.com,6281936915201,empty,1997-02-22,1997,...,Wifi,empty,Purple Wifi,SEAP,New Lead,false,false,false,false,Email and Phone
2,zcrm_3584690000000404477,2019-01-08 11:07:28,2019-01-03,Anak,Kleyangan,timotiustono83.tt@gmail.com,6285737081378,empty,empty,empty,...,Wifi,empty,Purple Wifi,SEAP,New Lead,false,false,false,false,Email and Phone
3,zcrm_3584690000000404481,2019-01-08 11:07:28,2019-01-03,Michael,Margono,michaelmargono@gmail.com,6287862823000,6287862823000,2001-01-16,2001,...,Wifi,Mall 21,Purple Wifi,SEAP,New Lead,false,false,false,false,Email and Phone
4,zcrm_3584690000000404589,2019-01-08 11:07:28,2019-01-03,Baden,Gray,baden@prosper.org.nz,62272446663,empty,1968-06-26,1968,...,Wifi,empty,Purple Wifi,SEAP,New Lead,false,false,false,false,Email and Phone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709061,zcrm_3584690000456702029,2023-08-06 11:57:54,empty,Cici,Asih,cici21.liocollection@gmail.com,6281353358951,empty,empty,empty,...,Wifi,Karma Beach Bali,Purple Wifi,SEAP,New Lead,false,false,false,false,Email and Phone
709062,zcrm_3584690000456702731,2023-08-07 17:43:41,empty,Hsjhs,Uuieug,raafh@gmail.com,628167769289,empty,empty,empty,...,Wifi,Karma Beach Bali,Purple Wifi,SEAP,New Lead,false,false,false,false,Email and Phone
709063,zcrm_3584690000456724001,2023-08-06 18:30:10,empty,Isyana,Yudita,isyanayl@gmail.com,6281277120679,6281277120679,empty,1982,...,Web Enquiry,Nyoman Cafe Jimbaran,YTID | Web | W2MAR23 | Guest Survey ID Nyoman ...,SEAP,Hot Prospect,false,false,false,false,Email and Phone
709064,zcrm_3584690000456725027,2023-08-06 18:44:57,empty,Agung,Agung,aduuunk@gmail.com,6281282819991,6281282819991,empty,1982,...,Web Enquiry,Rame Restaurant,YTID | Web | W2MAR23 | Guest Survey ID Rame Re...,SEAP,Hot Prospect,false,false,false,false,Email and Phone
709065,zcrm_3584690000456727041,2023-08-07 01:38:47,empty,Ela,Ela,blacklanaa@gmail.com,6287869605822,6287869605822,empty,1984,...,Web Enquiry,Pandan Sari,YTID | Web | W2MAR23 | Guest Survey ID Pandan ...,SEAP,Hot Prospect,false,false,false,false,Email and Phone

In [8]:
created_date = zoho_df['Created Date'].str.split('-', expand=True)
created_time = zoho_df['Created Time'].str.split('-', expand=True)
date_year = created_date[0]
time_year = created_time[0]

In [9]:
zoho_df['New Year'] = date_year

In [10]:
zoho_df.loc[zoho_df['New Year'] == 'empty', 'New Year'] = time_year

In [11]:
zoho_df.loc[zoho_df['New Year'] == 'empty']
zoho_df.loc[zoho_df['New Year'] == '2000']
# zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Do Not Contact,Do Not Mail,Contact Type,New Year
31755,zcrm_3584690000005929436,2019-04-02 03:56:26,2000-01-01,Kapil,Mehrotra,kapil1874@hotmail.com,6281364410414,empty,empty,empty,...,empty,Karma list email for Bhanu - International,SEAP,empty,false,false,false,false,Email and Phone,2000
31756,zcrm_3584690000005929437,2019-04-02 03:56:26,2000-01-01,Kapil,Mehrotra,kapil1874@yahoo.com,6281364410414,empty,empty,empty,...,empty,Karma list email for Bhanu - International,SEAP,empty,false,false,false,false,Email and Phone,2000
31834,zcrm_3584690000006080032,2019-04-02 04:17:04,2000-01-01,Setya,Aryaputra,kentung1982@yahoo.com,628128469854,6281330388337,empty,empty,...,empty,Karma list email for Bhanu - International,SEAP,empty,false,false,false,false,Email and Phone,2000
31847,zcrm_3584690000006080243,2019-04-02 04:17:05,2000-01-01,Mutiara,Sakti Hasibuan,sakti_hsb@yahoo.co.id,62778363367,6281364724433,empty,empty,...,empty,Karma list email for Bhanu - International,SEAP,empty,false,false,false,false,Email and Phone,2000
31867,zcrm_3584690000006080640,2019-04-02 04:17:08,2000-01-01,Kevin,Yoon,kevin2004@empal.com,628179752231,8179752231,empty,empty,...,empty,KarmaRoyalGroup-Indonesia-EmailOnly,SEAP,empty,false,false,false,false,Email and Phone,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214648,zcrm_3584690000014368779,2019-04-02 22:23:26,2000-01-01,John K,empty,empty,6281558501203,empty,empty,1963,...,Indian survey,COLDLINE DATA-AIRPORT SURVEYS BATCH 2,SEAP,empty,false,false,false,false,Phone Only,2000
214735,zcrm_3584690000015911168,2019-04-03 02:32:42,2000-01-01,Lussal Release,empty,empty,62811546602,empty,empty,1963,...,Indian survey,COLDLINE DATA-AIRPORT SURVEYS BATCH 4,SEAP,empty,false,false,false,false,Phone Only,2000
215120,zcrm_3584690000017483515,2019-04-03 06:26:30,2000-01-01,S N Jadiya,empty,empty,9925773772,empty,empty,1969,...,Indian survey,MAHABALESHWAR SURVEYS,SEAP,empty,false,false,false,false,Phone Only,2000
215124,zcrm_3584690000017776588,2019-04-03 07:41:35,2000-01-01,S N Jadiya,empty,empty,62882662655,empty,empty,1969,...,Indian survey,MAHABALESHWAR SURVEYS,SEAP,empty,false,false,false,false,Phone Only,2000
215276,zcrm_3584690000021779822,2019-04-03 17:39:25,2000-01-01,Eng Guan Lee,empty,empty,6296570314,empty,empty,empty,...,Indian survey,GUEST EXIT JIMBARAN,SEAP,empty,false,false,false,false,Phone Only,2000

# ====================== Akhir Filter Umum ======================

In [12]:
print("==========================================================")
print("Summary Report")
print("==========================================================")
print("Jumlah Data Awal : "+str(count_filter_awal))
print("Jumlah Wash Member : "+str(count_member_dedup))
print("Jumlah Wash Booking : "+str(count_booking_dedup))
print("Jumlah Wash Booking : "+str(count_final))

==========================================================
Summary Report
==========================================================
Jumlah Data Awal : 709066
Jumlah Wash Member : 0
Jumlah Wash Booking : 0
Jumlah Wash Booking : 709066

In [13]:
zoho_df.replace('empty', '', inplace=True)
zoho_df.to_excel(r'C:\Users\fajar\Documents\Python\Data\Request Data\Suhali\Agustus\10 Agustus\Flybuy ID\Update 12 Dec\zoho_tm_id_clean_update_12_dec_year.xlsx', index=False)