In [793]:
import main_module as m
import zoho_filter_module as fil
import pandas as pd
from openpyxl.utils.exceptions import IllegalCharacterError
import re
import numpy as np

%load_ext autoreload
%autoreload 2

dir_path = r'C:\Users\fajar.fatoni\Documents\Python\Data\Zoho_Backup'
file_name = '\Leads_'

cols = ['Record Id',	
'Created Time',
'Created Date',	
'First Name',	
'Last Name',	
'Email',	
'Phone',	
'Mobile',	
'Birthdate',	
'Year of Birth',
'Street',	
'Street2',	
'City',	
'State',	
'Country',	
'Nationality',
'Booking Status', 
'BookRef',
'Departure Date',	
'Arrival Date',	
'Card Type',	
'Marital Status',	
'Lead Brand',	
'Lead Sub-Brand',	
'Lead Source',	
'Lead Locations',	
'Lead Source Description',	
'Lead Regions',
'Lead Status',
'Email Opt Out',	
'Opt In',
'GDPR Compliant',
'Website',
'Comments',
'Do you live in Bali?']

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [794]:
df = m.load_data_multiple(dir_path, file_name, cols)
count_data_awal = df.shape[0]
df = df.reindex(columns=cols)
df.shape[0]

df['Created Time'] = pd.to_datetime(df['Created Time'], format='%Y-%m-%d %H:%M:%S')
df['Arrival Date'] = pd.to_datetime(df['Arrival Date'], format='%Y-%m-%d')
df['Departure Date'] = pd.to_datetime(df['Departure Date'], format='%Y-%m-%d')
# fungsi errors cource untuk menhindari error jika value data date null atau kosong
# df['Birthdate'] = pd.to_datetime(df['Birthdate'], format='%Y-%m-%d', errors='coerce')
df.dtypes
df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website,Comments,Do you live in Bali?
0,zcrm_3584690000000404602,2019-01-08 11:07:28,2021-07-21,Frederic,Bonin,fredericbonin79@gmail.com,+6281236100502,<NA>,1981-10-03,1981,...,Karma Kandara,KAREN,SEAP,New Lead,false,false,false,<NA>,<NA>,false
1,zcrm_3584690000000450071,2019-01-08 16:38:18,<NA>,Sebastian,Rach,<NA>,+498914342111,<NA>,1982-04-20,1982,...,Karma Bavaria,<NA>,UK/Europe,New Lead,true,false,false,<NA>,<NA>,false
2,zcrm_3584690000000450087,2019-01-08 16:38:18,<NA>,Siobhan,Gallagher,gallaghersiobhan@eircom.net,353879597603,<NA>,1973-03-14,1973,...,Karma Bavaria,<NA>,UK/Europe,New Lead,false,true,true,<NA>,<NA>,false
3,zcrm_3584690000000450106,2019-01-08 16:38:18,<NA>,Lisa,Ferkovich,lisajo2009@yahoo.com,14062394749,<NA>,1963-07-08,1963,...,Karma Bavaria,<NA>,UK/Europe,New Lead,true,false,false,<NA>,<NA>,false
4,zcrm_3584690000000450109,2019-01-08 16:38:18,<NA>,Ana Maria,Weileder,m.weileder@sonnenlink.de,15253234700,<NA>,<NA>,<NA>,...,Karma Bavaria,MICE Contacts from Ioanna email,UK/Europe,New Lead,false,true,true,<NA>,<NA>,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500010,zcrm_3584690000531084001,2025-03-17 16:10:04,2025-03-17,Gary,Cosgrove,cosgrove_gary@yahoo.co.uk,+4407709529900,<NA>,<NA>,<NA>,...,Karma Bayon,Karma Reservations - WhatsApp Channel,<NA>,New Lead,false,false,false,<NA>,<NA>,false
500011,zcrm_3584690000531086001,2025-03-17 16:13:48,2025-03-17,TEST,TEST,rajesh.kumar@karmagroup.com,+919876655432,<NA>,<NA>,<NA>,...,Karma Salford Hall,Karma Salford Hall - Weddings at Karma Salford...,India,<NA>,false,true,false,https://karmagroup.com/weddings-at-karma-salfo...,<NA>,false
500012,zcrm_3584690000531094001,2025-03-17 16:25:04,2025-03-17,Jana,D,jana@pragma.law,+61405501543,<NA>,<NA>,<NA>,...,Karma Kandara,Karma Reservations - WhatsApp Channel,<NA>,New Lead,false,false,false,<NA>,<NA>,false
500013,zcrm_3584690000531126001,2025-03-17 17:25:17,<NA>,Georgia,Goodyer,georgiaraedunkley@gmail.com,+447840040213,<NA>,1989-11-06,<NA>,...,<NA>,Karma Reciprocal Members,UK/Europe,<NA>,false,true,true,https://karmaclub.karmagroup.com/reciprocal-me...,<NA>,false
500014,zcrm_3584690000531144001,2025-03-17 17:59:52,2025-03-17,Feby,Jolanda,<NA>,+62818-0347-7331,<NA>,<NA>,<NA>,...,Karma Kandara,Karma Reservations - WhatsApp Channel,<NA>,New Lead,false,false,false,<NA>,<NA>,false

In [795]:
df.loc[df['Phone'].str.contains('^\\+62', regex=True)]

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website,Comments,Do you live in Bali?
0,zcrm_3584690000000404602,2019-01-08 11:07:28,2021-07-21,Frederic,Bonin,fredericbonin79@gmail.com,+6281236100502,<NA>,1981-10-03,1981,...,Karma Kandara,KAREN,SEAP,New Lead,false,false,false,<NA>,<NA>,false
10,zcrm_3584690000000450191,2019-01-08 16:38:18,2021-07-21,Ni Made Novia,Andryani,novia_made@yahoo.com,+6281511634635,<NA>,1980-11-10,1980,...,Karma Kandara,KAREN,SEAP,New Lead,false,false,false,<NA>,<NA>,false
12,zcrm_3584690000000450226,2019-01-08 16:38:18,2021-07-21,Maureellins,Joewyns,maureellinsjoewyns@gmail.com,+6282221100639,<NA>,2000-04-14,2000,...,Karma Kandara,KAREN,SEAP,New Lead,false,false,false,<NA>,<NA>,false
33,zcrm_3584690000000456097,2019-01-09 11:10:49,2021-07-21,Di,Zhang,156864136@qq.com,+628618339280777,<NA>,<NA>,<NA>,...,Karma Kandara,KAREN,SEAP,New Lead,false,false,false,<NA>,<NA>,false
86,zcrm_3584690000000456162,2019-01-09 11:10:49,2021-07-21,Ganef Hari,Sulistiono,abahdendy99@gmail.com,+628123255435,<NA>,1963-12-16,1963,...,Karma Kandara,KAREN,SEAP,New Lead,false,false,false,<NA>,<NA>,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499898,zcrm_3584690000530900043,2025-03-17 11:15:16,<NA>,-,Hartono,hartonoserutan@gmail.com,+628816404670,<NA>,<NA>,<NA>,...,Karma Royal Sanur,Viewpoint,<NA>,<NA>,false,true,false,<NA>,<NA>,false
499912,zcrm_3584690000530900502,2025-03-17 15:24:42,<NA>,Nadezhda,Shuvaeva,nvshuvaeva7@gmail.com,+6285190227284,<NA>,<NA>,<NA>,...,<NA>,Karma Beach VIP membership sign up 2023,SEAP,<NA>,false,true,false,https://karmagroup.com/karma-beach-vip/,<NA>,false
500001,zcrm_3584690000530905489,2025-03-17 13:00:53,<NA>,Evgenii,Semenkin,gaya108tree@gmail.com,+6281225467695,<NA>,<NA>,<NA>,...,<NA>,Karma Beach VIP membership sign up 2023,SEAP,<NA>,false,true,false,https://karmagroup.com/karma-beach-vip/,<NA>,false
500003,zcrm_3584690000531033039,2025-03-17 18:00:52,2025-03-17,-,-,<NA>,+62813-8178-5254,<NA>,<NA>,<NA>,...,Karma Kandara,Karma Reservations - WhatsApp Channel,<NA>,New Lead,false,false,false,<NA>,<NA>,false
500014,zcrm_3584690000531144001,2025-03-17 17:59:52,2025-03-17,Feby,Jolanda,<NA>,+62818-0347-7331,<NA>,<NA>,<NA>,...,Karma Kandara,Karma Reservations - WhatsApp Channel,<NA>,New Lead,false,false,false,<NA>,<NA>,false

In [796]:
path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04eXpvS1NXTWF2RVE\_BOOKING\Booking By Year\FlyBuy Booking Data (BGAU & BGID & KE).xlsx'
df_booking = pd.read_excel(path, dtype='string', sheet_name='BOOKING_BGAU_BGID_KE')

# path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04UUNBME5GOVhoMjA\_ODYSSEY\Phone Members.xlsx'
# df_phone = pd.read_excel(path, dtype='string', sheet_name='Sheet1')

path = r'C:\Users\fajar.fatoni\Documents\Python\Data\Phone Members for toni 22mar25.csv'
df_phone = pd.read_csv(path, dtype='string', encoding='ISO-8859-1')

# path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04UUNBME5GOVhoMjA\_ODYSSEY\Email Members.xlsx'
# df_email = pd.read_excel(path, dtype='string', sheet_name='Sheet1')

path = r'C:\Users\fajar.fatoni\Documents\Python\Data\Email Members for toni 22mar25.csv'
df_email = pd.read_csv(path, dtype='string', encoding='ISO-8859-1')

In [822]:
zoho_filter = fil.user_req(df)
zoho_df = df.loc[zoho_filter].copy() # menggunakan copy untuk menghindari setting copy warning
zoho_df.reset_index(drop=True, inplace=True)
count_filter_awal = zoho_df.shape[0]

# zoho_df.to_excel(r'C:\Users\fajar.fatoni\Documents\Python\Data\test_leads.xlsx', index=False)
# mengisi kolom <NA> dengan value string 'empty' supaya mudah mengecek data member dan booking dengan isin

zoho_df.fillna('empty', inplace=True)
zoho_df.sort_values('Created Time', ascending=True)

C:\Users\fajar.fatoni\AppData\Local\Temp\ipykernel_2636\2027893311.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'empty' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  zoho_df.fillna('empty', inplace=True)

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website,Comments,Do you live in Bali?
2,zcrm_3584690000501061001,2024-07-03 21:56:57,empty,Michael Roepen,Michael Roepen,cackle067@hotmail.com,+61403602041,+61403602041,empty,empty,...,General,KE | Web | Destination Amina Lantana Hoi An Ho...,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/a...,empty,false
3,zcrm_3584690000501102002,2024-07-04 06:13:21,empty,Ganesh,Shevkari,gps7777@gmail.com,+61423962131,+61423962131,empty,empty,...,General,KE | Web | Destination Karma Royal Jimbaran,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/k...,empty,false
0,zcrm_3584690000501053077,2024-07-04 07:54:15,empty,Rishan,Neelawala,Littauk@yahoo.co.uk,+610433912771,+610433912771,empty,empty,...,General,KE | WEB | Contact Us,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/contact/,empty,false
1,zcrm_3584690000501057143,2024-07-04 14:52:47,empty,Yilmaz,Erbas,ylmzerbas@hotmail.com,+61423207375,+61423207375,empty,empty,...,General,KE | Web | Destination Amina Lantana Hoi An Ho...,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/a...,empty,false
5,zcrm_3584690000501151001,2024-07-04 17:27:04,empty,Leanne,Gatt,leannegatt62@gmail.com,+61402312248,+61402312248,empty,empty,...,General,KE | Web | Destination Karma Kandara,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/k...,empty,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
791,zcrm_3584690000530815033,2025-03-17 09:22:31,empty,Mark,Cross,markcross502@yahoo.com.au,+610411606162,+610411606162,empty,empty,...,General,"KE | Web | Destination March Samui Resort, Koh...",SEAP,Not Qualified,false,false,false,https://karmaexperience.com/hotel-partner/marc...,empty,false
792,zcrm_3584690000530901644,2025-03-17 13:39:02,empty,Julieanne,Patten,julieannep@westnet.com.au,+61428590886,+61428590886,empty,empty,...,General,KE | Web | Destination Karma Kandara Mentari R...,SEAP,Not Qualified,false,false,false,https://karmaexperience.com/destinations/karma...,empty,false
789,zcrm_3584690000530642578,2025-03-17 13:52:57,empty,Test,Thiru,test305thi3ru@gmail.com,+912313212123,+912313212123,empty,empty,...,empty,KE | WEB | Jimbaran,SEAP,Not Qualified,false,false,false,https://karmaexperience.com/,empty,false
793,zcrm_3584690000530902623,2025-03-17 14:35:05,empty,Test2,Thiru93,test034thiru2@gmail.com,+61465654565,+61465654565,empty,empty,...,empty,KE | WEB | KEPH Pago,SEAP,Not Qualified,false,false,false,https://karmaexperience.com/#,empty,false
794,zcrm_3584690000531042001,2025-03-17 14:55:56,empty,Tanya,Esterhuizen,tanyaglam2@gmail.com,+610405140796,+610405140796,empty,1971,...,General,KE3 | EDM | KARMA KAMELEON - KARMA KANDARA | w...,SEAP,empty,false,false,false,empty,empty,false

In [799]:
zoho_df.loc[zoho_df['Lead Source Description'].str.contains('walk', regex=True, flags=re.I)]

Empty DataFrame
Columns: [Record Id, Created Time, Created Date, First Name, Last Name, Email, Phone, Mobile, Birthdate, Year of Birth, Street, Street2, City, State, Country, Nationality, Booking Status, BookRef, Departure Date, Arrival Date, Card Type, Marital Status, Lead Brand, Lead Sub-Brand, Lead Source, Lead Locations, Lead Source Description, Lead Regions, Lead Status, Email Opt Out, Opt In, GDPR Compliant, Website, Comments, Do you live in Bali?]
Index: []

[0 rows x 35 columns]

# ====================== Awal Filter Umum ======================

In [800]:
# data phone, mobile dam email member yang ada di master data (wash member)

m.clean_number(zoho_df, 'Phone')
m.clean_number(zoho_df, 'Mobile')
m.replace_not_valid_to_empty(zoho_df, 'Phone')
m.replace_not_valid_to_empty(zoho_df, 'Mobile')
zoho_df['Email'] = m.lowercase(zoho_df, 'Email')
m.clean_space(zoho_df, 'Email')
m.clean_not_valid_email_format(zoho_df, 'Email')

m.clean_number(df_booking, 'Phone1')
m.clean_number(df_booking, 'Mobile')
df_booking['Email'] = m.lowercase(df_booking, 'Email')
m.clean_space(df_booking, 'Email')
m.clean_not_valid_email_format(df_booking, 'Email')

m.clean_number(df_phone, 'Mobile')

df_email['Email'] = m.lowercase(df_email, 'Email')
m.clean_space(df_email, 'Email')
m.clean_not_valid_email_format(df_email, 'Email')

c:\Users\fajar.fatoni\Documents\Python\Task Offline\zoho_data_app\main_module.py:71: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\zoho_data_app\main_module.py:72: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('[^0-9]','', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\zoho_data_app\main_module.py:94: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\zoho_data_app\main_module.py:71: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\zoho_data_app\main_module.py:72: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('[^0-9]','', regex=True, inplace=True)

'Email'

In [801]:
zoho_df.loc[zoho_df['Phone']=='']

Empty DataFrame
Columns: [Record Id, Created Time, Created Date, First Name, Last Name, Email, Phone, Mobile, Birthdate, Year of Birth, Street, Street2, City, State, Country, Nationality, Booking Status, BookRef, Departure Date, Arrival Date, Card Type, Marital Status, Lead Brand, Lead Sub-Brand, Lead Source, Lead Locations, Lead Source Description, Lead Regions, Lead Status, Email Opt Out, Opt In, GDPR Compliant, Website, Comments, Do you live in Bali?]
Index: []

[0 rows x 35 columns]

In [802]:
count_deleted_wrong_format = m.delete_email_wrong_format(zoho_df, 'Email')
count_after_deleted_wrong_format = zoho_df.shape[0]

In [803]:
# hitung jumlah duplicate
count_duplicate_general = zoho_df.loc[zoho_df.duplicated(subset=['Phone','Email', 'Mobile'])].shape[0]

zoho_df.loc[zoho_df.duplicated(subset=['Phone','Email', 'Mobile'])]

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website,Comments,Do you live in Bali?
5,zcrm_3584690000501151001,2024-07-04 17:27:04,empty,Leanne,Gatt,leannegatt62@gmail.com,61402312248,61402312248,empty,empty,...,General,KE | Web | Destination Karma Kandara,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/k...,empty,false
38,zcrm_3584690000501808001,2024-07-10 13:46:17,empty,Rhonda,Parkinson,ronnieparkinson15@gmail.com,61452421117,61452421117,empty,empty,...,General,KE | Web | Newsletter Footer,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/thanks/,empty,false
80,zcrm_3584690000503188333,2024-07-23 05:55:37,empty,Anita Jones,Anita Jones,neet68@me.com,610474355043,610474355043,empty,empty,...,General,KE | Web | Destination Karma Kandara Mentari R...,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/k...,empty,false
101,zcrm_3584690000503934144,2024-07-31 19:31:04,empty,David,Newell,newell.david1962@gmail.com,61411507203,61411507203,empty,empty,...,General,KE | Web | Destination | amina-lantana-hoi-an-...,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/find-destinati...,empty,false
113,zcrm_3584690000504138633,2024-08-05 11:34:04,empty,Tevita,Tupou,tevitatupou19@gmail.com,61432284223,61432284223,empty,empty,...,General,KE | Web | Destination The Oceanic Sportel,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/t...,empty,false
161,zcrm_3584690000505648001,2024-08-23 05:49:11,empty,Brad,Hayden,bradhaydenbonvillevalley@gmail.com,61439041886,61439041886,empty,empty,...,empty,KE | WEB | Kandara,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/contact/,empty,false
221,zcrm_3584690000508082001,2024-09-12 16:55:32,empty,Inang,Nang,nangi1397@gmail.com,6285776503618,6285776503618,empty,empty,...,General,KE | Automation Competition | w1apr21 | KE Sal...,SEAP,empty,false,false,false,empty,empty,false
243,zcrm_3584690000508568068,2024-09-20 12:20:48,empty,Edmond,Hui,hlmed429@gmail.com,610413061332,610413061332,empty,empty,...,General,KE | Web | Destination Karma Kandara Mentari R...,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/k...,empty,false
276,zcrm_3584690000509661001,2024-09-29 15:52:49,empty,Philip,Pucci,fillsway@bigpond.com,610419254694,610419254694,empty,empty,...,General,KE | Web | Destination Karma Kandara Mentari R...,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/k...,empty,false
290,zcrm_3584690000510893001,2024-10-04 13:44:33,empty,Jill,Wood ainslie,torridonequine@hotmail.com,61498045631,61498045631,empty,empty,...,General,KE | Web | Destination Karma Kandara Mentari R...,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/k...,empty,false
310,zcrm_3584690000511458161,2024-10-09 14:53:11,empty,Brooke,Eckersley,brookeeckersley@gmail.com,610492421596,610492421596,empty,empty,...,General,"KE | Web | Destination Karma Minoan, Crete, Gr...",SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/k...,empty,false
317,zcrm_3584690000511869424,2024-10-14 12:39:53,empty,benazir,khoshbooie,julilene10@hotmail.com,61431522514,61431522514,empty,empty,...,General,KE | Web | Destination Karma Kandara Mentari R...,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/k...,empty,false
327,zcrm_3584690000512056043,2024-10-16 16:55:58,empty,Nivi,Nishant,nivinishant@gmail.com,610481258288,610481258288,empty,empty,...,General,KE | Web | Destination The Oceanic Sportel,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/hotel-partner/...,empty,false
401,zcrm_3584690000514289337,2024-11-07 15:47:35,empty,sourabh,jain,jainsorabh@gmail.com,919871464600,919871464600,empty,empty,...,General,KE | Web | Destination Jimbaran Bay Resort and...,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/hotel-partner/...,empty,false
422,zcrm_3584690000515262109,2024-11-14 10:22:11,empty,AUBREY NOEL,DOHERTY,adeecleaning@bigpond.com,610417238589,610417238589,empty,empty,...,General,KE | Web | Destination Amina Lantana Hoi An Ho...,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/hotel-partner/...,empty,false
436,zcrm_3584690000516000001,2024-11-22 05:33:01,empty,Paul,Green,paul.green@live.com,61404880880,61404880880,empty,empty,...,empty,KE | WEB | Bayon,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/contact/,empty,false
442,zcrm_3584690000516181067,2024-11-23 16:26:58,empty,Chris,Lourens,angchrislourens@gmail.com,610400039572,610400039572,empty,empty,...,General,KE | Web | Destination Karma Kandara Mentari R...,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/k...,empty,false
452,zcrm_3584690000516413143,2024-11-26 21:00:07,empty,Sofia,Kyriacou,sililildreamer@gmail.com,610411087740,610411087740,empty,empty,...,General,KE | Web | Destination Amina Lantana Hoi An Ho...,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/hotel-partner/...,empty,false
556,zcrm_3584690000519737001,2024-12-27 23:16:19,empty,Devinder,Kumar,kumardevinder24@gmail.com,916239302931,916239302931,empty,empty,...,General,KE3 | FB LMD | Multi Offer Resorts | w4oct19,SEAP,empty,false,false,false,empty,empty,false
558,zcrm_3584690000519768128,2024-12-29 01:53:14,empty,Sandeep,Patni,sandeep_ksl@rediffmail.com,919028011008,919028011008,empty,empty,...,General,KE3 | FB LMD | Multi Offer Resorts | w4oct19,SEAP,empty,false,false,false,empty,empty,false
568,zcrm_3584690000519905040,2025-01-02 23:51:05,empty,empty,Hemixa,itc_paresh@yahoo.com,empty,empty,empty,empty,...,General,KE | Web | Booking Confirmation | 50 Admin,SEAP,New Lead,false,false,false,empty,empty,false
600,zcrm_3584690000520543069,2025-01-10 13:30:16,empty,Charrie,RHI,charriee@hotmail.com,61415290076,61415290076,empty,empty,...,General,KE | Web | Destination Karma Kandara Mentari R...,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/k...,empty,false
603,zcrm_3584690000520701045,2025-01-11 13:53:37,empty,Charrie,Rhi,charriee@hotmail.com,61415290076,61415290076,empty,empty,...,empty,KE | WEB | Kandara,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/contact/,empty,false
656,zcrm_3584690000525622077,2025-02-25 08:03:29,empty,Chirag,Desai,chirag.sydney@gmail.com,610421202261,610421202261,empty,empty,...,General,KE | Web | Destination Karma Kandara Mentari R...,SEAP,Not Qualified,false,false,false,https://karmaexperience.com/destinations/karma...,empty,false
690,zcrm_3584690000526318482,2025-03-03 15:55:29,empty,Manjunath,Pv,pvmanjunath91@gmail.com,619900224088,619900224088,empty,empty,...,empty,KE | WEB | KEPH Oceanic,SEAP,Not Qualified,false,false,false,https://karmaexperience.com/,empty,false
757,zcrm_3584690000527747001,2025-03-11 21:06:20,empty,Abdul Hanan,Sayed,hanan.shah.official@gmail.com,61452436117,61452436117,empty,empty,...,empty,KE | WEB | KEPH Amina,SEAP,Not Qualified,false,false,false,https://karmaexperience.com/,empty,false
758,zcrm_3584690000527756119,2025-03-12 10:55:06,empty,vishal kumar,vishal kumar,vinnierajput1988@gmail.com,610449501565,610449501565,empty,empty,...,General,KE | Web | Destination Amina Lantana Hoi An Ho...,SEAP,Not Qualified,false,false,false,https://karmaexperience.com/destinations/amina...,empty,false
780,zcrm_3584690000529834001,2025-03-15 19:49:57,empty,DR HEMLATA,JADHAV,aayushmsh@yahoo.com,919321221000,919321221000,empty,empty,...,General,KE3 | FB LMD | Multi Offer Resorts | w4oct19,SEAP,empty,false,false,false,empty,empty,false

In [804]:
zoho_df.drop_duplicates(subset=['Phone','Email', 'Mobile'], inplace=True)
zoho_df.reset_index(drop=True, inplace=True)

# hitung jumlah setelah value duplicate dihapus
count_after_dedup_duplicate = zoho_df.shape[0]

zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website,Comments,Do you live in Bali?
0,zcrm_3584690000501053077,2024-07-04 07:54:15,empty,Rishan,Neelawala,littauk@yahoo.co.uk,610433912771,610433912771,empty,empty,...,General,KE | WEB | Contact Us,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/contact/,empty,false
1,zcrm_3584690000501057143,2024-07-04 14:52:47,empty,Yilmaz,Erbas,ylmzerbas@hotmail.com,61423207375,61423207375,empty,empty,...,General,KE | Web | Destination Amina Lantana Hoi An Ho...,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/a...,empty,false
2,zcrm_3584690000501061001,2024-07-03 21:56:57,empty,Michael Roepen,Michael Roepen,cackle067@hotmail.com,61403602041,61403602041,empty,empty,...,General,KE | Web | Destination Amina Lantana Hoi An Ho...,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/a...,empty,false
3,zcrm_3584690000501102002,2024-07-04 06:13:21,empty,Ganesh,Shevkari,gps7777@gmail.com,61423962131,61423962131,empty,empty,...,General,KE | Web | Destination Karma Royal Jimbaran,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/k...,empty,false
4,zcrm_3584690000501132076,2024-07-04 17:31:54,empty,Leanne,Gatt,leannegatt62@gmail.com,61402312248,61402312248,empty,empty,...,General,KE | Web | Destination |,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/#destinationch...,empty,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
762,zcrm_3584690000530696001,2025-03-17 01:03:04,empty,Vherine,Stiller,cherines@live.com.au,61424862780,61424862780,empty,empty,...,empty,KE | WEB | Kandara,SEAP,Not Qualified,false,false,false,https://karmaexperience.com/,empty,false
763,zcrm_3584690000530815033,2025-03-17 09:22:31,empty,Mark,Cross,markcross502@yahoo.com.au,610411606162,610411606162,empty,empty,...,General,"KE | Web | Destination March Samui Resort, Koh...",SEAP,Not Qualified,false,false,false,https://karmaexperience.com/hotel-partner/marc...,empty,false
764,zcrm_3584690000530901644,2025-03-17 13:39:02,empty,Julieanne,Patten,julieannep@westnet.com.au,61428590886,61428590886,empty,empty,...,General,KE | Web | Destination Karma Kandara Mentari R...,SEAP,Not Qualified,false,false,false,https://karmaexperience.com/destinations/karma...,empty,false
765,zcrm_3584690000530902623,2025-03-17 14:35:05,empty,Test2,Thiru93,test034thiru2@gmail.com,61465654565,61465654565,empty,empty,...,empty,KE | WEB | KEPH Pago,SEAP,Not Qualified,false,false,false,https://karmaexperience.com/#,empty,false
766,zcrm_3584690000531042001,2025-03-17 14:55:56,empty,Tanya,Esterhuizen,tanyaglam2@gmail.com,610405140796,610405140796,empty,1971,...,General,KE3 | EDM | KARMA KAMELEON - KARMA KANDARA | w...,SEAP,empty,false,false,false,empty,empty,false

In [805]:
# Cek leads test
test_leads = zoho_df.loc[
    
        zoho_df['Email'].str.contains('^test@', flags=re.I, regex=True) |
        zoho_df['Email'].str.contains('\+test', flags=re.I, regex=True) |
    
        zoho_df['First Name'].str.contains('^test$', flags=re.I, regex=True) |
        zoho_df['Last Name'].str.contains('^test$', flags=re.I, regex=True) |

        zoho_df['First Name'].str.contains('test 1', flags=re.I, regex=True) |
        zoho_df['Last Name'].str.contains('test 2', flags=re.I, regex=True)|
        zoho_df['First Name'].str.contains('test1', flags=re.I, regex=True) |
        zoho_df['Last Name'].str.contains('test2', flags=re.I, regex=True)|

        zoho_df['First Name'].str.contains(' test ', flags=re.I, regex=True) | 
        zoho_df['Last Name'].str.contains(' test ', flags=re.I, regex=True) | 
        zoho_df['Last Name'].str.contains(' test$', flags=re.I, regex=True)
    ]

count_leads_test = test_leads.shape[0]

# test_leads.to_excel(r'C:\Users\fajar.fatoni\Documents\Python\Data\test_leads_2.xlsx', index=False)
test_leads

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website,Comments,Do you live in Bali?
725,zcrm_3584690000527717001,2025-03-11 19:42:54,empty,test,asdas,asdasdg@gmail.com,618889888889,618889888889,empty,empty,...,empty,KE | WEB | Kandara,SEAP,Not Qualified,false,false,false,https://karmaexperience.com/,empty,false
761,zcrm_3584690000530642578,2025-03-17 13:52:57,empty,Test,Thiru,test305thi3ru@gmail.com,912313212123,912313212123,empty,empty,...,empty,KE | WEB | Jimbaran,SEAP,Not Qualified,false,false,false,https://karmaexperience.com/,empty,false

In [806]:
zoho_df.drop(test_leads.index, inplace=True)
zoho_df.reset_index(drop=True, inplace=True)

count_after_dedup_test = zoho_df.shape[0]

In [807]:
# dnm_leads = zoho_df.loc[(zoho_df['Do Not Mail'] == 'true') | (zoho_df['Do Not Contact'] == 'true')]
# count_dnm = dnm_leads.shape[0]

In [808]:
# zoho_df.drop(dnm_leads.index, inplace=True)
# zoho_df.reset_index(drop=True, inplace=True)

# count_after_dedup_dnm = zoho_df.shape[0]

In [809]:
# Cek Email OTA
email_OTA = m.find_OTA(zoho_df, 'Email')
count_email_OTA = email_OTA.shape[0]
# email_OTA.to_excel(r'C:\Users\fajar.fatoni\Documents\Python\Data\email_OTA.xlsx', index=False)

email_OTA

Empty DataFrame
Columns: [Record Id, Created Time, Created Date, First Name, Last Name, Email, Phone, Mobile, Birthdate, Year of Birth, Street, Street2, City, State, Country, Nationality, Booking Status, BookRef, Departure Date, Arrival Date, Card Type, Marital Status, Lead Brand, Lead Sub-Brand, Lead Source, Lead Locations, Lead Source Description, Lead Regions, Lead Status, Email Opt Out, Opt In, GDPR Compliant, Website, Comments, Do you live in Bali?]
Index: []

[0 rows x 35 columns]

In [810]:
# delete email OTA
count_after_clean_OTA = m.delete_OTA(zoho_df, 'Email')
# zoho_df.to_excel(r'C:\Users\fajar.fatoni\Documents\Python\Data\after_clean_OTA.xlsx', index=False)

zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website,Comments,Do you live in Bali?
0,zcrm_3584690000501053077,2024-07-04 07:54:15,empty,Rishan,Neelawala,littauk@yahoo.co.uk,610433912771,610433912771,empty,empty,...,General,KE | WEB | Contact Us,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/contact/,empty,false
1,zcrm_3584690000501057143,2024-07-04 14:52:47,empty,Yilmaz,Erbas,ylmzerbas@hotmail.com,61423207375,61423207375,empty,empty,...,General,KE | Web | Destination Amina Lantana Hoi An Ho...,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/a...,empty,false
2,zcrm_3584690000501061001,2024-07-03 21:56:57,empty,Michael Roepen,Michael Roepen,cackle067@hotmail.com,61403602041,61403602041,empty,empty,...,General,KE | Web | Destination Amina Lantana Hoi An Ho...,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/a...,empty,false
3,zcrm_3584690000501102002,2024-07-04 06:13:21,empty,Ganesh,Shevkari,gps7777@gmail.com,61423962131,61423962131,empty,empty,...,General,KE | Web | Destination Karma Royal Jimbaran,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/k...,empty,false
4,zcrm_3584690000501132076,2024-07-04 17:31:54,empty,Leanne,Gatt,leannegatt62@gmail.com,61402312248,61402312248,empty,empty,...,General,KE | Web | Destination |,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/#destinationch...,empty,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
760,zcrm_3584690000530696001,2025-03-17 01:03:04,empty,Vherine,Stiller,cherines@live.com.au,61424862780,61424862780,empty,empty,...,empty,KE | WEB | Kandara,SEAP,Not Qualified,false,false,false,https://karmaexperience.com/,empty,false
761,zcrm_3584690000530815033,2025-03-17 09:22:31,empty,Mark,Cross,markcross502@yahoo.com.au,610411606162,610411606162,empty,empty,...,General,"KE | Web | Destination March Samui Resort, Koh...",SEAP,Not Qualified,false,false,false,https://karmaexperience.com/hotel-partner/marc...,empty,false
762,zcrm_3584690000530901644,2025-03-17 13:39:02,empty,Julieanne,Patten,julieannep@westnet.com.au,61428590886,61428590886,empty,empty,...,General,KE | Web | Destination Karma Kandara Mentari R...,SEAP,Not Qualified,false,false,false,https://karmaexperience.com/destinations/karma...,empty,false
763,zcrm_3584690000530902623,2025-03-17 14:35:05,empty,Test2,Thiru93,test034thiru2@gmail.com,61465654565,61465654565,empty,empty,...,empty,KE | WEB | KEPH Pago,SEAP,Not Qualified,false,false,false,https://karmaexperience.com/#,empty,false
764,zcrm_3584690000531042001,2025-03-17 14:55:56,empty,Tanya,Esterhuizen,tanyaglam2@gmail.com,610405140796,610405140796,empty,1971,...,General,KE3 | EDM | KARMA KAMELEON - KARMA KANDARA | w...,SEAP,empty,false,false,false,empty,empty,false

In [811]:
# Cek Email Karma
email_karma = m.find_karma(zoho_df, 'Email')
count_email_karma = email_karma.shape[0]
# email_OTA.to_excel(r'C:\Users\fajar.fatoni\Documents\Python\Data\email_OTA.xlsx', index=False)

email_karma

Empty DataFrame
Columns: [Record Id, Created Time, Created Date, First Name, Last Name, Email, Phone, Mobile, Birthdate, Year of Birth, Street, Street2, City, State, Country, Nationality, Booking Status, BookRef, Departure Date, Arrival Date, Card Type, Marital Status, Lead Brand, Lead Sub-Brand, Lead Source, Lead Locations, Lead Source Description, Lead Regions, Lead Status, Email Opt Out, Opt In, GDPR Compliant, Website, Comments, Do you live in Bali?]
Index: []

[0 rows x 35 columns]

In [812]:
# delete email Karma
count_after_clean_karma = m.delete_karma(zoho_df, 'Email')
# zoho_df.to_excel(r'C:\Users\fajar.fatoni\Documents\Python\Data\after_clean_OTA.xlsx', index=False)

zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website,Comments,Do you live in Bali?
0,zcrm_3584690000501053077,2024-07-04 07:54:15,empty,Rishan,Neelawala,littauk@yahoo.co.uk,610433912771,610433912771,empty,empty,...,General,KE | WEB | Contact Us,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/contact/,empty,false
1,zcrm_3584690000501057143,2024-07-04 14:52:47,empty,Yilmaz,Erbas,ylmzerbas@hotmail.com,61423207375,61423207375,empty,empty,...,General,KE | Web | Destination Amina Lantana Hoi An Ho...,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/a...,empty,false
2,zcrm_3584690000501061001,2024-07-03 21:56:57,empty,Michael Roepen,Michael Roepen,cackle067@hotmail.com,61403602041,61403602041,empty,empty,...,General,KE | Web | Destination Amina Lantana Hoi An Ho...,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/a...,empty,false
3,zcrm_3584690000501102002,2024-07-04 06:13:21,empty,Ganesh,Shevkari,gps7777@gmail.com,61423962131,61423962131,empty,empty,...,General,KE | Web | Destination Karma Royal Jimbaran,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/destinations/k...,empty,false
4,zcrm_3584690000501132076,2024-07-04 17:31:54,empty,Leanne,Gatt,leannegatt62@gmail.com,61402312248,61402312248,empty,empty,...,General,KE | Web | Destination |,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/#destinationch...,empty,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
760,zcrm_3584690000530696001,2025-03-17 01:03:04,empty,Vherine,Stiller,cherines@live.com.au,61424862780,61424862780,empty,empty,...,empty,KE | WEB | Kandara,SEAP,Not Qualified,false,false,false,https://karmaexperience.com/,empty,false
761,zcrm_3584690000530815033,2025-03-17 09:22:31,empty,Mark,Cross,markcross502@yahoo.com.au,610411606162,610411606162,empty,empty,...,General,"KE | Web | Destination March Samui Resort, Koh...",SEAP,Not Qualified,false,false,false,https://karmaexperience.com/hotel-partner/marc...,empty,false
762,zcrm_3584690000530901644,2025-03-17 13:39:02,empty,Julieanne,Patten,julieannep@westnet.com.au,61428590886,61428590886,empty,empty,...,General,KE | Web | Destination Karma Kandara Mentari R...,SEAP,Not Qualified,false,false,false,https://karmaexperience.com/destinations/karma...,empty,false
763,zcrm_3584690000530902623,2025-03-17 14:35:05,empty,Test2,Thiru93,test034thiru2@gmail.com,61465654565,61465654565,empty,empty,...,empty,KE | WEB | KEPH Pago,SEAP,Not Qualified,false,false,false,https://karmaexperience.com/#,empty,false
764,zcrm_3584690000531042001,2025-03-17 14:55:56,empty,Tanya,Esterhuizen,tanyaglam2@gmail.com,610405140796,610405140796,empty,1971,...,General,KE3 | EDM | KARMA KAMELEON - KARMA KANDARA | w...,SEAP,empty,false,false,false,empty,empty,false

In [813]:
find_member_booking = zoho_df.copy()

find_member_booking.loc[find_member_booking['Phone'].isin(df_booking['Phone1']), 'Same Value Find'] = 'Booking-Phone1'
find_member_booking.loc[find_member_booking['Phone'].isin(df_booking['Mobile']), 'Same Value Find'] = 'Booking-Mobile'
find_member_booking.loc[find_member_booking['Mobile'].isin(df_booking['Phone1']), 'Same Value Find'] = 'Booking-Phone1' 
find_member_booking.loc[find_member_booking['Mobile'].isin(df_booking['Mobile']), 'Same Value Find'] = 'Booking-Mobile'
find_member_booking.loc[find_member_booking['Email'].isin(df_booking['Email']), 'Same Value Find'] = 'Booking-Email'

find_member_booking.loc[find_member_booking['Phone'].isin(df_phone['Mobile']), 'Same Value Find'] = 'Member-Mobile' 
find_member_booking.loc[find_member_booking['Mobile'].isin(df_phone['Mobile']), 'Same Value Find'] = 'Member-Mobile'

find_member_booking.loc[find_member_booking['Email'].isin(df_email['Email']), 'Same Value Find'] = 'Member-Email'

find_member_booking.drop(find_member_booking.loc[find_member_booking['Same Value Find'].isna()].index, inplace=True)

count_booking_dedup = find_member_booking.loc[find_member_booking['Same Value Find'].str.contains('Booking', flags=re.I, regex=True)].shape[0]
count_member_dedup = find_member_booking.loc[find_member_booking['Same Value Find'].str.contains('Member', flags=re.I, regex=True)].shape[0]

find_member_booking.replace('empty', '', inplace=True)
# find_member_booking.to_csv(r'C:\Users\fajar.fatoni\Documents\Python\Data\booking-member-dedup.csv', index=False)
# find_member_booking.to_excel(r'C:\Users\fajar.fatoni\Documents\Python\Data\booking-member-dedup.xlsx', index=False)

#find_member_booking.loc[find_member_booking['Same Value Find'] == 'Booking-Phone1']

In [814]:
# data phone, mobile dam email member yang ada di master data 
count_wash_member = zoho_df.loc[
    zoho_df['Phone'].isin(df_booking['Phone1']) | 
    zoho_df['Phone'].isin(df_booking['Mobile']) |
    zoho_df['Mobile'].isin(df_booking['Phone1']) | 
    zoho_df['Mobile'].isin(df_booking['Mobile']) |
    zoho_df['Email'].isin(df_booking['Email'])| 

    zoho_df['Phone'].isin(df_phone['Mobile']) | 
    zoho_df['Mobile'].isin(df_phone['Mobile']) |

    zoho_df['Email'].isin(df_email['Email'])

].shape[0]

zoho_df.drop(zoho_df.loc[
    zoho_df['Phone'].isin(df_booking['Phone1']) | 
    zoho_df['Phone'].isin(df_booking['Mobile']) |
    zoho_df['Mobile'].isin(df_booking['Phone1']) | 
    zoho_df['Mobile'].isin(df_booking['Mobile']) |
    zoho_df['Email'].isin(df_booking['Email']) |
    
    zoho_df['Phone'].isin(df_phone['Mobile']) | 
    zoho_df['Mobile'].isin(df_phone['Mobile']) |

    zoho_df['Email'].isin(df_email['Email'])

    ].index, inplace=True)
    
zoho_df.reset_index(drop=True, inplace=True)

count_after_wash_member = zoho_df.shape[0]

In [815]:
# Categorize contacts
m.categorize_contacts(zoho_df)

# Count contact types
count_email_only = (zoho_df['Contact Type'] == 'Email Only').sum()
count_phone_only = (zoho_df['Contact Type'] == 'Phone Only').sum()
count_email_and_phone = (zoho_df['Contact Type'] == 'Email and Phone').sum()
count_blank = (zoho_df['Contact Type'] == 'Blank').sum()

# Remove blank contacts if needed
zoho_df = zoho_df[zoho_df['Contact Type'] != 'Blank']
zoho_df.reset_index(drop=True, inplace=True)

count_after_wash_blank = zoho_df.shape[0]

In [816]:
arr_dedup = [count_deleted_wrong_format, count_duplicate_general, count_leads_test, count_email_OTA, count_email_karma, count_blank]
count_sum_dedup = sum(arr_dedup)
count_sum_dedup

np.int64(30)

In [817]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Keseluruhan Master Zoho : "+str(count_data_awal))
print("Jumlah Filter Leads Awal : "+str(count_filter_awal))
print("Jumlah Format Email Salah : "+str(count_deleted_wrong_format))
print("Jumlah Setelah Clean Format Email Salah : "+str(count_after_deleted_wrong_format))
print("Jumlah Duplicate (Phone, Mobile dan Email) : "+str(count_duplicate_general))
print("Jumlah Setelah Clean Duplicate : "+str(count_after_dedup_duplicate))
print("Jumlah Lead Test : "+str(count_leads_test))
print("Jumlah Setelah Clean Lead Test : "+str(count_after_dedup_test))
# print("Jumlah Lead Do Not Mail : "+str(count_dnm))
# print("Jumlah Setelah Clean Lead Do Not Mail : "+str(count_after_dedup_dnm))
print("Jumlah Email OTA : "+str(count_email_OTA))
print("Jumlah Setelah Clean Email OTA : "+str(count_after_clean_OTA))
print("Jumlah Email Karma : "+str(count_email_karma))
print("Jumlah Setelah Clean Email Karma : "+str(count_after_clean_karma))
print("Jumlah Wash Member : "+str(count_member_dedup))
print("Jumlah Wash Booking : "+str(count_booking_dedup))
print("Jumlah Setelah Wash Member : "+str(count_after_wash_member))
print("Jumlah Phone Email Blank (Setelah phone yang tidak valid dihapus) : "+str(count_blank))
print("Jumlah Setelah Wash Phone Email Blank : "+str(count_after_wash_blank))
print("==========================================================")
print("Contact Type")
print("==========================================================")
print("Jumlah Email Only : "+str(count_email_only))
print("Jumlah Phone Only : "+str(count_phone_only))
print("Jumlah Email dan Phone : "+str(count_email_and_phone))

==========================================================
Summary
==========================================================
Jumlah Keseluruhan Master Zoho : 500015
Jumlah Filter Leads Awal : 795
Jumlah Format Email Salah : 0
Jumlah Setelah Clean Format Email Salah : 795
Jumlah Duplicate (Phone, Mobile dan Email) : 28
Jumlah Setelah Clean Duplicate : 767
Jumlah Lead Test : 2
Jumlah Setelah Clean Lead Test : 765
Jumlah Email OTA : 0
Jumlah Setelah Clean Email OTA : 765
Jumlah Email Karma : 0
Jumlah Setelah Clean Email Karma : 765
Jumlah Wash Member : 44
Jumlah Wash Booking : 16
Jumlah Setelah Wash Member : 705
Jumlah Phone Email Blank (Setelah phone yang tidak valid dihapus) : 0
Jumlah Setelah Wash Phone Email Blank : 705
==========================================================
Contact Type
==========================================================
Jumlah Email Only : 8
Jumlah Phone Only : 0
Jumlah Email dan Phone : 697

In [818]:
print("==========================================================")
print("Summary Report")
print("==========================================================")
print("Jumlah Data Awal : "+str(count_filter_awal))
print("Jumlah Wash Dedup : "+str(count_sum_dedup))
print("Jumlah Wash Member : "+str(count_member_dedup))
print("Jumlah Wash Booking : "+str(count_booking_dedup))
print("Jumlah Data Akhir : "+str(count_after_wash_blank))

==========================================================
Summary Report
==========================================================
Jumlah Data Awal : 795
Jumlah Wash Dedup : 30
Jumlah Wash Member : 44
Jumlah Wash Booking : 16
Jumlah Data Akhir : 705

# ====================== Akhir Filter Umum ======================

In [ ]:
# Function to clean illegal characters except "Created Time"
def clean_illegal_chars(df):
    def remove_illegal_chars(value):
        if isinstance(value, str):
            return "".join(c for c in value if ord(c) >= 32)
        return value
    
    # Apply cleaning only to non-"Created Time" columns
    for col in df.columns:
        if col != "Created Time":  # Exclude "Created Time" from cleaning
            df[col] = df[col].apply(remove_illegal_chars)

    return df

# Load your dataframe (zoho_df assumed to be already loaded)
zoho_df.replace('empty', '', inplace=True, regex=True)

# Format name columns properly
zoho_df['First Name'] = zoho_df['First Name'].str.title()
zoho_df['Last Name'] = zoho_df['Last Name'].str.title()

# Define output path
output_path = r'C:\Users\fajar.fatoni\Documents\Python\Data\karma_experience.xlsx'

try:
    zoho_df.to_excel(output_path, index=False)
except IllegalCharacterError:
    print("IllegalCharacterError detected! Cleaning data...")
    zoho_df = clean_illegal_chars(zoho_df)  # Clean only non-"Created Time" columns
    zoho_df.to_excel(output_path, index=False)
    print("File saved successfully after cleaning.")

print(f"File saved at: {output_path}")

File saved at: C:\Users\fajar.fatoni\Documents\Python\Data\karma_experience.xlsx

In [820]:
zoho_df.groupby('Country').count()

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website,Comments,Do you live in Bali?,Contact Type
Country,,,,,,,,,,,,,,,,,,,,,
,7,7,7,7,7,7,7,7,7,7,...,7,7,7,7,7,7,7,7,7,7
Australia,569,569,569,569,569,569,569,569,569,569,...,569,569,569,569,569,569,569,569,569,569
Brunei,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Canada,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Denmark,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
France,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Germany,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Hong Kong,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
India,74,74,74,74,74,74,74,74,74,74,...,74,74,74,74,74,74,74,74,74,74
Indonesia,18,18,18,18,18,18,18,18,18,18,...,18,18,18,18,18,18,18,18,18,18
Ireland,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Israel,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Latvia,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Malaysia,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Montenegro,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Nepal,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Philippines,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Singapore,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
Spain,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Thailand,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Thailand (ไทย),1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Tunisia,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
United Arab Emirates,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
United Kingdom,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
United States,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6

In [821]:
# zoho_df['Country'].loc[
#     (zoho_df['Phone'].str.contains('^44|^\+44')) & 
#     (~zoho_df['Country'].str.contains('united kingdom|wales|england|scotland|northern ireland', regex=True, flags=re.I))
# ]