In [ ]:
import main_module as m
import zoho_filter_module as fil
import pandas as pd
import re
import numpy as np

%load_ext autoreload
%autoreload 2

cols = ['Record Id',	
'Created Time',
'Created Date',	
'First Name',	
'Last Name',	
'Email',	
'Phone',	
'Mobile',	
'Birthdate',	
'Year of Birth',
'Street',	
'Street2',	
'City',	
'State',	
'Country',	
'Nationality',
'Booking Status', 
'BookRef',
'Departure Date',	
'Arrival Date',	
'Card Type',	
'Marital Status',	
'Lead Brand',	
'Lead Sub-Brand',	
'Lead Source',	
'Lead Locations',	
'Lead Source Description',	
'Lead Regions',
'Lead Status',
'Email Opt Out',	
'Opt In']

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [48]:
path = r'C:\Users\fajar.fatoni\Documents\Python\Data\Karma Kandara - Wedding Leads.xlsx'
# zoho_df = pd.read_csv(path, dtype='string')
zoho_df = pd.read_excel(path, dtype='string', sheet_name='KK Wedding Leads')

zoho_df.reset_index(drop=True, inplace=True)
count_filter_awal = zoho_df.shape[0]

# mengisi kolom <NA> dengan value string 'empty' supaya mudah mengecek data member dan booking dengan isin
zoho_df.fillna('empty', inplace=True)

zoho_df['Mobile'] = 'empty'
# zoho_df['Phone'] = 'empty'
zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,City,Country,Lead Brand,...,Which type of wedding package are you interested,Approximately when are you planning to book wed,What is the estimated size of your guest list?,Agency Name,Messages,Description/Deal Stage,Enquiry/Budget,Comments,Website,Mobile
0,zcrm_3584690000535783234,2025-04-04 11:46:26,2025-04-03 00:00:00,Dani,Love,empty,61433287423,Sydney,Australia,Karma Resorts,...,empty,empty,Guest <49,ONTOP Agency,empty,? Qualified Lead,empty,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
1,zcrm_3584690000535783235,2025-04-04 11:46:26,2025-04-03 00:00:00,Danielle,Love,danielle.love@outlook.com.au,61433287423,Sydney,Australia,Karma Resorts,...,empty,empty,empty,ONTOP Agency,empty,? Qualified Lead,empty,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
2,zcrm_3584690000535783236,2025-04-04 11:46:26,2025-04-03 00:00:00,Reece,Limond,empty,61421081363,Sydney,Australia,Karma Resorts,...,empty,empty,Guest <49,ONTOP Agency,empty,? Qualified Lead,Budget 10 - 25K AUD,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
3,zcrm_3584690000535783237,2025-04-04 11:46:26,2025-04-02 00:00:00,Isaac,Lake,empty,61420562484,Sydney,Australia,Karma Resorts,...,empty,empty,Guest 50-99,ONTOP Agency,empty,?ï¸_x008f_First Contact,Budget 10 - 25K AUD,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
4,zcrm_3584690000535783238,2025-04-04 11:46:26,2025-04-02 00:00:00,Mariana,-,empty,61422438172,Sydney,Australia,Karma Resorts,...,empty,empty,Guest <49,ONTOP Agency,empty,?ï¸_x008f_First Contact,empty,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3346,zcrm_3584690000088602263,2019-08-05 17:22:05,2021-07-21 00:00:00,Andy,Cocoy,legacywo@hotmail.com,6287823303095,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,empty,empty
3347,zcrm_3584690000053541163,2019-06-27 20:37:26,2021-07-21 00:00:00,Imaa,-,masace@indo.net.id,628123914666,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,"Reservation ref. - Retail Agent , Market - Do...",empty,empty
3348,zcrm_3584690000029445895,2019-05-08 18:44:25,2021-07-21 00:00:00,Ekin,-,lebali.international@gmail.com,6281933035158,Badung,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,"Market: India, Segmentation: Overseas Agent",empty,empty
3349,zcrm_3584690000024815001,2019-04-08 22:44:50,2021-07-21 00:00:00,Viki,Kurniadi,vikikurniadi@gmail.com,628122376517,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,empty,empty
3350,zcrm_3584690000001674307,2019-02-08 17:46:35,2021-07-21 00:00:00,Calvin,Aprileo,calvinaprileo@yahoo.com,6282112898950,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,BGID | FB3 | w4dec18 | Harris Hotel Seminyak,empty,empty,empty,empty

In [49]:
path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04eXpvS1NXTWF2RVE\_BOOKING\Booking By Year\FlyBuy Booking Data (BGAU & BGID & KE).xlsx'
df_booking = pd.read_excel(path, dtype='string', sheet_name='BOOKING_BGAU_BGID_KE')

path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04UUNBME5GOVhoMjA\_ODYSSEY\Phone Members.xlsx'
df_phone = pd.read_excel(path, dtype='string', sheet_name='Sheet1')

path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04UUNBME5GOVhoMjA\_ODYSSEY\Email Members.xlsx'
df_email = pd.read_excel(path, dtype='string', sheet_name='Sheet1')

# ====================== Awal Filter Umum ======================

In [50]:
# data phone, mobile dam email member yang ada di master data (wash member)

m.clean_number(zoho_df, 'Phone')
m.clean_number(zoho_df, 'Mobile')
m.replace_not_valid_to_empty(zoho_df, 'Phone')
m.replace_not_valid_to_empty(zoho_df, 'Mobile')
zoho_df['Email'] = m.lowercase(zoho_df, 'Email')
m.clean_space(zoho_df, 'Email')
m.clean_not_valid_email_format(zoho_df, 'Email')

m.clean_number(df_booking, 'Phone1')
m.clean_number(df_booking, 'Mobile')
df_booking['Email'] = m.lowercase(df_booking, 'Email')
m.clean_space(df_booking, 'Email')
m.clean_not_valid_email_format(df_booking, 'Email')

m.clean_number(df_phone, 'Mobile')

df_email['Email'] = m.lowercase(df_email, 'Email')
m.clean_space(df_email, 'Email')
m.clean_not_valid_email_format(df_email, 'Email')

c:\Users\fajar.fatoni\Documents\Python\Task Offline\zoho_data_app\main_module.py:71: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\zoho_data_app\main_module.py:72: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('[^0-9]','', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\zoho_data_app\main_module.py:94: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\zoho_data_app\main_module.py:71: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace(' ','', regex=True, inplace=True)
c:\Users\fajar.fatoni\Documents\Python\Task Offline\zoho_data_app\main_module.py:72: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[df_columns].replace('[^0-9]','', regex=True, inplace=True)

'Email'

In [51]:
count_deleted_wrong_format = m.delete_email_wrong_format(zoho_df, 'Email')
count_after_deleted_wrong_format = zoho_df.shape[0]

# ====================== Akhir Filter Umum ======================

In [52]:
# hitung jumlah duplicate
count_duplicate_general = zoho_df.loc[zoho_df.duplicated(subset=['Phone','Mobile','Email','Lead Source Description'])].shape[0]

zoho_df.loc[zoho_df.duplicated(subset=['Phone','Mobile','Email','Lead Source Description'])]

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,City,Country,Lead Brand,...,Which type of wedding package are you interested,Approximately when are you planning to book wed,What is the estimated size of your guest list?,Agency Name,Messages,Description/Deal Stage,Enquiry/Budget,Comments,Website,Mobile
705,zcrm_3584690000504001050,2024-07-31 17:27:34,2024-07-31 00:00:00,Sherina,-,empty,empty,empty,empty,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,empty,empty

In [53]:
zoho_df.drop_duplicates(subset=['Phone','Mobile','Email','Lead Source Description'], inplace=True)
zoho_df.reset_index(drop=True, inplace=True)

# hitung jumlah setelah value duplicate dihapus
count_after_dedup_duplicate = zoho_df.shape[0]

zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,City,Country,Lead Brand,...,Which type of wedding package are you interested,Approximately when are you planning to book wed,What is the estimated size of your guest list?,Agency Name,Messages,Description/Deal Stage,Enquiry/Budget,Comments,Website,Mobile
0,zcrm_3584690000535783234,2025-04-04 11:46:26,2025-04-03 00:00:00,Dani,Love,empty,61433287423,Sydney,Australia,Karma Resorts,...,empty,empty,Guest <49,ONTOP Agency,empty,? Qualified Lead,empty,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
1,zcrm_3584690000535783235,2025-04-04 11:46:26,2025-04-03 00:00:00,Danielle,Love,danielle.love@outlook.com.au,61433287423,Sydney,Australia,Karma Resorts,...,empty,empty,empty,ONTOP Agency,empty,? Qualified Lead,empty,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
2,zcrm_3584690000535783236,2025-04-04 11:46:26,2025-04-03 00:00:00,Reece,Limond,empty,61421081363,Sydney,Australia,Karma Resorts,...,empty,empty,Guest <49,ONTOP Agency,empty,? Qualified Lead,Budget 10 - 25K AUD,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
3,zcrm_3584690000535783237,2025-04-04 11:46:26,2025-04-02 00:00:00,Isaac,Lake,empty,61420562484,Sydney,Australia,Karma Resorts,...,empty,empty,Guest 50-99,ONTOP Agency,empty,?ï¸_x008f_First Contact,Budget 10 - 25K AUD,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
4,zcrm_3584690000535783238,2025-04-04 11:46:26,2025-04-02 00:00:00,Mariana,-,empty,61422438172,Sydney,Australia,Karma Resorts,...,empty,empty,Guest <49,ONTOP Agency,empty,?ï¸_x008f_First Contact,empty,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3345,zcrm_3584690000088602263,2019-08-05 17:22:05,2021-07-21 00:00:00,Andy,Cocoy,legacywo@hotmail.com,6287823303095,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,empty,empty
3346,zcrm_3584690000053541163,2019-06-27 20:37:26,2021-07-21 00:00:00,Imaa,-,masace@indo.net.id,628123914666,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,"Reservation ref. - Retail Agent , Market - Do...",empty,empty
3347,zcrm_3584690000029445895,2019-05-08 18:44:25,2021-07-21 00:00:00,Ekin,-,lebali.international@gmail.com,6281933035158,Badung,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,"Market: India, Segmentation: Overseas Agent",empty,empty
3348,zcrm_3584690000024815001,2019-04-08 22:44:50,2021-07-21 00:00:00,Viki,Kurniadi,vikikurniadi@gmail.com,628122376517,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,empty,empty
3349,zcrm_3584690000001674307,2019-02-08 17:46:35,2021-07-21 00:00:00,Calvin,Aprileo,calvinaprileo@yahoo.com,6282112898950,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,BGID | FB3 | w4dec18 | Harris Hotel Seminyak,empty,empty,empty,empty

In [54]:
# # Cek leads test
# test_leads = zoho_df.loc[
    
#         zoho_df['Email'].str.contains('^test@', flags=re.I, regex=True) |
#         zoho_df['Email'].str.contains('\+test', flags=re.I, regex=True) |
    
#         zoho_df['First Name'].str.contains('^test$', flags=re.I, regex=True) |
#         zoho_df['Last Name'].str.contains('^test$', flags=re.I, regex=True) |

#         zoho_df['First Name'].str.contains('test 1', flags=re.I, regex=True) |
#         zoho_df['Last Name'].str.contains('test 2', flags=re.I, regex=True)|
#         zoho_df['First Name'].str.contains('test1', flags=re.I, regex=True) |
#         zoho_df['Last Name'].str.contains('test2', flags=re.I, regex=True)|

#         zoho_df['First Name'].str.contains(' test ', flags=re.I, regex=True) | 
#         zoho_df['Last Name'].str.contains(' test ', flags=re.I, regex=True) | 
#         zoho_df['Last Name'].str.contains(' test$', flags=re.I, regex=True)
#     ]

# count_leads_test = test_leads.shape[0]

# # test_leads.to_excel(r'C:\Users\fajar.fatoni\Documents\Python\Data\Beambox\test_leads_2.xlsx', index=False)
# test_leads

In [55]:
# zoho_df.drop(test_leads.index, inplace=True)
# zoho_df.reset_index(drop=True, inplace=True)

# count_after_dedup_test = zoho_df.shape[0]

In [56]:
# dnm_leads = zoho_df.loc[(zoho_df['Do Not Mail'] == 'true') | (zoho_df['Do Not Contact'] == 'true')]
# count_dnm = dnm_leads.shape[0]

In [57]:
# zoho_df.drop(dnm_leads.index, inplace=True)
# zoho_df.reset_index(drop=True, inplace=True)

# count_after_dedup_dnm = zoho_df.shape[0]

In [58]:
# Cek Email OTA
email_OTA = m.find_OTA(zoho_df, 'Email')
count_email_OTA = email_OTA.shape[0]
# email_OTA.to_excel(r'C:\Users\fajar.fatoni\Documents\Python\Data\Beambox\email_OTA.xlsx', index=False)

email_OTA

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,City,Country,Lead Brand,...,Which type of wedding package are you interested,Approximately when are you planning to book wed,What is the estimated size of your guest list?,Agency Name,Messages,Description/Deal Stage,Enquiry/Budget,Comments,Website,Mobile
3333,zcrm_3584690000301303893,2021-07-21 16:59:49,2021-07-21 00:00:00,Susan,"Kosasih, SE",baliamazingtour@yahoo.com,628126373522,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,empty,empty
3336,zcrm_3584690000301303943,2021-07-21 16:59:49,2021-07-21 00:00:00,Chatarina,Riris,chatarina.riris@lestaritour.com,6281802718899,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,empty,empty

In [59]:
# delete email OTA
count_after_clean_OTA = m.delete_OTA(zoho_df, 'Email')
# zoho_df.to_excel(r'C:\Users\fajar.fatoni\Documents\Python\Data\Beambox\after_clean_OTA.xlsx', index=False)

zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,City,Country,Lead Brand,...,Which type of wedding package are you interested,Approximately when are you planning to book wed,What is the estimated size of your guest list?,Agency Name,Messages,Description/Deal Stage,Enquiry/Budget,Comments,Website,Mobile
0,zcrm_3584690000535783234,2025-04-04 11:46:26,2025-04-03 00:00:00,Dani,Love,empty,61433287423,Sydney,Australia,Karma Resorts,...,empty,empty,Guest <49,ONTOP Agency,empty,? Qualified Lead,empty,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
1,zcrm_3584690000535783235,2025-04-04 11:46:26,2025-04-03 00:00:00,Danielle,Love,danielle.love@outlook.com.au,61433287423,Sydney,Australia,Karma Resorts,...,empty,empty,empty,ONTOP Agency,empty,? Qualified Lead,empty,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
2,zcrm_3584690000535783236,2025-04-04 11:46:26,2025-04-03 00:00:00,Reece,Limond,empty,61421081363,Sydney,Australia,Karma Resorts,...,empty,empty,Guest <49,ONTOP Agency,empty,? Qualified Lead,Budget 10 - 25K AUD,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
3,zcrm_3584690000535783237,2025-04-04 11:46:26,2025-04-02 00:00:00,Isaac,Lake,empty,61420562484,Sydney,Australia,Karma Resorts,...,empty,empty,Guest 50-99,ONTOP Agency,empty,?ï¸_x008f_First Contact,Budget 10 - 25K AUD,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
4,zcrm_3584690000535783238,2025-04-04 11:46:26,2025-04-02 00:00:00,Mariana,-,empty,61422438172,Sydney,Australia,Karma Resorts,...,empty,empty,Guest <49,ONTOP Agency,empty,?ï¸_x008f_First Contact,empty,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3343,zcrm_3584690000088602263,2019-08-05 17:22:05,2021-07-21 00:00:00,Andy,Cocoy,legacywo@hotmail.com,6287823303095,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,empty,empty
3344,zcrm_3584690000053541163,2019-06-27 20:37:26,2021-07-21 00:00:00,Imaa,-,masace@indo.net.id,628123914666,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,"Reservation ref. - Retail Agent , Market - Do...",empty,empty
3345,zcrm_3584690000029445895,2019-05-08 18:44:25,2021-07-21 00:00:00,Ekin,-,lebali.international@gmail.com,6281933035158,Badung,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,"Market: India, Segmentation: Overseas Agent",empty,empty
3346,zcrm_3584690000024815001,2019-04-08 22:44:50,2021-07-21 00:00:00,Viki,Kurniadi,vikikurniadi@gmail.com,628122376517,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,empty,empty
3347,zcrm_3584690000001674307,2019-02-08 17:46:35,2021-07-21 00:00:00,Calvin,Aprileo,calvinaprileo@yahoo.com,6282112898950,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,BGID | FB3 | w4dec18 | Harris Hotel Seminyak,empty,empty,empty,empty

In [60]:
# Cek Email Karma
email_karma = m.find_karma(zoho_df, 'Email')
count_email_karma = email_karma.shape[0]
# email_OTA.to_excel(r'C:\Users\fajar.fatoni\Documents\Python\Data\Beambox\email_OTA.xlsx', index=False)

email_karma

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,City,Country,Lead Brand,...,Which type of wedding package are you interested,Approximately when are you planning to book wed,What is the estimated size of your guest list?,Agency Name,Messages,Description/Deal Stage,Enquiry/Budget,Comments,Website,Mobile
118,zcrm_3584690000534660035,2025-03-26 11:19:47,2025-03-26 00:00:00,Benny,Risanto,benny.risanto+007@karmagroup.com,62811392202,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,Test,empty,empty,empty,https://karmagroup.com/weddings-at-karma-kanda...,empty
151,zcrm_3584690000531049042,2025-03-18 14:52:43,2025-03-18 00:00:00,Ferry,Ferry,ferry.yudhitama+85@karmagroup.com,6287861085142,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,"Test Message from web developer, Please ignor...",empty,empty,empty,https://karmagroup.com/weddings-at-karma-kanda...,empty
223,zcrm_3584690000524711431,2025-02-17 12:01:15,empty,tkl,tkl,tanya.klimentyeva@karmakandara.com,6281130835940,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,https://karmagroup.com/weddings-at-karma-kanda...,empty
226,zcrm_3584690000524712318,2025-02-17 11:39:57,empty,Agus,Maryana,agus.maryana@karmaresorts.com,628122730101,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,https://karmagroup.com/weddings-at-karma-kanda...,empty
241,zcrm_3584690000524238218,2025-02-12 10:55:59,empty,Asthinni,Sri,eventcoordinator@karmakandara.com,62895355698853,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,https://karmagroup.com/weddings-at-karma-kanda...,empty
243,zcrm_3584690000524290202,2025-02-12 10:53:56,empty,Alfonso,R,alfonso.carnevali@karmagroup.com,6281330916979,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,https://karmagroup.com/weddings-at-karma-kanda...,empty
407,zcrm_3584690000517464001,2024-12-05 10:03:32,2024-12-05 00:00:00,Dayu,Dayu,asst.dohr@karmakandara.com,6282144135058,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,Please provide me the detail for more information,empty,empty,empty,https://karmagroup.com/weddings-at-karma-kanda...,empty
408,zcrm_3584690000517451035,2024-12-05 10:02:40,2024-12-05 00:00:00,Rai,Rai,rai.artawan@karmakandara.com,6281338016603,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,Wedding booking in march 2025,empty,empty,empty,https://karmagroup.com/weddings-at-karma-kanda...,empty
409,zcrm_3584690000517412068,2024-12-05 10:02:24,2024-12-05 00:00:00,Shaun,Shaun,gm@karmakandara.com,6281138006892,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,Location,empty,empty,empty,https://karmagroup.com/weddings-at-karma-kanda...,empty
1352,zcrm_3584690000496311706,2024-05-21 12:46:21,2024-05-21 00:00:00,Maida,Maida,maida.pratiwi@karmaresorts.com,62878900098978,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,https://karmagroup.com/weddings-at-karma-kanda...,empty
1422,zcrm_3584690000492392060,2024-04-18 15:56:41,empty,Tanya,Klimentyeva,tanya.klimentyeva@karmakandara.com,6281138305940,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,https://karmagroup.com/weddings-at-karma-kanda...,empty
1427,zcrm_3584690000491983036,2024-04-16 18:26:51,empty,Stephen,Halim,salescoordinator@karmaresorts.com,6281617722971,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,https://karmagroup.com/weddings-at-karma-kanda...,empty
1795,zcrm_3584690000470644676,2023-11-22 11:57:12,empty,Lita,Rahayu,novalita.rahayu@karmagroup.com,6282237453320,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,https://karmagroup.com/weddings-at-karma-kanda...,empty
2907,zcrm_3584690000415832001,2022-12-08 21:36:33,empty,Shaun,Duenhofen,shaun.duenhofen@karmakandara.com,6281138006892,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,https://karmagroup.com/weddings-at-karma-kanda...,empty

In [61]:
# delete email Karma
count_after_clean_karma = m.delete_karma(zoho_df, 'Email')
# zoho_df.to_excel(r'C:\Users\fajar.fatoni\Documents\Python\Data\Beambox\after_clean_OTA.xlsx', index=False)

zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,City,Country,Lead Brand,...,Which type of wedding package are you interested,Approximately when are you planning to book wed,What is the estimated size of your guest list?,Agency Name,Messages,Description/Deal Stage,Enquiry/Budget,Comments,Website,Mobile
0,zcrm_3584690000535783234,2025-04-04 11:46:26,2025-04-03 00:00:00,Dani,Love,empty,61433287423,Sydney,Australia,Karma Resorts,...,empty,empty,Guest <49,ONTOP Agency,empty,? Qualified Lead,empty,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
1,zcrm_3584690000535783235,2025-04-04 11:46:26,2025-04-03 00:00:00,Danielle,Love,danielle.love@outlook.com.au,61433287423,Sydney,Australia,Karma Resorts,...,empty,empty,empty,ONTOP Agency,empty,? Qualified Lead,empty,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
2,zcrm_3584690000535783236,2025-04-04 11:46:26,2025-04-03 00:00:00,Reece,Limond,empty,61421081363,Sydney,Australia,Karma Resorts,...,empty,empty,Guest <49,ONTOP Agency,empty,? Qualified Lead,Budget 10 - 25K AUD,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
3,zcrm_3584690000535783237,2025-04-04 11:46:26,2025-04-02 00:00:00,Isaac,Lake,empty,61420562484,Sydney,Australia,Karma Resorts,...,empty,empty,Guest 50-99,ONTOP Agency,empty,?ï¸_x008f_First Contact,Budget 10 - 25K AUD,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
4,zcrm_3584690000535783238,2025-04-04 11:46:26,2025-04-02 00:00:00,Mariana,-,empty,61422438172,Sydney,Australia,Karma Resorts,...,empty,empty,Guest <49,ONTOP Agency,empty,?ï¸_x008f_First Contact,empty,empty,https://weddings.karmagroup.com/sydney?utm_sou...,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3329,zcrm_3584690000088602263,2019-08-05 17:22:05,2021-07-21 00:00:00,Andy,Cocoy,legacywo@hotmail.com,6287823303095,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,empty,empty
3330,zcrm_3584690000053541163,2019-06-27 20:37:26,2021-07-21 00:00:00,Imaa,-,masace@indo.net.id,628123914666,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,"Reservation ref. - Retail Agent , Market - Do...",empty,empty
3331,zcrm_3584690000029445895,2019-05-08 18:44:25,2021-07-21 00:00:00,Ekin,-,lebali.international@gmail.com,6281933035158,Badung,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,"Market: India, Segmentation: Overseas Agent",empty,empty
3332,zcrm_3584690000024815001,2019-04-08 22:44:50,2021-07-21 00:00:00,Viki,Kurniadi,vikikurniadi@gmail.com,628122376517,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,empty,empty,empty,empty,empty
3333,zcrm_3584690000001674307,2019-02-08 17:46:35,2021-07-21 00:00:00,Calvin,Aprileo,calvinaprileo@yahoo.com,6282112898950,empty,Indonesia,Karma Resorts,...,empty,empty,empty,empty,empty,BGID | FB3 | w4dec18 | Harris Hotel Seminyak,empty,empty,empty,empty

In [62]:
find_member_booking = zoho_df.copy()

find_member_booking.loc[find_member_booking['Phone'].isin(df_booking['Phone1']), 'Same Value Find'] = 'Booking-Phone1'
find_member_booking.loc[find_member_booking['Phone'].isin(df_booking['Mobile']), 'Same Value Find'] = 'Booking-Mobile'
find_member_booking.loc[find_member_booking['Mobile'].isin(df_booking['Phone1']), 'Same Value Find'] = 'Booking-Phone1' 
find_member_booking.loc[find_member_booking['Mobile'].isin(df_booking['Mobile']), 'Same Value Find'] = 'Booking-Mobile'
find_member_booking.loc[find_member_booking['Email'].isin(df_booking['Email']), 'Same Value Find'] = 'Booking-Email'

find_member_booking.loc[find_member_booking['Phone'].isin(df_phone['Mobile']), 'Same Value Find'] = 'Member-Mobile' 
find_member_booking.loc[find_member_booking['Mobile'].isin(df_phone['Mobile']), 'Same Value Find'] = 'Member-Mobile'

find_member_booking.loc[find_member_booking['Email'].isin(df_email['Email']), 'Same Value Find'] = 'Member-Email'

find_member_booking.drop(find_member_booking.loc[find_member_booking['Same Value Find'].isna()].index, inplace=True)

count_booking_dedup = find_member_booking.loc[find_member_booking['Same Value Find'].str.contains('Booking', flags=re.I, regex=True)].shape[0]
count_member_dedup = find_member_booking.loc[find_member_booking['Same Value Find'].str.contains('Member', flags=re.I, regex=True)].shape[0]

find_member_booking.replace('empty', '', inplace=True)
# find_member_booking.to_csv(r'C:\Users\fajar.fatoni\Documents\Python\Data\Beambox\booking-member-dedup.csv', index=False)
# find_member_booking.to_excel(r'C:\Users\fajar.fatoni\Documents\Python\Data\Beambox\booking-member-dedup.xlsx', index=False)

#find_member_booking.loc[find_member_booking['Same Value Find'] == 'Booking-Phone1']

In [63]:
# data phone, mobile dam email member yang ada di master data 
count_wash_member = zoho_df.loc[
    zoho_df['Phone'].isin(df_booking['Phone1']) | 
    zoho_df['Phone'].isin(df_booking['Mobile']) |
    zoho_df['Mobile'].isin(df_booking['Phone1']) | 
    zoho_df['Mobile'].isin(df_booking['Mobile']) |
    zoho_df['Email'].isin(df_booking['Email'])| 

    zoho_df['Phone'].isin(df_phone['Mobile']) | 
    zoho_df['Mobile'].isin(df_phone['Mobile']) |

    zoho_df['Email'].isin(df_email['Email'])

].shape[0]

zoho_df.drop(zoho_df.loc[
    zoho_df['Phone'].isin(df_booking['Phone1']) | 
    zoho_df['Phone'].isin(df_booking['Mobile']) |
    zoho_df['Mobile'].isin(df_booking['Phone1']) | 
    zoho_df['Mobile'].isin(df_booking['Mobile']) |
    zoho_df['Email'].isin(df_booking['Email']) |
    
    zoho_df['Phone'].isin(df_phone['Mobile']) | 
    zoho_df['Mobile'].isin(df_phone['Mobile']) |

    zoho_df['Email'].isin(df_email['Email'])

    ].index, inplace=True)
    
zoho_df.reset_index(drop=True, inplace=True)

count_after_wash_member = zoho_df.shape[0]

In [64]:
count_email_only = zoho_df.loc[(zoho_df['Email'] != 'empty') & ((zoho_df['Phone'] == 'empty') & (zoho_df['Mobile'] == 'empty'))].shape[0]
count_phone_only = zoho_df.loc[(zoho_df['Email'] == 'empty') & ((zoho_df['Phone'] != 'empty') | (zoho_df['Mobile'] != 'empty'))].shape[0]
count_email_and_phone = zoho_df.loc[(zoho_df['Email'] != 'empty') & ((zoho_df['Phone'] != 'empty') | (zoho_df['Mobile'] != 'empty'))].shape[0]

count_blank = zoho_df.loc[(zoho_df['Email'] =='empty') & (zoho_df['Phone']=='empty') & (zoho_df['Mobile']=='empty')].shape[0]

# zoho_df.loc[(zoho_df['Email'] =='empty') & (zoho_df['Phone']=='empty') & (zoho_df['Mobile']=='empty')].to_excel(r'C:\Users\fajar.fatoni\Documents\Python\Data\Beambox\blank_data.xlsx', index=False)

zoho_df.loc[(zoho_df['Email'] != 'empty') & ((zoho_df['Phone'] == 'empty') & (zoho_df['Mobile'] == 'empty')), 'Contact Type'] = 'Email Only'
zoho_df.loc[(zoho_df['Email'] == 'empty') & ((zoho_df['Phone'] != 'empty') | (zoho_df['Mobile'] != 'empty')), 'Contact Type'] = 'Phone Only'
zoho_df.loc[(zoho_df['Email'] != 'empty') & ((zoho_df['Phone'] != 'empty') | (zoho_df['Mobile'] != 'empty')), 'Contact Type'] = 'Email and Phone'

zoho_df.drop(zoho_df.loc[(zoho_df['Email'] =='empty') & (zoho_df['Phone']=='empty') & (zoho_df['Mobile']=='empty')].index, inplace=True)
zoho_df.reset_index(drop=True, inplace=True)

count_after_wash_blank = zoho_df.shape[0]

In [65]:
arr_dedup = [count_deleted_wrong_format, count_duplicate_general, count_email_OTA, count_email_karma, count_blank]
count_sum_dedup = sum(arr_dedup)
count_sum_dedup

19

In [69]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Filter Leads Awal : "+str(count_filter_awal))
print("Jumlah Format Email Salah : "+str(count_deleted_wrong_format))
print("Jumlah Setelah Clean Format Email Salah : "+str(count_after_deleted_wrong_format))
print("Jumlah Duplicate (Phone, Mobile, Email dan LSD) : "+str(count_duplicate_general))
print("Jumlah Setelah Clean Duplicate : "+str(count_after_dedup_duplicate))
# print("Jumlah Lead Test : "+str(count_leads_test))
# print("Jumlah Setelah Clean Lead Test : "+str(count_after_dedup_test))
# print("Jumlah Lead Do Not Mail : "+str(count_dnm))
# print("Jumlah Setelah Clean Lead Do Not Mail : "+str(count_after_dedup_dnm))
print("Jumlah Email OTA : "+str(count_email_OTA))
print("Jumlah Setelah Clean Email OTA : "+str(count_after_clean_OTA))
print("Jumlah Email Karma : "+str(count_email_karma))
print("Jumlah Setelah Clean Email Karma : "+str(count_after_clean_karma))
print("Jumlah Wash Member : "+str(count_member_dedup))
print("Jumlah Wash Booking : "+str(count_booking_dedup))
print("Jumlah Setelah Wash Member : "+str(count_after_wash_member))
print("Jumlah Phone Email Blank (Setelah phone yang tidak valid dihapus) : "+str(count_blank))
print("Jumlah Setelah Wash Phone Email Blank : "+str(count_after_wash_blank))
print("==========================================================")
print("Contact Type")
print("==========================================================")
print("Jumlah Email Only : "+str(count_email_only))
print("Jumlah Phone Only : "+str(count_phone_only))
print("Jumlah Email dan Phone : "+str(count_email_and_phone))

==========================================================
Summary
==========================================================
Jumlah Filter Leads Awal : 3351
Jumlah Format Email Salah : 0
Jumlah Setelah Clean Format Email Salah : 3351
Jumlah Duplicate (Phone, Mobile, Email dan LSD) : 1
Jumlah Setelah Clean Duplicate : 3350
Jumlah Email OTA : 2
Jumlah Setelah Clean Email OTA : 3348
Jumlah Email Karma : 14
Jumlah Setelah Clean Email Karma : 3334
Jumlah Wash Member : 133
Jumlah Wash Booking : 4
Jumlah Setelah Wash Member : 3197
Jumlah Phone Email Blank (Setelah phone yang tidak valid dihapus) : 2
Jumlah Setelah Wash Phone Email Blank : 3195
==========================================================
Contact Type
==========================================================
Jumlah Email Only : 50
Jumlah Phone Only : 164
Jumlah Email dan Phone : 2981

In [67]:
print("==========================================================")
print("Summary Report")
print("==========================================================")
print("Jumlah Data Awal : "+str(count_filter_awal))
print("Jumlah Wash Dedup : "+str(count_sum_dedup))
print("Jumlah Wash Member : "+str(count_member_dedup))
print("Jumlah Wash Booking : "+str(count_booking_dedup))
print("Jumlah Data Akhir : "+str(count_after_wash_blank))

==========================================================
Summary Report
==========================================================
Jumlah Data Awal : 3351
Jumlah Wash Dedup : 19
Jumlah Wash Member : 133
Jumlah Wash Booking : 4
Jumlah Data Akhir : 3195

In [68]:
zoho_df.replace('empty', '', inplace=True, regex=True)

# zoho_df['First Name'] = zoho_df['First Name'].str.title()
# zoho_df['Last Name'] = zoho_df['Last Name'].str.title()

# zoho_df.to_csv(r'C:\Users\fajar.fatoni\Documents\Python\Data\Beambox\karma beach cleand.csv', index=False)
zoho_df.to_excel(r'C:\Users\fajar.fatoni\Documents\Python\Data\Karma Kandara - Wedding Leads - clean.xlsx', index=False)