In [3]:
import main_module as m
import zoho_filter_module as fil
import pandas as pd
import re
import numpy as np

%load_ext autoreload
%autoreload 2

dir_path = r'C:\Users\fajar\Documents\Python\Data\Zoho_Backup'
file_name = '\Leads_'

cols = ['Record Id',	
'Created Time',
'Created Date',	
'First Name',	
'Last Name',	
'Email',	
'Phone',	
'Mobile',	
'Birthdate',	
'Year of Birth',
'Street',	
'Street2',	
'City',	
'State',	
'Country',	
'Nationality',
'Booking Status', 
'BookRef',
'Departure Date',	
'Arrival Date',	
'Card Type',	
'Marital Status',	
'Lead Brand',	
'Lead Sub-Brand',	
'Lead Source',	
'Lead Locations',	
'Lead Source Description',	
'Lead Regions',
'Lead Status',
'Email Opt Out',	
'Opt In',
'GDPR Compliant',
'Website']

<>:11: SyntaxWarning: invalid escape sequence '\L'
<>:11: SyntaxWarning: invalid escape sequence '\L'
C:\Users\fajar\AppData\Local\Temp\ipykernel_8380\3222793355.py:11: SyntaxWarning: invalid escape sequence '\L'
  file_name = '\Leads_'

In [4]:
df = m.load_data_multiple(dir_path, file_name, cols)
count_data_awal = df.shape[0]
df = df.reindex(columns=cols)
df.shape[0]

df['Created Time'] = pd.to_datetime(df['Created Time'], format='%Y-%m-%d %H:%M:%S')
df['Arrival Date'] = pd.to_datetime(df['Arrival Date'], format='%Y-%m-%d')
df['Departure Date'] = pd.to_datetime(df['Departure Date'], format='%Y-%m-%d')
# fungsi errors cource untuk menhindari error jika value data date null atau kosong
# df['Birthdate'] = pd.to_datetime(df['Birthdate'], format='%Y-%m-%d', errors='coerce')
df.dtypes
df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website
0,zcrm_3584690000000404602,2019-01-08 11:07:28,2021-07-21,Frederic,Bonin,fredericbonin79@gmail.com,+6281236100502,<NA>,1981-10-03,1981,...,Other,Agency,Karma Kandara,KAREN,SEAP,New Lead,false,false,false,<NA>
1,zcrm_3584690000000450071,2019-01-08 16:38:18,<NA>,Sebastian,Rach,<NA>,+498914342111,<NA>,1982-04-20,1982,...,Other,Past Guests,Karma Bavaria,<NA>,UK/Europe,New Lead,true,false,false,<NA>
2,zcrm_3584690000000450087,2019-01-08 16:38:18,<NA>,Siobhan,Gallagher,gallaghersiobhan@eircom.net,353879597603,<NA>,1973-03-14,1973,...,Other,Past Guests,Karma Bavaria,<NA>,UK/Europe,New Lead,false,true,true,<NA>
3,zcrm_3584690000000450106,2019-01-08 16:38:18,<NA>,Lisa,Ferkovich,lisajo2009@yahoo.com,14062394749,<NA>,1963-07-08,1963,...,Other,Past Guests,Karma Bavaria,<NA>,UK/Europe,New Lead,true,false,false,<NA>
4,zcrm_3584690000000450109,2019-01-08 16:38:18,<NA>,Ana Maria,Weileder,m.weileder@sonnenlink.de,15253234700,<NA>,<NA>,<NA>,...,Other,Other,Karma Bavaria,MICE Contacts from Ioanna email,UK/Europe,New Lead,false,true,true,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462403,zcrm_3584690000504265571,2024-08-05 17:37:48,<NA>,Goyal,Madhurima,<NA>,919986885250,<NA>,<NA>,<NA>,...,Other,WhatsApp Enquiry,Karma Jimbaran,<NA>,<NA>,New Lead,false,false,false,<NA>
462404,zcrm_3584690000504265572,2024-08-05 17:37:48,<NA>,Bryan,Whiting,<NA>,447931789709,<NA>,<NA>,<NA>,...,Other,WhatsApp Enquiry,Karma Jimbaran,<NA>,<NA>,New Lead,false,false,false,<NA>
462405,zcrm_3584690000504265573,2024-08-05 17:37:48,<NA>,Oki,Ramadhana,<NA>,62811150700,<NA>,<NA>,<NA>,...,Other,WhatsApp Enquiry,Karma Jimbaran,<NA>,<NA>,New Lead,false,false,false,<NA>
462406,zcrm_3584690000504265574,2024-08-05 17:37:48,<NA>,Arya,Wijaya,<NA>,6285738679736,<NA>,<NA>,<NA>,...,Other,WhatsApp Enquiry,Karma Jimbaran,<NA>,<NA>,New Lead,false,false,false,<NA>
462407,zcrm_3584690000504265575,2024-08-05 17:37:48,<NA>,Info,Bri,<NA>,6281393445510,<NA>,<NA>,<NA>,...,Other,WhatsApp Enquiry,Karma Jimbaran,<NA>,<NA>,New Lead,false,false,false,<NA>

In [6]:
df.loc[df['Phone'].str.contains('^\\+62', regex=True)]

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website
0,zcrm_3584690000000404602,2019-01-08 11:07:28,2021-07-21,Frederic,Bonin,fredericbonin79@gmail.com,+6281236100502,<NA>,1981-10-03,1981,...,Other,Agency,Karma Kandara,KAREN,SEAP,New Lead,false,false,false,<NA>
10,zcrm_3584690000000450191,2019-01-08 16:38:18,2021-07-21,Ni Made Novia,Andryani,novia_made@yahoo.com,+6281511634635,<NA>,1980-11-10,1980,...,Other,Agency,Karma Kandara,KAREN,SEAP,New Lead,false,false,false,<NA>
12,zcrm_3584690000000450226,2019-01-08 16:38:18,2021-07-21,Maureellins,Joewyns,maureellinsjoewyns@gmail.com,+6282221100639,<NA>,2000-04-14,2000,...,Other,Agency,Karma Kandara,KAREN,SEAP,New Lead,false,false,false,<NA>
33,zcrm_3584690000000456097,2019-01-09 11:10:49,2021-07-21,Di,Zhang,156864136@qq.com,+628618339280777,<NA>,<NA>,<NA>,...,Other,Agency,Karma Kandara,KAREN,SEAP,New Lead,false,false,false,<NA>
86,zcrm_3584690000000456162,2019-01-09 11:10:49,2021-07-21,Ganef Hari,Sulistiono,abahdendy99@gmail.com,+628123255435,<NA>,1963-12-16,1963,...,Other,Agency,Karma Kandara,KAREN,SEAP,New Lead,false,false,false,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460110,zcrm_3584690000504244407,2024-08-05 16:51:13,<NA>,Benny,Risanto,benny.risanto+no18rtest@karmagroup.com,+62811392202,<NA>,2024-08-30,<NA>,...,House Of Karma,Web,<NA>,Karma Reciprocal Members,SEAP,<NA>,false,true,false,https://karmaclub.karmagroup.com/reciprocal-me...
460111,zcrm_3584690000504244475,2024-08-05 16:53:24,<NA>,Benny,Risanto,benny.risanto+yayem3@karmagroup.com,+62811392202,<NA>,2024-08-27,<NA>,...,House Of Karma,Web,<NA>,Karma Reciprocal Members,SEAP,<NA>,false,true,false,https://karmaclub.karmagroup.com/reciprocal-me...
460133,zcrm_3584690000504251108,2024-08-05 16:50:03,<NA>,Benny,Risanto,benny.risanto+tgtr@karmagroup.com,+62811392202,<NA>,2024-08-14,<NA>,...,House Of Karma,Web,<NA>,Karma Reciprocal Members,SEAP,<NA>,false,true,false,https://karmaclub.karmagroup.com/reciprocal-me...
460136,zcrm_3584690000504252097,2024-08-05 16:30:03,<NA>,Benny,Risanto,benny.risanto+TRGCR@karmagroup.com,+62811392202,<NA>,1991-03-01,<NA>,...,House Of Karma,Web,<NA>,Karma Reciprocal Members,SEAP,<NA>,false,true,false,https://karmaclub.karmagroup.com/reciprocal-me...
460144,zcrm_3584690000504256006,2024-08-05 16:20:54,<NA>,Benny,Risanto,benny.risanto+TEST@karmagroup.com,+62811392202,<NA>,2005-08-03,<NA>,...,House Of Karma,Web,<NA>,Karma Reciprocal Members,SEAP,<NA>,false,true,false,https://karmaclub.karmagroup.com/reciprocal-me...

In [4]:
path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04eXpvS1NXTWF2RVE\_BOOKING\Booking By Year\FlyBuy Booking Data (BGAU & BGID & KE).xlsx'
df_booking = pd.read_excel(path, dtype='string', sheet_name='BOOKING_BGAU_BGID_KE')

path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04UUNBME5GOVhoMjA\_ODYSSEY\Phone Members.xlsx'
df_phone = pd.read_excel(path, dtype='string', sheet_name='Sheet1')

path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04UUNBME5GOVhoMjA\_ODYSSEY\Email Members.xlsx'
df_email = pd.read_excel(path, dtype='string', sheet_name='Sheet1')

In [5]:
zoho_filter = fil.user_req(df)
zoho_df = df.loc[zoho_filter].copy() # menggunakan copy untuk menghindari setting copy warning
zoho_df.reset_index(drop=True, inplace=True)
count_filter_awal = zoho_df.shape[0]

# zoho_df.to_excel(r'C:\Users\fajar\Documents\Python\Data\test_leads.xlsx', index=False)
# mengisi kolom <NA> dengan value string 'empty' supaya mudah mengecek data member dan booking dengan isin

zoho_df.fillna('empty', inplace=True)
zoho_df.sort_values('Created Time', ascending=True)

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website
0,zcrm_3584690000000456191,2019-01-09 11:10:49,empty,Kim Guan,Pua,adelinephua555@gmail.com,empty,empty,1937-09-14,1937,...,Other,Past Guests,Karma Jimbaran,empty,Other,New Lead,true,false,false,empty
1,zcrm_3584690000000456198,2019-01-09 11:10:49,empty,Pauline,Shek,admin@surpass.com.sg,6597811782,empty,empty,empty,...,Other,Past Guests,Karma Rottnest,empty,Other,New Lead,true,false,false,empty
2,zcrm_3584690000000457744,2019-01-09 11:10:59,empty,Tan Cheng,Kiat,christan@telair.com.sg,6596601533,empty,1963-11-03,1963,...,Other,Past Guests,Karma Bavaria,empty,Other,No Response,true,false,false,empty
3,zcrm_3584690000000458638,2019-01-09 11:11:04,empty,Eilleen,Keith Luna,ekalfarosale@gmail.com,6598607340,empty,1988-11-07,1988,...,Other,Past Guests,Karma Kandara,empty,Other,No Response,true,false,false,empty
4,zcrm_3584690000000459002,2019-01-09 11:11:06,empty,Fong,Jong Han,empty,60122987926,empty,empty,empty,...,Other,Past Guests,Karma Rottnest,empty,Other,New Lead,true,false,false,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4813,zcrm_3584690000501949300,2024-07-13 14:02:21,empty,Hue,Vern Chie,joyce_hue@yahoo.com,+600122749032,empty,empty,empty,...,Other,Web Enquiry,Karma Cay Tre,Form Contact Us,Other,empty,false,true,false,https://karmagroup.com/contact-us/
4819,zcrm_3584690000501997518,2024-07-14 11:29:42,empty,philippe,magnin,philippe.mr@outlook.com,+6580234245,empty,empty,empty,...,Other,Web Enquiry,Karma Song Hoai,Form Contact Us,Other,empty,false,true,false,https://karmagroup.com/contact-us/
4814,zcrm_3584690000501952879,2024-07-14 16:52:37,empty,Aileen,Neoh,aneoh@hotmail.com,+6588230189,empty,empty,empty,...,Other,Web Enquiry,Karma Bayon,Timeshare Booking Request,Other,empty,false,true,true,https://karmagroup.com/find-destination/karma-...
4816,zcrm_3584690000501960205,2024-07-14 19:56:26,2024-07-01,Simeen,Malik,simeenz@gmail.com,empty,empty,empty,empty,...,Karma Spa,Past Guests,Karma Kandara,empty,empty,New Lead,false,false,false,empty
4820,zcrm_3584690000501997940,2024-07-15 12:33:59,empty,Ong Sze,Keong,ongsk2626@gmail.com,+60123132626,empty,empty,empty,...,Other,Past Guests,Karma Jimbaran,Viewpoint,empty,empty,false,true,false,empty

In [6]:
zoho_df.loc[zoho_df['Lead Source Description'].str.contains('walk', regex=True, flags=re.I)]

Empty DataFrame
Columns: [Record Id, Created Time, Created Date, First Name, Last Name, Email, Phone, Mobile, Birthdate, Year of Birth, Street, Street2, City, State, Country, Nationality, Booking Status, BookRef, Departure Date, Arrival Date, Card Type, Marital Status, Lead Brand, Lead Sub-Brand, Lead Source, Lead Locations, Lead Source Description, Lead Regions, Lead Status, Email Opt Out, Opt In, GDPR Compliant, Website]
Index: []

[0 rows x 33 columns]

# ====================== Awal Filter Umum ======================

In [7]:
# data phone, mobile dam email member yang ada di master data (wash member)

m.clean_number(zoho_df, 'Phone')
m.clean_number(zoho_df, 'Mobile')
m.replace_not_valid_to_empty(zoho_df, 'Phone')
m.replace_not_valid_to_empty(zoho_df, 'Mobile')
zoho_df['Email'] = m.lowercase(zoho_df, 'Email')
m.clean_space(zoho_df, 'Email')
m.clean_not_valid_email_format(zoho_df, 'Email')

m.clean_number(df_booking, 'Phone1')
m.clean_number(df_booking, 'Mobile')
df_booking['Email'] = m.lowercase(df_booking, 'Email')
m.clean_space(df_booking, 'Email')
m.clean_not_valid_email_format(df_booking, 'Email')

m.clean_number(df_phone, 'Mobile')

df_email['Email'] = m.lowercase(df_email, 'Email')
m.clean_space(df_email, 'Email')
m.clean_not_valid_email_format(df_email, 'Email')

'Email'

In [8]:
zoho_df.loc[zoho_df['Phone']=='']

Empty DataFrame
Columns: [Record Id, Created Time, Created Date, First Name, Last Name, Email, Phone, Mobile, Birthdate, Year of Birth, Street, Street2, City, State, Country, Nationality, Booking Status, BookRef, Departure Date, Arrival Date, Card Type, Marital Status, Lead Brand, Lead Sub-Brand, Lead Source, Lead Locations, Lead Source Description, Lead Regions, Lead Status, Email Opt Out, Opt In, GDPR Compliant, Website]
Index: []

[0 rows x 33 columns]

In [9]:
count_deleted_wrong_format = m.delete_email_wrong_format(zoho_df, 'Email')
count_after_deleted_wrong_format = zoho_df.shape[0]

In [10]:
# hitung jumlah duplicate
count_duplicate_general = zoho_df.loc[zoho_df.duplicated(subset=['Phone','Email', 'Mobile'])].shape[0]

zoho_df.loc[zoho_df.duplicated(subset=['Phone','Email', 'Mobile'])]

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website
1643,zcrm_3584690000007255329,2019-04-02 05:36:29,2016-12-19,Sabrina,Ng,empty,6565337704,empty,1990-10-10,1990,...,Karma Club,Membership,empty,External Custom Form,Other,empty,false,false,false,empty
2061,zcrm_3584690000025158031,2019-04-09 21:51:45,empty,Jillian,Wah,empty,6562275535,empty,empty,empty,...,Other,Chairman database,empty,Singapore,Other,New Lead,false,false,false,empty
2283,zcrm_3584690000036494005,2019-05-28 19:46:00,2019-05-28,Charis,Cheung,charischeung119@yahoo.com,empty,empty,empty,empty,...,Karma Spa,Past Guests,Karma Kandara,empty,Other,empty,false,false,false,empty
3027,zcrm_3584690000044531463,2019-06-13 16:08:39,empty,Margaret,Koh,empty,6565357704,empty,empty,empty,...,Other,Agency,empty,empty,Other,New Lead,false,false,false,empty
3085,zcrm_3584690000044532581,2019-06-13 16:08:48,empty,Janel,Teo,empty,6591886673,empty,empty,empty,...,Other,Agency,empty,empty,Other,New Lead,false,false,false,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4806,zcrm_3584690000501852034,2024-07-10 17:07:44,empty,Nicole,Urbanski,nicoleur@live.com,6580328537,empty,empty,empty,...,Other,Web Enquiry,Karma Kandara,Karma Kandara -Download Wedding Brochure at Ka...,Other,empty,false,true,false,https://karmagroup.com/weddings-at-karma-kanda...
4807,zcrm_3584690000501853034,2024-07-10 17:07:44,empty,Nicole,Urbanski,nicoleur@live.com,6580328537,empty,empty,empty,...,Other,Web Enquiry,Karma Kandara,Karma Kandara -Download Wedding Brochure at Ka...,Other,empty,false,true,false,https://karmagroup.com/weddings-at-karma-kanda...
4810,zcrm_3584690000501937269,2024-07-12 17:59:19,empty,Kathryn Mei Fern,Chai,kathrynchai18@yahoo.com,6598269028,empty,empty,empty,...,Other,Web Enquiry,Karma Kandara,Karma Kandara -Download Wedding Brochure at Ka...,Other,empty,false,true,false,https://karmagroup.com/weddings-at-karma-kanda...
4815,zcrm_3584690000501953346,2024-07-12 17:50:44,empty,Kathryn Mei Fern,Chai,kathrynchai18@yahoo.com,6598269028,empty,empty,empty,...,Other,Web Enquiry,Karma Kandara,Karma Kandara -Download Wedding Brochure at Ka...,Other,empty,false,true,false,https://karmagroup.com/weddings-at-karma-kanda...
4818,zcrm_3584690000501980176,2024-07-12 17:50:45,empty,Kathryn Mei Fern,Chai,kathrynchai18@yahoo.com,6598269028,empty,empty,empty,...,Other,Web Enquiry,Karma Kandara,Karma Kandara -Download Wedding Brochure at Ka...,Other,empty,false,true,false,https://karmagroup.com/weddings-at-karma-kanda...

In [11]:
zoho_df.drop_duplicates(subset=['Phone','Email', 'Mobile'], inplace=True)
zoho_df.reset_index(drop=True, inplace=True)

# hitung jumlah setelah value duplicate dihapus
count_after_dedup_duplicate = zoho_df.shape[0]

zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website
0,zcrm_3584690000000456191,2019-01-09 11:10:49,empty,Kim Guan,Pua,adelinephua555@gmail.com,empty,empty,1937-09-14,1937,...,Other,Past Guests,Karma Jimbaran,empty,Other,New Lead,true,false,false,empty
1,zcrm_3584690000000456198,2019-01-09 11:10:49,empty,Pauline,Shek,admin@surpass.com.sg,6597811782,empty,empty,empty,...,Other,Past Guests,Karma Rottnest,empty,Other,New Lead,true,false,false,empty
2,zcrm_3584690000000457744,2019-01-09 11:10:59,empty,Tan Cheng,Kiat,christan@telair.com.sg,6596601533,empty,1963-11-03,1963,...,Other,Past Guests,Karma Bavaria,empty,Other,No Response,true,false,false,empty
3,zcrm_3584690000000458638,2019-01-09 11:11:04,empty,Eilleen,Keith Luna,ekalfarosale@gmail.com,6598607340,empty,1988-11-07,1988,...,Other,Past Guests,Karma Kandara,empty,Other,No Response,true,false,false,empty
4,zcrm_3584690000000459002,2019-01-09 11:11:06,empty,Fong,Jong Han,empty,60122987926,empty,empty,empty,...,Other,Past Guests,Karma Rottnest,empty,Other,New Lead,true,false,false,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4697,zcrm_3584690000501952879,2024-07-14 16:52:37,empty,Aileen,Neoh,aneoh@hotmail.com,6588230189,empty,empty,empty,...,Other,Web Enquiry,Karma Bayon,Timeshare Booking Request,Other,empty,false,true,true,https://karmagroup.com/find-destination/karma-...
4698,zcrm_3584690000501960205,2024-07-14 19:56:26,2024-07-01,Simeen,Malik,simeenz@gmail.com,empty,empty,empty,empty,...,Karma Spa,Past Guests,Karma Kandara,empty,empty,New Lead,false,false,false,empty
4699,zcrm_3584690000501977044,2024-07-12 03:12:18,empty,Jolene,Quek,jolenedayle@gmail.com,6596920977,empty,empty,empty,...,Other,Web Enquiry,Karma Kandara,Karma Kandara -Download Wedding Brochure at Ka...,Other,empty,false,true,false,https://karmagroup.com/weddings-at-karma-kanda...
4700,zcrm_3584690000501997518,2024-07-14 11:29:42,empty,philippe,magnin,philippe.mr@outlook.com,6580234245,empty,empty,empty,...,Other,Web Enquiry,Karma Song Hoai,Form Contact Us,Other,empty,false,true,false,https://karmagroup.com/contact-us/
4701,zcrm_3584690000501997940,2024-07-15 12:33:59,empty,Ong Sze,Keong,ongsk2626@gmail.com,60123132626,empty,empty,empty,...,Other,Past Guests,Karma Jimbaran,Viewpoint,empty,empty,false,true,false,empty

In [12]:
# Cek leads test
test_leads = zoho_df.loc[
    
        zoho_df['Email'].str.contains('^test@', flags=re.I, regex=True) |
        zoho_df['Email'].str.contains('\+test', flags=re.I, regex=True) |
    
        zoho_df['First Name'].str.contains('^test$', flags=re.I, regex=True) |
        zoho_df['Last Name'].str.contains('^test$', flags=re.I, regex=True) |

        zoho_df['First Name'].str.contains('test 1', flags=re.I, regex=True) |
        zoho_df['Last Name'].str.contains('test 2', flags=re.I, regex=True)|
        zoho_df['First Name'].str.contains('test1', flags=re.I, regex=True) |
        zoho_df['Last Name'].str.contains('test2', flags=re.I, regex=True)|

        zoho_df['First Name'].str.contains(' test ', flags=re.I, regex=True) | 
        zoho_df['Last Name'].str.contains(' test ', flags=re.I, regex=True) | 
        zoho_df['Last Name'].str.contains(' test$', flags=re.I, regex=True)
    ]

count_leads_test = test_leads.shape[0]

# test_leads.to_excel(r'C:\Users\fajar\Documents\Python\Data\test_leads_2.xlsx', index=False)
test_leads

Empty DataFrame
Columns: [Record Id, Created Time, Created Date, First Name, Last Name, Email, Phone, Mobile, Birthdate, Year of Birth, Street, Street2, City, State, Country, Nationality, Booking Status, BookRef, Departure Date, Arrival Date, Card Type, Marital Status, Lead Brand, Lead Sub-Brand, Lead Source, Lead Locations, Lead Source Description, Lead Regions, Lead Status, Email Opt Out, Opt In, GDPR Compliant, Website]
Index: []

[0 rows x 33 columns]

In [13]:
zoho_df.drop(test_leads.index, inplace=True)
zoho_df.reset_index(drop=True, inplace=True)

count_after_dedup_test = zoho_df.shape[0]

In [14]:
# dnm_leads = zoho_df.loc[(zoho_df['Do Not Mail'] == 'true') | (zoho_df['Do Not Contact'] == 'true')]
# count_dnm = dnm_leads.shape[0]

In [15]:
# zoho_df.drop(dnm_leads.index, inplace=True)
# zoho_df.reset_index(drop=True, inplace=True)

# count_after_dedup_dnm = zoho_df.shape[0]

In [16]:
# Cek Email OTA
email_OTA = m.find_OTA(zoho_df, 'Email')
count_email_OTA = email_OTA.shape[0]
# email_OTA.to_excel(r'C:\Users\fajar\Documents\Python\Data\email_OTA.xlsx', index=False)

email_OTA

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website
836,zcrm_3584690000005994723,2019-04-02 02:19:27,2015-03-11,Nopri,Aries,summertourtravel@yahoo.com.sg,empty,empty,empty,empty,...,Other,Karma Chronicles,empty,empty,Other,empty,false,false,false,empty
1110,zcrm_3584690000006463501,2019-04-02 03:59:28,2015-03-10,Hock,Goh,beltraveltour@yahoo.com,6062822712,60126822712,empty,empty,...,Other,Chairman database,empty,Singapore,Other,empty,false,false,false,empty
1201,zcrm_3584690000007152561,2019-04-02 05:24:22,2016-04-21,James,Pelham,james@culturebitesfoodtours.com,6597694845,empty,1978-10-03,1978,...,Other,Chairman database,John Spence,Event Chairman Invite,Other,empty,false,false,false,empty
3020,zcrm_3584690000044531427,2019-06-13 16:08:39,empty,Woo,K M (Jimmy),econtours@gmail.com,62613218,empty,empty,empty,...,Other,Agency,empty,empty,Other,New Lead,false,false,false,empty
3026,zcrm_3584690000044531711,2019-06-13 16:08:42,empty,Eileen,Lim,eileen.lim@hanatour.com,6562224501,6596731516,empty,empty,...,Other,Agency,empty,"Yemi - 30%, TA Asian market",Other,New Lead,false,false,false,empty
3030,zcrm_3584690000044531717,2019-06-13 16:08:42,empty,Elaine,Lim,outbound.sales2@skyzonetours.com,60321187888,empty,empty,empty,...,Other,Agency,empty,empty,Other,New Lead,false,false,false,empty
3046,zcrm_3584690000044531850,2019-06-13 16:08:42,empty,Lynn,Ng,jjlynnng@hanatour.com,6562224501,6597450803,empty,empty,...,Other,Agency,empty,"Yemi - 30%, TA Asian market",Other,New Lead,false,false,false,empty
3101,zcrm_3584690000044532949,2019-06-13 16:08:51,empty,Amy,Zuo,amyzuo@satours.com.sg,65352611,6565013927,empty,empty,...,Other,Agency,empty,"Yemi - 30%, TA Asian market",Other,New Lead,false,false,false,empty
3409,zcrm_3584690000178433001,2020-04-07 20:00:42,empty,empty,Jowee,jowee.soh@agoda.com,empty,empty,empty,empty,...,Other,Webchat,empty,Karma Resorts Reservations | Webchat Web,Other,empty,false,false,false,https://www.google.com/

In [17]:
# delete email OTA
count_after_clean_OTA = m.delete_OTA(zoho_df, 'Email')
# zoho_df.to_excel(r'C:\Users\fajar\Documents\Python\Data\after_clean_OTA.xlsx', index=False)

zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website
0,zcrm_3584690000000456191,2019-01-09 11:10:49,empty,Kim Guan,Pua,adelinephua555@gmail.com,empty,empty,1937-09-14,1937,...,Other,Past Guests,Karma Jimbaran,empty,Other,New Lead,true,false,false,empty
1,zcrm_3584690000000456198,2019-01-09 11:10:49,empty,Pauline,Shek,admin@surpass.com.sg,6597811782,empty,empty,empty,...,Other,Past Guests,Karma Rottnest,empty,Other,New Lead,true,false,false,empty
2,zcrm_3584690000000457744,2019-01-09 11:10:59,empty,Tan Cheng,Kiat,christan@telair.com.sg,6596601533,empty,1963-11-03,1963,...,Other,Past Guests,Karma Bavaria,empty,Other,No Response,true,false,false,empty
3,zcrm_3584690000000458638,2019-01-09 11:11:04,empty,Eilleen,Keith Luna,ekalfarosale@gmail.com,6598607340,empty,1988-11-07,1988,...,Other,Past Guests,Karma Kandara,empty,Other,No Response,true,false,false,empty
4,zcrm_3584690000000459002,2019-01-09 11:11:06,empty,Fong,Jong Han,empty,60122987926,empty,empty,empty,...,Other,Past Guests,Karma Rottnest,empty,Other,New Lead,true,false,false,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4688,zcrm_3584690000501952879,2024-07-14 16:52:37,empty,Aileen,Neoh,aneoh@hotmail.com,6588230189,empty,empty,empty,...,Other,Web Enquiry,Karma Bayon,Timeshare Booking Request,Other,empty,false,true,true,https://karmagroup.com/find-destination/karma-...
4689,zcrm_3584690000501960205,2024-07-14 19:56:26,2024-07-01,Simeen,Malik,simeenz@gmail.com,empty,empty,empty,empty,...,Karma Spa,Past Guests,Karma Kandara,empty,empty,New Lead,false,false,false,empty
4690,zcrm_3584690000501977044,2024-07-12 03:12:18,empty,Jolene,Quek,jolenedayle@gmail.com,6596920977,empty,empty,empty,...,Other,Web Enquiry,Karma Kandara,Karma Kandara -Download Wedding Brochure at Ka...,Other,empty,false,true,false,https://karmagroup.com/weddings-at-karma-kanda...
4691,zcrm_3584690000501997518,2024-07-14 11:29:42,empty,philippe,magnin,philippe.mr@outlook.com,6580234245,empty,empty,empty,...,Other,Web Enquiry,Karma Song Hoai,Form Contact Us,Other,empty,false,true,false,https://karmagroup.com/contact-us/
4692,zcrm_3584690000501997940,2024-07-15 12:33:59,empty,Ong Sze,Keong,ongsk2626@gmail.com,60123132626,empty,empty,empty,...,Other,Past Guests,Karma Jimbaran,Viewpoint,empty,empty,false,true,false,empty

In [18]:
# Cek Email Karma
email_karma = m.find_karma(zoho_df, 'Email')
count_email_karma = email_karma.shape[0]
# email_OTA.to_excel(r'C:\Users\fajar\Documents\Python\Data\email_OTA.xlsx', index=False)

email_karma

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website
571,zcrm_3584690000005973712,2019-04-02 02:17:28,2017-01-18,Fariz,Ab,odysseyasiapac@rci.com,6591060936,empty,1982-10-05,1982,...,Other,Past Guests,Karma Jimbaran,Karma Jimbaran,Other,No Response,false,false,false,empty
1082,zcrm_3584690000006012896,2019-04-02 02:21:13,2017-01-18,Natalie,Poh,natalie.poh@rci.com,65064122146,empty,empty,empty,...,Other,Past Guests,Karma Kandara,Karma Kandara,Other,No Response,false,false,false,empty
1218,zcrm_3584690000007157037,2019-04-02 05:24:46,2016-07-26,Seri,Seri,seri.okuno@rci.com,6585690316,15708,empty,empty,...,Other,Webchat,empty,empty,Other,empty,false,false,false,empty
1889,zcrm_3584690000008522519,2019-04-02 08:11:21,2017-01-18,Jonathan,Mills,jonathan.mills@rci.com,65091380059,empty,empty,empty,...,Other Bali DB,Chairman database,empty,Purple Wifi,Other,empty,false,false,false,empty
3308,zcrm_3584690000158666052,2020-01-13 20:54:22,2019-10-22,empty,empty,alisa.nguyen@rci.com,6562234333,empty,empty,empty,...,Other,Webchat,empty,Karma Group Website Concierge,Other,New Lead,false,false,false,https://karmagroup.com/
3756,zcrm_3584690000414915776,2022-12-05 13:29:19,empty,Liu Juan,Jane,jane.liu@rci.com,6562234333,empty,empty,empty,...,Other,Past Guests,Karma Royal Candidasa,Viewpoint,empty,empty,false,true,false,empty

In [19]:
# delete email Karma
count_after_clean_karma = m.delete_karma(zoho_df, 'Email')
# zoho_df.to_excel(r'C:\Users\fajar\Documents\Python\Data\after_clean_OTA.xlsx', index=False)

zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website
0,zcrm_3584690000000456191,2019-01-09 11:10:49,empty,Kim Guan,Pua,adelinephua555@gmail.com,empty,empty,1937-09-14,1937,...,Other,Past Guests,Karma Jimbaran,empty,Other,New Lead,true,false,false,empty
1,zcrm_3584690000000456198,2019-01-09 11:10:49,empty,Pauline,Shek,admin@surpass.com.sg,6597811782,empty,empty,empty,...,Other,Past Guests,Karma Rottnest,empty,Other,New Lead,true,false,false,empty
2,zcrm_3584690000000457744,2019-01-09 11:10:59,empty,Tan Cheng,Kiat,christan@telair.com.sg,6596601533,empty,1963-11-03,1963,...,Other,Past Guests,Karma Bavaria,empty,Other,No Response,true,false,false,empty
3,zcrm_3584690000000458638,2019-01-09 11:11:04,empty,Eilleen,Keith Luna,ekalfarosale@gmail.com,6598607340,empty,1988-11-07,1988,...,Other,Past Guests,Karma Kandara,empty,Other,No Response,true,false,false,empty
4,zcrm_3584690000000459002,2019-01-09 11:11:06,empty,Fong,Jong Han,empty,60122987926,empty,empty,empty,...,Other,Past Guests,Karma Rottnest,empty,Other,New Lead,true,false,false,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4682,zcrm_3584690000501952879,2024-07-14 16:52:37,empty,Aileen,Neoh,aneoh@hotmail.com,6588230189,empty,empty,empty,...,Other,Web Enquiry,Karma Bayon,Timeshare Booking Request,Other,empty,false,true,true,https://karmagroup.com/find-destination/karma-...
4683,zcrm_3584690000501960205,2024-07-14 19:56:26,2024-07-01,Simeen,Malik,simeenz@gmail.com,empty,empty,empty,empty,...,Karma Spa,Past Guests,Karma Kandara,empty,empty,New Lead,false,false,false,empty
4684,zcrm_3584690000501977044,2024-07-12 03:12:18,empty,Jolene,Quek,jolenedayle@gmail.com,6596920977,empty,empty,empty,...,Other,Web Enquiry,Karma Kandara,Karma Kandara -Download Wedding Brochure at Ka...,Other,empty,false,true,false,https://karmagroup.com/weddings-at-karma-kanda...
4685,zcrm_3584690000501997518,2024-07-14 11:29:42,empty,philippe,magnin,philippe.mr@outlook.com,6580234245,empty,empty,empty,...,Other,Web Enquiry,Karma Song Hoai,Form Contact Us,Other,empty,false,true,false,https://karmagroup.com/contact-us/
4686,zcrm_3584690000501997940,2024-07-15 12:33:59,empty,Ong Sze,Keong,ongsk2626@gmail.com,60123132626,empty,empty,empty,...,Other,Past Guests,Karma Jimbaran,Viewpoint,empty,empty,false,true,false,empty

In [20]:
find_member_booking = zoho_df.copy()

find_member_booking.loc[find_member_booking['Phone'].isin(df_booking['Phone1']), 'Same Value Find'] = 'Booking-Phone1'
find_member_booking.loc[find_member_booking['Phone'].isin(df_booking['Mobile']), 'Same Value Find'] = 'Booking-Mobile'
find_member_booking.loc[find_member_booking['Mobile'].isin(df_booking['Phone1']), 'Same Value Find'] = 'Booking-Phone1' 
find_member_booking.loc[find_member_booking['Mobile'].isin(df_booking['Mobile']), 'Same Value Find'] = 'Booking-Mobile'
find_member_booking.loc[find_member_booking['Email'].isin(df_booking['Email']), 'Same Value Find'] = 'Booking-Email'

find_member_booking.loc[find_member_booking['Phone'].isin(df_phone['Mobile']), 'Same Value Find'] = 'Member-Mobile' 
find_member_booking.loc[find_member_booking['Mobile'].isin(df_phone['Mobile']), 'Same Value Find'] = 'Member-Mobile'

find_member_booking.loc[find_member_booking['Email'].isin(df_email['Email']), 'Same Value Find'] = 'Member-Email'

find_member_booking.drop(find_member_booking.loc[find_member_booking['Same Value Find'].isna()].index, inplace=True)

count_booking_dedup = find_member_booking.loc[find_member_booking['Same Value Find'].str.contains('Booking', flags=re.I, regex=True)].shape[0]
count_member_dedup = find_member_booking.loc[find_member_booking['Same Value Find'].str.contains('Member', flags=re.I, regex=True)].shape[0]

find_member_booking.replace('empty', '', inplace=True)
# find_member_booking.to_csv(r'C:\Users\fajar\Documents\Python\Data\booking-member-dedup.csv', index=False)
# find_member_booking.to_excel(r'C:\Users\fajar\Documents\Python\Data\booking-member-dedup.xlsx', index=False)

#find_member_booking.loc[find_member_booking['Same Value Find'] == 'Booking-Phone1']

In [21]:
# data phone, mobile dam email member yang ada di master data 
count_wash_member = zoho_df.loc[
    zoho_df['Phone'].isin(df_booking['Phone1']) | 
    zoho_df['Phone'].isin(df_booking['Mobile']) |
    zoho_df['Mobile'].isin(df_booking['Phone1']) | 
    zoho_df['Mobile'].isin(df_booking['Mobile']) |
    zoho_df['Email'].isin(df_booking['Email'])| 

    zoho_df['Phone'].isin(df_phone['Mobile']) | 
    zoho_df['Mobile'].isin(df_phone['Mobile']) |

    zoho_df['Email'].isin(df_email['Email'])

].shape[0]

zoho_df.drop(zoho_df.loc[
    zoho_df['Phone'].isin(df_booking['Phone1']) | 
    zoho_df['Phone'].isin(df_booking['Mobile']) |
    zoho_df['Mobile'].isin(df_booking['Phone1']) | 
    zoho_df['Mobile'].isin(df_booking['Mobile']) |
    zoho_df['Email'].isin(df_booking['Email']) |
    
    zoho_df['Phone'].isin(df_phone['Mobile']) | 
    zoho_df['Mobile'].isin(df_phone['Mobile']) |

    zoho_df['Email'].isin(df_email['Email'])

    ].index, inplace=True)
    
zoho_df.reset_index(drop=True, inplace=True)

count_after_wash_member = zoho_df.shape[0]

In [23]:
# Categorize contacts
m.categorize_contacts(zoho_df)

# Count contact types
count_email_only = (zoho_df['Contact Type'] == 'Email Only').sum()
count_phone_only = (zoho_df['Contact Type'] == 'Phone Only').sum()
count_email_and_phone = (zoho_df['Contact Type'] == 'Email and Phone').sum()
count_blank = (zoho_df['Contact Type'] == 'Blank').sum()

# Remove blank contacts if needed
zoho_df = zoho_df[zoho_df['Contact Type'] != 'Blank']
zoho_df.reset_index(drop=True, inplace=True)

count_after_wash_blank = zoho_df.shape[0]

In [24]:
arr_dedup = [count_deleted_wrong_format, count_duplicate_general, count_leads_test, count_email_OTA, count_email_karma, count_blank]
count_sum_dedup = sum(arr_dedup)
count_sum_dedup

134

In [25]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Keseluruhan Master Zoho : "+str(count_data_awal))
print("Jumlah Filter Leads Awal : "+str(count_filter_awal))
print("Jumlah Format Email Salah : "+str(count_deleted_wrong_format))
print("Jumlah Setelah Clean Format Email Salah : "+str(count_after_deleted_wrong_format))
print("Jumlah Duplicate (Phone, Mobile dan Email) : "+str(count_duplicate_general))
print("Jumlah Setelah Clean Duplicate : "+str(count_after_dedup_duplicate))
print("Jumlah Lead Test : "+str(count_leads_test))
print("Jumlah Setelah Clean Lead Test : "+str(count_after_dedup_test))
# print("Jumlah Lead Do Not Mail : "+str(count_dnm))
# print("Jumlah Setelah Clean Lead Do Not Mail : "+str(count_after_dedup_dnm))
print("Jumlah Email OTA : "+str(count_email_OTA))
print("Jumlah Setelah Clean Email OTA : "+str(count_after_clean_OTA))
print("Jumlah Email Karma : "+str(count_email_karma))
print("Jumlah Setelah Clean Email Karma : "+str(count_after_clean_karma))
print("Jumlah Wash Member : "+str(count_member_dedup))
print("Jumlah Wash Booking : "+str(count_booking_dedup))
print("Jumlah Setelah Wash Member : "+str(count_after_wash_member))
print("Jumlah Phone Email Blank (Setelah phone yang tidak valid dihapus) : "+str(count_blank))
print("Jumlah Setelah Wash Phone Email Blank : "+str(count_after_wash_blank))
print("==========================================================")
print("Contact Type")
print("==========================================================")
print("Jumlah Email Only : "+str(count_email_only))
print("Jumlah Phone Only : "+str(count_phone_only))
print("Jumlah Email dan Phone : "+str(count_email_and_phone))

==========================================================
Summary
==========================================================
Jumlah Keseluruhan Master Zoho : 456203
Jumlah Filter Leads Awal : 4821
Jumlah Format Email Salah : 0
Jumlah Setelah Clean Format Email Salah : 4821
Jumlah Duplicate (Phone, Mobile dan Email) : 119
Jumlah Setelah Clean Duplicate : 4702
Jumlah Lead Test : 0
Jumlah Setelah Clean Lead Test : 4702
Jumlah Email OTA : 9
Jumlah Setelah Clean Email OTA : 4693
Jumlah Email Karma : 6
Jumlah Setelah Clean Email Karma : 4687
Jumlah Wash Member : 187
Jumlah Wash Booking : 19
Jumlah Setelah Wash Member : 4481
Jumlah Phone Email Blank (Setelah phone yang tidak valid dihapus) : 0
Jumlah Setelah Wash Phone Email Blank : 4481
==========================================================
Contact Type
==========================================================
Jumlah Email Only : 880
Jumlah Phone Only : 583
Jumlah Email dan Phone : 3018

In [26]:
print("==========================================================")
print("Summary Report")
print("==========================================================")
print("Jumlah Data Awal : "+str(count_filter_awal))
print("Jumlah Wash Dedup : "+str(count_sum_dedup))
print("Jumlah Wash Member : "+str(count_member_dedup))
print("Jumlah Wash Booking : "+str(count_booking_dedup))
print("Jumlah Data Akhir : "+str(count_after_wash_blank))

==========================================================
Summary Report
==========================================================
Jumlah Data Awal : 4821
Jumlah Wash Dedup : 134
Jumlah Wash Member : 187
Jumlah Wash Booking : 19
Jumlah Data Akhir : 4481

# ====================== Akhir Filter Umum ======================

In [27]:
zoho_df.replace('empty', '', inplace=True, regex=True)

zoho_df['First Name'] = zoho_df['First Name'].str.title()
zoho_df['Last Name'] = zoho_df['Last Name'].str.title()

zoho_df.to_excel(r'C:\Users\fajar\Documents\Python\Data\data_req_new.xlsx', index=False)

In [28]:
zoho_df.groupby('Country').count()

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website,Contact Type
Country,,,,,,,,,,,,,,,,,,,,,
Australia,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
China,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
France,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Germany,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
Indonesia,8,8,8,8,8,8,8,8,8,8,...,8,8,8,8,8,8,8,8,8,8
Malaysia,898,898,898,898,898,898,898,898,898,898,...,898,898,898,898,898,898,898,898,898,898
New Zealand,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
SIngapore,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Singapore,3548,3548,3548,3548,3548,3548,3548,3548,3548,3548,...,3548,3548,3548,3548,3548,3548,3548,3548,3548,3548
South Korea,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
United Arab Emirates,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
United Kingdom,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
United States,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
empty,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
singapore,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3

In [29]:
# zoho_df['Country'].loc[
#     (zoho_df['Phone'].str.contains('^44|^\+44')) & 
#     (~zoho_df['Country'].str.contains('united kingdom|wales|england|scotland|northern ireland', regex=True, flags=re.I))
# ]