In [1]:
import main_module as m
import zoho_filter_module as fil
import pandas as pd
import re
import numpy as np

%load_ext autoreload
%autoreload 2

dir_path = r'C:\Users\fajar\Documents\Python\Data\Zoho_Backup\2020-2024'
dir_path_live = r'C:\Users\fajar\Documents\Python\Data\Zoho_Backup'
dir_path_old = r'C:\Users\fajar\Documents\Python\Data\Zoho_Backup\old'
file_name = '\Leads_'

cols = ['Record Id',	
'Created Time',
'Created Date',	
'First Name',	
'Last Name',	
'Email',	
'Phone',	
'Mobile',	
'Birthdate',	
'Year of Birth',
'Street',	
'Street2',	
'City',	
'State',	
'Country',	
'Nationality',
'Booking Status', 
'BookRef',
'Departure Date',	
'Arrival Date',	
'Card Type',	
'Marital Status',	
'Lead Brand',	
'Lead Sub-Brand',	
'Lead Source',	
'Lead Locations',	
'Lead Source Description',	
'Lead Regions',
'Lead Status',
'Email Opt Out',	
'Opt In',
'GDPR Compliant',
'Website',
'Comments']

In [ ]:
email = 'patrick@opply.com'

In [2]:
path = dir_path_live+'\\backup.csv'
df_all = pd.read_csv(path, dtype='string', on_bad_lines='skip')
count_data_awal = df_all.shape[0]
df_all.drop(df_all.loc[df_all['Created Time'].str.len() < 5 ].index, inplace=True)
df_all.reset_index(drop=True, inplace=True)

df_all['Created Time'] = pd.to_datetime(df_all['Created Time'], format='%Y-%m-%d %H:%M:%S')

df_all.shape[0]
df_all

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Arrival Date,Card Type,Marital Status,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status
0,zcrm_3584690000000404058,2019-01-07 15:08:38,2019-01-06,Nicholas,Wood,1230woodnicholas@gmail.com,61438600845,<NA>,<NA>,<NA>,...,2019-01-06 00:00:00,<NA>,<NA>,Timeshare Marketing,Other Bali DB,Wifi,Purple Wifi,<NA>,SEAP,New Lead
1,zcrm_3584690000000404059,2019-01-07 15:08:38,2019-01-06,Liao,Yuan,158066546@qq.com,8618718399923,<NA>,<NA>,<NA>,...,2019-01-06 00:00:00,<NA>,<NA>,Timeshare Marketing,Other Bali DB,Wifi,Purple Wifi,<NA>,Other,New Lead
2,zcrm_3584690000000404060,2019-01-07 15:08:38,2019-01-06,Vedanta,Abhiyoga,abhiyoga.vedanta@gmail.com,6282146524550,<NA>,2000-07-05,2000,...,2018-12-01 00:00:00,<NA>,Pelajar,Timeshare Marketing,Other Bali DB,Wifi,Purple Wifi,<NA>,SEAP,New Lead
3,zcrm_3584690000000404065,2019-01-07 15:08:38,2019-01-06,Aidai,Atakanova,aidai.nurbek@gmail.com,996779641590,<NA>,1997-02-05,1997,...,2019-01-06 00:00:00,<NA>,Single,Timeshare Marketing,Other Bali DB,Wifi,Purple Wifi,<NA>,UK/Europe,New Lead
4,zcrm_3584690000000404068,2019-01-07 15:08:38,2019-01-06,Ardra,Ardra,aliefardraqariru@gmail.com,+6282139300818,+6282139300818,2005-01-20,2005,...,2018-11-30 00:00:00,<NA>,OTHER,Timeshare Marketing,Other Bali DB,Wifi,Purple Wifi,WIFI USER ID 13494142,SEAP,New Lead
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9965978,zcrm_3584690000489266005,2024-03-25 16:19:45,<NA>,Keval,Gala,keval2403@gmail.com,+919022872972,+917700904802,<NA>,<NA>,...,2024-03-21,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Royal Palms,Viewpoint,<NA>,<NA>
9965979,zcrm_3584690000489266034,2024-03-25 16:19:51,<NA>,Suresh,Shroff,sureshshroff@breachcandyhospital.org,+919819533303,+919819814280,<NA>,<NA>,...,2024-03-21,<NA>,<NA>,Karma Resorts,Other,Past Guests,"Karma Sitabani, Corbett",Viewpoint,<NA>,<NA>
9965980,zcrm_3584690000489266063,2024-03-25 17:29:27,<NA>,Nathan,Fernandes,nathan.fernandes@karmagroup.com,+9179724486854,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,Karma Group,Karma Community,Quiz,<NA>,Karma Community | Edition 218 - Words to the Wise,India,<NA>
9965981,zcrm_3584690000489269015,2024-03-25 16:20:25,<NA>,Leonora,Hackman,leonora_hf@bigpond.com,+61439855115,<NA>,<NA>,<NA>,...,2024-03-14,<NA>,<NA>,Karma Resorts,Other,Past Guests,Karma Jimbaran,Viewpoint,<NA>,<NA>
9965982,zcrm_3584690000489271002,2024-03-25 18:40:17,<NA>,Annu,Shriwastav,annusrivastava1990@gmail.com,+919561074124,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,Timeshare Marketing,Other,Web Enquiry,Karma Sitabani,Timeshare Booking Request,India,<NA>

In [3]:
df_old = m.load_data_multiple(dir_path_old, file_name, cols)
count_data_awal = df_old.shape[0]
df_old = df_old.reindex(columns=cols)
df_old.shape[0]

df_old['Created Time'] = pd.to_datetime(df_old['Created Time'], format='%Y-%m-%d %H:%M:%S')
df_old['Arrival Date'] = pd.to_datetime(df_old['Arrival Date'], format='%Y-%m-%d')
df_old['Departure Date'] = pd.to_datetime(df_old['Departure Date'], format='%Y-%m-%d')
# fungsi errors cource untuk menhindari error jika value data date null atau kosong
# df['Birthdate'] = pd.to_datetime(df['Birthdate'], format='%Y-%m-%d', errors='coerce')
df_old.dtypes
df_old

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website,Comments
0,zcrm_3584690000000404058,2019-01-07 15:08:38,2019-01-06,Nicholas,Wood,1230woodnicholas@gmail.com,+61438600845,<NA>,<NA>,<NA>,...,Wifi,<NA>,Purple Wifi,SEAP,New Lead,false,false,false,<NA>,<NA>
1,zcrm_3584690000000404059,2019-01-07 15:08:38,2019-01-06,Liao,Yuan,158066546@qq.com,8618718399923,<NA>,<NA>,<NA>,...,Wifi,<NA>,Purple Wifi,Other,New Lead,false,false,false,<NA>,<NA>
2,zcrm_3584690000000404060,2019-01-07 15:08:38,2019-01-06,Vedanta,Abhiyoga,abhiyoga.vedanta@gmail.com,+6282146524550,<NA>,2000-07-05,2000,...,Wifi,<NA>,Purple Wifi,SEAP,New Lead,false,false,false,<NA>,<NA>
3,zcrm_3584690000000404065,2019-01-07 15:08:38,2019-01-06,Aidai,Atakanova,aidai.nurbek@gmail.com,996779641590,<NA>,1997-02-05,1997,...,Wifi,<NA>,Purple Wifi,UK/Europe,New Lead,false,false,false,<NA>,<NA>
4,zcrm_3584690000000404068,2019-01-07 15:08:38,2019-01-06,Ardra,Ardra,aliefardraqariru@gmail.com,+6282139300818,+6282139300818,2005-01-20,2005,...,Wifi,Mall 21,Purple Wifi,SEAP,New Lead,false,false,false,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4717718,zcrm_3584690000475135007,2024-01-01 18:16:02,<NA>,Upendra,Mishra,upendra.sir@gmail.com,+919036084550,<NA>,<NA>,<NA>,...,Web Enquiry,Karma Sunshine Village,Timeshare Booking Request,India,<NA>,false,true,true,https://karmagroup.com/find-destination/karma-...,<NA>
4717719,zcrm_3584690000475135045,2024-01-01 18:16:37,<NA>,Mehul,Prajapati,mehul.m111985@gmail.com,+919714713689,<NA>,<NA>,<NA>,...,Facebook Ads,General,IND | FB MF | Lead captured,<NA>,<NA>,false,false,false,<NA>,<NA>
4717720,zcrm_3584690000475136005,2024-01-01 18:17:13,<NA>,swati,agarwala,cswatiadv@gmail.com,+919733055636,<NA>,<NA>,<NA>,...,Facebook Ads,Karma Martam,IND | FB MF | Martam,<NA>,<NA>,false,false,false,<NA>,<NA>
4717721,zcrm_3584690000475138034,2024-01-01 18:48:36,<NA>,SUMON,SAHOO,sumonsahoo@gmail.com,+918910484814,<NA>,<NA>,<NA>,...,Facebook Ads,Karma Martam,IND | FB MF | Martam,<NA>,<NA>,false,false,false,<NA>,<NA>
4717722,zcrm_3584690000475138069,2024-01-01 18:52:24,<NA>,Rohit,Kadam,rohit0918.rk@gmail.com,+919819185446,<NA>,<NA>,<NA>,...,Facebook Ads,Royal Palms,IND | FB AF | KRP,<NA>,<NA>,false,false,false,<NA>,<NA>

In [4]:
df_live = m.load_data_multiple(dir_path_live, file_name, cols)
count_data_awal = df_live.shape[0]
df_live = df_live.reindex(columns=cols)
df_live.shape[0]

df_live['Created Time'] = pd.to_datetime(df_live['Created Time'], format='%Y-%m-%d %H:%M:%S')
df_live['Arrival Date'] = pd.to_datetime(df_live['Arrival Date'], format='%Y-%m-%d')
df_live['Departure Date'] = pd.to_datetime(df_live['Departure Date'], format='%Y-%m-%d')
# fungsi errors cource untuk menhindari error jika value data date null atau kosong
# df['Birthdate'] = pd.to_datetime(df['Birthdate'], format='%Y-%m-%d', errors='coerce')
df_live.dtypes
df_live

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,GDPR Compliant,Website,Comments
0,zcrm_3584690000000404602,2019-01-08 11:07:28,2021-07-21,Frederic,Bonin,fredericbonin79@gmail.com,+6281236100502,<NA>,1981-10-03,1981,...,Agency,Karma Kandara,KAREN,SEAP,New Lead,false,false,false,<NA>,<NA>
1,zcrm_3584690000000450071,2019-01-08 16:38:18,<NA>,Sebastian,Rach,<NA>,+498914342111,<NA>,1982-04-20,1982,...,Past Guests,Karma Bavaria,<NA>,UK/Europe,New Lead,true,false,false,<NA>,<NA>
2,zcrm_3584690000000450087,2019-01-08 16:38:18,<NA>,Siobhan,Gallagher,gallaghersiobhan@eircom.net,353879597603,<NA>,1973-03-14,1973,...,Past Guests,Karma Bavaria,<NA>,UK/Europe,New Lead,false,true,true,<NA>,<NA>
3,zcrm_3584690000000450106,2019-01-08 16:38:18,<NA>,Lisa,Ferkovich,lisajo2009@yahoo.com,14062394749,<NA>,1963-07-08,1963,...,Past Guests,Karma Bavaria,<NA>,UK/Europe,New Lead,true,false,false,<NA>,<NA>
4,zcrm_3584690000000450109,2019-01-08 16:38:18,<NA>,Ana Maria,Weileder,m.weileder@sonnenlink.de,15253234700,<NA>,<NA>,<NA>,...,Other,Karma Bavaria,MICE Contacts from Ioanna email,UK/Europe,New Lead,false,true,true,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456198,zcrm_3584690000502118035,2024-07-15 17:01:09,<NA>,P,M BHADRE,pmbhadre@gmail.com,<NA>,<NA>,<NA>,<NA>,...,Webchat,<NA>,Karma Experience India | Webchat Web,India,<NA>,false,true,false,https://karmagroup.com/member-login/,<NA>
456199,zcrm_3584690000502118068,2024-07-15 17:42:29,<NA>,Stephan,Joachim,joastephan@yahoo.de,+491621791259,<NA>,<NA>,<NA>,...,Web Enquiry,<NA>,Form Contact Us,UK/Europe,<NA>,false,true,true,https://karmagroup.com/contact-us/,<NA>
456200,zcrm_3584690000502119001,2024-07-15 16:34:56,<NA>,Alvin,Cabautan,alvin.cabautan@gmail.com,+610416159756,+610416159756,<NA>,<NA>,...,Web Enquiry,General,KE | Web | Newsletter Footer,SEAP,Not Qualified,false,false,false,https://www.karmaexperience.com/,<NA>
456201,zcrm_3584690000502121002,2024-07-15 17:01:02,<NA>,Quyen,Martin,cindykim10@yahoo.com,+61421235687,<NA>,<NA>,<NA>,...,Web Enquiry,Karma Song Hoai,Timeshare Booking Request,SEAP,<NA>,false,true,true,https://karmagroup.com/,<NA>
456202,zcrm_3584690000502124001,2024-07-15 17:36:44,2024-07-15,<NA>,Jen Clay,jenclay22@hotmail.com,+971582433297,<NA>,<NA>,<NA>,...,Web Enquiry,Karma La Herriza,Karma La Herriza - Download Wedding Brochure a...,Middle East,<NA>,false,true,false,https://karmagroup.com/weddings-at-karma-la-he...,<NA>

In [5]:
df = pd.concat([df_all,df_old,df_live])
df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source Description,Lead Regions,Lead Status,Booking Status,BookRef,Email Opt Out,Opt In,GDPR Compliant,Website,Comments
0,zcrm_3584690000000404058,2019-01-07 15:08:38,2019-01-06,Nicholas,Wood,1230woodnicholas@gmail.com,61438600845,<NA>,<NA>,<NA>,...,<NA>,SEAP,New Lead,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,zcrm_3584690000000404059,2019-01-07 15:08:38,2019-01-06,Liao,Yuan,158066546@qq.com,8618718399923,<NA>,<NA>,<NA>,...,<NA>,Other,New Lead,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,zcrm_3584690000000404060,2019-01-07 15:08:38,2019-01-06,Vedanta,Abhiyoga,abhiyoga.vedanta@gmail.com,6282146524550,<NA>,2000-07-05,2000,...,<NA>,SEAP,New Lead,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,zcrm_3584690000000404065,2019-01-07 15:08:38,2019-01-06,Aidai,Atakanova,aidai.nurbek@gmail.com,996779641590,<NA>,1997-02-05,1997,...,<NA>,UK/Europe,New Lead,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,zcrm_3584690000000404068,2019-01-07 15:08:38,2019-01-06,Ardra,Ardra,aliefardraqariru@gmail.com,+6282139300818,+6282139300818,2005-01-20,2005,...,WIFI USER ID 13494142,SEAP,New Lead,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456198,zcrm_3584690000502118035,2024-07-15 17:01:09,<NA>,P,M BHADRE,pmbhadre@gmail.com,<NA>,<NA>,<NA>,<NA>,...,Karma Experience India | Webchat Web,India,<NA>,<NA>,<NA>,false,true,false,https://karmagroup.com/member-login/,<NA>
456199,zcrm_3584690000502118068,2024-07-15 17:42:29,<NA>,Stephan,Joachim,joastephan@yahoo.de,+491621791259,<NA>,<NA>,<NA>,...,Form Contact Us,UK/Europe,<NA>,<NA>,<NA>,false,true,true,https://karmagroup.com/contact-us/,<NA>
456200,zcrm_3584690000502119001,2024-07-15 16:34:56,<NA>,Alvin,Cabautan,alvin.cabautan@gmail.com,+610416159756,+610416159756,<NA>,<NA>,...,KE | Web | Newsletter Footer,SEAP,Not Qualified,<NA>,<NA>,false,false,false,https://www.karmaexperience.com/,<NA>
456201,zcrm_3584690000502121002,2024-07-15 17:01:02,<NA>,Quyen,Martin,cindykim10@yahoo.com,+61421235687,<NA>,<NA>,<NA>,...,Timeshare Booking Request,SEAP,<NA>,<NA>,<NA>,false,true,true,https://karmagroup.com/,<NA>
456202,zcrm_3584690000502124001,2024-07-15 17:36:44,2024-07-15,<NA>,Jen Clay,jenclay22@hotmail.com,+971582433297,<NA>,<NA>,<NA>,...,Karma La Herriza - Download Wedding Brochure a...,Middle East,<NA>,<NA>,<NA>,false,true,false,https://karmagroup.com/weddings-at-karma-la-he...,<NA>

In [6]:
df.loc[df['Email'] == email]

Empty DataFrame
Columns: [Record Id, Created Time, Created Date, First Name, Last Name, Email, Phone, Mobile, Birthdate, Year of Birth, Street, Street2, City, State, Country, Nationality, Departure Date, Arrival Date, Card Type, Marital Status, Lead Brand, Lead Sub-Brand, Lead Source, Lead Locations, Lead Source Description, Lead Regions, Lead Status, Booking Status, BookRef, Email Opt Out, Opt In, GDPR Compliant, Website, Comments]
Index: []

[0 rows x 34 columns]

In [36]:
df.drop_duplicates(subset=['Record Id'], inplace=True)
df.reset_index(drop=True, inplace=True)
count_data_awal = df.shape[0]
df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source Description,Lead Regions,Lead Status,Booking Status,BookRef,Email Opt Out,Opt In,GDPR Compliant,Website,Comments
0,zcrm_3584690000000404058,2019-01-07 15:08:38,2019-01-06,Nicholas,Wood,1230woodnicholas@gmail.com,61438600845,<NA>,<NA>,<NA>,...,<NA>,SEAP,New Lead,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,zcrm_3584690000000404059,2019-01-07 15:08:38,2019-01-06,Liao,Yuan,158066546@qq.com,8618718399923,<NA>,<NA>,<NA>,...,<NA>,Other,New Lead,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,zcrm_3584690000000404060,2019-01-07 15:08:38,2019-01-06,Vedanta,Abhiyoga,abhiyoga.vedanta@gmail.com,6282146524550,<NA>,2000-07-05,2000,...,<NA>,SEAP,New Lead,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,zcrm_3584690000000404065,2019-01-07 15:08:38,2019-01-06,Aidai,Atakanova,aidai.nurbek@gmail.com,996779641590,<NA>,1997-02-05,1997,...,<NA>,UK/Europe,New Lead,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,zcrm_3584690000000404068,2019-01-07 15:08:38,2019-01-06,Ardra,Ardra,aliefardraqariru@gmail.com,+6282139300818,+6282139300818,2005-01-20,2005,...,WIFI USER ID 13494142,SEAP,New Lead,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9984371,zcrm_3584690000499998012,2024-06-24 15:37:00,<NA>,"Infray,",Simon,<NA>,+33785154671,<NA>,<NA>,<NA>,...,Viewpoint,<NA>,<NA>,Checked-Out,2538879,false,true,true,<NA>,<NA>
9984372,zcrm_3584690000499998045,2024-06-24 15:37:34,<NA>,Ni Putu Ethika,Febriyanthi,<NA>,+6282146920092,<NA>,<NA>,<NA>,...,Viewpoint,<NA>,<NA>,Checked-Out,2537438,false,true,false,<NA>,<NA>
9984373,zcrm_3584690000499998078,2024-06-24 16:19:11,<NA>,Joseph,Pangaribuan,joseph.pangaribuan@id.yazaki.com,<NA>,<NA>,<NA>,<NA>,...,Karma Concierge Bali Indonesian | Webchat Web,SEAP,<NA>,<NA>,<NA>,false,true,false,https://karmagroup.com/member-login/,<NA>
9984374,zcrm_3584690000499998111,2024-06-24 17:30:29,<NA>,pintu,lal,plmeena@yahoo.co.in,+919811880301,<NA>,<NA>,<NA>,...,Timeshare Booking Request,India,<NA>,<NA>,<NA>,false,true,true,https://karmagroup.com/find-destination/karma-...,<NA>
9984375,zcrm_3584690000499999015,2024-06-24 16:15:57,<NA>,Anand,Kumar,anandkmr644@gmail.com,+919818617676,<NA>,<NA>,<NA>,...,Form Contact Us,India,<NA>,<NA>,<NA>,false,true,false,https://karmagroup.com/find-destination/karma-...,<NA>

In [37]:
path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04eXpvS1NXTWF2RVE\_BOOKING\Booking By Year\FlyBuy Booking Data (BGAU & BGID & KE).xlsx'
df_booking = pd.read_excel(path, dtype='string', sheet_name='BOOKING_BGAU_BGID_KE')

path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04UUNBME5GOVhoMjA\_ODYSSEY\Phone Members.xlsx'
df_phone = pd.read_excel(path, dtype='string', sheet_name='Sheet1')

path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04UUNBME5GOVhoMjA\_ODYSSEY\Email Members.xlsx'
df_email = pd.read_excel(path, dtype='string', sheet_name='Sheet1')

In [38]:
zoho_filter = fil.user_req(df)
zoho_df = df.loc[zoho_filter].copy() # menggunakan copy untuk menghindari setting copy warning
zoho_df.reset_index(drop=True, inplace=True)
count_filter_awal = zoho_df.shape[0]

# zoho_df.to_excel(r'C:\Users\fajar\Documents\Python\Data\test_leads.xlsx', index=False)
# mengisi kolom <NA> dengan value string 'empty' supaya mudah mengecek data member dan booking dengan isin

zoho_df.fillna('empty', inplace=True)
zoho_df.sort_values('Created Time', ascending=True)

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source Description,Lead Regions,Lead Status,Booking Status,BookRef,Email Opt Out,Opt In,GDPR Compliant,Website,Comments
0,zcrm_3584690000000404133,2019-01-07 15:08:38,2019-01-06,Johannes,Hauptmann,johannesh@hotmail.com,6590189726,empty,1982-05-19,1982,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
1,zcrm_3584690000000404160,2019-01-07 15:08:38,2019-01-06,Philippa,Spellman,philspellman@hotmail.com,6596515025,empty,1972-05-10,1972,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
2,zcrm_3584690000000404199,2019-01-07 15:08:38,2019-01-06,V,H,vimidaminiharidasan@gmail.com,6596526640,empty,empty,empty,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
14,zcrm_3584690000000427592,2019-01-07 16:58:52,2019-02-01,Cheryl,Yong,glamsicle_@msn.com,6598368211,empty,1992-02-01,1992,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
13,zcrm_3584690000000427591,2019-01-07 16:58:52,2019-02-01,Hirohisa,Fukuda,fukudahirohisa1981@yahoo.co.jp,6598207908,empty,empty,empty,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56112,zcrm_3584690000499884136,2024-06-23 20:40:13,2024-06-23,Eli,Weir,eli@weirwhanau.com,empty,empty,empty,empty,...,empty,empty,New Lead,empty,empty,false,false,false,empty,empty
56110,zcrm_3584690000499836586,2024-06-24 15:20:40,empty,Loic,Hemard,loic.hemard@gmail.com,+6598270507,empty,empty,empty,...,Viewpoint,empty,empty,Checked-Out,2456649,false,true,false,empty,empty
56109,zcrm_3584690000499823664,2024-06-24 15:25:28,empty,Rayyan Revinnath Tengga Daram &,Fatimah Jamal Sandairan,revinnath.personal@gmail.com,+60173464207,empty,empty,empty,...,Viewpoint,empty,empty,Checked-Out,2293889,false,true,false,empty,empty
56113,zcrm_3584690000499974416,2024-06-24 15:29:53,empty,Subramaniam,Muniandy,subramuni6633@gmail.com,+60124730660,empty,empty,empty,...,Viewpoint,empty,empty,Checked-Out,2475345,false,true,false,empty,empty
56111,zcrm_3584690000499860873,2024-06-24 15:31:48,empty,Yixiang,Zhou,benkden@yahoo.com,+6598319447,empty,empty,empty,...,Viewpoint,empty,empty,Checked-Out,2538889,false,true,false,empty,empty

# ====================== Awal Filter Umum ======================

In [39]:
# data phone, mobile dam email member yang ada di master data (wash member)

m.clean_number(zoho_df, 'Phone')
m.clean_number(zoho_df, 'Mobile')
m.replace_not_valid_to_empty(zoho_df, 'Phone')
m.replace_not_valid_to_empty(zoho_df, 'Mobile')
zoho_df['Email'] = m.lowercase(zoho_df, 'Email')
m.clean_space(zoho_df, 'Email')
m.clean_not_valid_email_format(zoho_df, 'Email')

m.clean_number(df_booking, 'Phone1')
m.clean_number(df_booking, 'Mobile')
df_booking['Email'] = m.lowercase(df_booking, 'Email')
m.clean_space(df_booking, 'Email')
m.clean_not_valid_email_format(df_booking, 'Email')

m.clean_number(df_phone, 'Mobile')

df_email['Email'] = m.lowercase(df_email, 'Email')
m.clean_space(df_email, 'Email')
m.clean_not_valid_email_format(df_email, 'Email')

'Email'

In [40]:
zoho_df.loc[zoho_df['Phone']=='']

Empty DataFrame
Columns: [Record Id, Created Time, Created Date, First Name, Last Name, Email, Phone, Mobile, Birthdate, Year of Birth, Street, Street2, City, State, Country, Nationality, Departure Date, Arrival Date, Card Type, Marital Status, Lead Brand, Lead Sub-Brand, Lead Source, Lead Locations, Lead Source Description, Lead Regions, Lead Status, Booking Status, BookRef, Email Opt Out, Opt In, GDPR Compliant, Website, Comments]
Index: []

[0 rows x 34 columns]

In [41]:
count_deleted_wrong_format = m.delete_email_wrong_format(zoho_df, 'Email')
count_after_deleted_wrong_format = zoho_df.shape[0]

In [42]:
# hitung jumlah duplicate
count_duplicate_general = zoho_df.loc[zoho_df.duplicated(subset=['Phone','Email', 'Mobile'])].shape[0]

zoho_df.loc[zoho_df.duplicated(subset=['Phone','Email'])]

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source Description,Lead Regions,Lead Status,Booking Status,BookRef,Email Opt Out,Opt In,GDPR Compliant,Website,Comments
61,zcrm_3584690000000462533,2019-01-09 11:11:28,empty,Min,Li Lee,empty,602035640799,empty,empty,empty,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
19822,zcrm_3584690000007587628,2019-04-02 06:13:56,2017-01-16,Binod,Kumar,manju@treamyk.com,60193235960,empty,empty,empty,...,Black Hole Consolidate,Other,empty,empty,empty,empty,empty,empty,empty,empty
36986,zcrm_3584690000009897230,2019-04-02 11:59:09,2000-01-01,Azumi Zul,empty,zaarnis@hotmail.com,6063027629,empty,empty,empty,...,MALAYSIAN ASSOCIATION IN HONG KONG - SONI,Other,empty,empty,empty,empty,empty,empty,empty,empty
49856,zcrm_3584690000024579388,2019-04-07 15:29:28,empty,Elisabeth,Cox,empty,6564699780,empty,empty,empty,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
50017,zcrm_3584690000027868823,2019-04-28 19:09:35,empty,Mariawaty,Mariawaty,mariatjoe@yahoo.com,601115417735,empty,empty,1978,...,BGID | Teleperformance | w4apr19 | Free stay m...,Other,empty,empty,empty,empty,empty,empty,empty,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56093,zcrm_3584690000498865287,2024-06-14 14:25:22,empty,Khoo Kwang,Ulysses,ulysseskhoo@gmail.com,6594375261,6596652223,empty,empty,...,Viewpoint,empty,empty,Checked-Out,2381476,false,true,false,empty,empty
56102,zcrm_3584690000499041168,2024-06-16 12:21:40,empty,Harshal,Joshi,jharshal29jo@gmail.com,6591039703,empty,empty,empty,...,Chat with your Karma Concierge,Other,empty,empty,empty,false,false,false,https://karmaai.karmagroup.com/,empty
56108,zcrm_3584690000499823664,2024-06-24 15:25:28,empty,Rayyan Revinnath Tengga Daram &,Fatimah Jamal Sandairan,revinnath.personal@gmail.com,60173464207,empty,empty,empty,...,Viewpoint,empty,empty,Checked-Out,2293889,false,true,false,empty,empty
56111,zcrm_3584690000499884136,2024-06-23 20:40:13,2024-06-23,Eli,Weir,eli@weirwhanau.com,empty,empty,empty,empty,...,empty,empty,New Lead,empty,empty,false,false,false,empty,empty
56112,zcrm_3584690000499974416,2024-06-24 15:29:53,empty,Subramaniam,Muniandy,subramuni6633@gmail.com,60124730660,empty,empty,empty,...,Viewpoint,empty,empty,Checked-Out,2475345,false,true,false,empty,empty

In [43]:
zoho_df.drop_duplicates(subset=['Phone','Email', 'Mobile'], inplace=True)
zoho_df.reset_index(drop=True, inplace=True)

# hitung jumlah setelah value duplicate dihapus
count_after_dedup_duplicate = zoho_df.shape[0]

zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source Description,Lead Regions,Lead Status,Booking Status,BookRef,Email Opt Out,Opt In,GDPR Compliant,Website,Comments
0,zcrm_3584690000000404133,2019-01-07 15:08:38,2019-01-06,Johannes,Hauptmann,johannesh@hotmail.com,6590189726,empty,1982-05-19,1982,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
1,zcrm_3584690000000404160,2019-01-07 15:08:38,2019-01-06,Philippa,Spellman,philspellman@hotmail.com,6596515025,empty,1972-05-10,1972,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
2,zcrm_3584690000000404199,2019-01-07 15:08:38,2019-01-06,V,H,vimidaminiharidasan@gmail.com,6596526640,empty,empty,empty,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
3,zcrm_3584690000000404452,2019-01-08 11:07:28,2019-01-03,Shigeo,Kawasaki,shigeou1123@gmail.com,6597228507,empty,1977-11-23,1977,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
4,zcrm_3584690000000404870,2019-01-08 11:07:30,2019-01-03,Hsbs,Babas,ssd@sss.com,6593728273,empty,empty,empty,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55631,zcrm_3584690000499165001,2024-06-17 14:42:23,empty,Angela,Tay,angela.wearnxin@gmail.com,60177595390,empty,empty,empty,...,Karma Kandara -Download Wedding Brochure at Ka...,Other,empty,empty,empty,false,true,false,https://karmagroup.com/weddings-at-karma-kanda...,empty
55632,zcrm_3584690000499443111,2024-06-18 23:47:02,empty,sals,gupta,salonigaba@yahoo.com,6586062557,empty,empty,empty,...,Timeshare Booking Request,Other,empty,empty,empty,false,true,true,https://karmagroup.com/find-destination/karma-...,empty
55633,zcrm_3584690000499792076,2024-06-21 10:27:41,empty,Hahs,Hshhz,hshsj@gmail.com,6584160285,empty,empty,empty,...,Karma Beach VIP membership sign up 2023,Other,empty,empty,empty,false,true,false,https://karmagroup.com/karma-beach-vip/,empty
55634,zcrm_3584690000499836586,2024-06-24 15:20:40,empty,Loic,Hemard,loic.hemard@gmail.com,6598270507,empty,empty,empty,...,Viewpoint,empty,empty,Checked-Out,2456649,false,true,false,empty,empty
55635,zcrm_3584690000499860873,2024-06-24 15:31:48,empty,Yixiang,Zhou,benkden@yahoo.com,6598319447,empty,empty,empty,...,Viewpoint,empty,empty,Checked-Out,2538889,false,true,false,empty,empty

In [44]:
# Cek leads test
test_leads = zoho_df.loc[
    
        zoho_df['Email'].str.contains('^test@', flags=re.I, regex=True) |
        zoho_df['Email'].str.contains('\+test', flags=re.I, regex=True) |
    
        zoho_df['First Name'].str.contains('^test$', flags=re.I, regex=True) |
        zoho_df['Last Name'].str.contains('^test$', flags=re.I, regex=True) |

        zoho_df['First Name'].str.contains('test 1', flags=re.I, regex=True) |
        zoho_df['Last Name'].str.contains('test 2', flags=re.I, regex=True)|
        zoho_df['First Name'].str.contains('test1', flags=re.I, regex=True) |
        zoho_df['Last Name'].str.contains('test2', flags=re.I, regex=True)|

        zoho_df['First Name'].str.contains(' test ', flags=re.I, regex=True) | 
        zoho_df['Last Name'].str.contains(' test ', flags=re.I, regex=True) | 
        zoho_df['Last Name'].str.contains(' test$', flags=re.I, regex=True)
    ]

count_leads_test = test_leads.shape[0]

# test_leads.to_excel(r'C:\Users\fajar\Documents\Python\Data\test_leads_2.xlsx', index=False)
test_leads

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source Description,Lead Regions,Lead Status,Booking Status,BookRef,Email Opt Out,Opt In,GDPR Compliant,Website,Comments
53313,zcrm_3584690000305511893,2021-08-10 10:06:23,empty,Test,Booking,hazeline.furing@sojern.com,98745632,empty,empty,empty,...,empty,empty,empty,empty,empty,empty,empty,empty,empty,empty
53722,zcrm_3584690000414940071,2022-12-05 13:17:30,empty,Test,Test,testing-ads@google.com,12345678,empty,empty,empty,...,empty,empty,empty,empty,empty,empty,empty,empty,empty,empty
53764,zcrm_3584690000418823383,2022-12-22 15:14:53,empty,Fajar,Fatoni,fajar.fatoni+test@karmagroup.com,1234759984,empty,empty,empty,...,empty,empty,New Lead,empty,empty,empty,empty,empty,empty,empty

In [45]:
zoho_df.drop(test_leads.index, inplace=True)
zoho_df.reset_index(drop=True, inplace=True)

count_after_dedup_test = zoho_df.shape[0]

In [46]:
# dnm_leads = zoho_df.loc[(zoho_df['Do Not Mail'] == 'true') | (zoho_df['Do Not Contact'] == 'true')]
# count_dnm = dnm_leads.shape[0]

In [47]:
# zoho_df.drop(dnm_leads.index, inplace=True)
# zoho_df.reset_index(drop=True, inplace=True)

# count_after_dedup_dnm = zoho_df.shape[0]

In [48]:
# Cek Email OTA
email_OTA = m.find_OTA(zoho_df, 'Email')
count_email_OTA = email_OTA.shape[0]
# email_OTA.to_excel(r'C:\Users\fajar\Documents\Python\Data\email_OTA.xlsx', index=False)

email_OTA

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source Description,Lead Regions,Lead Status,Booking Status,BookRef,Email Opt Out,Opt In,GDPR Compliant,Website,Comments
1173,zcrm_3584690000005994723,2019-04-02 02:19:27,2015-03-11,Nopri,Aries,summertourtravel@yahoo.com.sg,empty,empty,empty,empty,...,empty,Other,empty,empty,empty,empty,empty,empty,empty,empty
2064,zcrm_3584690000006445354,2019-04-02 03:57:45,2000-01-01,Norazran,Bmohdnor,roy2000tour@hotmail.com,60341061900,empty,empty,empty,...,Karma list email for Bhanu - International,Other,empty,empty,empty,empty,empty,empty,empty,empty
2423,zcrm_3584690000006463501,2019-04-02 03:59:28,2015-03-10,Hock,Goh,beltraveltour@yahoo.com,6062822712,60126822712,empty,empty,...,Singapore,Other,empty,empty,empty,empty,empty,empty,empty,empty
3736,zcrm_3584690000006523479,2019-04-02 04:05:30,2000-01-01,Frederique,Tourret,frederique.tourret@clubmed.com,6568300821,empty,empty,empty,...,Karma list email for Bhanu - Karma,Other,empty,empty,empty,empty,empty,empty,empty,empty
3739,zcrm_3584690000006523490,2019-04-02 04:05:30,2000-01-01,Freddie,Sim,fredsim@creativetours.com.sg,6563203209,empty,empty,empty,...,Karma list email for Bhanu - Karma,Other,empty,empty,empty,empty,empty,empty,empty,empty
5358,zcrm_3584690000006595652,2019-04-02 04:12:49,2000-01-01,Jenny,Wong,jenny@creativetours.com.sg,6563203226,empty,empty,empty,...,Karma list email for Bhanu - Karma,Other,empty,empty,empty,empty,empty,empty,empty,empty
6652,zcrm_3584690000006654115,2019-04-02 04:19:23,2015-04-23,Simon,Graves,simon.graves@pagoda-partners.com,90664607,98184475,empty,empty,...,Belvedere,Other,empty,empty,empty,empty,empty,empty,empty,empty
6738,zcrm_3584690000006656277,2019-04-02 04:19:38,2000-01-01,Dennis,Twchoo,dchoo@holidaytours.com.sg,6562354222,6562382800,empty,empty,...,KARMA DATA - BOOTH DATA,Other,empty,empty,empty,empty,empty,empty,empty,empty
6774,zcrm_3584690000006658105,2019-04-02 04:19:50,2000-01-01,Siti,Majminshaikhsallehjalani,smj@tourismpenang.gov.my,6042620202,empty,empty,empty,...,Karma list email for Bhanu - International,Other,empty,empty,empty,empty,empty,empty,empty,empty
7344,zcrm_3584690000006686949,2019-04-02 04:22:59,2000-01-01,Wang,Shouzhi,tour@singachinatrvl.com.sg,6565329988,empty,empty,empty,...,Karma list email for Bhanu - Karma,Other,empty,empty,empty,empty,empty,empty,empty,empty
7345,zcrm_3584690000006686975,2019-04-02 04:22:59,2000-01-01,Gopinath,Pillai,tourmasters@tour-masters.com,6562957770,empty,empty,empty,...,Karma list email for Bhanu - Karma,Other,empty,empty,empty,empty,empty,empty,empty,empty
9937,zcrm_3584690000006798096,2019-04-02 04:36:00,2000-01-01,Jeff,Radzuankasim,jeff@skyzonetours.com,60321187988,60321187999,empty,empty,...,Karma list email for Bhanu - International,Other,empty,empty,empty,empty,empty,empty,empty,empty
10097,zcrm_3584690000006804938,2019-04-02 04:36:50,2000-01-01,Brigitte,Ow,bodycontours@pacific.net.sg,empty,empty,empty,empty,...,Karma list email for Bhanu - Karma,Other,empty,empty,empty,empty,empty,empty,empty,empty
10557,zcrm_3584690000006822553,2019-04-02 04:38:59,2000-01-01,David,Lai,davidlai@skyzonetours.com,60321429288,empty,empty,empty,...,Karma list email for Bhanu - International,Other,empty,empty,empty,empty,empty,empty,empty,empty
11441,zcrm_3584690000006860465,2019-04-02 04:44:01,2000-01-01,Alice,Lim,alice@creativetours.com.sg,6563203220,empty,empty,empty,...,Karma list email for Bhanu - Karma,Other,empty,empty,empty,empty,empty,empty,empty,empty
12454,zcrm_3584690000006905676,2019-04-02 04:49:38,2000-01-01,Jacqueline,Limkahling,jackielim@holidaytours.com.my,60327191833,empty,empty,empty,...,Karma list email for Bhanu - International,Other,empty,empty,empty,empty,empty,empty,empty,empty
13707,zcrm_3584690000006964042,2019-04-02 04:56:45,2000-01-01,Karin,Lee,klee@toureast.net,6562382894,empty,empty,empty,...,Karma list email for Bhanu - International,Other,empty,empty,empty,empty,empty,empty,empty,empty
14383,zcrm_3584690000006994924,2019-04-02 05:00:58,2000-01-01,Noran,Ujang,noran@tourism.gov.my,60326935188,empty,empty,empty,...,Karma list email for Bhanu - International,Other,empty,empty,empty,empty,empty,empty,empty,empty
14424,zcrm_3584690000006996781,2019-04-02 05:01:14,2015-03-11,Luciano,Paparelli,luk@originaltour.net,empty,empty,empty,empty,...,Business Card Competition,Other,empty,empty,empty,empty,empty,empty,empty,empty
15109,zcrm_3584690000007025790,2019-04-02 05:05:29,2000-01-01,Fabio,Delisi,fabio.delisi@synergy-tours.com,60321633833,empty,empty,empty,...,Karma list email for Bhanu - International,Other,empty,empty,empty,empty,empty,empty,empty,empty
15370,zcrm_3584690000007036773,2019-04-02 05:07:01,2000-01-01,Prema,Muniandy,prema@tourlandmy.com,60379554753,empty,empty,empty,...,Karma list email for Bhanu - International,Other,empty,empty,empty,empty,empty,empty,empty,empty
17343,zcrm_3584690000007122458,2019-04-02 05:20:04,2000-01-01,Padmini,Narayanansivakumar,padmini@millenium-tours.com,6562956930,empty,empty,empty,...,Karma list email for Bhanu - International,Other,empty,empty,empty,empty,empty,empty,empty,empty
17344,zcrm_3584690000007122459,2019-04-02 05:20:04,2000-01-01,Padmini,Narayanan,padmini@millennium-tours.com,6562956930,empty,empty,empty,...,Karma list email for Bhanu - Karma,Other,empty,empty,empty,empty,empty,empty,empty,empty
17757,zcrm_3584690000007152561,2019-04-02 05:24:22,2016-04-21,James,Pelham,james@culturebitesfoodtours.com,6597694845,empty,1978-10-03,1978,...,Event Chairman Invite,Other,empty,empty,empty,empty,empty,empty,empty,empty
18658,zcrm_3584690000007330996,2019-04-02 05:45:54,2015-03-11,Noredah,Otiman,noredah@sabahtourism.com,empty,empty,empty,empty,...,Perth Holiday Travel Expo 2010,Other,empty,empty,empty,empty,empty,empty,empty,empty
18823,zcrm_3584690000007342876,2019-04-02 05:46:59,2015-03-11,empty,Andrey,lolita@vista-tour.ru,empty,empty,empty,empty,...,Restaurant Survey (Rosy),Other,empty,empty,empty,empty,empty,empty,empty,empty
19176,zcrm_3584690000007371608,2019-04-02 05:49:38,2015-03-13,Callie,Tan,callie.tan@holidaytours.com.my,empty,empty,empty,empty,...,empty,Other,empty,empty,empty,empty,empty,empty,empty,empty
19581,zcrm_3584690000007420455,2019-04-02 05:56:16,2015-03-11,Djony,A,djony@bmbtours.com,90012013,empty,empty,empty,...,DATA Jakarta_all_survey NOV 2012,Other,empty,empty,empty,empty,empty,empty,empty,empty
20127,zcrm_3584690000007590487,2019-04-02 06:14:12,2017-01-16,empty,Jada,jacquelitourneur@yahoo.com,empty,empty,empty,empty,...,Black Hole Consolidate,Other,empty,empty,empty,empty,empty,empty,empty,empty
21563,zcrm_3584690000007604603,2019-04-02 06:15:33,2015-05-12,empty,empty,wiwit@amythastours.com,empty,empty,empty,empty,...,Black All Database Mergin,Other,empty,empty,empty,empty,empty,empty,empty,empty
21778,zcrm_3584690000007606452,2019-04-02 06:15:42,2015-04-18,Jane,Durham,tours@okavango.com,empty,empty,empty,empty,...,Black Hole Consolidate,Other,empty,empty,empty,empty,empty,empty,empty,empty
23519,zcrm_3584690000007658602,2019-04-02 06:27:00,2017-06-29,Rzzz,Ali,tours@hin.com.my,empty,empty,empty,empty,...,empty,Other,empty,empty,empty,empty,empty,empty,empty,empty
25330,zcrm_3584690000007880061,2019-04-02 06:50:30,2017-06-29,Norlizah,Soon Jahaya,norlizah@tourism.gov.my,empty,empty,empty,empty,...,empty,Other,empty,empty,empty,empty,empty,empty,empty,empty
29867,zcrm_3584690000008073709,2019-04-02 07:14:51,2017-06-21,Kitty,Chong,deluxetours@hotmail.com,empty,empty,empty,empty,...,empty,Other,empty,empty,empty,empty,empty,empty,empty,empty
32374,zcrm_3584690000008538262,2019-04-02 08:13:32,2000-01-01,Geoh,Coombes,geoff@tourdecure.com.au,6581386865,61294373225,empty,empty,...,Guest exit,Other,empty,empty,empty,empty,empty,empty,empty,empty
33505,zcrm_3584690000008668965,2019-04-02 08:28:06,2019-02-08,Anthony,Lee,owrdreamtour@gmail.com,6598506066,empty,empty,empty,...,empty,Other,empty,empty,empty,empty,empty,empty,empty,empty
33706,zcrm_3584690000008731835,2019-04-02 09:13:16,2012-01-01,Shekhar Basnet,empty,acmetours@wlink.com.np/fivetravel@streamyx.com...,60320267878,6562960317,empty,empty,...,TTF HYDERABAD,Other,empty,empty,empty,empty,empty,empty,empty,empty
35272,zcrm_3584690000009311975,2019-04-02 10:24:17,2011-01-01,Om Prakash Rao,empty,omprakashr@airlinkstours.com,6562995664,6596581214,empty,empty,...,TTF BANGALORE,Other,empty,empty,empty,empty,empty,empty,empty,empty
35276,zcrm_3584690000009313858,2019-04-02 10:24:33,2009-01-01,Bhuvana Ramanand,empty,india@millennium-tours.com,6562956930,9444393595,empty,empty,...,IITM CHENNAI,Other,empty,empty,empty,empty,empty,empty,empty,empty
37412,zcrm_3584690000010080674,2019-04-02 12:33:52,2016-07-11,M Balasubramanian,empty,info@moulistours.com,empty,empty,empty,empty,...,GULF LEADS PRITI 2016 - BATCH 2,Other,empty,empty,empty,empty,empty,empty,empty,empty
40970,zcrm_3584690000012083677,2019-04-02 15:46:26,2015-08-05,Paramasvari,empty,tours@kualalampurbadgrttown.com,60193790571,empty,empty,empty,...,IITM BANGALORE 2015,Other,empty,empty,empty,empty,empty,empty,empty,empty
41250,zcrm_3584690000012265482,2019-04-02 16:03:38,2000-01-01,Pradeep Kumar,empty,pradeep@asianfamoustours.com.my,60342581018,empty,empty,empty,...,ARABIAN TRAVEL MART 2007(UMMAR),Other,empty,empty,empty,empty,empty,empty,empty,empty
49866,zcrm_3584690000025157953,2019-04-09 21:51:45,empty,Stephen,Cheah,scheah@tourism.australia.com,60326111143,empty,empty,empty,...,Media,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
49888,zcrm_3584690000025158022,2019-04-09 21:51:45,empty,Fara,Nokmang,fnokmang@fastbooking.com,6562332730,6591264917,empty,empty,...,Singapore,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
49895,zcrm_3584690000025158029,2019-04-09 21:51:45,empty,Leong,Low,ellow@fastbooking.com,6562232730,6597953436,empty,empty,...,Singapore,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
51092,zcrm_3584690000044531427,2019-06-13 16:08:39,empty,Woo,K M (Jimmy),econtours@gmail.com,62613218,empty,empty,empty,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
51099,zcrm_3584690000044531711,2019-06-13 16:08:42,empty,Eileen,Lim,eileen.lim@hanatour.com,6562224501,6596731516,empty,empty,...,"Yemi - 30%, TA Asian market",Other,New Lead,empty,empty,empty,empty,empty,empty,empty
51103,zcrm_3584690000044531717,2019-06-13 16:08:42,empty,Elaine,Lim,outbound.sales2@skyzonetours.com,60321187888,empty,empty,empty,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
51119,zcrm_3584690000044531850,2019-06-13 16:08:42,empty,Lynn,Ng,jjlynnng@hanatour.com,6562224501,6597450803,empty,empty,...,"Yemi - 30%, TA Asian market",Other,New Lead,empty,empty,empty,empty,empty,empty,empty
51148,zcrm_3584690000044532563,2019-06-13 16:08:48,empty,Eileen,Tan,eileen@atgtours.sg,6564382811,6585118313,empty,empty,...,"Yemi - 30%, TA Asian market",Other,New Lead,empty,empty,empty,empty,empty,empty,empty
51164,zcrm_3584690000044532654,2019-06-13 16:08:48,empty,Kar,Wei Kwong,karwei.kwong@holidatours.com.my,60362866200,empty,empty,empty,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
51174,zcrm_3584690000044532917,2019-06-13 16:08:51,empty,Hanson,Yong,hanson@mtg.tours,6569061089,6598580389,empty,empty,...,"Yemi - 30%, TA Asian market",Other,New Lead,empty,empty,empty,empty,empty,empty,empty
51176,zcrm_3584690000044532949,2019-06-13 16:08:51,empty,Amy,Zuo,amyzuo@satours.com.sg,65352611,6565013927,empty,empty,...,"Yemi - 30%, TA Asian market",Other,New Lead,empty,empty,empty,empty,empty,empty,empty
52117,zcrm_3584690000178433001,2020-04-07 20:00:42,empty,empty,Jowee,jowee.soh@agoda.com,empty,empty,empty,empty,...,Karma Resorts Reservations | Webchat Web,Other,empty,empty,empty,empty,empty,empty,empty,empty
53798,zcrm_3584690000421287078,2023-01-07 18:54:23,empty,Judith,von Prockl,jp@gourmetontour.com,6587277080,empty,empty,empty,...,Form Contact Us,SEAP,empty,empty,empty,empty,empty,empty,empty,empty

In [49]:
# delete email OTA
count_after_clean_OTA = m.delete_OTA(zoho_df, 'Email')
# zoho_df.to_excel(r'C:\Users\fajar\Documents\Python\Data\after_clean_OTA.xlsx', index=False)

zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source Description,Lead Regions,Lead Status,Booking Status,BookRef,Email Opt Out,Opt In,GDPR Compliant,Website,Comments
0,zcrm_3584690000000404133,2019-01-07 15:08:38,2019-01-06,Johannes,Hauptmann,johannesh@hotmail.com,6590189726,empty,1982-05-19,1982,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
1,zcrm_3584690000000404160,2019-01-07 15:08:38,2019-01-06,Philippa,Spellman,philspellman@hotmail.com,6596515025,empty,1972-05-10,1972,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
2,zcrm_3584690000000404199,2019-01-07 15:08:38,2019-01-06,V,H,vimidaminiharidasan@gmail.com,6596526640,empty,empty,empty,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
3,zcrm_3584690000000404452,2019-01-08 11:07:28,2019-01-03,Shigeo,Kawasaki,shigeou1123@gmail.com,6597228507,empty,1977-11-23,1977,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
4,zcrm_3584690000000404870,2019-01-08 11:07:30,2019-01-03,Hsbs,Babas,ssd@sss.com,6593728273,empty,empty,empty,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55573,zcrm_3584690000499165001,2024-06-17 14:42:23,empty,Angela,Tay,angela.wearnxin@gmail.com,60177595390,empty,empty,empty,...,Karma Kandara -Download Wedding Brochure at Ka...,Other,empty,empty,empty,false,true,false,https://karmagroup.com/weddings-at-karma-kanda...,empty
55574,zcrm_3584690000499443111,2024-06-18 23:47:02,empty,sals,gupta,salonigaba@yahoo.com,6586062557,empty,empty,empty,...,Timeshare Booking Request,Other,empty,empty,empty,false,true,true,https://karmagroup.com/find-destination/karma-...,empty
55575,zcrm_3584690000499792076,2024-06-21 10:27:41,empty,Hahs,Hshhz,hshsj@gmail.com,6584160285,empty,empty,empty,...,Karma Beach VIP membership sign up 2023,Other,empty,empty,empty,false,true,false,https://karmagroup.com/karma-beach-vip/,empty
55576,zcrm_3584690000499836586,2024-06-24 15:20:40,empty,Loic,Hemard,loic.hemard@gmail.com,6598270507,empty,empty,empty,...,Viewpoint,empty,empty,Checked-Out,2456649,false,true,false,empty,empty
55577,zcrm_3584690000499860873,2024-06-24 15:31:48,empty,Yixiang,Zhou,benkden@yahoo.com,6598319447,empty,empty,empty,...,Viewpoint,empty,empty,Checked-Out,2538889,false,true,false,empty,empty

In [50]:
# Cek Email Karma
email_karma = m.find_karma(zoho_df, 'Email')
count_email_karma = email_karma.shape[0]
# email_OTA.to_excel(r'C:\Users\fajar\Documents\Python\Data\email_OTA.xlsx', index=False)

email_karma

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source Description,Lead Regions,Lead Status,Booking Status,BookRef,Email Opt Out,Opt In,GDPR Compliant,Website,Comments
861,zcrm_3584690000005973712,2019-04-02 02:17:28,2017-01-18,Fariz,Ab,odysseyasiapac@rci.com,6591060936,empty,1982-10-05,1982,...,Karma Jimbaran,Other,No Response,empty,empty,empty,empty,empty,empty,empty
1476,zcrm_3584690000006012896,2019-04-02 02:21:13,2017-01-18,Natalie,Poh,natalie.poh@rci.com,65064122146,empty,empty,empty,...,Karma Kandara,Other,No Response,empty,empty,empty,empty,empty,empty,empty
3578,zcrm_3584690000006516392,2019-04-02 04:04:45,2017-01-23,Eunice,Yap,eunice.yap@rci.com,64122171,empty,empty,empty,...,Belvedere,Other,empty,empty,empty,empty,empty,empty,empty,empty
5272,zcrm_3584690000006591763,2019-04-02 04:12:25,2015-04-23,Winnie,Ding,winnie.ding@rci.com,empty,empty,empty,empty,...,Belvedere,Other,empty,empty,empty,empty,empty,empty,empty,empty
7312,zcrm_3584690000006685934,2019-04-02 04:22:52,2015-05-12,Edena,Soong Ing Low Ing,edena.low@rci.com,empty,empty,empty,empty,...,Belvedere,Other,empty,empty,empty,empty,empty,empty,empty,empty
10386,zcrm_3584690000006816897,2019-04-02 04:38:17,2015-05-12,empty,empty,chris.joseph@rci.com,empty,empty,empty,empty,...,Karma Samui In House,Other,empty,empty,empty,empty,empty,empty,empty,empty
11277,zcrm_3584690000006853411,2019-04-02 04:43:11,2017-01-16,Kendall,Oei,kendall.oei@rci.com,811797218,empty,empty,empty,...,Belvedere,Other,empty,empty,empty,empty,empty,empty,empty,empty
17758,zcrm_3584690000007157037,2019-04-02 05:24:46,2016-07-26,Seri,Seri,seri.okuno@rci.com,6585690316,15708,empty,empty,...,empty,Other,empty,empty,empty,empty,empty,empty,empty,empty
32185,zcrm_3584690000008522519,2019-04-02 08:11:21,2017-01-18,Jonathan,Mills,jonathan.mills@rci.com,65091380059,empty,empty,empty,...,registration_form,Other,empty,empty,empty,empty,empty,empty,empty,empty
49886,zcrm_3584690000025161556,2019-04-09 21:52:07,empty,Ricardo,Montaudon,ricardo.montaudon@rci.com,6564122106,6597762360,empty,empty,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
51820,zcrm_3584690000158666052,2020-01-13 20:54:22,2019-10-22,empty,empty,alisa.nguyen@rci.com,6562234333,empty,empty,empty,...,Karma Group Website Concierge,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
51939,zcrm_3584690000163489418,2020-02-06 11:14:38,empty,Beewer Corona,Plej,adhitya.putra.20dev@karmagroup.com,empty,empty,empty,empty,...,Test Bot Bali | Webchat Web,Other,empty,empty,empty,empty,empty,empty,empty,empty
53666,zcrm_3584690000414915776,2022-12-05 13:29:19,empty,Liu Juan,Jane,jane.liu@rci.com,6562234333,empty,empty,empty,...,Viewpoint,empty,empty,empty,empty,empty,empty,empty,empty,empty

In [51]:
# delete email Karma
count_after_clean_karma = m.delete_karma(zoho_df, 'Email')
# zoho_df.to_excel(r'C:\Users\fajar\Documents\Python\Data\after_clean_OTA.xlsx', index=False)

zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Source Description,Lead Regions,Lead Status,Booking Status,BookRef,Email Opt Out,Opt In,GDPR Compliant,Website,Comments
0,zcrm_3584690000000404133,2019-01-07 15:08:38,2019-01-06,Johannes,Hauptmann,johannesh@hotmail.com,6590189726,empty,1982-05-19,1982,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
1,zcrm_3584690000000404160,2019-01-07 15:08:38,2019-01-06,Philippa,Spellman,philspellman@hotmail.com,6596515025,empty,1972-05-10,1972,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
2,zcrm_3584690000000404199,2019-01-07 15:08:38,2019-01-06,V,H,vimidaminiharidasan@gmail.com,6596526640,empty,empty,empty,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
3,zcrm_3584690000000404452,2019-01-08 11:07:28,2019-01-03,Shigeo,Kawasaki,shigeou1123@gmail.com,6597228507,empty,1977-11-23,1977,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
4,zcrm_3584690000000404870,2019-01-08 11:07:30,2019-01-03,Hsbs,Babas,ssd@sss.com,6593728273,empty,empty,empty,...,empty,Other,New Lead,empty,empty,empty,empty,empty,empty,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55560,zcrm_3584690000499165001,2024-06-17 14:42:23,empty,Angela,Tay,angela.wearnxin@gmail.com,60177595390,empty,empty,empty,...,Karma Kandara -Download Wedding Brochure at Ka...,Other,empty,empty,empty,false,true,false,https://karmagroup.com/weddings-at-karma-kanda...,empty
55561,zcrm_3584690000499443111,2024-06-18 23:47:02,empty,sals,gupta,salonigaba@yahoo.com,6586062557,empty,empty,empty,...,Timeshare Booking Request,Other,empty,empty,empty,false,true,true,https://karmagroup.com/find-destination/karma-...,empty
55562,zcrm_3584690000499792076,2024-06-21 10:27:41,empty,Hahs,Hshhz,hshsj@gmail.com,6584160285,empty,empty,empty,...,Karma Beach VIP membership sign up 2023,Other,empty,empty,empty,false,true,false,https://karmagroup.com/karma-beach-vip/,empty
55563,zcrm_3584690000499836586,2024-06-24 15:20:40,empty,Loic,Hemard,loic.hemard@gmail.com,6598270507,empty,empty,empty,...,Viewpoint,empty,empty,Checked-Out,2456649,false,true,false,empty,empty
55564,zcrm_3584690000499860873,2024-06-24 15:31:48,empty,Yixiang,Zhou,benkden@yahoo.com,6598319447,empty,empty,empty,...,Viewpoint,empty,empty,Checked-Out,2538889,false,true,false,empty,empty

In [52]:
find_member_booking = zoho_df.copy()

find_member_booking.loc[find_member_booking['Phone'].isin(df_booking['Phone1']), 'Same Value Find'] = 'Booking-Phone1'
find_member_booking.loc[find_member_booking['Phone'].isin(df_booking['Mobile']), 'Same Value Find'] = 'Booking-Mobile'
find_member_booking.loc[find_member_booking['Mobile'].isin(df_booking['Phone1']), 'Same Value Find'] = 'Booking-Phone1' 
find_member_booking.loc[find_member_booking['Mobile'].isin(df_booking['Mobile']), 'Same Value Find'] = 'Booking-Mobile'
find_member_booking.loc[find_member_booking['Email'].isin(df_booking['Email']), 'Same Value Find'] = 'Booking-Email'

find_member_booking.loc[find_member_booking['Phone'].isin(df_phone['Mobile']), 'Same Value Find'] = 'Member-Mobile' 
find_member_booking.loc[find_member_booking['Mobile'].isin(df_phone['Mobile']), 'Same Value Find'] = 'Member-Mobile'

find_member_booking.loc[find_member_booking['Email'].isin(df_email['Email']), 'Same Value Find'] = 'Member-Email'

find_member_booking.drop(find_member_booking.loc[find_member_booking['Same Value Find'].isna()].index, inplace=True)

count_booking_dedup = find_member_booking.loc[find_member_booking['Same Value Find'].str.contains('Booking', flags=re.I, regex=True)].shape[0]
count_member_dedup = find_member_booking.loc[find_member_booking['Same Value Find'].str.contains('Member', flags=re.I, regex=True)].shape[0]

find_member_booking.replace('empty', '', inplace=True)
# find_member_booking.to_csv(r'C:\Users\fajar\Documents\Python\Data\booking-member-dedup.csv', index=False)
# find_member_booking.to_excel(r'C:\Users\fajar\Documents\Python\Data\booking-member-dedup.xlsx', index=False)

#find_member_booking.loc[find_member_booking['Same Value Find'] == 'Booking-Phone1']

In [53]:
# data phone, mobile dam email member yang ada di master data 
count_wash_member = zoho_df.loc[
    zoho_df['Phone'].isin(df_booking['Phone1']) | 
    zoho_df['Phone'].isin(df_booking['Mobile']) |
    zoho_df['Mobile'].isin(df_booking['Phone1']) | 
    zoho_df['Mobile'].isin(df_booking['Mobile']) |
    zoho_df['Email'].isin(df_booking['Email'])| 

    zoho_df['Phone'].isin(df_phone['Mobile']) | 
    zoho_df['Mobile'].isin(df_phone['Mobile']) |

    zoho_df['Email'].isin(df_email['Email'])

].shape[0]

zoho_df.drop(zoho_df.loc[
    zoho_df['Phone'].isin(df_booking['Phone1']) | 
    zoho_df['Phone'].isin(df_booking['Mobile']) |
    zoho_df['Mobile'].isin(df_booking['Phone1']) | 
    zoho_df['Mobile'].isin(df_booking['Mobile']) |
    zoho_df['Email'].isin(df_booking['Email']) |
    
    zoho_df['Phone'].isin(df_phone['Mobile']) | 
    zoho_df['Mobile'].isin(df_phone['Mobile']) |

    zoho_df['Email'].isin(df_email['Email'])

    ].index, inplace=True)
    
zoho_df.reset_index(drop=True, inplace=True)

count_after_wash_member = zoho_df.shape[0]

In [54]:
count_email_only = zoho_df.loc[(zoho_df['Email'] != 'empty') & ((zoho_df['Phone'] == 'empty') & (zoho_df['Mobile'] == 'empty'))].shape[0]
count_phone_only = zoho_df.loc[(zoho_df['Email'] == 'empty') & ((zoho_df['Phone'] != 'empty') | (zoho_df['Mobile'] != 'empty'))].shape[0]
count_email_and_phone = zoho_df.loc[(zoho_df['Email'] != 'empty') & ((zoho_df['Phone'] != 'empty') | (zoho_df['Mobile'] != 'empty'))].shape[0]

count_blank = zoho_df.loc[(zoho_df['Email'] =='empty') & (zoho_df['Phone']=='empty') & (zoho_df['Mobile']=='empty')].shape[0]

# zoho_df.loc[(zoho_df['Email'] =='empty') & (zoho_df['Phone']=='empty') & (zoho_df['Mobile']=='empty')].to_excel(r'C:\Users\fajar\Documents\Python\Data\blank_data.xlsx', index=False)

zoho_df.loc[(zoho_df['Email'] != 'empty') & ((zoho_df['Phone'] == 'empty') & (zoho_df['Mobile'] == 'empty')), 'Contact Type'] = 'Email Only'
zoho_df.loc[(zoho_df['Email'] == 'empty') & ((zoho_df['Phone'] != 'empty') | (zoho_df['Mobile'] != 'empty')), 'Contact Type'] = 'Phone Only'
zoho_df.loc[(zoho_df['Email'] != 'empty') & ((zoho_df['Phone'] != 'empty') | (zoho_df['Mobile'] != 'empty')), 'Contact Type'] = 'Email and Phone'

zoho_df.drop(zoho_df.loc[(zoho_df['Email'] =='empty') & (zoho_df['Phone']=='empty') & (zoho_df['Mobile']=='empty')].index, inplace=True)
zoho_df.reset_index(drop=True, inplace=True)

count_after_wash_blank = zoho_df.shape[0]

In [55]:
arr_dedup = [count_deleted_wrong_format, count_duplicate_general, count_leads_test, count_email_OTA, count_email_karma, count_blank]
count_sum_dedup = sum(arr_dedup)
count_sum_dedup

549

In [56]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Keseluruhan Master Zoho : "+str(count_data_awal))
print("Jumlah Filter Leads Awal : "+str(count_filter_awal))
print("Jumlah Format Email Salah : "+str(count_deleted_wrong_format))
print("Jumlah Setelah Clean Format Email Salah : "+str(count_after_deleted_wrong_format))
print("Jumlah Duplicate (Phone, Mobile dan Email) : "+str(count_duplicate_general))
print("Jumlah Setelah Clean Duplicate : "+str(count_after_dedup_duplicate))
print("Jumlah Lead Test : "+str(count_leads_test))
print("Jumlah Setelah Clean Lead Test : "+str(count_after_dedup_test))
# print("Jumlah Lead Do Not Mail : "+str(count_dnm))
# print("Jumlah Setelah Clean Lead Do Not Mail : "+str(count_after_dedup_dnm))
print("Jumlah Email OTA : "+str(count_email_OTA))
print("Jumlah Setelah Clean Email OTA : "+str(count_after_clean_OTA))
print("Jumlah Email Karma : "+str(count_email_karma))
print("Jumlah Setelah Clean Email Karma : "+str(count_after_clean_karma))
print("Jumlah Wash Member : "+str(count_member_dedup))
print("Jumlah Wash Booking : "+str(count_booking_dedup))
print("Jumlah Setelah Wash Member : "+str(count_after_wash_member))
print("Jumlah Phone Email Blank (Setelah phone yang tidak valid dihapus) : "+str(count_blank))
print("Jumlah Setelah Wash Phone Email Blank : "+str(count_after_wash_blank))
print("==========================================================")
print("Contact Type")
print("==========================================================")
print("Jumlah Email Only : "+str(count_email_only))
print("Jumlah Phone Only : "+str(count_phone_only))
print("Jumlah Email dan Phone : "+str(count_email_and_phone))

==========================================================
Summary
==========================================================
Jumlah Keseluruhan Master Zoho : 9984376
Jumlah Filter Leads Awal : 56114
Jumlah Format Email Salah : 1
Jumlah Setelah Clean Format Email Salah : 56113
Jumlah Duplicate (Phone, Mobile dan Email) : 477
Jumlah Setelah Clean Duplicate : 55636
Jumlah Lead Test : 3
Jumlah Setelah Clean Lead Test : 55633
Jumlah Email OTA : 55
Jumlah Setelah Clean Email OTA : 55578
Jumlah Email Karma : 13
Jumlah Setelah Clean Email Karma : 55565
Jumlah Wash Member : 2143
Jumlah Wash Booking : 79
Jumlah Setelah Wash Member : 53343
Jumlah Phone Email Blank (Setelah phone yang tidak valid dihapus) : 0
Jumlah Setelah Wash Phone Email Blank : 53343
==========================================================
Contact Type
==========================================================
Jumlah Email Only : 15775
Jumlah Phone Only : 9585
Jumlah Email dan Phone : 27983

In [57]:
print("==========================================================")
print("Summary Report")
print("==========================================================")
print("Jumlah Data Awal : "+str(count_filter_awal))
print("Jumlah Wash Dedup : "+str(count_sum_dedup))
print("Jumlah Wash Member : "+str(count_member_dedup))
print("Jumlah Wash Booking : "+str(count_booking_dedup))
print("Jumlah Data Akhir : "+str(count_after_wash_blank))

==========================================================
Summary Report
==========================================================
Jumlah Data Awal : 56114
Jumlah Wash Dedup : 549
Jumlah Wash Member : 2143
Jumlah Wash Booking : 79
Jumlah Data Akhir : 53343

# ====================== Akhir Filter Umum ======================

In [58]:
zoho_df.replace('empty', '', inplace=True, regex=True)

zoho_df['First Name'] = zoho_df['First Name'].str.title()
zoho_df['Last Name'] = zoho_df['Last Name'].str.title()

zoho_df.to_excel(r'C:\Users\fajar\Documents\Python\Data\data_req_sg_my.xlsx', index=False)

In [59]:
zoho_df.groupby('Country').count()

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Regions,Lead Status,Booking Status,BookRef,Email Opt Out,Opt In,GDPR Compliant,Website,Comments,Contact Type
Country,,,,,,,,,,,,,,,,,,,,,
,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Australia,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
China,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
France,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Germany,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
Indonesia,7,7,7,7,7,7,7,7,7,7,...,7,7,7,7,7,7,7,7,7,7
MALAYSIA,188,188,188,188,188,188,188,188,188,188,...,188,188,188,188,188,188,188,188,188,188
Malaysia,15004,15004,15004,15004,15004,15004,15004,15004,15004,15004,...,15004,15004,15004,15004,15004,15004,15004,15004,15004,15004
New Zealand,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
SINGAPORE,180,180,180,180,180,180,180,180,180,180,...,180,180,180,180,180,180,180,180,180,180
SIngapore,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Singapore,37936,37936,37936,37936,37936,37936,37936,37936,37936,37936,...,37936,37936,37936,37936,37936,37936,37936,37936,37936,37936
South Korea,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
United Arab Emirates,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
United Kingdom,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
United States,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
singapore,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2

In [60]:
# zoho_df['Country'].loc[
#     (zoho_df['Phone'].str.contains('^44|^\+44')) & 
#     (~zoho_df['Country'].str.contains('united kingdom|wales|england|scotland|northern ireland', regex=True, flags=re.I))
# ]