In [68]:
import main_module as m
import zoho_filter_module as fil
import pandas as pd
import re
import numpy as np

%load_ext autoreload
%autoreload 2

dir_path = r'C:\Users\fajar\Documents\Python\Data\Zoho_Backup'
file_name = '\Leads_'

cols = ['Record Id',	
'Created Time',
'Created Date',	
'First Name',	
'Last Name',	
'Email',	
'Phone',	
'Mobile',	
'Birthdate',	
'Year of Birth',
'Street',	
'Street2',	
'City',	
'State',	
'Country',	
'Nationality',
'Booking Status', 
'BookRef',
'Departure Date',	
'Arrival Date',	
'Card Type',	
'Marital Status',	
'Lead Brand',	
'Lead Sub-Brand',	
'Lead Source',	
'Lead Locations',	
'Lead Source Description',	
'Lead Regions',
'Lead Status',
'Email Opt Out',	
'Opt In']

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [69]:
path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04eXpvS1NXTWF2RVE\_BOOKING\Booking By Year\FlyBuy Booking Data (BGAU & BGID & KE).xlsx'
df_booking = pd.read_excel(path, dtype='string', sheet_name='BOOKING_BGAU_BGID_KE')

path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04UUNBME5GOVhoMjA\_ODYSSEY\Phone Members.xlsx'
df_phone = pd.read_excel(path, dtype='string', sheet_name='Sheet1')

path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04UUNBME5GOVhoMjA\_ODYSSEY\Email Members.xlsx'
df_email = pd.read_excel(path, dtype='string', sheet_name='Sheet1')

In [70]:
df = m.load_data_multiple(dir_path, file_name, cols)
count_data_awal = df.shape[0]
df = df.reindex(columns=cols)
df.shape[0]

df['Created Time'] = pd.to_datetime(df['Created Time'], format='%Y-%m-%d %H:%M:%S')
df.dtypes

Record Id                          string
Created Time               datetime64[ns]
Created Date                       string
First Name                         string
Last Name                          string
Email                              string
Phone                              string
Mobile                             string
Birthdate                          string
Year of Birth                      string
Street                             string
Street2                            string
City                               string
State                              string
Country                            string
Nationality                        string
Booking Status                     string
BookRef                            string
Departure Date                     string
Arrival Date                       string
Card Type                          string
Marital Status                     string
Lead Brand                         string
Lead Sub-Brand                     string
Lead Source                        string
Lead Locations                     string
Lead Source Description            string
Lead Regions                       string
Lead Status                        string
Email Opt Out                      string
Opt In                             string
dtype: object

In [71]:
zoho_filter = fil.user_req(df)
zoho_df = df.loc[zoho_filter].copy() # menggunakan copy untuk menghindari setting copy warning
zoho_df.reset_index(drop=True, inplace=True)
count_filter_awal = zoho_df.shape[0]

# mengisi kolom <NA> dengan value string 'empty' supaya mudah mengecek data member dan booking dengan isin

zoho_df.fillna('empty', inplace=True)
zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Marital Status,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In
0,zcrm_3584690000000450173,2019-01-08 16:38:18,empty,Dr. Steven,Tracy,steven@dental.diavie.net,61434462592,empty,1952-05-16,1952,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,SEAP,Not Sold,false,false
1,zcrm_3584690000000450184,2019-01-08 16:38:18,empty,Paul,May,paulmay@intercept-australia.asia.com,61411094681,empty,1959-01-14,1959,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,SEAP,New Lead,false,false
2,zcrm_3584690000000450549,2019-01-08 16:38:20,empty,Emma,Fredericks,em_fredericks@hotmail.com,61401799329,61401799329,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Rottnest,empty,SEAP,New Lead,true,false
3,zcrm_3584690000000450556,2019-01-08 16:38:20,empty,Gian,Barritt,gian.barritt@gmail.com,61434567117,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Rottnest,empty,SEAP,New Lead,true,false
4,zcrm_3584690000000450562,2019-01-08 16:38:20,empty,Heidi,Naish,heidinaish@yahoo.com.au,9933006,61409933027,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Rottnest,empty,SEAP,New Lead,true,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74853,zcrm_3584690000428461132,2023-02-13 15:26:10,empty,Tomica,Yakimov,empty,61406444958,61406444958,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,empty,empty,true,false
74854,zcrm_3584690000428463034,2023-02-13 15:24:48,empty,Matantsev,Arseniy,solnyshkina@mail.ru,6179852478787,6179852478787,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,empty,empty,false,true
74855,zcrm_3584690000428463682,2023-02-13 15:42:55,empty,Marcia,Vallance,empty,61417209169,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Apsara,Viewpoint,empty,empty,false,true
74856,zcrm_3584690000428466005,2023-02-13 15:29:26,empty,Shiji,Titus,shiji_titus@yahoo.co.uk,61405516642,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Royal Sanur,Viewpoint,empty,empty,false,true
74857,zcrm_3584690000428472360,2023-02-13 15:42:43,empty,Bo,Cheng,empty,61405790527,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,KRR @ Karma Kandara,Viewpoint,empty,empty,false,true

# ====================== Awal Filter Umum ======================

In [72]:
# data phone, mobile dam email member yang ada di master data (wash member)

m.clean_number(zoho_df, 'Phone')
m.clean_number(zoho_df, 'Mobile')
m.replace_not_valid_to_empty(zoho_df, 'Phone')
m.replace_not_valid_to_empty(zoho_df, 'Mobile')
zoho_df['Email'] = m.lowercase(zoho_df, 'Email')
m.clean_space(zoho_df, 'Email')

m.clean_number(df_booking, 'Phone1')
m.clean_number(df_booking, 'Mobile')
df_booking['Email'] = m.lowercase(df_booking, 'Email')
m.clean_space(df_booking, 'Email')

m.clean_number(df_phone, 'Mobile')

df_email['Email'] = m.lowercase(df_email, 'Email')
m.clean_space(df_email, 'Email')

count_deleted_wrong_format = m.delete_email_wrong_format(zoho_df, 'Email')
count_after_deleted_wrong_format = zoho_df.shape[0]

In [73]:
# Cek leads test
test_leads = zoho_df.loc[
    
        zoho_df['Email'].str.contains('^test@', flags=re.I, regex=True) |
        zoho_df['Email'].str.contains('\+test', flags=re.I, regex=True) |
    
        zoho_df['First Name'].str.contains('^test$', flags=re.I, regex=True) |
        zoho_df['Last Name'].str.contains('^test$', flags=re.I, regex=True) |

        zoho_df['First Name'].str.contains('test 1', flags=re.I, regex=True) |
        zoho_df['Last Name'].str.contains('test 2', flags=re.I, regex=True)|
        zoho_df['First Name'].str.contains('test1', flags=re.I, regex=True) |
        zoho_df['Last Name'].str.contains('test2', flags=re.I, regex=True)|

        zoho_df['First Name'].str.contains(' test ', flags=re.I, regex=True) | 
        zoho_df['Last Name'].str.contains(' test ', flags=re.I, regex=True) | 
        zoho_df['Last Name'].str.contains(' test$', flags=re.I, regex=True)
    ]

count_leads_test = test_leads.shape[0]

# test_leads.to_excel(r'C:\Users\fajar\Documents\Python\Data\test_leads_2.xlsx', index=False)
test_leads

Empty DataFrame
Columns: [Record Id, Created Time, Created Date, First Name, Last Name, Email, Phone, Mobile, Birthdate, Year of Birth, Street, Street2, City, State, Country, Nationality, Booking Status, BookRef, Departure Date, Arrival Date, Card Type, Marital Status, Lead Brand, Lead Sub-Brand, Lead Source, Lead Locations, Lead Source Description, Lead Regions, Lead Status, Email Opt Out, Opt In]
Index: []

[0 rows x 31 columns]

In [74]:
zoho_df.drop(test_leads.index, inplace=True)
zoho_df.reset_index(drop=True, inplace=True)

count_after_dedup_test = zoho_df.shape[0]

In [75]:
# Cek Email Karma
email_karma = m.find_karma(zoho_df, 'Email')
count_email_karma = email_karma.shape[0]
# email_OTA.to_excel(r'C:\Users\fajar\Documents\Python\Data\email_OTA.xlsx', index=False)

email_karma

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Marital Status,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In
6965,zcrm_3584690000005952354,2019-04-02 02:15:28,2015-03-10,Mary,Muscat,heather@thebaligetaway.com,61449957118,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Rottnest,empty,SEAP,empty,false,false
51305,zcrm_3584690000024588171,2019-04-07 15:41:20,empty,Claire,Morrison,bookings@karmaclub.com,61414953799,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Rottnest,empty,SEAP,New Lead,false,false

In [76]:
# delete email Karma
count_after_clean_karma = m.delete_karma(zoho_df, 'Email')
# zoho_df.to_excel(r'C:\Users\fajar\Documents\Python\Data\after_clean_OTA.xlsx', index=False)

zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Marital Status,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In
0,zcrm_3584690000000450173,2019-01-08 16:38:18,empty,Dr. Steven,Tracy,steven@dental.diavie.net,61434462592,empty,1952-05-16,1952,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,SEAP,Not Sold,false,false
1,zcrm_3584690000000450184,2019-01-08 16:38:18,empty,Paul,May,paulmay@intercept-australia.asia.com,61411094681,empty,1959-01-14,1959,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,SEAP,New Lead,false,false
2,zcrm_3584690000000450549,2019-01-08 16:38:20,empty,Emma,Fredericks,em_fredericks@hotmail.com,61401799329,61401799329,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Rottnest,empty,SEAP,New Lead,true,false
3,zcrm_3584690000000450556,2019-01-08 16:38:20,empty,Gian,Barritt,gian.barritt@gmail.com,61434567117,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Rottnest,empty,SEAP,New Lead,true,false
4,zcrm_3584690000000450562,2019-01-08 16:38:20,empty,Heidi,Naish,heidinaish@yahoo.com.au,9933006,61409933027,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Rottnest,empty,SEAP,New Lead,true,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74842,zcrm_3584690000428461132,2023-02-13 15:26:10,empty,Tomica,Yakimov,empty,61406444958,61406444958,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,empty,empty,true,false
74843,zcrm_3584690000428463034,2023-02-13 15:24:48,empty,Matantsev,Arseniy,solnyshkina@mail.ru,6179852478787,6179852478787,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,empty,empty,false,true
74844,zcrm_3584690000428463682,2023-02-13 15:42:55,empty,Marcia,Vallance,empty,61417209169,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Apsara,Viewpoint,empty,empty,false,true
74845,zcrm_3584690000428466005,2023-02-13 15:29:26,empty,Shiji,Titus,shiji_titus@yahoo.co.uk,61405516642,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Royal Sanur,Viewpoint,empty,empty,false,true
74846,zcrm_3584690000428472360,2023-02-13 15:42:43,empty,Bo,Cheng,empty,61405790527,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,KRR @ Karma Kandara,Viewpoint,empty,empty,false,true

In [77]:
# hitung jumlah duplicate
count_duplicate_general = zoho_df.loc[zoho_df.duplicated(subset=['Phone','Mobile','Email'])].shape[0]

zoho_df.loc[zoho_df.duplicated(subset=['Phone','Mobile','Email'])]

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Marital Status,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In
250,zcrm_3584690000000459055,2019-01-09 11:11:06,empty,Fiona,Sermon,empty,612035640799,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Rottnest,empty,SEAP,New Lead,false,false
291,zcrm_3584690000000459406,2019-01-09 11:11:09,empty,Graham,Porter,empty,61432414454,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Rottnest,empty,SEAP,New Lead,true,false
332,zcrm_3584690000000459803,2019-01-09 11:11:11,empty,Ian,Adair,empty,612035640799,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Rottnest,empty,SEAP,New Lead,false,false
377,zcrm_3584690000000460182,2019-01-09 11:11:13,empty,Jessica,Barnden,empty,612035640799,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Rottnest,empty,SEAP,New Lead,false,false
387,zcrm_3584690000000460206,2019-01-09 11:11:13,empty,John,Dickson,empty,612035640799,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Rottnest,empty,SEAP,New Lead,false,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74752,zcrm_3584690000422310243,2023-01-12 12:56:54,2023-01-12,Alex,mclaren,alexmclaren00@gmail.com,61414106118,empty,empty,empty,...,empty,Odyssey,Other,Past Guests,Pelikanos - Greece,Karma Group Booking Request Form,SEAP,empty,false,true
74761,zcrm_3584690000422863858,2023-01-16 15:54:46,empty,Scherone,Arndell,scheronelea@icloud.com,61499889493,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,empty,empty,false,true
74771,zcrm_3584690000423856314,2023-01-22 13:54:02,2023-01-22,Mardi,Warby,mardi@rdwtransport.com.au,61407469955,empty,empty,empty,...,empty,Odyssey,Other,Past Guests,Pelikanos - Greece,Karma Group Booking Request Form,SEAP,empty,false,true
74782,zcrm_3584690000425183985,2023-01-30 16:19:47,2023-01-30,Nicki,Page,nickipage1505@gmail.com,61410411833,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Minoan,Karma Group Booking Request Form,SEAP,empty,false,true
74845,zcrm_3584690000428466005,2023-02-13 15:29:26,empty,Shiji,Titus,shiji_titus@yahoo.co.uk,61405516642,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Royal Sanur,Viewpoint,empty,empty,false,true

In [78]:
zoho_df.drop_duplicates(subset=['Phone','Mobile','Email'], inplace=True)
zoho_df.reset_index(drop=True, inplace=True)

# hitung jumlah setelah value duplicate dihapus
count_after_dedup_duplicate = zoho_df.shape[0]

zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Marital Status,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In
0,zcrm_3584690000000450173,2019-01-08 16:38:18,empty,Dr. Steven,Tracy,steven@dental.diavie.net,61434462592,empty,1952-05-16,1952,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,SEAP,Not Sold,false,false
1,zcrm_3584690000000450184,2019-01-08 16:38:18,empty,Paul,May,paulmay@intercept-australia.asia.com,61411094681,empty,1959-01-14,1959,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,SEAP,New Lead,false,false
2,zcrm_3584690000000450549,2019-01-08 16:38:20,empty,Emma,Fredericks,em_fredericks@hotmail.com,61401799329,61401799329,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Rottnest,empty,SEAP,New Lead,true,false
3,zcrm_3584690000000450556,2019-01-08 16:38:20,empty,Gian,Barritt,gian.barritt@gmail.com,61434567117,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Rottnest,empty,SEAP,New Lead,true,false
4,zcrm_3584690000000450562,2019-01-08 16:38:20,empty,Heidi,Naish,heidinaish@yahoo.com.au,9933006,61409933027,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Rottnest,empty,SEAP,New Lead,true,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64170,zcrm_3584690000428458552,2023-02-13 15:36:37,empty,Marco,Ventura,surfnink@gmail.com,61418455894,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Royal Sanur,Viewpoint,empty,empty,false,true
64171,zcrm_3584690000428461132,2023-02-13 15:26:10,empty,Tomica,Yakimov,empty,61406444958,61406444958,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,empty,empty,true,false
64172,zcrm_3584690000428463034,2023-02-13 15:24:48,empty,Matantsev,Arseniy,solnyshkina@mail.ru,6179852478787,6179852478787,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Kandara,empty,empty,empty,false,true
64173,zcrm_3584690000428463682,2023-02-13 15:42:55,empty,Marcia,Vallance,empty,61417209169,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,Karma Apsara,Viewpoint,empty,empty,false,true
64174,zcrm_3584690000428472360,2023-02-13 15:42:43,empty,Bo,Cheng,empty,61405790527,empty,empty,empty,...,empty,Karma Resorts,Other,Past Guests,KRR @ Karma Kandara,Viewpoint,empty,empty,false,true

In [79]:
find_member_booking = zoho_df.copy()

find_member_booking.loc[find_member_booking['Phone'].isin(df_booking['Phone1']), 'Same Value Find'] = 'Booking-Phone1'
find_member_booking.loc[find_member_booking['Phone'].isin(df_booking['Mobile']), 'Same Value Find'] = 'Booking-Mobile'
find_member_booking.loc[find_member_booking['Mobile'].isin(df_booking['Phone1']), 'Same Value Find'] = 'Booking-Phone1' 
find_member_booking.loc[find_member_booking['Mobile'].isin(df_booking['Mobile']), 'Same Value Find'] = 'Booking-Mobile'
find_member_booking.loc[find_member_booking['Email'].isin(df_booking['Email']), 'Same Value Find'] = 'Booking-Email'

find_member_booking.loc[find_member_booking['Phone'].isin(df_phone['Mobile']), 'Same Value Find'] = 'Member-Mobile' 
find_member_booking.loc[find_member_booking['Mobile'].isin(df_phone['Mobile']), 'Same Value Find'] = 'Member-Mobile'

find_member_booking.loc[find_member_booking['Email'].isin(df_email['Email']), 'Same Value Find'] = 'Member-Email'

find_member_booking.drop(find_member_booking.loc[find_member_booking['Same Value Find'].isna()].index, inplace=True)

count_booking_dedup = find_member_booking.loc[find_member_booking['Same Value Find'].str.contains('Booking', flags=re.I, regex=True)].shape[0]
count_member_dedup = find_member_booking.loc[find_member_booking['Same Value Find'].str.contains('Member', flags=re.I, regex=True)].shape[0]

find_member_booking.replace('empty', '', inplace=True)
find_member_booking.to_csv(r'C:\Users\fajar\Documents\Python\Data\booking-member-dedup(AU).csv', index=False)

#find_member_booking.loc[find_member_booking['Same Value Find'] == 'Booking-Phone1']

In [80]:
# data phone, mobile dam email member yang ada di master data 
count_wash_member = zoho_df.loc[
    zoho_df['Phone'].isin(df_booking['Phone1']) | 
    zoho_df['Phone'].isin(df_booking['Mobile']) |
    zoho_df['Mobile'].isin(df_booking['Phone1']) | 
    zoho_df['Mobile'].isin(df_booking['Mobile']) |
    zoho_df['Email'].isin(df_booking['Email'])| 

    zoho_df['Phone'].isin(df_phone['Mobile']) | 
    zoho_df['Mobile'].isin(df_phone['Mobile']) |

    zoho_df['Email'].isin(df_email['Email'])

].shape[0]

zoho_df.drop(zoho_df.loc[
    zoho_df['Phone'].isin(df_booking['Phone1']) | 
    zoho_df['Phone'].isin(df_booking['Mobile']) |
    zoho_df['Mobile'].isin(df_booking['Phone1']) | 
    zoho_df['Mobile'].isin(df_booking['Mobile']) |
    zoho_df['Email'].isin(df_booking['Email']) |
    
    zoho_df['Phone'].isin(df_phone['Mobile']) | 
    zoho_df['Mobile'].isin(df_phone['Mobile']) |

    zoho_df['Email'].isin(df_email['Email'])

    ].index, inplace=True)
    
zoho_df.reset_index(drop=True, inplace=True)

count_after_wash_member = zoho_df.shape[0]

In [81]:
count_email_only = zoho_df.loc[(zoho_df['Email'] != 'empty') & ((zoho_df['Phone'] == 'empty') & (zoho_df['Mobile'] == 'empty'))].shape[0]
count_phone_only = zoho_df.loc[(zoho_df['Email'] == 'empty') & ((zoho_df['Phone'] != 'empty') | (zoho_df['Mobile'] != 'empty'))].shape[0]
count_email_and_phone = zoho_df.loc[(zoho_df['Email'] != 'empty') & ((zoho_df['Phone'] != 'empty') | (zoho_df['Mobile'] != 'empty'))].shape[0]

count_blank = zoho_df.loc[(zoho_df['Email'] =='empty') & (zoho_df['Phone']=='empty') & (zoho_df['Mobile']=='empty')].shape[0]

# zoho_df.loc[(zoho_df['Email'] =='empty') & (zoho_df['Phone']=='empty') & (zoho_df['Mobile']=='empty')].to_excel(r'C:\Users\fajar\Documents\Python\Data\blank_data.xlsx', index=False)

zoho_df.loc[(zoho_df['Email'] != 'empty') & ((zoho_df['Phone'] == 'empty') & (zoho_df['Mobile'] == 'empty')), 'Contact Type'] = 'Email Only'
zoho_df.loc[(zoho_df['Email'] == 'empty') & ((zoho_df['Phone'] != 'empty') | (zoho_df['Mobile'] != 'empty')), 'Contact Type'] = 'Phone Only'
zoho_df.loc[(zoho_df['Email'] != 'empty') & ((zoho_df['Phone'] != 'empty') | (zoho_df['Mobile'] != 'empty')), 'Contact Type'] = 'Email and Phone'

zoho_df.drop(zoho_df.loc[(zoho_df['Email'] =='empty') & (zoho_df['Phone']=='empty') & (zoho_df['Mobile']=='empty')].index, inplace=True)
zoho_df.reset_index(drop=True, inplace=True)

count_after_wash_blank = zoho_df.shape[0]

In [82]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Keseluruhan Master Zoho : "+str(count_data_awal))
print("Jumlah Filter Leads Awal : "+str(count_filter_awal))
print("Jumlah Format Email Salah : "+str(count_deleted_wrong_format))
print("Jumlah Setelah Clean Format Email Salah : "+str(count_after_deleted_wrong_format))
print("Jumlah Lead Test : "+str(count_leads_test))
print("Jumlah Setelah Clean Lead Test : "+str(count_after_dedup_test))
print("Jumlah Email Karma : "+str(count_email_karma))
print("Jumlah Setelah Clean Email Karma : "+str(count_after_clean_karma))
print("Jumlah Duplicate (Phone, Mobile dan Email) : "+str(count_duplicate_general))
print("Jumlah Setelah Clean Duplicate : "+str(count_after_dedup_duplicate))
print("Jumlah Wash Member : "+str(count_member_dedup))
print("Jumlah Wash Booking : "+str(count_booking_dedup))
print("Jumlah Setelah Wash Member : "+str(count_after_wash_member))
print("Jumlah Phone Email Blank (Setelah phone yang tidak valid dihapus) : "+str(count_blank))
print("Jumlah Setelah Wash Phone Email Blank : "+str(count_after_wash_blank))
print("==========================================================")
print("Contact Type")
print("==========================================================")
print("Jumlah Email Only : "+str(count_email_only))
print("Jumlah Phone Only : "+str(count_phone_only))
print("Jumlah Email dan Phone : "+str(count_email_and_phone))

==========================================================
Summary
==========================================================
Jumlah Keseluruhan Master Zoho : 4619344
Jumlah Filter Leads Awal : 74858
Jumlah Format Email Salah : 9
Jumlah Setelah Clean Format Email Salah : 74849
Jumlah Lead Test : 0
Jumlah Setelah Clean Lead Test : 74849
Jumlah Email Karma : 2
Jumlah Setelah Clean Email Karma : 74847
Jumlah Duplicate (Phone, Mobile dan Email) : 10672
Jumlah Setelah Clean Duplicate : 64175
Jumlah Wash Member : 2822
Jumlah Wash Booking : 637
Jumlah Setelah Wash Member : 60716
Jumlah Phone Email Blank (Setelah phone yang tidak valid dihapus) : 0
Jumlah Setelah Wash Phone Email Blank : 60716
==========================================================
Contact Type
==========================================================
Jumlah Email Only : 7632
Jumlah Phone Only : 23954
Jumlah Email dan Phone : 29130

# ====================== Akhir Filter Umum ======================

In [83]:
zoho_df.replace('empty', '', inplace=True)
zoho_df.to_excel(r'C:\Users\fajar\Documents\Python\Data\Past Guest (AU).xlsx', index=False)