In [2]:
import pandas as pd
import re
import numpy as np

import sys
sys.path.append('../../zoho_data_app/')

import main_module as m
import zoho_filter_module as fil


%load_ext autoreload
%autoreload 2



dir_path = r'C:\Users\fajar\Documents\Python\Data\Zoho_Backup'
file_name = '\Leads_'

cols = ['Record Id',	
'Created Time',
'Created Date',	
'First Name',	
'Last Name',	
'Email',	
'Phone',	
'Mobile',	
'Birthdate',	
'Year of Birth',
'Street',	
'Street2',	
'City',	
'State',	
'Country',	
'Departure Date',	
'Arrival Date',	
'Card Type',	
'Marital Status',	
'Lead Brand',	
'Lead Sub-Brand',	
'Lead Source',	
'Lead Locations',	
'Lead Source Description',	
'Lead Regions',
'Lead Status',
'Email Opt Out',	
'Opt In',
'Comments']

In [92]:
df = m.load_data_multiple(dir_path, file_name, cols)
count_data_awal = df.shape[0]
df = df.reindex(columns=cols)

In [93]:
path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04UUNBME5GOVhoMjA\_ODYSSEY\KCE Members.xlsx'
df_phone = pd.read_excel(path, dtype='string', sheet_name='Phone')

path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04UUNBME5GOVhoMjA\_ODYSSEY\KCE Members.xlsx'
df_email = pd.read_excel(path, dtype='string', sheet_name='Email')

In [94]:
zoho_filter = fil.guest_exit_1(df)
zoho_df = df.loc[zoho_filter].copy() # menggunakan copy untuk menghindari setting copy warning
zoho_df.reset_index(drop=True, inplace=True)
count_filter_awal = zoho_df.shape[0]

# mengisi kolom <NA> dengan value string 'empty' supaya mudah mengecek data member dan booking dengan isin

zoho_df.fillna('empty', inplace=True)
zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Comments
0,zcrm_3584690000000409050,2019-01-08 10:28:06,2019-01-07,Takenori,Kawamata,wudian84@gmail.com,8021545591,empty,1961-01-31,1961,...,Timeshare Marketing,Other Bali DB,Guest Exit,empty,empty,Other,empty,false,false,KE2 - Guest Exit
1,zcrm_3584690000000414023,2019-01-08 10:33:21,2019-01-08,Conor,Burke,secxnicole101@hotmail.com,4508023889,empty,1987-12-08,1987,...,Timeshare Marketing,Other Bali DB,Guest Exit,empty,empty,SEAP,empty,false,false,KE2 - Guest Exit
2,zcrm_3584690000000414030,2019-01-08 12:06:00,2019-01-08,Ian,Brown,shawnte199@gmail.com,4164355943,6479999976,1983-01-29,1983,...,Timeshare Marketing,Other Bali DB,Guest Exit,empty,empty,SEAP,empty,false,false,empty
3,zcrm_3584690000000417044,2019-01-08 11:58:00,2019-01-08,Edwards,Lee,edward@pockettourer.com,61438828618,empty,1956-04-09,1956,...,Timeshare Marketing,Other Bali DB,Guest Exit,empty,empty,SEAP,empty,false,false,KE2 - Guest Exit
4,zcrm_3584690000000417050,2019-01-08 12:21:03,2019-01-08,Suresh,Kumar Karunakaran,karuna22@gmail.com,14167059922,empty,1962-04-20,1962,...,Timeshare Marketing,Other Bali DB,Guest Exit,empty,empty,SEAP,empty,false,false,KE2 - Guest Exit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60899,zcrm_3584690000176822948,2020-03-21 15:38:31,empty,empty,KAYLA URBANOWSKI,KAYLAURBANOWSKI1@GMAIL.COM,+19148197103,empty,empty,1995,...,Timeshare Marketing,Other Bali DB,KE2 (Guest Exit),Sales Deck Jimbaran,KE | Web | Gift Registration v2,SEAP,empty,false,false,empty
60900,zcrm_3584690000177022563,2020-03-22 12:25:14,empty,empty,MOHAMMED MAGDY,MOHAMED.MAGDY2027@GMAIL.COM,+96597871151,empty,empty,1993,...,Timeshare Marketing,Other Bali DB,KE2 (Guest Exit),Sales Deck Jimbaran,KE | Web | Gift Registration v2,Middle East,empty,false,false,empty
60901,zcrm_3584690000177050220,2020-03-22 15:43:44,empty,empty,Brianna Brook,briannabrook98@hotmail.co.nz,+64223008303,empty,empty,1998,...,Timeshare Marketing,Other Bali DB,KE2 (Guest Exit),Sales Deck Jimbaran,KE | Web | Gift Registration v2,SEAP,empty,false,false,empty
60902,zcrm_3584690000177056497,2020-03-22 16:19:28,empty,empty,MUHAMMAD OKY ERZANDI,oky_erzandi@yahoo.com,+6285216714487,empty,empty,1989,...,Timeshare Marketing,Other Bali DB,KE2 (Guest Exit),Sales Deck Jimbaran,KE | Web | Gift Registration v2,SEAP,empty,false,false,empty
60903,zcrm_3584690000385704199,2022-07-25 16:27:48,empty,empty,steve,steve.chadwick@outlook.com,+6108113860665,empty,empty,1973,...,Timeshare Marketing,Other Bali DB,KE2 (Guest Exit),Sales Deck Jimbaran,KE | Web | Gift Registration v2,SEAP,New Lead,false,false,empty

In [95]:
zoho_filter2 = fil.guest_exit_2(df)
zoho_df2 = df.loc[zoho_filter2].copy() # menggunakan copy untuk menghindari setting copy warning
zoho_df2.reset_index(drop=True, inplace=True)
count_filter_awal = zoho_df2.shape[0]

# mengisi kolom <NA> dengan value string 'empty' supaya mudah mengecek data member dan booking dengan isin

zoho_df2.fillna('empty', inplace=True)
zoho_df2

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Comments
0,zcrm_3584690000000409050,2019-01-08 10:28:06,2019-01-07,Takenori,Kawamata,wudian84@gmail.com,8021545591,empty,1961-01-31,1961,...,Timeshare Marketing,Other Bali DB,Guest Exit,empty,empty,Other,empty,false,false,KE2 - Guest Exit
1,zcrm_3584690000000414023,2019-01-08 10:33:21,2019-01-08,Conor,Burke,secxnicole101@hotmail.com,4508023889,empty,1987-12-08,1987,...,Timeshare Marketing,Other Bali DB,Guest Exit,empty,empty,SEAP,empty,false,false,KE2 - Guest Exit
2,zcrm_3584690000000417044,2019-01-08 11:58:00,2019-01-08,Edwards,Lee,edward@pockettourer.com,61438828618,empty,1956-04-09,1956,...,Timeshare Marketing,Other Bali DB,Guest Exit,empty,empty,SEAP,empty,false,false,KE2 - Guest Exit
3,zcrm_3584690000000417050,2019-01-08 12:21:03,2019-01-08,Suresh,Kumar Karunakaran,karuna22@gmail.com,14167059922,empty,1962-04-20,1962,...,Timeshare Marketing,Other Bali DB,Guest Exit,empty,empty,SEAP,empty,false,false,KE2 - Guest Exit
4,zcrm_3584690000000417056,2019-01-08 12:47:09,2019-01-08,Hemraj,Ramphul,kesramphul@gmail.com,2304174393,23058889042,1974-03-10,1974,...,Timeshare Marketing,Other Bali DB,Guest Exit,empty,empty,Other,empty,false,false,KE2 - Guest Exit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24198,zcrm_3584690000094322261,2019-08-12 17:21:57,empty,Ryan,Worrall,charlottemills_5@hotmail.com,empty,empty,empty,empty,...,Timeshare Marketing,Other Bali DB,KE2 (Guest Exit),empty,empty,empty,New Lead,false,false,KE2 - Guest Exit
24199,zcrm_3584690000094322262,2019-08-12 17:21:57,empty,Mark,Wright,markcwright82@gmail.com,empty,empty,empty,empty,...,Timeshare Marketing,Other Bali DB,KE2 (Guest Exit),empty,empty,empty,New Lead,false,false,KE2 - Guest Exit
24200,zcrm_3584690000094322263,2019-08-12 17:21:57,empty,Karen,Wyatt,kwyatt15@hotmail.com,empty,empty,empty,empty,...,Timeshare Marketing,Other Bali DB,KE2 (Guest Exit),empty,empty,empty,New Lead,false,false,KE2 - Guest Exit
24201,zcrm_3584690000094322264,2019-08-12 17:21:57,empty,Matt,Zamiska,mattzami@gmail.com,empty,empty,empty,empty,...,Timeshare Marketing,Other Bali DB,KE2 (Guest Exit),empty,empty,empty,New Lead,false,false,KE2 - Guest Exit
24202,zcrm_3584690000094322265,2019-08-12 17:21:57,empty,Amir,Zolfaghari,amirzolfaghari@hotmail.com,empty,empty,empty,empty,...,Timeshare Marketing,Other Bali DB,KE2 (Guest Exit),empty,empty,empty,New Lead,false,false,KE2 - Guest Exit

In [96]:
zoho_filter3 = fil.guest_exit_3(df)
zoho_df3 = df.loc[zoho_filter3].copy() # menggunakan copy untuk menghindari setting copy warning
zoho_df3.reset_index(drop=True, inplace=True)
count_filter_awal = zoho_df3.shape[0]

# mengisi kolom <NA> dengan value string 'empty' supaya mudah mengecek data member dan booking dengan isin

zoho_df3.fillna('empty', inplace=True)
zoho_df3

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Comments
0,zcrm_3584690000383890268,2022-07-15 20:47:30,empty,empty,Andrew Lillas,alillas@yahoo.com.au,+61414980763,empty,1965-05-16,empty,...,Timeshare Marketing,KCE,Facebook Ads,empty,KCE | w2july22 | Launching KCE,empty,empty,false,false,empty
1,zcrm_3584690000383933445,2022-07-16 13:08:44,empty,empty,Spencer Harris,Mkl2344@gmail.com,+610415142389,empty,1967-11-11,empty,...,Timeshare Marketing,KCE,Facebook Ads,empty,KCE | w2july22 | Launching KCE,empty,empty,false,false,empty
2,zcrm_3584690000383933683,2022-07-16 20:21:03,empty,empty,Bruce Toddun,btoddun@yahoo.com,+61409430467,empty,1954-01-22,empty,...,Timeshare Marketing,KCE,Facebook Ads,empty,KCE | w2july22 | Launching KCE,empty,empty,false,false,empty
3,zcrm_3584690000383973874,2022-07-17 15:07:01,empty,empty,Jason,jasal2020@outlook.com,+610412345678,empty,1982-08-04,empty,...,Timeshare Marketing,KCE,Facebook Ads,empty,KCE | w2july22 | Launching KCE,empty,empty,false,false,empty
4,zcrm_3584690000384006360,2022-07-16 14:20:58,empty,empty,Brenda Wilson,brenda1303@iinet.net.au,+61409893964,empty,1949-12-15,empty,...,Timeshare Marketing,KCE,Facebook Ads,empty,KCE | w2july22 | Launching KCE,empty,empty,false,false,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3292,zcrm_3584690000414892385,2022-12-05 15:38:02,empty,JAGJEET,SINGH MANDER,harwindergill612@gmail.com,+61467696783,empty,1993-09-15,1993,...,Timeshare Marketing,KCE,Guest Exit,Sales Deck Jimbaran,REGISTRATION CONFIRMED | Your Exclusive 7 NIGH...,SEAP,Hot Prospect,false,false,empty
3293,zcrm_3584690000414896231,2022-12-05 14:41:04,empty,ANDREAS,SOCRATOUS,andreas.socratous14@gmail.com,+35799876997,empty,1983-01-14,1983,...,Timeshare Marketing,KCE,Guest Exit,Sales Deck Jimbaran,REGISTRATION CONFIRMED | Your Exclusive 7 NIGH...,SEAP,Hot Prospect,false,false,empty
3294,zcrm_3584690000414898295,2022-12-05 16:14:08,empty,RAJESHKUMAR,DOBARIYA,rajesh.dobariya007@gmail.com,+6582657274,empty,1990-01-20,1990,...,Timeshare Marketing,KCE,Guest Exit,Sales Deck Jimbaran,REGISTRATION CONFIRMED | Your Exclusive 7 NIGH...,SEAP,Hot Prospect,false,false,empty
3295,zcrm_3584690000414924090,2022-12-05 13:47:38,empty,SAIFUL,RAHMAN,lidyakoyongian77@gmail.com,+6281646985206,empty,1978-07-27,1978,...,Timeshare Marketing,KCE,Guest Exit,Sales Deck Jimbaran,REGISTRATION CONFIRMED | Your Exclusive 7 NIGH...,SEAP,Hot Prospect,false,false,empty
3296,zcrm_3584690000414924149,2022-12-05 14:20:44,empty,KAMLESH,KHANDELWAL,kamlesh2903@hotmail.com,+919831014655,empty,1964-03-29,1964,...,Timeshare Marketing,KCE,Guest Exit,Sales Deck Jimbaran,REGISTRATION CONFIRMED | Your Exclusive 7 NIGH...,SEAP,Hot Prospect,false,false,empty

In [97]:
frames = [zoho_df, zoho_df2, zoho_df3]

# concat dataframe dan menambahkan kolom nama sheets
dfs = pd.concat(
frames, 
)
# reset index agar nomor indexnya berurutan
dfs.reset_index(drop=True, inplace=True)

dfs

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Brand,Lead Sub-Brand,Lead Source,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Comments
0,zcrm_3584690000000409050,2019-01-08 10:28:06,2019-01-07,Takenori,Kawamata,wudian84@gmail.com,8021545591,empty,1961-01-31,1961,...,Timeshare Marketing,Other Bali DB,Guest Exit,empty,empty,Other,empty,false,false,KE2 - Guest Exit
1,zcrm_3584690000000414023,2019-01-08 10:33:21,2019-01-08,Conor,Burke,secxnicole101@hotmail.com,4508023889,empty,1987-12-08,1987,...,Timeshare Marketing,Other Bali DB,Guest Exit,empty,empty,SEAP,empty,false,false,KE2 - Guest Exit
2,zcrm_3584690000000414030,2019-01-08 12:06:00,2019-01-08,Ian,Brown,shawnte199@gmail.com,4164355943,6479999976,1983-01-29,1983,...,Timeshare Marketing,Other Bali DB,Guest Exit,empty,empty,SEAP,empty,false,false,empty
3,zcrm_3584690000000417044,2019-01-08 11:58:00,2019-01-08,Edwards,Lee,edward@pockettourer.com,61438828618,empty,1956-04-09,1956,...,Timeshare Marketing,Other Bali DB,Guest Exit,empty,empty,SEAP,empty,false,false,KE2 - Guest Exit
4,zcrm_3584690000000417050,2019-01-08 12:21:03,2019-01-08,Suresh,Kumar Karunakaran,karuna22@gmail.com,14167059922,empty,1962-04-20,1962,...,Timeshare Marketing,Other Bali DB,Guest Exit,empty,empty,SEAP,empty,false,false,KE2 - Guest Exit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88399,zcrm_3584690000414892385,2022-12-05 15:38:02,empty,JAGJEET,SINGH MANDER,harwindergill612@gmail.com,+61467696783,empty,1993-09-15,1993,...,Timeshare Marketing,KCE,Guest Exit,Sales Deck Jimbaran,REGISTRATION CONFIRMED | Your Exclusive 7 NIGH...,SEAP,Hot Prospect,false,false,empty
88400,zcrm_3584690000414896231,2022-12-05 14:41:04,empty,ANDREAS,SOCRATOUS,andreas.socratous14@gmail.com,+35799876997,empty,1983-01-14,1983,...,Timeshare Marketing,KCE,Guest Exit,Sales Deck Jimbaran,REGISTRATION CONFIRMED | Your Exclusive 7 NIGH...,SEAP,Hot Prospect,false,false,empty
88401,zcrm_3584690000414898295,2022-12-05 16:14:08,empty,RAJESHKUMAR,DOBARIYA,rajesh.dobariya007@gmail.com,+6582657274,empty,1990-01-20,1990,...,Timeshare Marketing,KCE,Guest Exit,Sales Deck Jimbaran,REGISTRATION CONFIRMED | Your Exclusive 7 NIGH...,SEAP,Hot Prospect,false,false,empty
88402,zcrm_3584690000414924090,2022-12-05 13:47:38,empty,SAIFUL,RAHMAN,lidyakoyongian77@gmail.com,+6281646985206,empty,1978-07-27,1978,...,Timeshare Marketing,KCE,Guest Exit,Sales Deck Jimbaran,REGISTRATION CONFIRMED | Your Exclusive 7 NIGH...,SEAP,Hot Prospect,false,false,empty
88403,zcrm_3584690000414924149,2022-12-05 14:20:44,empty,KAMLESH,KHANDELWAL,kamlesh2903@hotmail.com,+919831014655,empty,1964-03-29,1964,...,Timeshare Marketing,KCE,Guest Exit,Sales Deck Jimbaran,REGISTRATION CONFIRMED | Your Exclusive 7 NIGH...,SEAP,Hot Prospect,false,false,empty

In [98]:
dfs.columns

Index(['Record Id', 'Created Time', 'Created Date', 'First Name', 'Last Name',
       'Email', 'Phone', 'Mobile', 'Birthdate', 'Year of Birth', 'Street',
       'Street2', 'City', 'State', 'Country', 'Departure Date', 'Arrival Date',
       'Card Type', 'Marital Status', 'Lead Brand', 'Lead Sub-Brand',
       'Lead Source', 'Lead Locations', 'Lead Source Description',
       'Lead Regions', 'Lead Status', 'Email Opt Out', 'Opt In', 'Comments'],
      dtype='object')

In [99]:
# membersihkan format phone number dan email

m.clean_number(dfs, 'Phone')
m.clean_number(dfs, 'Mobile')
dfs['Email'] = m.lowercase(dfs, 'Email')
m.clean_space(dfs, 'Email')

0                   wudian84@gmail.com
1            secxnicole101@hotmail.com
2                 shawnte199@gmail.com
3              edward@pockettourer.com
4                   karuna22@gmail.com
                     ...
88399       harwindergill612@gmail.com
88400    andreas.socratous14@gmail.com
88401     rajesh.dobariya007@gmail.com
88402       lidyakoyongian77@gmail.com
88403          kamlesh2903@hotmail.com
Name: Email, Length: 88404, dtype: string

In [100]:
df_master_email = dfs['Email'].copy()
df_master_phone = dfs['Phone'].copy()
df_master_mobile = dfs['Mobile'].copy()

df_master_email_csv = df_master_email.copy()
df_master_phone_csv = df_master_phone.copy()
df_master_mobile_csv = df_master_mobile.copy()

df_master_email_csv.replace('empty', '', inplace=True)
df_master_phone_csv.replace('empty', '', inplace=True)
df_master_mobile_csv.replace('empty', '', inplace=True)

df_master_email_csv.to_csv(r'C:\Users\fajar\Documents\Python\Data\ke2_email.csv', index=False)
df_master_phone_csv.to_csv(r'C:\Users\fajar\Documents\Python\Data\ke2_phone.csv', index=False)
df_master_mobile_csv.to_csv(r'C:\Users\fajar\Documents\Python\Data\ke2_mobile.csv', index=False)

In [101]:
df_master_email.drop(df_master_email.loc[df_master_email == 'empty'].index, inplace=True)
df_master_phone.drop(df_master_phone.loc[df_master_phone == ''].index, inplace=True)
df_master_mobile.drop(df_master_mobile.loc[df_master_mobile == ''].index, inplace=True)

df_master_email.drop_duplicates(inplace=True)
df_master_phone.drop_duplicates(inplace=True)
df_master_mobile.drop_duplicates(inplace=True)

df_master_email.reset_index(drop=True, inplace=True)
df_master_phone.reset_index(drop=True, inplace=True)
df_master_mobile.reset_index(drop=True, inplace=True)

In [102]:
df_master_email

0                   wudian84@gmail.com
1            secxnicole101@hotmail.com
2                 shawnte199@gmail.com
3              edward@pockettourer.com
4                   karuna22@gmail.com
                     ...
57559       harwindergill612@gmail.com
57560    andreas.socratous14@gmail.com
57561     rajesh.dobariya007@gmail.com
57562       lidyakoyongian77@gmail.com
57563          kamlesh2903@hotmail.com
Name: Email, Length: 57564, dtype: string

In [103]:
df_master_email.to_excel(r'C:\Users\fajar\Documents\Python\Data\ke2_master_email.xlsx', index=False)
df_master_phone.to_excel(r'C:\Users\fajar\Documents\Python\Data\ke2_master_phone.xlsx', index=False)
df_master_mobile.to_excel(r'C:\Users\fajar\Documents\Python\Data\ke2_master_mobile.xlsx', index=False)

In [106]:
zoho_df.replace('empty', '', inplace=True)

In [107]:
# print("==========================================================")
# print("Summary")
# print("==========================================================")
# print("Jumlah Data Awal : "+str(count_data_kce))
# print("Jumlah Wash Booking dan Member : "+str(count_wash_kce_clean))
# print("Jumlah Setelah Wash Member : "+str(count_after_wash_kce))
# print("Jumlah Wash Booking dan Member : "+str(count_wash_member))
# print("Jumlah Setelah Wash Member : "+str(count_after_wash_member))