In [2]:
import pandas as pd
import numpy as np
from datetime import datetime

import re

import sys
sys.path.append('../../zoho_data_app/')

# importing
import main_module as m
import zoho_filter_module as fil

%load_ext autoreload
%autoreload 2

In [3]:
path = r'C:\Users\fajar\Documents\Python\Data\Request Data\karmaspa.xlsx'
zoho_df = pd.read_excel(path, dtype='string', sheet_name='Sheet0')

In [4]:
path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04eXpvS1NXTWF2RVE\_BOOKING\Booking By Year\FlyBuy Booking Data (BGAU & BGID & KE).xlsx'
df_booking = pd.read_excel(path, dtype='string', sheet_name='BOOKING_BGAU_BGID_KE')

path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04UUNBME5GOVhoMjA\_ODYSSEY\Phone Members.xlsx'
df_phone = pd.read_excel(path, dtype='string', sheet_name='Sheet1')

path = r'G:\.shortcut-targets-by-id\0B_d3smBjzo04UUNBME5GOVhoMjA\_ODYSSEY\Email Members.xlsx'
df_email = pd.read_excel(path, dtype='string', sheet_name='Sheet1')

In [5]:
path = r'C:\Users\fajar\Documents\Python\Data\Zoho_Campaign\unsub-zoho-campaigns.csv'
df_unsub_zoho = pd.read_csv(path, dtype='string')

In [6]:
count_filter_awal = zoho_df.shape[0]

# mengisi kolom <NA> dengan value string 'empty' supaya mudah mengecek data member dan booking dengan isin

zoho_df.fillna('empty', inplace=True)
zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Booking Status,BookRef,Guest Type,External ID
0,zcrm_3584690000409794028,2022-11-10 00:54:00,2022-11-09 00:00:00,Guru,C,gururajgcss@gmail.com,empty,empty,empty,empty,...,Karma Royal Benaulim,Karma Spa at Karma Royal Benaulim,India,empty,false,false,empty,empty,empty,empty
1,zcrm_3584690000404526047,2022-10-12 19:13:00,2022-10-12 00:00:00,Joao,Tavares,jmtavares@btinternet.com,empty,empty,empty,empty,...,Karma Royal Sanur,Karma Spa at Karma Royal Sanur,UK/Europe,empty,false,false,empty,empty,empty,empty
2,zcrm_3584690000402673323,2022-10-03 16:10:00,2022-10-03 00:00:00,Valencia,Lopez,valencia.lopez00@gmail.com,empty,empty,empty,empty,...,Karma Royal Haathi Mahal,Karma Spa at Karma Royal Haathi Mahal,India,empty,false,false,empty,empty,empty,empty
3,zcrm_3584690000402072082,2022-09-29 17:38:00,2022-09-29 00:00:00,Ranjitha,BM,ranju281094@gmail.com,empty,empty,empty,empty,...,Karma Royal Benaulim,Karma Spa at Karma Royal Benaulim,India,empty,false,false,empty,empty,empty,empty
4,zcrm_3584690000400243001,2022-09-20 21:52:00,2022-09-20 00:00:00,vishal,ingle,vishal.ingle1@gmail.com,empty,empty,empty,empty,...,Karma Chakra,Karma Spa at Karma Chakra,India,empty,false,false,empty,empty,empty,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11443,zcrm_3584690000002607163,2019-02-23 18:21:00,empty,Bhargav,Patel,bhargv@gmail.com,empty,empty,empty,empty,...,empty,empty,India,New Lead,false,false,empty,empty,empty,empty
11444,zcrm_3584690000002503001,2019-02-21 23:22:00,empty,Lauren,Brenton,laurenbrenton@outlook.com,empty,empty,1984-06-08 00:00:00,1984,...,empty,empty,SEAP,New Lead,false,false,empty,empty,empty,empty
11445,zcrm_3584690000001876097,2019-02-12 17:44:00,2019-02-12 00:00:00,Aishwarya,Ganesh,divya_g24@yahoo.co.in,917709923249,empty,empty,empty,...,Karma Chakra,empty,India,New Lead,false,false,empty,empty,empty,empty
11446,zcrm_3584690000001291015,2019-01-31 20:19:00,2019-01-31 00:00:00,Ajay,Mahan,ajay.mahan@theintelligentsp.co.uk,441543483700,empty,empty,empty,...,Karma Kandara,empty,UK/Europe,New Lead,false,false,empty,empty,empty,empty
11447,zcrm_3584690000001115009,2019-01-27 13:22:00,2019-01-27 00:00:00,Amilya,Amilya,amilya.rossintya@gmail.com,6281336773732,empty,empty,empty,...,Karma Mayura,empty,SEAP,New Lead,false,false,empty,empty,empty,empty

In [32]:
# zoho_df_awal = df.loc[zoho_filter].copy() # menggunakan copy untuk menghindari setting copy warning
# zoho_df_awal.reset_index(drop=True, inplace=True)

# # mengisi kolom <NA> dengan value string 'empty' supaya mudah mengecek data member dan booking dengan isin
# zoho_df_awal.to_csv(r'C:\Users\fajar\Documents\Python\Data\filter_awal_newsletter.csv', index=False)

In [7]:
# membersihkan format phone number dan email

m.clean_number(zoho_df, 'Phone')
m.clean_number(zoho_df, 'Mobile')
m.replace_not_valid_to_empty(zoho_df, 'Phone')
m.replace_not_valid_to_empty(zoho_df, 'Mobile')
zoho_df['Email'] = m.lowercase(zoho_df, 'Email')
m.clean_space(zoho_df, 'Email')

m.clean_number(df_booking, 'Phone1')
m.clean_number(df_booking, 'Mobile')
df_booking['Email'] = m.lowercase(df_booking, 'Email')
m.clean_space(df_booking, 'Email')

m.clean_number(df_phone, 'Mobile')

df_email['Email'] = m.lowercase(df_email, 'Email')
m.clean_space(df_email, 'Email')

df_unsub_zoho['Contact Email'] = m.lowercase(df_unsub_zoho, 'Contact Email')
m.clean_space(df_unsub_zoho, 'Contact Email')

count_deleted_wrong_fromat = m.delete_email_wrong_format(zoho_df, 'Email')
count_after_deleted_wrong_format = zoho_df.shape[0]

In [8]:
# membersihkan email kosong dan duplikat

count_empty_email = zoho_df.loc[zoho_df['Email'] == 'empty'].shape[0]
zoho_df.drop(zoho_df.loc[zoho_df['Email'] == 'empty'].index, inplace=True)
count_after_dedup_empty_email = zoho_df.shape[0]

count_email_duplicate = zoho_df.loc[zoho_df['Email'].duplicated()].shape[0]
zoho_df.drop_duplicates('Email', inplace=True)
count_after_dedup_duplicated_email = zoho_df.shape[0]

zoho_df.reset_index(drop=True, inplace=True)
zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Booking Status,BookRef,Guest Type,External ID
0,zcrm_3584690000409794028,2022-11-10 00:54:00,2022-11-09 00:00:00,Guru,C,gururajgcss@gmail.com,empty,empty,empty,empty,...,Karma Royal Benaulim,Karma Spa at Karma Royal Benaulim,India,empty,false,false,empty,empty,empty,empty
1,zcrm_3584690000404526047,2022-10-12 19:13:00,2022-10-12 00:00:00,Joao,Tavares,jmtavares@btinternet.com,empty,empty,empty,empty,...,Karma Royal Sanur,Karma Spa at Karma Royal Sanur,UK/Europe,empty,false,false,empty,empty,empty,empty
2,zcrm_3584690000402673323,2022-10-03 16:10:00,2022-10-03 00:00:00,Valencia,Lopez,valencia.lopez00@gmail.com,empty,empty,empty,empty,...,Karma Royal Haathi Mahal,Karma Spa at Karma Royal Haathi Mahal,India,empty,false,false,empty,empty,empty,empty
3,zcrm_3584690000402072082,2022-09-29 17:38:00,2022-09-29 00:00:00,Ranjitha,BM,ranju281094@gmail.com,empty,empty,empty,empty,...,Karma Royal Benaulim,Karma Spa at Karma Royal Benaulim,India,empty,false,false,empty,empty,empty,empty
4,zcrm_3584690000400243001,2022-09-20 21:52:00,2022-09-20 00:00:00,vishal,ingle,vishal.ingle1@gmail.com,empty,empty,empty,empty,...,Karma Chakra,Karma Spa at Karma Chakra,India,empty,false,false,empty,empty,empty,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11146,zcrm_3584690000002607163,2019-02-23 18:21:00,empty,Bhargav,Patel,bhargv@gmail.com,empty,empty,empty,empty,...,empty,empty,India,New Lead,false,false,empty,empty,empty,empty
11147,zcrm_3584690000002503001,2019-02-21 23:22:00,empty,Lauren,Brenton,laurenbrenton@outlook.com,empty,empty,1984-06-08 00:00:00,1984,...,empty,empty,SEAP,New Lead,false,false,empty,empty,empty,empty
11148,zcrm_3584690000001876097,2019-02-12 17:44:00,2019-02-12 00:00:00,Aishwarya,Ganesh,divya_g24@yahoo.co.in,917709923249,empty,empty,empty,...,Karma Chakra,empty,India,New Lead,false,false,empty,empty,empty,empty
11149,zcrm_3584690000001291015,2019-01-31 20:19:00,2019-01-31 00:00:00,Ajay,Mahan,ajay.mahan@theintelligentsp.co.uk,441543483700,empty,empty,empty,...,Karma Kandara,empty,UK/Europe,New Lead,false,false,empty,empty,empty,empty
11150,zcrm_3584690000001115009,2019-01-27 13:22:00,2019-01-27 00:00:00,Amilya,Amilya,amilya.rossintya@gmail.com,6281336773732,empty,empty,empty,...,Karma Mayura,empty,SEAP,New Lead,false,false,empty,empty,empty,empty

In [9]:
# Cek Email OTA
count_email_OTA = m.find_OTA(zoho_df, 'Email')
zoho_df.loc[zoho_df['Email']=='OTA']

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Booking Status,BookRef,Guest Type,External ID
417,zcrm_3584690000346108276,2022-02-17 13:39:00,2022-02-17 00:00:00,Agus,Mardika,OTA,empty,empty,empty,empty,...,Karma Kandara,Karma Spa at Karma Kandara,UK/Europe,empty,false,false,empty,empty,empty,empty
2374,zcrm_3584690000265563361,2021-02-17 08:53:00,2021-02-17 00:00:00,Gavin,Parker,OTA,empty,empty,empty,empty,...,Karma Rottnest,Karma Spa at Karma Rottnest,SEAP,empty,false,false,empty,empty,empty,empty
4014,zcrm_3584690000147162352,2019-11-28 10:51:00,2019-11-27 00:00:00,Dorothy,Nullmayers,OTA,0452565958,empty,empty,empty,...,Karma Rottnest,empty,SEAP,empty,false,false,empty,empty,empty,empty
4886,zcrm_3584690000090856537,2019-08-06 19:55:00,2018-12-15 00:00:00,Adam,Saunders,OTA,empty,empty,empty,empty,...,Karma Rottnest,empty,empty,New Lead,false,false,empty,empty,empty,empty
5294,zcrm_3584690000073302177,2019-07-16 18:56:00,2019-07-15 00:00:00,Ingrid,sellarulo,OTA,empty,empty,empty,empty,...,Karma Kandara,empty,SEAP,empty,false,false,empty,empty,empty,empty
5429,zcrm_3584690000054562511,2019-06-29 13:07:00,2019-06-28 00:00:00,Renee,Rudolf,OTA,empty,empty,empty,empty,...,Karma Kandara,empty,SEAP,empty,false,false,empty,empty,empty,empty
5467,zcrm_3584690000050011008,2019-06-22 13:41:00,2019-05-22 00:00:00,tes,dev,OTA,empty,empty,empty,empty,...,Karma Kandara,empty,Other,empty,false,false,empty,empty,empty,empty
7047,zcrm_3584690000029864256,2019-05-10 16:20:00,empty,empty,Manny,OTA,empty,empty,empty,empty,...,empty,empty,SEAP,New Lead,false,false,empty,empty,empty,empty
10419,zcrm_3584690000024541960,2019-04-07 15:08:00,2018-01-31 00:00:00,Josefin,Pote,OTA,empty,empty,empty,empty,...,Karma Kandara,Karma Kandara Spa January 2018,UK/Europe,New Lead,false,false,empty,empty,empty,empty

In [10]:
# Hapus email OTA

zoho_df.drop(zoho_df[zoho_df['Email'] == 'OTA'].index, inplace=True)
zoho_df.reset_index(drop=True, inplace=True)

count_after_clean_OTA = zoho_df.shape[0]

zoho_df

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Booking Status,BookRef,Guest Type,External ID
0,zcrm_3584690000409794028,2022-11-10 00:54:00,2022-11-09 00:00:00,Guru,C,gururajgcss@gmail.com,empty,empty,empty,empty,...,Karma Royal Benaulim,Karma Spa at Karma Royal Benaulim,India,empty,false,false,empty,empty,empty,empty
1,zcrm_3584690000404526047,2022-10-12 19:13:00,2022-10-12 00:00:00,Joao,Tavares,jmtavares@btinternet.com,empty,empty,empty,empty,...,Karma Royal Sanur,Karma Spa at Karma Royal Sanur,UK/Europe,empty,false,false,empty,empty,empty,empty
2,zcrm_3584690000402673323,2022-10-03 16:10:00,2022-10-03 00:00:00,Valencia,Lopez,valencia.lopez00@gmail.com,empty,empty,empty,empty,...,Karma Royal Haathi Mahal,Karma Spa at Karma Royal Haathi Mahal,India,empty,false,false,empty,empty,empty,empty
3,zcrm_3584690000402072082,2022-09-29 17:38:00,2022-09-29 00:00:00,Ranjitha,BM,ranju281094@gmail.com,empty,empty,empty,empty,...,Karma Royal Benaulim,Karma Spa at Karma Royal Benaulim,India,empty,false,false,empty,empty,empty,empty
4,zcrm_3584690000400243001,2022-09-20 21:52:00,2022-09-20 00:00:00,vishal,ingle,vishal.ingle1@gmail.com,empty,empty,empty,empty,...,Karma Chakra,Karma Spa at Karma Chakra,India,empty,false,false,empty,empty,empty,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11137,zcrm_3584690000002607163,2019-02-23 18:21:00,empty,Bhargav,Patel,bhargv@gmail.com,empty,empty,empty,empty,...,empty,empty,India,New Lead,false,false,empty,empty,empty,empty
11138,zcrm_3584690000002503001,2019-02-21 23:22:00,empty,Lauren,Brenton,laurenbrenton@outlook.com,empty,empty,1984-06-08 00:00:00,1984,...,empty,empty,SEAP,New Lead,false,false,empty,empty,empty,empty
11139,zcrm_3584690000001876097,2019-02-12 17:44:00,2019-02-12 00:00:00,Aishwarya,Ganesh,divya_g24@yahoo.co.in,917709923249,empty,empty,empty,...,Karma Chakra,empty,India,New Lead,false,false,empty,empty,empty,empty
11140,zcrm_3584690000001291015,2019-01-31 20:19:00,2019-01-31 00:00:00,Ajay,Mahan,ajay.mahan@theintelligentsp.co.uk,441543483700,empty,empty,empty,...,Karma Kandara,empty,UK/Europe,New Lead,false,false,empty,empty,empty,empty
11141,zcrm_3584690000001115009,2019-01-27 13:22:00,2019-01-27 00:00:00,Amilya,Amilya,amilya.rossintya@gmail.com,6281336773732,empty,empty,empty,...,Karma Mayura,empty,SEAP,New Lead,false,false,empty,empty,empty,empty

In [11]:
find_member_booking = zoho_df.copy()

find_member_booking.loc[find_member_booking['Phone'].isin(df_booking['Phone1']), 'Same Value Find'] = 'Booking-Phone1'
find_member_booking.loc[find_member_booking['Phone'].isin(df_booking['Mobile']), 'Same Value Find'] = 'Booking-Mobile'
find_member_booking.loc[find_member_booking['Mobile'].isin(df_booking['Phone1']), 'Same Value Find'] = 'Booking-Phone1' 
find_member_booking.loc[find_member_booking['Mobile'].isin(df_booking['Mobile']), 'Same Value Find'] = 'Booking-Mobile'
find_member_booking.loc[find_member_booking['Email'].isin(df_booking['Email']), 'Same Value Find'] = 'Booking-Email'

find_member_booking.loc[find_member_booking['Phone'].isin(df_phone['Mobile']), 'Same Value Find'] = 'Member-Mobile' 
find_member_booking.loc[find_member_booking['Mobile'].isin(df_phone['Mobile']), 'Same Value Find'] = 'Member-Mobile'

find_member_booking.loc[find_member_booking['Email'].isin(df_email['Email']), 'Same Value Find'] = 'Member-Email'

find_member_booking.drop(find_member_booking.loc[find_member_booking['Same Value Find'].isna()].index, inplace=True)

count_booking_dedup = find_member_booking.loc[find_member_booking['Same Value Find'].str.contains('Booking', flags=re.I, regex=True)].shape[0]
count_member_dedup = find_member_booking.loc[find_member_booking['Same Value Find'].str.contains('Member', flags=re.I, regex=True)].shape[0]

find_member_booking.replace('empty', '', inplace=True)

# find_member_booking.to_csv(r'C:\Users\fajar\Documents\Python\Data\booking-member-dedup-spa.csv', index=False)

In [12]:
# data phone, mobile dam email member yang ada di master data (wash member)
count_wash_member = zoho_df.loc[
    zoho_df['Phone'].isin(df_booking['Phone1']) | 
    zoho_df['Phone'].isin(df_booking['Mobile']) |
    zoho_df['Mobile'].isin(df_booking['Phone1']) | 
    zoho_df['Mobile'].isin(df_booking['Mobile']) |
    zoho_df['Email'].isin(df_booking['Email'])| 

    zoho_df['Phone'].isin(df_phone['Mobile']) | 
    zoho_df['Mobile'].isin(df_phone['Mobile']) |

    zoho_df['Email'].isin(df_email['Email'])

].shape[0]

zoho_df.drop(zoho_df.loc[
    zoho_df['Phone'].isin(df_booking['Phone1']) | 
    zoho_df['Phone'].isin(df_booking['Mobile']) |
    zoho_df['Mobile'].isin(df_booking['Phone1']) | 
    zoho_df['Mobile'].isin(df_booking['Mobile']) |
    zoho_df['Email'].isin(df_booking['Email']) |
    
    zoho_df['Phone'].isin(df_phone['Mobile']) | 
    zoho_df['Mobile'].isin(df_phone['Mobile']) |

    zoho_df['Email'].isin(df_email['Email'])

    ].index, inplace=True)
zoho_df.reset_index(drop=True, inplace=True)

count_after_wash_member = zoho_df.shape[0]

In [13]:
find_zoho_unsubs = zoho_df.loc[zoho_df['Email'].isin(df_unsub_zoho['Contact Email'])].copy()
count_wash_zoho_unsubs = find_zoho_unsubs.shape[0]

find_zoho_unsubs.replace('empty', '', inplace=True)

# find_zoho_unsubs.to_csv(r'C:\Users\fajar\Documents\Python\Data\zoho-unsub-dedup-spa.csv', index=False)
zoho_df.drop(find_zoho_unsubs.index, inplace=True)

count_after_wash_zoho_unsubs = zoho_df.shape[0]
print(count_after_wash_zoho_unsubs)

5734

In [14]:
zoho_df.replace('empty', '', inplace=True)

In [15]:
print("==========================================================")
print("Summary")
print("==========================================================")
print("Jumlah Filter Leads Awal : "+str(count_filter_awal))
print("Jumlah Format Email Salah : "+str(count_deleted_wrong_fromat))
print("Jumlah Setelah Clean Format Email Salah : "+str(count_after_deleted_wrong_format))
print("Jumlah Email Kosong : "+str(count_empty_email))
print("Jumlah Setelah Clean Email Kosong : "+str(count_after_dedup_empty_email))
print("Jumlah Email Duplikat : "+str(count_email_duplicate))
print("Jumlah Setelah Clean Format Email Duplikat : "+str(count_after_dedup_duplicated_email))
print("Jumlah Email OTA : "+str(count_email_OTA))
print("Jumlah Setelah Clean Email OTA : "+str(count_after_clean_OTA))
print("Jumlah Wash Member dan Booking : "+str(count_wash_member))
print("Jumlah Setelah Wash Member : "+str(count_after_wash_member))
print("Jumlah Wash Zoho Unsubs: "+str(count_wash_zoho_unsubs))
print("Jumlah Setelah Wash Zoho Unsubs : "+str(count_after_wash_zoho_unsubs))

==========================================================
Summary
==========================================================
Jumlah Filter Leads Awal : 11448
Jumlah Format Email Salah : 16
Jumlah Setelah Clean Format Email Salah : 11432
Jumlah Email Kosong : 0
Jumlah Setelah Clean Email Kosong : 11432
Jumlah Email Duplikat : 281
Jumlah Setelah Clean Format Email Duplikat : 11151
Jumlah Email OTA : 9
Jumlah Setelah Clean Email OTA : 11142
Jumlah Wash Member dan Booking : 459
Jumlah Setelah Wash Member : 10683
Jumlah Wash Zoho Unsubs: 4949
Jumlah Setelah Wash Zoho Unsubs : 5734

In [42]:
# zoho_df.to_csv(r'C:\Users\fajar\Documents\Python\Data\karmaspa-clean.csv', index=False)

# ===================== Split File =====================

In [43]:
# membuat batch file excel

zoho_df['Batch'] = ''
batch_number = 10000
zoho_df = m.insert_batch_loop(zoho_df, batch_number, -1)
zoho_df.groupby('Batch').count()

,Record Id,Created Time,Created Date,First Name,Last Name,Email,Phone,Mobile,Birthdate,Year of Birth,...,Lead Locations,Lead Source Description,Lead Regions,Lead Status,Email Opt Out,Opt In,Booking Status,BookRef,Guest Type,External ID
Batch,,,,,,,,,,,,,,,,,,,,,
,5734,5734,5734,5734,5734,5734,5734,5734,5734,5734,...,5734,5734,5734,5734,5734,5734,5734,5734,5734,5734

In [44]:
# melakukan split file

filename = 'test'
split_number = 50000
m.split_file(zoho_df, split_number, filename)