In [1]:
import pandas as pd
import re
import numpy as np
import openpyxl

import sys
sys.path.append('../arrival_list_app/compile_data/')

import arrival_compile_main as ac

import sys
sys.path.append('../zoho_data_app/')

import main_module as m

%load_ext autoreload
%autoreload 2

In [2]:
path = r'G:\My Drive\Debounce\Debounce Bank Data.xlsx'

In [3]:
xl = pd.ExcelFile(path)
sheets = xl.sheet_names  # see all sheet names

delete_sheets = [
    'DeBounce Reasons',
    'Test'
]

arr = np.array(sheets)
# arr = np.delete(arr, delete_sheets)

sheet_will_be_used = []

for i in sheets:
    sheets_name = i
    result = np.isin(sheets_name, delete_sheets)
    if result == True:
        print(sheets_name)
    else:
        print(sheets_name)
        sheet_will_be_used.extend([sheets_name])

sheet_will_be_used

# sheet_will_be_used = ['JAN 23']
# arr

DeBounce Reasons
Test
All Campaign
Beambox KLOM
Leads TM Kevin OConnor
KK Past Guests ALL
Past Guest
29 Apr 22
31 May 22
29 Apr 22 - 2
SEAP-Western1 - 18Mar22
SEAP-Western2 - 18Mar22
SEAP-Western3 - 18Mar22
KE Cold Line - 17 Sep 21
KE Drive Buy - 17 Sep 21
10 Sep 21
Sanctum Soho - 7 Sep 21
Sanctum Soho - 2 Sep 21
BGID - 27 Aug 21
Karma Resorts DB ID - 24 Aug 20
Karma Group ID - 23 Aug 2021
UK Data  11 Aug 2021
Rottnest WIFI - 26 Jul 2021
Past Guests - 21 Jul 2021
BGID - 29 Jul 21
KEID - 29 Jul 21
KSH - 3 Aug 21
BGAU
All SEAP email need to dedup ag
HDAU
HDID
KE
Purple WIFI

['All Campaign',
 'Beambox KLOM',
 'Leads TM Kevin OConnor',
 'KK Past Guests ALL',
 'Past Guest',
 '29 Apr 22',
 '31 May 22',
 '29 Apr 22 - 2',
 'SEAP-Western1 - 18Mar22',
 'SEAP-Western2 - 18Mar22',
 'SEAP-Western3 - 18Mar22',
 'KE Cold Line - 17 Sep 21',
 'KE Drive Buy - 17 Sep 21',
 '10 Sep 21',
 'Sanctum Soho - 7 Sep 21',
 'Sanctum Soho - 2 Sep 21',
 'BGID - 27 Aug 21',
 'Karma Resorts DB ID - 24 Aug 20',
 'Karma Group ID - 23 Aug 2021',
 'UK Data  11 Aug 2021',
 'Rottnest WIFI - 26 Jul 2021',
 'Past Guests - 21 Jul 2021',
 'BGID - 29 Jul 21',
 'KEID - 29 Jul 21',
 'KSH - 3 Aug 21',
 'BGAU',
 'All SEAP email need to dedup ag',
 'HDAU',
 'HDID',
 'KE',
 'Purple WIFI']

In [4]:
key_columns = 'EMAIL'

cols = [key_columns, 
        'RESULT', 
        'REASON',
        'STATUS CODE',
        'ROLE', 
        'FREE', 
        'DOMAIN']

In [5]:
df = ac.load_data_multiple(path, sheet_will_be_used, cols, key_columns)
df

Compiling sheets [All Campaign] - On progress : Proses Single Header
Compiling sheets [Beambox KLOM] - On progress : Proses Single Header
Compiling sheets [Leads TM Kevin OConnor] - On progress : Proses Single Header
Compiling sheets [KK Past Guests ALL] - On progress : Proses Single Header
Compiling sheets [Past Guest] - On progress : Proses Single Header
Compiling sheets [29 Apr 22] - On progress : Proses Single Header
Compiling sheets [31 May 22] - On progress : Proses Single Header
Compiling sheets [29 Apr 22 - 2] - On progress : Proses Single Header
Compiling sheets [SEAP-Western1 - 18Mar22] - On progress : Proses Single Header
Compiling sheets [SEAP-Western2 - 18Mar22] - On progress : Proses Single Header
Compiling sheets [SEAP-Western3 - 18Mar22] - On progress : Proses Single Header
Compiling sheets [KE Cold Line - 17 Sep 21] - On progress : Proses Single Header
Compiling sheets [KE Drive Buy - 17 Sep 21] - On progress : Proses Single Header
Compiling sheets [10 Sep 21] - On progress : Proses Single Header
Compiling sheets [Sanctum Soho - 7 Sep 21] - On progress : Proses Single Header
Compiling sheets [Sanctum Soho - 2 Sep 21] - On progress : Proses Single Header
Compiling sheets [BGID - 27 Aug 21] - On progress : Proses Single Header
Compiling sheets [Karma Resorts DB ID - 24 Aug 20] - On progress : Proses Single Header
Compiling sheets [Karma Group ID - 23 Aug 2021] - On progress : Proses Single Header
Compiling sheets [UK Data  11 Aug 2021] - On progress : Proses Single Header
Compiling sheets [Rottnest WIFI - 26 Jul 2021] - On progress : Proses Single Header
Compiling sheets [Past Guests - 21 Jul 2021] - On progress : Proses Single Header
Compiling sheets [BGID - 29 Jul 21] - On progress : Proses Single Header
Compiling sheets [KEID - 29 Jul 21] - On progress : Proses Single Header
Compiling sheets [KSH - 3 Aug 21] - On progress : Proses Single Header
Compiling sheets [BGAU] - On progress : Proses Single Header
Compiling sheets [All SEAP email need to dedup ag] - On progress : Proses Single Header
Compiling sheets [HDAU] - On progress : Proses Single Header
Compiling sheets [HDID] - On progress : Proses Single Header
Compiling sheets [KE] - On progress : Proses Single Header
Compiling sheets [Purple WIFI] - On progress : Proses Single Header

,EMAIL,RESULT,REASON,STATUS CODE,ROLE,FREE,DOMAIN,Sheet Name
0,00001111den@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
1,007dhananjaykumbhar@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
2,0597396@mail.ru,Safe to Send,Deliverable,5,No,Yes,mail.ru,All Campaign
3,07deepanshu@gmail.com,Safe to Send,Deliverable,5,No,Yes,gmail.com,All Campaign
4,1078049354@qq.com,Safe to Send,Deliverable,5,No,Yes,qq.com,All Campaign
...,...,...,...,...,...,...,...,...
1261464,z_forbes_92@hotmail.com,Safe to Send,Deliverable,5,No,Yes,hotmail.com,Purple WIFI
1261465,z_mingwei@hotmail.com,Safe to Send,Deliverable,5,No,Yes,hotmail.com,Purple WIFI
1261466,z_o_ni@hotmail.com,Safe to Send,Deliverable,5,No,Yes,hotmail.com,Purple WIFI
1261467,_argo@mail.ru,Safe to Send,Deliverable,5,No,Yes,mail.ru,Purple WIFI
1261468,_joanne_mckay@hotmail.co.nz,Safe to Send,Deliverable,5,No,Yes,hotmail.co.nz,Purple WIFI

In [6]:
df.groupby('RESULT').count()

,EMAIL,REASON,STATUS CODE,ROLE,FREE,DOMAIN,Sheet Name
RESULT,,,,,,,
Invalid,113040,113040,112736,110929,110330,107827,113040
Risky,59732,59732,59324,53730,53716,52877,59732
Safe to Send,1034475,1034475,1034475,1014005,1013559,986508,1034475
Unknown,54208,54208,54208,50773,50768,50124,54208

In [7]:
df.loc[df['EMAIL'] == '']

Empty DataFrame
Columns: [EMAIL, RESULT, REASON, STATUS CODE, ROLE, FREE, DOMAIN, Sheet Name]
Index: []

In [8]:
df.to_csv(r'C:\Users\fajar\Documents\Python\Data\Debounce\debounce_backup.csv', index=False)